### ISSUE TITLE
Support prettier v3 in blueprints

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#10312]
When I tried to do it, I got

```
  TypeError: prettier.resolveConfig.sync is not a function
  Occurred while linting /home/runner/work/ember-cli/ember-cli/tmp/some_cool_app_clone-SwV0SfKd.tmp/.eslintrc.js:1
  Rule: "prettier/prettier"
      at Program (tmp/node-RyeOV7op.tmp/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:138:40)
      at ruleErrorHandler (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1050:28)
      at /home/runner/work/ember-cli/ember-cli/tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/safe-emitter.js:45:58
      at Array.forEach (<anonymous>)
      at Object.emit (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
      at NodeEventGenerator.applySelector (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
      at NodeEventGenerator.applySelectors (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
      at NodeEventGenerator.enterNode (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
      at CodePathAnalyzer.enterNode (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
      at /home/runner/work/ember-cli/ember-cli/tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1085:32
      at Array.forEach (<anonymous>)
      at runRules (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1080:15)
      at Linter._verifyWithoutProcessors (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1330:31)
      at Linter._verifyWithConfigArray (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1706:21)
      at Linter.verify (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1412:65)
      at Linter.verifyAndFix (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/linter/linter.js:1967:29)
      at verifyText (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/cli-engine/cli-engine.js:254:48)
      at CLIEngine.executeOnFiles (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/cli-engine/cli-engine.js:834:28)
      at ESLint.lintFiles (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/eslint/eslint.js:551:23)
      at Object.execute (tmp/node-RyeOV7op.tmp/node_modules/eslint/lib/cli.js:391:36)
      at async main (tmp/node-RyeOV7op.tmp/node_modules/eslint/bin/eslint.js:135:24)
      at makeError (node_modules/execa/lib/error.js:60:11)
      at handlePromise (node_modules/execa/index.js:118:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (tests/acceptance/smoke-test-slow.js:512:7)
```

**Comment by bertdeblock** [comment]
@kellyselden `eslint-plugin-prettier` v5 is out, which now supports `prettier` v3.

**Comment by jelhan** [comment]
I think this issue is solved already and can be closed.     https://github.com/ember-cli/ember-new-output/blob/e8b02e7160266148674e3d0f18166c7115ab9536/package.json#L65

**Comment by NullVoxPopuli** [comment]
Ye! Thanks!
