### ISSUE TITLE
App blueprint has invalid ESLint config

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#10443]
repro:
```bash
❯ npx ember-cli@latest new my-app --pnpm
installing app
Ember CLI v5.6.0

✨  Creating a new Ember app in /home/nvp/Development/tmp/my-app:
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .github/workflows/ci.yml
  create .prettierignore
  create .prettierrc.js
  create .stylelintignore
  create .stylelintrc.js
  create .template-lintrc.js
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create config/ember-cli-update.json
  create config/environment.js
  create config/optional-features.json
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.js
  create tests/helpers/index.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep

🚧  Installing packages... This might take a couple of minutes.
pnpm: Installed dependencies

🎥  Initializing git repository.
Git: successfully initialized.

🎉  Successfully created project my-app.
👉  Get started by typing:

  $ cd my-app
  $ pnpm start

Happy coding!

~/Development/tmp took 10s 
❯ cd my-app/

my-app on  main 

   

❯ pnpm lint

> my-app@0.0.0 lint /home/nvp/Development/tmp/my-app
> concurrently "npm:lint:*(!fix)" --names "lint:"

[lint:hbs] 
[lint:hbs] > my-app@0.0.0 lint:hbs
[lint:hbs] > ember-template-lint .
[lint:hbs] 
[lint:js] 
[lint:js] > my-app@0.0.0 lint:js
[lint:js] > eslint . --cache
[lint:js] 
[lint:css] 
[lint:css] > my-app@0.0.0 lint:css
[lint:css] > stylelint "**/*.css"
[lint:css] 
[lint:css] npm run lint:css exited with code 0
[lint:js] 
[lint:js] Oops! Something went wrong! :(
[lint:js] 
[lint:js] ESLint: 8.56.0
[lint:js] 
[lint:js] Error: ESLint configuration in .eslintrc.js#overrides[1] » plugin:qunit/recommended is invalid:
[lint:js] 	- Unexpected top-level property "description".
[lint:js] 
[lint:js] Referenced from: /home/nvp/Development/tmp/my-app/.eslintrc.js
[lint:js]     at ConfigValidator.validateConfigSchema (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:19)
[lint:js]     at ConfigArrayFactory._normalizeConfigData (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
[lint:js]     at ConfigArrayFactory._loadExtendedPluginConfig (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
[lint:js]     at ConfigArrayFactory._loadExtends (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
[lint:js]     at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
[lint:js]     at _normalizeObjectConfigDataBody.next (<anonymous>)
[lint:js]     at ConfigArrayFactory._normalizeObjectConfigData (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
[lint:js]     at _normalizeObjectConfigData.next (<anonymous>)
[lint:js]     at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/nvp/Development/tmp/my-app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3133:25)
[lint:js]     at _normalizeObjectConfigDataBody.next (<anonymous>)
[lint:hbs] 
[lint:js] npm run lint:js exited with code 2
[lint:hbs] npm run lint:hbs exited with code 0
 ELIFECYCLE  Command failed with exit code 1.

my-app on  ma
```

**Comment by NullVoxPopuli** [comment]
Potentially more a problem with eslint-plugin-qunit.

**Comment by NullVoxPopuli** [comment]
new release from 10 hours ago: https://github.com/platinumazure/eslint-plugin-qunit/releases/tag/v8.1.0

**Comment by bertdeblock** [comment]
Can be closed I think?

https://github.com/platinumazure/eslint-plugin-qunit/releases/tag/v8.1.1

**Comment by NullVoxPopuli** [comment]
Yup
