### ISSUE TITLE
Deprecation warning on Node 22

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#10463]
Upgrading to Node 22, running `ember serve` and making a request to the server leads to:

```
(node:971449) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at common.setupOutgoing (/home/boris/code/project/node_modules/.pnpm/http-proxy@1.18.1/node_modules/http-proxy/lib/http-proxy/common.js:43:22)
    at Array.stream (/home/boris/code/project/node_modules/.pnpm/http-proxy@1.18.1/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/home/boris/code/project/node_modules/.pnpm/http-proxy@1.18.1/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at /home/boris/code/project/node_modules/.pnpm/ember-cli@5.8.1/node_modules/ember-cli/lib/tasks/server/middleware/proxy-server/index.js:43:35
    at Layer.handle [as handle_request] (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)
    at /home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:346:12)
    at next (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:280:10)
    at logger (/home/boris/code/project/node_modules/.pnpm/morgan@1.10.0/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)
    at /home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:346:12)
    at next (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:280:10)
    at serveAssetsMiddleware (/home/boris/code/project/node_modules/.pnpm/broccoli-middleware@2.1.1/node_modules/broccoli-middleware/lib/serve-asset-middleware.js:24:7)
    at /home/boris/code/project/node_modules/.pnpm/ember-cli@5.8.1/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-serve-files/index.js:28:7
    at Layer.handle [as handle_request] (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)
    at /home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:346:12)
    at next (/home/boris/code/project/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:280:10)
    at /home/boris/code/project/node_modules/.pnpm/ember-cli@5.8.1/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11
    at watcher.then.errorHandler.buildError (/home/boris/code/project/node_modules/.pnpm/broccoli-middleware@2.1.1/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 5.8.1
node: 22.0.0
acorn: 8.11.3
ada: 2.7.7
ares: 1.28.1
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 44.1
icu: 74.2
llhttp: 9.2.1
modules: 127
napi: 9
nghttp2: 1.61.0
openssl: 3.3.0
simdjson: 3.8.0
simdutf: 5.2.4
tz: 2023c
undici: 6.11.1
unicode: 15.1
uv: 1.48.0
uvwasi: 0.0.20
v8: 12.4.254.14-node.10
zlib: 1.3.1
os: linux x64
10.7.0
1.22.22
```

**Comment by bertdeblock** [comment]
https://github.com/http-party/node-http-proxy/pull/1666

**Comment by chancancode** [comment]
https://github.com/http-party/node-http-proxy/issues/1696#issuecomment-2624577947 FWIW, this comment also indicates there is a memory leak with the dependency on modern Node
