### ISSUE TITLE
Livereload bug

### ISSUE THREAD

**Issue by wyaeld** [ember-cli/ember-cli#1054]
First run, clean app

```
12:36 $ ember server
version: 0.0.34-master-5cfcb86a7a
Livereload server on port 35729
Serving on http://0.0.0.0:4200

Build successful - 593ms.

Slowest Trees                  | Total          
-------------------------------+----------------
TreeMerger (appAndDependencies) | 60ms           
TreeMerger (vendor)            | 48ms           
StaticCompiler                 | 41ms           
TreeMerger (app)               | 40ms           
StaticCompiler                 | 34ms           
TreeMerger (allTrees)          | 33ms           
ES3SafeFilter                  | 31ms 
```

`ctrl+c`

Second run, same app

```
12:38 $ ember server
version: 0.0.34-master-5cfcb86a7a
Livereload server on port 35729
Serving on http://0.0.0.0:4200
watch ENOSPC
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Watcher.watchdir (/home/brad/rails_projects/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/index.js:184:20)
    at new Watcher (/home/brad/rails_projects/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/index.js:63:10)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/brad/rails_projects/ember-cli/node_modules/broccoli-sane-watcher/index.js:65:17)
    at /home/brad/rails_projects/ember-cli/node_modules/broccoli/lib/builder.js:66:35
    at tryCatch (/home/brad/rails_projects/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:163:16)
    at invokeCallback (/home/brad/rails_projects/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:172:17)
    at /home/brad/rails_projects/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/promise.js:186:17
    at flush (/home/brad/rails_projects/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/asap.js:51:9)
    at process._tickCallback (node.js:415:13)

fs.js:1051
    throw errnoException(process._errno, 'watch');
          ^
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Watcher.watchdir (/home/brad/rails_projects/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/index.js:184:20)
    at Walker.EventEmitter.emit (events.js:98:17)
    at /home/brad/rails_projects/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at Object.oncomplete (fs.js:107:15)
```

This is ubuntu 14.04

```
12:52 $ npm -v
1.3.8

12:56 $ node -v
v0.10.17
```

Does anyone know the cause?

**Comment by betasve** [comment]
Deleting the /tmp and changing the max watchfile number worked for me too. (thumbs up)

**Comment by milosb793** [comment]
Changing watchfile worked for me too! Thanks!!
