### ISSUE TITLE
Ember-cli addon can't import from node_modules

### ISSUE THREAD

**Issue by kumavis** [ember-cli/ember-cli#1072]
disclaimer: I perused the existing addons and tried to copy their style, but I don't really know how this is supposed to work.

addon's index.js

``` js
var fs = require('fs');
var path = require('path');

function EmberCLIWow(project) {
  this.project = project;
  this.name = 'Ember CLI Wow';
}

EmberCLIWow.prototype.treeFor = function(name) {

  if (name === 'app') {
    return path.join('node_modules/wow/app/');
  }

};

EmberCLIWow.prototype.included = function included(app) {
  // app.import('vendor/wow/app/widgets/index.js');
  app.import('node_modules/wow/app/widgets/index.js');
};

module.exports = EmberCLIWow;

```

Error:

```
 mono git:(cli-up) ✗ npm start

> mono@0.0.0 start /Users/aarondavis/Development/Ember/mono
> ember server

version: 0.0.34
Livereload server on port 35729
Serving on http://0.0.0.0:4200

Path or pattern "node_modules/wow/app/widgets/index.js" did not match any files
Error: Path or pattern "node_modules/wow/app/widgets/index.js" did not match any files
    at Object.multiGlob (/Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:216:13)
    at /Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/broccoli-concat/index.js:41:30
    at tryCatch (/Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:163:16)
    at invokeCallback (/Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:172:17)
    at publish (/Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:150:13)
    at flush (/Users/aarondavis/Development/Ember/mono/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/asap.js:51:9)
    at process._tickCallback (node.js:419:13)
```

I guess I thought that because we're requesting a tree, that we would be able to import those assets...

**Comment by dylan947** [comment]
Adding to this issue. I'm writing an addon that imports my own sass library (which includes images, FontAwesome and pre compiled version). The structure is as follows:

```javascript
my-addon
  |- vendor
   |-- font-awesome
   |-- my-addon-sass
     -- images
     -- stylesheets
  -- index.js
```

**index.js**

```javascript
var fs = require("fs");
var path = require("path");

module.exports = {
  name: "Ember CLI my addon",
  included: function (app) {
    var modulePath = path.relative(app.project.root, __dirname);
    var myAddonPath = "vendor/my-addon-sass";
    var sassOptions = app.options.sassOptions || {};
    var includePaths = sassOptions.includePaths || [];

    // first issue, this only works if I set my sassOptions in my consuming app's environment. (an issue with ember-cli-sass?)
    includePaths.push(path.join(modulePath, myAddonPath, "stylesheets"));
    ...
    includePaths.push(path.join(modulePath, myAddonPath, "stylesheets/library"));

    app.import(path.join(modulePath, myAddonPath, "stylesheets/myAddon.css"));
    // path or pattern "node_modules/ember-cli-myaddon/vendor/myAddon/stylesheets/myAddon.css" did not match any files

    // this doesn't work because app.import takes a file
    app.import(path.join(modulePath, myAddonPath, "images/"));

    // this doesn't work for the same reason as the pre compile css
    var images = fs.readdirSync(path.join(modulePath, myAddonPath, "images"));
    
    images.forEach(function (image) {
      app.import(path.join(modulePath, myAddonPath, "images", image), { destDir: "images/my-addon");
    });
  }
}
```

As I said, I can get my sass to import and compile correctly if I set my `sassOptions` in the consuming app, but only if I remove the imports of my precompiled css and my images. Is there something I'm missing or some other way I should be importing these? Possibly in the `treeFor` hook (which I tried but couldn't get to work with

 ```
if (name === "vendor") { 
  return this.treeGenerator(path.join(__dirname, "node_modules")); 
}
```
