### ISSUE TITLE
Build fails after removing ember-data

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#1226]
NEVERMIND... (I think a model was still importing ember-data)

The guide on ember-cli.com indicates that ember-data can be removed like so:

`npm rm ember-cli-ember-data --save-dev`

However, after removing ember-data, when I try to build it fails.

Steps to reproduce:
1. I executed the npm command to remove ember-data 
2. Then I ran `npm install`. 
3. Next I tried a build with `ember build` and got an error which complained about ember-data not being found.

I also noticed that ember-qunit has ember-data as a dependency too. So ember-data still ends up in the vendor directory.

The build fails and displays this error:

```
ENOENT, no such file or directory '/path-to-my-app/tmp/tree_merger-tmp_dest_dir-t2dyuooR.tmp/ember-data.js'
File: ember-data.js
Error: ENOENT, no such file or directory '/path-to-my-app/tmp/tree_merger-tmp_dest_dir-t2dyuooR.tmp/ember-data.js'
    at Object.fs.statSync (fs.js:684:18)
    at addModule (/path-to-my-app/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:81:46)
    at addModule (/path-to-my-app/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:124:9)
    at /path-to-my-app/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:57:7
    at tryCatch (/path-to-my-app/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:163:16)
    at invokeCallback (/path-to-my-app/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:172:17)
    at publish (/path-to-my-app/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:150:13)
    at flush (/path-to-my-app/node_modules/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/asap.js:51:9)
```

**Comment by mmitchellgarcia** [comment]
I had the same exact error on a clean install, so I was not referencing ember-data anywhere in the app. When I removed the reference to Ember Data in **package.json** in addition to bower.json, clear cache/remove tmp/etc. it worked.
