### ISSUE TITLE
'watch ENOSPC' error on 0.0.37-master-08d002e3d5

### ISSUE THREAD

**Issue by EmergentBehavior** [ember-cli/ember-cli#1240]
Hello -- I'm receiving the following error after upgrading ember-cli to 0.0.37-master-08d002e3d5 and running `ember serve`:

```
watch ENOSPC
Error: watch ENOSPC
  at errnoException (fs.js:1024:11)
  at FSWatcher.start (fs.js:1056:11)
  at Object.fs.watch (fs.js:1081:11)
  at Watcher.watchdir ([MY-PATH]/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/index.js:184:20)
  at new Watcher ([MY-PATH]/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/index.js:63:10)
  at EventEmitter.Watcher_addWatchDir [as addWatchDir] [MY-PATH]/ember-cli/node_modules/broccoli-sane-watcher/index.js:65:17)
  at [MY-PATH]/ember-cli/node_modules/broccoli/lib/builder.js:66:35
  at tryCatch ([MY-PATH]/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:163:16)
  at invokeCallback ([MY-PATH]/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/-internal.js:172:17)
  at [MY-PATH]/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/promise.js:186:17
  at flush ([MY-PATH]/ember-cli/node_modules/rsvp/dist/commonjs/rsvp/asap.js:51:9)
  at process._tickCallback (node.js:419:13)

```

I always run `ember init` after upgrade and adjust as necessary. I'm wondering if the new `broccoli-asset-rev` dependency has anything to do with this. I tried clearing `tmp/` but that also didn't make enough difference. I have more than ample HD space so it's not a space issues...

**Comment by lmcardle** [comment]
I just started getting this error with Ember 2.12. Previously it was fine with Ember version 2.7.

I tried running `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` to no avail.

**Comment by lmcardle** [comment]
installing and using Watchman solves this.

**Comment by gitvishu12345** [comment]
Hello -- I'm receiving the following error running ember serve:

Build error

Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. ðŸ’¥
watch /home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-source/dist ENOSPC

Error: watch /home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-source/dist ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-cli-broccoli-sane-watcher/node_modules/sane/src/node_watcher.js:175:20)
    at new NodeWatcher (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-cli-broccoli-sane-watcher/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-cli-broccoli-sane-watcher/node_modules/sane/index.js:20:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/ember-cli-broccoli-sane-watcher/index.js:145:17)
    at /home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/broccoli-builder/lib/builder.js:134:35
    at tryCatch (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/viswajitdkolekar/ember_projects/purchase_practice/node_modules/rsvp/dist/rsvp.js:538:13)


Anyone can solve or fix this issue please let me know
