### ISSUE TITLE
`ember serve` crashes when rebuilding on Windows

### ISSUE THREAD

**Issue by BFalkner** [ember-cli/ember-cli#1253]
This only happens when there's old stuff in the tmp directory.  For instance, if the server crashes.

ENOTEMPTY, directory not empty 'C:\Users\bfalkner.IDPLANS\GitHub\webappv4\tmp\tree_merger-tmp_dest_dir-wy1Zkslv.tmp\images'
Error: ENOTEMPTY, directory not empty 'C:\Users\bfalkner.IDPLANS\GitHub\webappv4\tmp\tree_merger-tmp_dest_dir-wy1Zkslv.tmp\images'
    at Object.fs.rmdirSync (fs.js:617:18)
    at rmkidsSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at Function.rimrafSync [as sync](C:Usersbfalkner.IDPLANSGitHubwebappv4node_modulesbroccoli-merge-treesnode_modulesbroccoli-writernode_modulesquick-tempnode_modulesrimrafrimraf.js:216:26)
    at remove (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\index.js:26:12)
    at Object.makeOrRemake (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\node_modules\quick-temp\index.js:10:5)
    at TreeMerger.Writer.read (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\broccoli-merge-trees\node_modules\broccoli-writer\index.js:10:13)
    at C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:78:23
    at tryCatch (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\ember-cli\node_modules\rsvp\dist\commonjs\rsvp-internal.js:163:16)
    at invokeCallback (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\ember-cli\node_modules\rsvp\dist\commonjs\rsvp-internal.js:172:17)
    at C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\ember-cli\node_modules\rsvp\dist\commonjs\rsvp\promise.js:186:17
    at flush (C:\Users\bfalkner.IDPLANS\GitHub\webappv4\node_modules\ember-cli\node_modules\rsvp\dist\commonjs\rsvp\asap.js:51:9)
    at process._tickDomainCallback (node.js:463:13)

**Comment by KOGI** [comment]
Can confirm, for me, it was Sumblime Text watching the `tmp` directory. Adding it to the `folder_exclude_patterns` fixed everything!

**Comment by stefanpenner** [comment]
There is WIP moving the tmp dir of broccoli out to the system tmp dir. I suspect this will help

**Comment by blisst** [comment]
Just so other people don't have the same issue as me, running two Git Bash windows on the same folder (the project root) will also create this behavior.

I was having one Administrator-privileges window running 'ember server' and another for doing other things and for some reason it didn't register with me that that would cause this issue!

**Comment by philipbreau** [comment]
Just another note on the continuing saga for anyone still struggling with this, uninstalling git bash and windows defender did significantly alleviate the problem for me, but it was still occurring about half the time when updating .hbs files. 

Since I upgraded the local version of rimraf for ember-cli to 2.3.2 from 2.2.8 I haven't seen the issue once. So I assume some of the recent updates for rimraf such as https://github.com/isaacs/rimraf/commit/ec8bbddfec583c6eb2e4113c867887c577871568 might have helped.

**Comment by stefanpenner** [comment]
> Since I upgraded the local version of rimraf for ember-cli to 2.3.2 from 2.2.8 I haven't seen the issue once.

this is good news

**Comment by BFalkner** [comment]
Just noticed this notification.  It hasn't happened to me for several months.

**Comment by famousgarkin** [comment]
Still crashes on 0.2.3 on Windows 7. Development moved to Vagrant box for the time being.

**Comment by kellyselden** [comment]
I'm on Windows 7 and 0.2.3. The ENOTEMPTY is intermittent for me. I just keep saving a file and letting it rebuild until it works.

**Comment by temo44** [comment]
I just want to comment the fix that worked for our entire team. It was actually proposed here https://github.com/npm/npm/issues/7552 by miguelmota. Just perform the following commands:

    (npm install -g rimraf)
    rm -rf node_modules bower_components dist tmp
    npm install ember-cli --save-dev
    npm install
    bower install

Make sure that the first command is repeated until the entire `tmp` folder is gone. After this, enjoy your fast, not breaking build

**Comment by MohamadAtieh** [comment]
@blisst Thanks Bliss, I can confirm. Running `ember server` on one terminal window and having another open on the root would cause this issue.
