### ISSUE TITLE
Cannot find module 'ember-cli/lib/preprocessors'

### ISSUE THREAD

**Issue by kumavis** [ember-cli/ember-cli#126]
```
$  ember new zzz
Created project directory: zzzinstalling
  create .bowerrc
  create .jshintrc
  create .npmignore
  create Brocfile.js
  create api-stub/README.md
  create api-stub/routes.js
  create app/adapters/application.js
  create app/app.js
  create app/components/.gitkeep
  create app/components/pretty-color.js
  create app/components/template-less.js
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/helpers/reverse-word.js
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/routes/component_test.js
  create app/routes/helper_test.js
  create app/routes/index.js
  create app/styles/.gitkeep
  create app/styles/app.css
  create app/templates/.gitkeep
  create app/templates/application.hbs
  create app/templates/component-test.hbs
  create app/templates/components/.gitkeep
  create app/templates/components/pretty-color.hbs
  create app/templates/error.hbs
  create app/templates/helper-test.hbs
  create app/templates/index.hbs
  create app/templates/loading.hbs
  create app/utils/.gitkeep
  create app/utils/ajax.js
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create config/environments/development.js
  create config/environments/production.js
  create config/environments/test.js
  create package.json
  create public/index.html
  create tests/.jshintrc
  create tests/acceptance/component_test.js
  create tests/acceptance/helper_test.js
  create tests/acceptance/index_test.js
  create tests/helpers/isolated_container.js
  create tests/helpers/module_for.js
  create tests/helpers/resolver.js
  create tests/helpers/start_app.js
  create tests/test_helper.js
  create tests/test_loader.js
  create tests/unit/.gitkeep
  create tests/unit/components/pretty_color_test.js
  create tests/unit/components/template_less_component_test.js
  create tests/unit/routes/index_test.js
  create vendor/loader.js
Installing project dependencies.broccoli-env@0.0.1 node_modules/broccoli-env

originate@0.1.5 node_modules/originate
├── shelljs@0.2.6
└── cli-color@0.2.3 (es5-ext@0.9.2, memoizee@0.2.6)

loom-generators-ember-appkit@1.0.5 node_modules/loom-generators-ember-appkit
├── fleck@0.5.1
├── fs-extra@0.6.4 (jsonfile@1.0.1, ncp@0.4.2, rimraf@2.2.6, mkdirp@0.3.5)
└── glob@3.2.9 (inherits@2.0.1, minimatch@0.2.14)

broccoli-static-compiler@0.1.2 node_modules/broccoli-static-compiler
├── mkdirp@0.3.5
├── broccoli-kitchen-sink-helpers@0.1.0 (glob@3.2.9)
└── broccoli-transform@0.1.1 (quick-temp@0.1.0)

broccoli-uglify-js@0.1.1 node_modules/broccoli-uglify-js
├── uglify-js@2.4.13 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.33, optimist@0.3.7)
└── broccoli-filter@0.1.4 (broccoli-transform@0.1.1, walk-sync@0.1.0, mkdirp@0.3.5, rsvp@3.0.6, broccoli-kitchen-sink-helpers@0.1.0, quick-temp@0.1.0)

loom@3.1.2 node_modules/loom
├── commander@2.0.0
├── async@0.2.10
├── cli-prompt@0.3.2 (keypress@0.2.1)
├── fs-extra@0.6.4 (jsonfile@1.0.1, ncp@0.4.2, rimraf@2.2.6, mkdirp@0.3.5)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
└── loom-engine-hbs@2.0.0 (handlebars@1.0.12)

broccoli-es6-concatenator@0.1.2 node_modules/broccoli-es6-concatenator
├── js-string-escape@1.0.0
├── mkdirp@0.3.5
├── es6-module-transpiler@0.3.6 (through@2.3.4, optimist@0.3.7)
├── broccoli-kitchen-sink-helpers@0.1.0 (glob@3.2.9)
└── broccoli-transform@0.1.1 (quick-temp@0.1.0)

broccoli@0.4.1 node_modules/broccoli
├── commander@2.1.0
├── ncp@0.5.0
├── rsvp@3.0.6
├── send@0.2.0 (range-parser@1.0.0, fresh@0.2.2, debug@0.7.4, mime@1.2.11)
├── tiny-lr@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── broccoli-kitchen-sink-helpers@0.1.0 (mkdirp@0.3.5, glob@3.2.9)
├── handlebars@1.3.0 (optimist@0.3.7, uglify-js@2.3.6)
├── findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.9)
├── quick-temp@0.1.0 (mktemp@0.3.4, rimraf@2.2.6, underscore.string@2.3.3)
├── bower-config@0.5.0 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.6.0)
└── connect@2.14.3 (response-time@1.0.0, pause@0.0.1, cookie-signature@1.0.3, connect-timeout@1.0.0, vhost@1.0.0, fresh@0.2.2, qs@0.6.6, basic-auth-connect@1.0.0, morgan@1.0.0, serve-static@1.0.2, debug@0.7.4, bytes@0.2.1, static-favicon@1.0.2, raw-body@1.1.3, errorhandler@1.0.0, csurf@1.0.0, method-override@1.0.0, cookie-parser@1.0.1, compression@1.0.0, express-session@1.0.2, serve-index@1.0.1, multiparty@2.2.0)

broccoli-template@0.1.0 node_modules/broccoli-template
├── js-string-escape@1.0.0
└── broccoli-filter@0.1.4 (broccoli-transform@0.1.1, walk-sync@0.1.0, mkdirp@0.3.5, broccoli-kitchen-sink-helpers@0.1.0, rsvp@3.0.6, quick-temp@0.1.0)

bower@1.3.1 node_modules/bower
├── is-root@0.1.0
├── junk@0.2.2
├── stringify-object@0.2.0
├── abbrev@1.0.4
├── which@1.0.5
├── chmodr@0.1.0
├── archy@0.0.2
├── rimraf@2.2.6
├── open@0.0.4
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.1
├── lru-cache@2.5.0
├── nopt@2.1.2
├── retry@0.6.0
├── osenv@0.0.3
├── tmp@0.0.23
├── graceful-fs@2.0.3
├── q@1.0.1
├── chalk@0.4.0 (has-color@0.1.4, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── semver@2.2.1
├── request-progress@0.3.1 (throttleit@0.0.2)
├── bower-json@0.4.0 (deep-extend@0.2.8, intersect@0.0.3)
├── p-throttler@0.0.1 (q@0.9.7)
├── shell-quote@1.4.1 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
├── promptly@0.2.0 (read@1.0.5)
├── fstream@0.1.25 (inherits@2.0.1)
├── tar@0.1.19 (inherits@2.0.1, block-stream@0.0.7)
├── mkdirp@0.3.5
├── fstream-ignore@0.0.7 (inherits@2.0.1, minimatch@0.2.14)
├── decompress-zip@0.0.5 (nopt@2.2.0, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.11, binary@0.3.0)
├── glob@3.2.9 (inherits@2.0.1, minimatch@0.2.14)
├── request@2.33.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, node-uuid@1.4.1, mime@1.2.11, form-data@0.1.2, tough-cookie@0.12.1, http-signature@0.10.0, hawk@1.0.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── handlebars@1.3.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.4.1 (readline2@0.1.0, mute-stream@0.0.4, through@2.3.4, async@0.2.10, lodash@2.4.1, cli-color@0.2.3)
├── mout@0.9.0
├── update-notifier@0.1.8 (semver@2.1.0, request@2.27.0, configstore@0.2.3)
├── insight@0.3.1 (object-assign@0.1.2, async@0.2.10, lodash.debounce@2.4.1, request@2.27.0, configstore@0.2.3)
├── bower-registry-client@0.1.6 (request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, request@2.27.0, bower-config@0.4.5)
└── bower-config@0.5.0 (optimist@0.6.1, mout@0.6.0)

Dependencies installed.
  cached git://github.com/stefanpenner/ember-jj-abrams-resolver.git#e2acb295a5
  cached git://github.com/jquery/jquery.git#1.9.1
  cached git://github.com/jquery/qunit.git#1.12.0
  cached git://github.com/components/handlebars.js.git#1.3.0
  cached git://github.com/components/ember.git#1.5.0-beta.4
  cached git://github.com/components/ember-data.git#1.0.0-beta.7
  cached git://github.com/instructure/ic-ajax.git#0.3.0
  cached git://github.com/trek/ember-testing-httpRespond.git#0.1.2
  cached git://github.com/components/ember.git#1.5.0-beta.4
  cached git://github.com/components/ember.git#1.4.0
  cached git://github.com/components/ember.git#1.4.0
  cached git://github.com/trek/FakeXMLHttpRequest.git#0.0.1
  cached git://github.com/trek/fakehr.git#0.1.0
  cached git://github.com/components/handlebars.js.git#1.3.0
  cached git://github.com/jquery/jquery.git#2.0.3
$  cd zzz
$  ember init
installing
  identical .bowerrc
  identical .jshintrc
  identical .npmignore
  identical Brocfile.js
  identical api-stub/README.md
  identical api-stub/routes.js
  identical app/adapters/application.js
  identical app/app.js
  identical app/components/.gitkeep
  identical app/components/pretty-color.js
  identical app/components/template-less.js
  identical app/controllers/.gitkeep
  identical app/helpers/.gitkeep
  identical app/helpers/reverse-word.js
  identical app/models/.gitkeep
  identical app/router.js
  identical app/routes/.gitkeep
  identical app/routes/component_test.js
  identical app/routes/helper_test.js
  identical app/routes/index.js
  identical app/styles/.gitkeep
  identical app/styles/app.css
  identical app/templates/.gitkeep
  identical app/templates/application.hbs
  identical app/templates/component-test.hbs
  identical app/templates/components/.gitkeep
  identical app/templates/components/pretty-color.hbs
  identical app/templates/error.hbs
  identical app/templates/helper-test.hbs
  identical app/templates/index.hbs
  identical app/templates/loading.hbs
  identical app/utils/.gitkeep
  identical app/utils/ajax.js
  identical app/views/.gitkeep
  identical bower.json
  identical config/environment.js
  identical config/environments/development.js
  identical config/environments/production.js
  identical config/environments/test.js
  identical package.json
  identical public/index.html
  identical tests/.jshintrc
  identical tests/acceptance/component_test.js
  identical tests/acceptance/helper_test.js
  identical tests/acceptance/index_test.js
  identical tests/helpers/isolated_container.js
  identical tests/helpers/module_for.js
  identical tests/helpers/resolver.js
  identical tests/helpers/start_app.js
  identical tests/test_helper.js
  identical tests/test_loader.js
  identical tests/unit/.gitkeep
  identical tests/unit/components/pretty_color_test.js
  identical tests/unit/components/template_less_component_test.js
  identical tests/unit/routes/index_test.js
  identical vendor/loader.js

Dependencies installed.
$  ember server

module.js:340
    throw err;
    ^
Error: Cannot find module 'ember-cli/lib/preprocessors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/aarondavis/Development/Monolith/new/zzz/Brocfile.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
$  ember build
Unhandled Error

/usr/local/lib/node_modules/ember-cli/lib/cli.js:13
  throw error;
        ^
Error: Cannot find module 'ember-cli/lib/preprocessors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/aarondavis/Development/Monolith/new/zzz/Brocfile.js:5:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by JulianHang** [comment]
waitting...
