### ISSUE TITLE
Error: ENOTEMPTY when changing .hbs template file

### ISSUE THREAD

**Issue by davidlukerice** [ember-cli/ember-cli#1280]
ember server errors when trying to change a template file on windows with 0.0.39 (latest: c6e5f368b06f1522298b97eb8781f7215ef27e82)

```
file changed templates\application.hbs
ENOTEMPTY, directory not empty 'C:\projects\genSynth\app\tmp\static_compiler-tmp
_dest_dir-ABdrTYIF.tmp\vendor\bourbon\app\assets\stylesheets'
Error: ENOTEMPTY, directory not empty 'C:\projects\genSynth\app\tmp\static_compi
ler-tmp_dest_dir-ABdrTYIF.tmp\vendor\bourbon\app\assets\stylesheets'
    at Object.fs.rmdirSync (fs.js:612:18)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:247:11)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:216:26)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rimraf\rimra
f.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:216:26)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rimraf\rimra
f.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:216:26)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rimraf\rimra
f.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:216:26)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rimraf\rimra
f.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:216:26)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rimraf\rimra
f.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\
rimraf\rimraf.js:244:26)
    at rmdirSync (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\r
imraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\projects\genSynth\app\node_modules\ember-cli\node_mod
ules\rimraf\rimraf.js:150:5)
    at Function.rimrafSync [as sync] (C:\projects\genSynth\app\node_modules\embe
r-cli\node_modules\rimraf\rimraf.js:216:26)
    at remove (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\quic
k-temp\index.js:26:12)
    at Object.makeOrRemake (C:\projects\genSynth\app\node_modules\ember-cli\node
_modules\quick-temp\index.js:10:5)
    at StaticCompiler.Writer.read (C:\projects\genSynth\app\node_modules\ember-c
li\node_modules\broccoli-writer\index.js:10:13)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\broccoli\lib
\builder.js:78:23
    at tryCatch (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rs
vp\dist\commonjs\rsvp\-internal.js:163:16)
    at invokeCallback (C:\projects\genSynth\app\node_modules\ember-cli\node_modu
les\rsvp\dist\commonjs\rsvp\-internal.js:172:17)
    at C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rsvp\dist\co
mmonjs\rsvp\promise.js:186:17
    at flush (C:\projects\genSynth\app\node_modules\ember-cli\node_modules\rsvp\
dist\commonjs\rsvp\asap.js:51:9)
    at process._tickCallback (node.js:415:13)
```

**Comment by temo44** [comment]
I just want to comment the fix that worked for our entire team. It was actually proposed here npm/npm#7552 by miguelmota. Just perform the following commands:

    (npm install -g rimraf)
    rm -rf node_modules bower_components dist tmp
    npm install ember-cli --save-dev
    npm install
    bower install
Make sure that the first command is repeated until the entire tmp folder is gone. After this, enjoy your fast, not breaking build
