### ISSUE TITLE
Mocha has issue with ES6 modules

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#1292]
I have a fresh fork of the master branch. I've run a `npm install` successfully on the ember-cli dir. According to the docs, all that's left is to run `npm test`. I get the error:

```
E:\Code\ember-cli\tests\fixtures\brocfile-tests\default-development\tests\integr
ation\app-boots-test.js:4
import Ember from 'ember';
^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at E:\Code\ember-cli\node_modules\mocha\lib\mocha.js:172:27
    at Array.forEach (native)
    at Mocha.loadFiles (E:\Code\ember-cli\node_modules\mocha\lib\mocha.js:169:14
)
    at Mocha.run (E:\Code\ember-cli\node_modules\mocha\lib\mocha.js:356:31)
    at Object.<anonymous> (E:\Code\ember-cli\node_modules\mocha\bin\_mocha:366:1
6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Is there another step that I am\the docs are missing to get the tests to understand ES6 module syntax?

**Comment by yairEO** [comment]
fixed in what way? I see the error still
