### ISSUE TITLE
Proxy and self-signed certificate.

### ISSUE THREAD

**Issue by VboxNick** [ember-cli/ember-cli#1296]
I've got a backend with self-signed certificate installed. Ember-cli always tries to verify whether certificate valid or not. For  developer's reasons it should have an opportunity to enable/disable it, shouldn't it? Thanks.

```
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
    at SecurePair.<anonymous> (tls.js:1370:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
```

**Comment by turboMaCk** [comment]
@VboxNick How did you solve it?

**Comment by ksng** [comment]
Sorry, I should have closed this issue. It was related to node, not ember-cli

**Comment by VboxNick** [comment]
Sorry, I should have closed this issue. It was related to node, not ember-cli
