### ISSUE TITLE
can't fine modules

### ISSUE THREAD

**Issue by justinbkay** [ember-cli/ember-cli#1661]
I just installed ember-cli and I'm getting:

<pre>
<code>
ember -v

module.js:340
    throw err;
          ^
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jkay/node_modules/ember-cli/lib/ext/promise.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</code>
</pre>

I installed rsvp manually, but then got:

<pre>
<code>
ember -v                  

module.js:340
    throw err;
          ^
Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jkay/node_modules/ember-cli/node_modules/nopt/lib/nopt.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</code>
</pre>

I tried installing that, but no joy.

node: v0.10.30
npm: 1.4.23
ember-cli: 0.0.40

**Comment by patroqueeet** [comment]
same applies to me
