### ISSUE TITLE
Build Error: EISDIR, illegal operation on a directory

### ISSUE THREAD

**Issue by WooDzu** [ember-cli/ember-cli#1694]
Hi all. I'm just starting with ember-cli, here's what I get on Windows:

* npm install -g ember-cli
* ember new my-new-app2
* cd my-new-app2 && ember server

```
version: 0.0.40
EISDIR, illegal operation on a directory 'F:\SVN\Ember\my-new-app\tmp\remover-tmp_cache_dir-JlaWxDis.tmp\app.js'
Error: EISDIR, illegal operation on a directory 'F:\SVN\Ember\my-new-app\tmp\remover-tmp_cache_dir-JlaWxDis.tmp\app.js'
    at Object.fs.linkSync (fs.js:748:18)
    at linkAndOverwrite (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\broccoli-file-remover\node_modules\broccoli-caching-writer\index.js:104:8)
    at linkRecursivelySync (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\broccoli-file-remover\node_modules\broccoli-caching-writer\index.js:97:5)
    at linkRecursivelySync (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\broccoli-file-remover\node_modules\broccoli-caching-writer\index.js:91:7)
    at F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\broccoli-file-remover\node_modules\broccoli-caching-writer\index.js:43:5
    at $$$internal$$tryCatch (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:470:16)
    at $$$internal$$invokeCallback (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:482:17)
    at $$$internal$$publish (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:453:11)
    at $$rsvp$asap$$flush (F:\SVN\Ember\my-new-app\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1531:9)
    at process._tickCallback (node.js:415:13)
```

The server running on port 4200 gives the same build error as above.
I'm sorry if this is not a bug.

Windows 7 Pro
node 0.10.24, 0.10.30
npm 1.3.21, 1.4.21
bower 1.3.8
ember-cli 0.0.40

**Comment by jamesarosen** [comment]
I'm having a similar problem on OSX:
```
UNKNOWN, unknown error '/Volumes/Home Directory/my_project/tmp/concat-tmp_cache_dir-F0jYvIxl.tmp/cached-output'
Error: UNKNOWN, unknown error '/Volumes/Home Directory/my_project/tmp/concat-tmp_cache_dir-F0jYvIxl.tmp/cached-output'
    at Object.fs.linkSync (fs.js:759:18)
    at /Volumes/Home Directory/my_project/node_modules/ember-cli/node_modules/broccoli-concat/index.js:86:10
    at $$$internal$$tryCatch (/Volumes/Home Directory/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Volumes/Home Directory/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/Volumes/Home Directory/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/Volumes/Home Directory/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```
There are two things that might be getting in the way here:

 1. the space in `Home Directory`
 2. That `/Volumes/Home Directory/` is an [AFP](http://en.wikipedia.org/wiki/Apple_Filing_Protocol) mount

**Comment by ef4** [comment]
@jamesarosen the current ember-cli shouldn't be able to generate that stack trace, because it doesn't depend on broccoli-concat.

**Comment by jamesarosen** [comment]
Ember-CLI moves fast! I only created this Ember project 8 days ago. I'll try updating the dependencies.

**Comment by jamesarosen** [comment]
0.1.5 seems to have fixed. Thanks.
