### ISSUE TITLE
[0.0.42] Cannot install

### ISSUE THREAD

**Issue by mewben** [ember-cli/ember-cli#1856]
I just installed the recent version ember-cli 0.0.42.

When I fire `ember new emb42`, it throws the following error:

```
bower EACCES        EACCES, rename '/var/folders/jh/y1vmck9j6fg3hysd5pgndzn40000gn/T/melvin/bower/ember-qunit-notifications-23166-ssnciZ'

Stack trace:
Error: EACCES, rename '/var/folders/jh/y1vmck9j6fg3hysd5pgndzn40000gn/T/melvin/bower/ember-qunit-notifications-23166-ssnciZ'

System info:
Bower version: 1.3.9
Node version: 0.10.31
OS: Darwin 13.3.0 x64
ember-cli-qunit@0.0.5 postinstall: `bower install`
Exit status 1
Error: ember-cli-qunit@0.0.5 postinstall: `bower install`
Exit status 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

I tried with sudo but still no luck...

I also tried `ember init` and here is the error:

```
sudo ember init
version: 0.0.42
Cannot read property 'keywords' of undefined
TypeError: Cannot read property 'keywords' of undefined
    at Project.isEmberCLIAddon (/usr/local/lib/node_modules/ember-cli/lib/models/project.js:31:18)
    at Class.module.exports.Command.extend._defaultBlueprint (/usr/local/lib/node_modules/ember-cli/lib/commands/init.js:29:22)
    at Class.module.exports.Command.extend.run (/usr/local/lib/node_modules/ember-cli/lib/commands/init.js:64:51)
    at Class.Command.validateAndRun (/usr/local/lib/node_modules/ember-cli/lib/models/command.js:72:15)
    at /usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:54:22
    at $$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at /usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1066:13
    at $$rsvp$asap$$flush (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```

I also tried this with a windows machine and still no luck. :(

**Comment by ambasador** [comment]
I had the same error 

sudo bower install --allow-root

This the solution
