### ISSUE TITLE
Problem with creating new application

### ISSUE THREAD

**Issue by dlmccoy** [ember-cli/ember-cli#187]
After a clean install of ember-cli, I call 'ember new testapp', and get the following error:

```
/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/cache.js:1304
    throw new Error("Attempt to unlock " + u + ", which hasn't been locked")
          ^
Error: Attempt to unlock ember-cli@^0.0.16, which hasn't been locked
    at unlock (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/cache.js:1304:11)
    at cb (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/cache.js:646:5)
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/cache.js:655:20
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/cache.js:1290:7
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
    at OpenReq.Req.done (/usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
    at OpenReq.done (/usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
    at OpenReq.Req.done (/usr/local/lib/node_modules/ember-cli/node_modules/insight/node_modules/configstore/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/local/lib/node_modules/ember-cli/node_modules/insight/node_modules/configstore/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:107:15)
```

This doesn't seem to affect the subsequent 'npm install', 'bower install', or 'ember server', so maybe it's not worth thinking about too much, but it's a little alarming to see this every time I start a new ember application. Any ideas?

**Comment by narayand4** [comment]
Hi @stefanpenner same issue with me. i'm using ember version 0.2.0-beta.1. showing this in terminal when i create new ember app.

Error: Attempt to unlock /home/narayand4/projects/ember/userapp/node_modules/ember-cli, which hasn't been locked
    at unlock (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:66:11)
    at cb (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/install.js:929:5)
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/install.js:933:20
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:40:9
    at cb (/usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
    at OpenReq.Req.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    at OpenReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:64:22)

**Comment by narayand4** [comment]
node, npm + OS version are 
++++++++++++++++++++++++++
ubuntu 14.04 LTS
node version: v0.10.25
npm version: 1.3.10

when i'm creating my ember app with "sudo" like "sudo ember new userapp" then everything working fine.

**Comment by stefanpenner** [comment]
We don't actually support and npm version that old. I highly suggest upgrading to 2.x

**Comment by stefanpenner** [comment]
Basically at some point your npm crashed or was killed during install. And that session leaked a lock file in ~/.npm/_locks or something. Removing that should fix the current error. Upgrading npm will help prevent this but also give you a clear error that indicates exactly what file

**Comment by narayand4** [comment]
thanks i have updated my npm and node, now issue has been resolved.
