### ISSUE TITLE
Windows Brocoli Compilation Fails: nested loader.js/loader.js

### ISSUE THREAD

**Issue by srsgores** [ember-cli/ember-cli#2233]
Upgraded from `0.0.44` to `0.1.1`.  Upon following the directions listed on the upgrade guide, I get the following error:

```
C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end>ember server
version: 0.1.1
Livereload server on port 35729
Serving on http://0.0.0.0:4200

===== 1 JSHint Error

Path or pattern "bower_components/loader.js/loader.js" did not match any files [string exception]
Error: Path or pattern "bower_components/loader.js/loader.js" did not match any files [string exception]
  at C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:34:15
  at $$$internal$$tryCatch (C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\rsvp\dist\rsvp
.js:470:16)
  at $$$internal$$invokeCallback (C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\rsvp\dis
t\rsvp.js:482:17)
  at $$$internal$$publish (C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.
js:453:11)
  at $$$internal$$publishRejection (C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\rsvp\d
ist\rsvp.js:395:7)
  at $$rsvp$asap$$flush (C:\Users\Sean\Documents\svn\app\branch\development.br\app\front-end\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js
:1531:9)
  at process._tickCallback (node.js:419:13)
```

Would appreciate any advice on completing the migration.

**Comment by kirantpatil** [comment]
I am having the same issue but on Fedora. Please find the filed issue https://github.com/benoithubert/sails-ember-carpooling/issues/9#issuecomment-160759251

**Comment by stefanpenner** [comment]
@kirantpatil it appears the version of CLI you are using is quite old, let me recommend using 1.13.13.

**Comment by kirantpatil** [comment]
@stefanpenner, thanks and upgrade to 1.13.13 resolved the issue.

**Comment by stefanpenner** [comment]
Good to hear :). Happy hacking
