### ISSUE TITLE
Cannot run preprocessors on templates

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2383]
It appears that you can not run preprocessors on HBS files before they go through the template compiler, by the time my preprocessor runs the template files are already JS files. Using the "before" field in the package.json and setting it to "broccoli-ember-hbs-template-compiler" results in the following error. I think this is because it is not an addon.  I think it would be helpful to have a DAG on the registry and do a top sort before the instances are created. This would allow you to perform multiple preprocessors in a single addon if order matters.

```
Cannot read property 'pkg' of null
TypeError: Cannot read property 'pkg' of null
    at Function.Addon.resolvePath (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/models/addon.js:318:18)
    at Function.Addon.lookup (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/models/addon.js:333:22)
    at /Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/models/project.js:204:34
    at visit (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at Project.initializeAddons (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/models/project.js:202:9)
    at Project.eachAddonCommand (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/models/project.js:229:10)
    at module.exports (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/cli/lookup-command.js:52:13)
    at CLI.<anonymous> (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/lib/cli/cli.js:31:26)
    at $$$internal$$tryCatch (/Users/chietala/workspace/shift/ember-cli-pemberly/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
```

**Comment by zackthehuman** [comment]
Ping. I'm running in to this very issue right now. I'm using ember-cli 0.2.7. I'm also depending on `ember-cli-htmlbars` so how does this change the advice given above by @rwjblue ? It looks like I may be picking up what @chadhietala was working on before :)

**Comment by stefanpenner** [comment]
seems to have gone stale
