### ISSUE TITLE
File not found error when referencing config/environment from addon dummy applications.

### ISSUE THREAD

**Issue by SimonKaluza** [ember-cli/ember-cli#2776]
It seems the config file directory tree is not getting added to Ember CLI Addon projects when running `ember serve` to deploy the "dummy" application.

Though the EmberAddon object seems to correctly resolve the full path `dummy/config/environment.js` and pass this and the environment information to the Broccoli build correctly, any file in the dummy application that has an `import ENV from 'config/environment'` statement eventually throws "a file not found" error during the broccoli-es6-concatenation step as follow:

```
File: dummy/adapters/application.js
ENOENT, no such file or directory '/myproject/tmp/tree_merger-tmp_dest_dir-KG1tamoR.tmp/dummy/config/environment.js'
Error: ENOENT, no such file or directory '/myproject/tmp/tree_merger-tmp_dest_dir-KG1tamoR.tmp/dummy/config/environment.js'
    at Error (native)
    at Object.fs.statSync (fs.js:721:18)
    at addModule (/myproject/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:94:46)
    at addModule (/myproject/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:143:9)
    at /myproject/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:59:7
    at $$$internal$$tryCatch (/myproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/myproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/myproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/myproject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:372:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unable to resolve root /myproject/tests/dummy/app: directory /myproject/tests/dummy/app is not watched
    at null.<anonymous> (/myproject/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Readable.push (_stream_readable.js:125:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/myproject/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:265:12)
    at writeOrBuffer (_stream_writable.js:252:5)
```

Though I experimented with various filepathing tricks and modifying the EmberAddon's `configPath` property, no amount of tweaking could get this error to go away.  I did notice that [at one point during the EmberApp index tree generation the config file seems to get moved to a tree where it exists as config/environment/{development.json}](https://github.com/stefanpenner/ember-cli/blob/master/lib/broccoli/ember-app.js#L318) before it gets fed to Broccoli, which I think might be confusing the concatenator, though this doesn't explain why importing config/environment seems to work fine in my regular application.

If someone could point me in the right direction for where the es6 concatenator's configPath trees diverge from the rest of the build I'd be happy to work on a pull request that fixes this.

**Comment by bgentry** [comment]
I think I'm running into an issue like this with brand new generated addons. Here's the full list of commands and output:

```
➜ ember addon bg-test-addon
version: 0.1.6
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create tests/dummy/app/app.js
  create tests/dummy/app/components/.gitkeep
  create tests/dummy/app/controllers/.gitkeep
  create tests/dummy/app/helpers/.gitkeep
  create tests/dummy/app/index.html
  create tests/dummy/app/models/.gitkeep
  create tests/dummy/app/router.js
  create tests/dummy/app/routes/.gitkeep
  create tests/dummy/app/styles/app.css
  create tests/dummy/app/templates/application.hbs
  create tests/dummy/app/templates/components/.gitkeep
  create tests/dummy/app/views/.gitkeep
  create bower.json
  create tests/dummy/config/environment.js
  create .gitignore
  create package.json
  create tests/dummy/public/crossdomain.xml
  create tests/dummy/public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
  create LICENSE.md
  create config/environment.js
  create index.js
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.

➜ cd bg-test-addon

➜ ember install
version: 0.1.6
Installed browser packages via Bower.
Installed packages for tooling via npm.

➜ ember test
version: 0.1.6
Build failed.
ENOENT, no such file or directory 'app/'
Error: ENOENT, no such file or directory 'app/'
    at Object.fs.readdirSync (fs.js:666:18)
    at walkSync (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/walk-sync/index.js:14:20)
    at Funnel.processFilters (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:101:15)
    at Funnel.handleReadTree (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:87:10)
    at $$$internal$$tryCatch (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

➜ mkdir app && touch app/.gitkeep
version: 0.1.6
Build failed.
ENOENT, no such file or directory '/Users/bgentry/Code/bg-test-addon/tmp/funnel-dest_14xo09.tmp/index.html'
Error: ENOENT, no such file or directory '/Users/bgentry/Code/bg-test-addon/tmp/funnel-dest_14xo09.tmp/index.html'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at CustomReplace.processFile (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:58:21)
    at CustomReplace.process (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:53:10)
    at $$$internal$$tryCatch (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/bgentry/Code/bg-test-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Seems like at the very least the generator should add a `app/.gitkeep` since the tests don't work without it. But I have no idea what's going on with the missing `index.html` bit.

I've posted the full repo here: https://github.com/bgentry/bg-test-ember-addon

**Comment by rafalp** [comment]
@bgentry I too had "missing index.html" error in newly created ember addon, and I've solved it by changing `EmberApp` to `EmberAddon` as well as its import path in my brocfile.

**Comment by stefanpenner** [comment]
> version: 0.1.6

this should be fixed on the latest version (atleast the manifestation looks related to a recent fix)

**Comment by bgentry** [comment]
@stefanpenner looks like it works for me in 0.1.9 :+1:
