### ISSUE TITLE
File: app/templates/article.hbs Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by cannect** [ember-cli/ember-cli#2812]
Hi,

I updated to Ember-cli 0.1.4 and got this error when I run: `ember server`.
I use Windows 8.1 and the canary versions of Ember and Ember Data.

What is really strange is, that I do not have a property start in article.hbs, nor in the article.js view file.

Below the error log:
```
C:\xampp\htdocs\dev\app>ember server
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: app/templates/article.hbs
Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at HTMLProcessor.tokenHandlers.EndTag (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\token-handlers.js:134:84)
    at HTMLProcessor.acceptToken (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\parser.js:73:43)
    at forEach (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-util\array-utils.js:10:16)
    at HTMLProcessor.nodeHandlers.ContentStatement (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\node-handlers.js:85:12)
    at HTMLProcessor.acceptNode (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\parser.js:68:39)
    at HTMLProcessor.nodeHandlers.Program (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\node-handlers.js:22:12)
    at HTMLProcessor.acceptNode (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\parser.js:68:39)
    at HTMLProcessor.nodeHandlers.BlockStatement (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\node-handlers.js:52:40)
    at HTMLProcessor.acceptNode (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\parser.js:68:39)
    at HTMLProcessor.nodeHandlers.Program (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\node-handlers.js:22:12)
    at HTMLProcessor.acceptNode (C:\xampp\htdocs\dev\app\node_modules\ember-cli-htmlbars\node_modules\htmlbars\dist\cjs\htmlbars-syntax\parser.js:68:39)

```

**Comment by oneeman** [comment]
This seems to be htmlbars trying to throw an error for a mismatched end tag but it going wrong.  Specifically, I think this was most likely the same problem as in github.com/emberjs/ember.js/issues/9928 .  If so, it should be fixed now in canary.  If not, we would greatly appreciate it if you were able to replicate it and open up an issue on htmlbars.

**Comment by rwjblue** [comment]
@cannect - @oneeman is correct, this should be fixed on both canary and beta versions (as of v1.10.0-beta.3).  Closing for now, but will happily reopen if it is still an issue. (Thanks for fixing @oneeman!).
