### ISSUE TITLE
Build failed with default example

### ISSUE THREAD

**Issue by seven1240** [ember-cli/ember-cli#2870]
Hi there,

First thanks for the great project. I created a simple ember-cli project and it fails when build and ember server. I noticed it supports node 0.10.5 but my node is 0.10.13, is that a problem? Do you need more information on this? logs below. Thanks.

dujinfang@seven /t/t/t> ember build
version: 0.1.5
Looks like you have a different program called watchman, falling back to NodeWatcher
Build failed.
File: bower_components/bower_components/qunit/src/intro
Line 13: Unexpected end of input
Error: Line 13: Unexpected end of input
    at throwError (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2579:21)
    at throwUnexpected (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2611:13)
    at expect (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2650:13)
    at parseFunctionSourceElements (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:4610:9)
    at /private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
    at parseConciseBody (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:4551:20)
    at parseFunctionExpression (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:4826:16)
    at /private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
    at parsePrimaryExpression (/private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:3050:24)
    at /private/tmp/test/t/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
dujinfang@seven /t/t/t> ember version
version: 0.1.5
Looks like you have a different program called watchman, falling back to NodeWatcher
node: 0.10.13
npm: 2.1.8

**Comment by jakecraige** [comment]
Can you paste in what your `Brocfile.js` looks like? It looks like something is trying to import `qunit/src/intro.js` and it shouldn't be. Also, your `bower.json` and `package.json` would be helpful as well

**Comment by seven1240** [comment]
I just tried again and the problem is gone. something must be changed however I have no idea. Close this for now. Thanks for looking into that.
