### ISSUE TITLE
having both template.hbs and template.handlebars results in having a bad time

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2895]
having both:

```
templates/application.hbs
templates/application.handlebars
```

during `ember s`, followed by a rebuild results in:

```
file changed app.js
Error: EEXIST, file already exists '/Users/stefan/src/yapp/projects/yapp/tmp/template_compiler-tmp_dest_dir-qjvcNW4M.tmp/yapp/templates/application.js'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Object.copyPreserveSync (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/broccoli-kitchen-sink-helpers/index.js:150:8)
    at copyFromCache (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/index.js:108:15)
    at TemplateCompiler.Filter.processAndCacheFile (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/index.js:78:5)
    at /Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/index.js:39:23
    at /Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:11:14
    at $$$internal$$tryCatch (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/stefan/src/yapp/projects/yapp/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:473:11)
```

the error is almost useful.

**Comment by stefanpenner** [comment]
I suspect generators may want to be aware of such conflicts aswell.

**Comment by stefanpenner** [comment]
something good for ember-doctor cc @chadhietala

**Comment by stefanpenner** [comment]
hasn't come up, likely not an issue or extremely low on the triage order
