### ISSUE TITLE
ember serve fails if vendor does not have source map in expected location

### ISSUE THREAD

**Issue by tjhart** [ember-cli/ember-cli#2912]
To reproduce:

```
$ mkdir src-map-issue
$ cd src-map-issue
$ ember init
$ bower install js-xlsx --save

```

Then edit Brocfile.js to look like this:

```javascript
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

app.import('bower_components/js-xlsx/dist/xlsx.core.min.js'); //This is the interesting line

module.exports = app.toTree();
```

Then run `ember serve`:

```
ENOENT, no such file or directory '/Users/tjhart/projects/sandbox/tmp/tree_merger-tmp_dest_dir-08TvaFvL.tmp/bower_components/js-xlsx/dist/dist/xlsx.core.min.map'
Error: ENOENT, no such file or directory '/Users/tjhart/projects/sandbox/tmp/tree_merger-tmp_dest_dir-08TvaFvL.tmp/bower_components/js-xlsx/dist/dist/xlsx.core.min.map'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at SourceMap._resolveSourcemap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:183:17)
    at SourceMap._assimilateExistingMap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:216:21)
    at SourceMap._addMap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:196:8)
    at SourceMap.<anonymous> (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:82:21)
    at SourceMap._cacheEncoderResults (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:116:16)
    at SourceMap.addFile (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:80:8)
    at Class.<anonymous> (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
    at Array.forEach (native)
ENOENT, no such file or directory '/Users/tjhart/projects/sandbox/tmp/tree_merger-tmp_dest_dir-bASCh6Kw.tmp/bower_components/js-xlsx/dist/dist/xlsx.core.min.map'
Error: ENOENT, no such file or directory '/Users/tjhart/projects/sandbox/tmp/tree_merger-tmp_dest_dir-bASCh6Kw.tmp/bower_components/js-xlsx/dist/dist/xlsx.core.min.map'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at SourceMap._resolveSourcemap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:183:17)
    at SourceMap._assimilateExistingMap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:216:21)
    at SourceMap._addMap (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:196:8)
    at SourceMap.<anonymous> (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:82:21)
    at SourceMap._cacheEncoderResults (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:116:16)
    at SourceMap.addFile (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:80:8)
    at Class.<anonymous> (/Users/tjhart/projects/sandbox/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
    at Array.forEach (native)
```

**Comment by ef4** [comment]
I would argue this is really a bug in the way js-xlsx is writings its sourceMapURL. The package puts `xlsx.core.min.js` and `xlsx.core.min.map` side-by-side in the same directory, but the URL inside the JS file is written as `dist/xlsx.core.min.map` instead of `xlsx.core.min.map`. It's essentially a broken link.

If you remove that `dist/` prefix on the sourceMappingURL it works. Alternatively, if you create a `dist` subdir inside the existing `dist` and move the map files into it, it works.

It is arguably a bug that we fail instead of just ignoring the missing sourcemap.

**Comment by tjhart** [comment]
I agree that the package's map link is broken. I'm sure there are many packages in the wild with missing or broken source maps.

I'm stuck on 1.4 unless your team decides to ignore the broken link. In the build environment I'm forced to use packages as published.

**Comment by rwjblue** [comment]
@ef4 - I agree, feels like a bug to fail to build due to an invalid sourcemap url in dep.  I think that we should `console.log(chalk.yellow('<file-name> is stupid and this is why we can't have nice things.'))` then continue if the sourcemap URL is invalid/not-found.

**Comment by jakecraige** [comment]
:+1: that excellent error message. #jsrox

**Comment by ef4** [comment]
@tjhart I plan to fix this so it ignores the bad link. But in the mean time you can still upgrade to 1.5 by turning off sourcemaps with `{sourcemaps: { enabled: false }}` in your Brocfile.

**Comment by tjhart** [comment]
@ef4 Thanks for pointing that out. I missed it in the documentation. I still find the organization of the documentation (i.e., http://www.ember-cli.com), to be odd. It's difficult to find what I'm looking for if what I'm doing doesn't neatly fit into the expected task.

**Comment by ef4** [comment]
Yeah, the docs need improvement. This particular one only shows up due to being in the changelog.

**Comment by ef4** [comment]
This should be fixed in https://github.com/ef4/fast-sourcemap-concat/commit/1c637681462b2d62752f5abeb939f5864aae083f which is released in fast-sourcemap-concat 0.2.1.

**Comment by rwjblue** [comment]
I did kinda like my message, but yours looks more polite :smile:

**Comment by ef4** [comment]
I'm not prepared to bet that the exception won't someday be my own fault. :-)
