### ISSUE TITLE
addBowerPackageToProject doesn't allow host target

### ISSUE THREAD

**Issue by jasonmit** [ember-cli/ember-cli#2930]
`this.addBowerPackageToProject('foo', 'ssh://git@github.com/foo/bar.git#0.0.1');`

results in:
```sh
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
Package foo not found
Error: Package foo not found
    at createError (/Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:749:13)
    at /Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/Users/jasonmit/projects/dsp/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by jasonmit** [comment]
Closing, I think it may be possible with the options object that's passed into the bower module.

**Comment by MiguelMadero** [comment]
@jasonmit did you figure out how to do this? I'm facing the same issue
