### ISSUE TITLE
After upgrading to v0.1.6,  ember new command gets errors

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#2961]
I followed upgrade steps following the document (http://www.ember-cli.com/#upgrading-an-ember-cli-app)  
and run ```ember new testapp-0-1-6``` and got the error messages below.

````
Invalid Version: 0.0.t4
TypeError: Invalid Version: 0.0.t4
    at new SemVer (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/semver/semver.js:460:10)
    at Object.neq (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/core/resolvers/GitResolver.js:224:56)
    at GitHubResolver._savePkgMeta (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/core/resolvers/GitHubResolver.js:131:53)
    at _fulfilled (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:108:17)
````
What am I missing?
Thanks.

**Comment by stefanpenner** [comment]
can you provide an example app that demonstrates this issue. My apps upgraded nicely.

I suspect you package.json or bower.json contains 0.0.t4 by mistake.

**Comment by stefanpenner** [comment]
after thinking about it, this issue is with: https://github.com/quaertym/ember-cli-dependency-checker as if it fails it would try give a better failure of a version is invalid

**Comment by stefanpenner** [comment]
i just tried and was unable to demonstrate.. Bower was having issues earlier, maybe you got some malformed output.

Will reopen if steps to reproduce are provided.

**Comment by vsymguysung** [comment]
All of sudden, this error has gone.
Now ```ember new``` works without errors. I have no idea now but you may have.
Anyway it works now.
