### ISSUE TITLE
Test all is failing locally

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2966]
System:
```
OSX: 10.9.5
http_parser: 1.0
node: 0.10.33
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.29
zlib: 1.2.3
modules: 11
openssl: 1.0.1j
npm: 2.1.8
```

I'm at 9aab2d7eda2608 and everything seems good till we get to this one:

```bash
    ✓ ember addon foo, clean from scratch (3093ms)
      Running: node_modules/ember-cli/bin/ember server --port=54323 --live-reload=false


events.js:72
        throw er; // Unhandled 'error' event
              ^

Error: unable to resolve root /Users/chietala/workspace/ember-cli/tmp/some-cool-addon/tests/dummy/config: directory /Users/chietala/workspace/ember-cli/tmp/some-cool-addon/tests/dummy/config is not watched
    at null.<anonymous> (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:764:14)
    at emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

    ✓ ember addon without addon/ directory (1698ms)
    1) "after each" hook
```

And then FSEventStream bug rears it's ugly head again:

```bash
  Acceptance: express server restart
      Running: ../bin/ember new --skip-git express-server-restart-test-app
      Running: node_modules/ember-cli/bin/ember serve --silent --live-reload-port 32580 --port 49741
2015-01-12 16:52 ember[3367] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

2015-01-12 16:52 ember[3367] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)



events.js:72

        throw er; // Unhandled 'error' event
     
         ^

Error: unable to resolve root /Users/chietala/workspace/ember-cli/tmp/express-server-restart-test-app/app: directory /Users/chietala/workspace/ember-cli/tmp/express-server-restart-test-app/app is not watched
    at null.<anonymous> (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:764:14)
    at emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

    ✓ Server restarts successfully on copy1 (1646ms)
    2) "after each" hook

```
And another:

```bash

events.js:72

        throw er; // Unhandled 'error' event
              ^

Error: unable to resolve root /Users/chietala/workspace/ember-cli/tmp/some-cool-app/app: directory /Users/chietala/workspace/ember-cli/tmp/some-cool-app/app is not watched
    at null.<anonymous> (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:764:14)
    at emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/chietala/workspace/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

    ✓ ember new foo, build --watch development, and verify rebuilt after change (1535ms)
    3) "after each" hook
```

[Mocha error report](https://gist.github.com/chadhietala/95359cdd0d0d253f7d3e)

**Comment by stefanpenner** [comment]
strange, seems unrelated?

**Comment by chadhietala** [comment]
Future travelers... either Sublime Text 2.0.2 Build 2221 or some plugin that is causing runaway threads.

For instance there is this in the logs.
```
1/12/15 4:51:01.000 PM kernel[0]: process Sublime Text 2[1312] thread 6170 caught burning CPU! It used more than 50% CPU (Actual recent usage: 72%) over 180 seconds. thread lifetime cpu usage 201.361958 seconds, (187.390495 user, 13.971463 system) ledger info: balance: 90001221798 credit: 175405642693 debit: 85404420895 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 124615669401 
```
