### ISSUE TITLE
Build error on a brand new ember app

### ISSUE THREAD

**Issue by SirZach** [ember-cli/ember-cli#2977]
After running
```
ember new testapp
cd testapp
ember test
```

It produces the following:
```
zachs-mbp:testapp sirzach$ ember test
version: 0.1.4
valid watchman found, version: [3.0.0]
Build failed.
File: testapp/app.js
false == true
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/lib/visit.js:31:18)
    at transform (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:86:23)
    at compile (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:33:9)
    at EsnextFilter.processString (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/index.js:41:16)
    at EsnextFilter.Filter.processFile (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:82:21)
    at $$$internal$$tryCatch (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/sirzach/workspace/testapp/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
```

I can also reproduce in our real app which is what prompted me to try this out on a brand new app. @joshbuckley

**Comment by stefanpenner** [comment]
duplicate, please search before posting an issue.

https://github.com/ember-cli/ember-cli/issues/2968
https://github.com/ember-cli/ember-cli/issues/2974

**Comment by SirZach** [comment]
thank you for your quick response. sorry that my search results didn't find the two issues that you mentioned.

**Comment by stefanpenner** [comment]
@SirZach we can blame GH search :P
