### ISSUE TITLE
ember server error

### ISSUE THREAD

**Issue by liyang051** [ember-cli/ember-cli#2988]
I try to start a ember server on MacOS 10.10.1 by execute "ember new borrowers && cd borrowers && ember server".

```
$ ember --version
version: 0.1.5
node: 0.10.35
npm: 2.1.8
```
```
$ ember new borrowers && cd borrowers && ember server -p 8888
version: 0.1.5
Livereload server on port 40417
Serving on http://0.0.0.0:8888/
File: borrowers/app.js
false == true
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/lib/visit.js:31:18)
    at transform (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:86:23)
    at compile (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:33:9)
    at EsnextFilter.processString (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/index.js:41:16)
    at EsnextFilter.Filter.processFile (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:82:21)
    at $$$internal$$tryCatch (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/private/tmp/borrowers/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17))`
```
It's works several days ago.   Then I copy the old ember-cli-esnex directory to borrowers. It's works again. What's wrong with it?

**Comment by stefanpenner** [comment]
duplicate: https://github.com/ember-cli/ember-cli/search?q=AssertionError%3A+false+%3D%3D+true&type=Issues&utf8=%E2%9C%93

**Comment by liyang051** [comment]
@stefanpenner  Thanks.
