### ISSUE TITLE
6to5 Bug: unknown transformer true specified in blacklist

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#2999]
Hi friends!

Just updated an app from 0.1.5 to 0.1.7 - and I'm getting the below on `ember server`

```js
version: 0.1.7
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: my-app/app.js
unknown transformer true specified in blacklist
ReferenceError: unknown transformer true specified in blacklist
    at Function.transform._ensureTransformerNames (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transform.js:26:13)
    at Function.File.normaliseOptions (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/file.js:117:13)
    at new File (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/file.js:15:32)
    at Object.transform (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transform.js:9:14)
    at SixToFive.transform (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/index.js:23:21)
    at SixToFive.processString (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/index.js:31:15)
    at SixToFive.Filter.processFile (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-filter/index.js:82:21)
    at $$$internal$$tryCatch (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
```

Anyone seen this yet?  My wild guess would be it has something to do with my use of emberscript...

**Comment by stefanpenner** [comment]
it seems like `blacklist:` contains something strange

**Comment by hhff** [comment]
Thanks @stefanpenner !

Hmm - [this line](https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/transform.js#L23) in 6to5 appears to be the problem.  `keys` is an array - not an object, so replacing that line with:

```js
for (var i = 0; i < keys.length; i++) {
```
Fixes the above error - but trickles to a new error instead.

```js
version: 0.1.7
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: ember-cli-spree-frontend/app.js
ember-cli-spree-frontend/app.js: Cannot read property 'id' of undefined
TypeError: ember-cli-spree-frontend/app.js: Cannot read property 'id' of undefined
    at TraversalContext.exports.VariableDeclaration (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformers/es6-destructuring.js:283:27)
    at TraversalContext.<anonymous> (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformer.js:68:17)
    at TraversalContext.visit (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:72:25)
    at traverse (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:120:17)
    at TraversalContext.visit (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:85:3)
    at traverse (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:134:15)
    at Transformer.transform (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformer.js:74:3)
    at /Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/file.js:280:17
    at Function.forEach (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/lodash/dist/lodash.js:3297:15)
    at File.transform (/Users/hhff/dev/Ember/spree_ember/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/file.js:279:5)
```

How do you want to attack this Stef?  Should I open something in 6to5 - or should we continue here for a bit longer?  I won't be able to deep dive into this for a while...

**Comment by stefanpenner** [comment]
it seems something is funky with config, as my own apps appear fine. Can you isolate in a public repo? I would love to see what is going on.

**Comment by hhff** [comment]
@stefanpenner can do !  gimme a few hours

**Comment by hhff** [comment]
@stefanpenner - managed to repro in a new app.

https://github.com/hhff/6to5-bug

Seems like the initializer written in EmberScript is the issue

If I uninstall 6to5 - everything works fine.

**Comment by sebmck** [comment]
Likely has something to do with an ember dependency globally polluting some native prototypes.

**Comment by sebmck** [comment]
Looks like it's ember itself polluting `Array.prototype` with `isEnumerable`. I'm planning on replacing all `for (var i in arr)` loops to `for (var i = 0; i < arr.length; i++)` anyway for a small perf boost but ember really shouldn't be doing this anyway, it'll introduce subtle bugs that I'm sure have probably biten someone in the ass before.

**Comment by rwjblue** [comment]
@sebmck - This is erroring in node, where Ember is not loaded at all.

**Comment by sebmck** [comment]
@rwjblue Something ember is being loaded. When I run `ember build` on @hhff's [6to5-bug](https://github.com/hhff/6to5-bug) repo I get that error message.

**Comment by rwjblue** [comment]
@sebmck - You are correct.  [ember-script]((https://github.com/ghempton/ember-script)) is loading Ember.

**Comment by sebmck** [comment]
As of 2.12.4 I've changed all array iteration to basic `for` loops instead of `for...in`. I'm still of the opinion that this should also be fixed upstream as polluting globals is a big no-no.

**Comment by rwjblue** [comment]
@sebmck - Completely agree.

**Comment by hhff** [comment]
nice!  thanks dudes

starting the bump train

**Comment by stefanpenner** [comment]
that version of broccoli-6to5 is out.

**Comment by hhff** [comment]
will test noaw

**Comment by hhff** [comment]
Testing with the new version of 6to5-core, I get past the above error, but now I'm hitting another.

[This function](https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/transformers/es6-let-scoping.js#L27) is the problem.  I tried commenting ```delete declars[i]._let;``` and the app loaded nicely - so we're getting close!  It would appear emberscript (and most likely prototype extensions) are causing undefined values to be passed into ```declars```.

@sebmck I'm looking into this at the moment - but if you have any clues I'd love to hear em

```js
version: 0.1.7
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: blank/initializers/export-application-global.js
blank/initializers/export-application-global.js: Cannot convert null to object
TypeError: blank/initializers/export-application-global.js: Cannot convert null to object
    at standardiseLets (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformers/es6-let-scoping.js:29:19)
    at LetScoping.noClosure (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformers/es6-let-scoping.js:156:3)
    at LetScoping.run (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformers/es6-let-scoping.js:102:46)
    at TraversalContext.exports.BlockStatement (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformers/es6-let-scoping.js:61:16)
    at TraversalContext.<anonymous> (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/transformation/transformer.js:68:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:72:25)
    at traverse (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:134:15)
    at TraversalContext.visit (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:85:3)
    at traverse (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:134:15)
    at TraversalContext.visit (/usr/local/lib/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/lib/6to5/traverse/index.js:85:3)
```

**Comment by hhff** [comment]
Just pushed up a fix: https://github.com/6to5/6to5/pull/509

Not sure it's the best place to fix this - more pushed up for discussion...

thoughts @sebmck / @stefanpenner / @rwjblue ?  

Sorry to bug - but realized with the new version of broccoli-6to5-transpiler (Stef just released this morning) anyone attempting to use EmberScript in a new app will get this error

**Comment by hhff** [comment]
due to [this version line in ember-cli-6to5](https://github.com/gordonkristan/ember-cli-6to5/blob/master/package.json#L19)

**Comment by sebmck** [comment]
@hhff Looks like there was a `for...in` loop were there shouldn't have been. Fixed in 2.12.5

**Comment by hhff** [comment]
thanks @sebmck - will restart the bump train

**Comment by hhff** [comment]
hi all just tested with `2.0.4` of the broccoli transpiler and all is :+1:

**Comment by stefanpenner** [comment]
:+1:
