### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#3004]
Trying to get my code to work on my host OSX box I have created a new user to overcome the bodged Node installation and have managed to get a bit further. 

Running ```ember server``` now yields this:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at sequence (/Users/dev/sonatribe/src/sonatribe-ui/node_modules/broccoli-caching-writer/node_modules/promise-map-series/index.js:4:21)
    at CompassCompiler.proto.read (/Users/dev/sonatribe/src/sonatribe-ui/node_modules/broccoli-caching-writer/index.js:74:10)
    at /Users/dev/sonatribe/src/sonatribe-ui/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at $$$internal$$tryCatch (/Users/dev/sonatribe/src/sonatribe-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/dev/sonatribe/src/sonatribe-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at /Users/dev/sonatribe/src/sonatribe-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1066:13
    at $$rsvp$asap$$flush (/Users/dev/sonatribe/src/sonatribe-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:415:13)
```

Does anyone have any clue as to what that might be telling me?

**Comment by wayne-o** [comment]
Or, how can i debug this?

**Comment by stefanpenner** [comment]
what versions of stuff?
can you provide a repo that demonstrates this.

**Comment by wayne-o** [comment]
Updgraded to latest and this is not an issue any more

**Comment by stefanpenner** [comment]
woohoo!!
