### ISSUE TITLE
Creating a new addon does not generate a working addon starting in 0.1.6

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#3016]
In 0.1.5 I can run `ember addon test-new-addon` go into the directory, run `ember s` and the addon will build and I can run tests sucessfully. 

In 0.1.6 and 0.1.7 `ember addon test-addons` still generates a directory, but is missing the `app` and `addon` directories. If I add them back and run `ember s`, it then fails looking for an index.html. 

Error for the index.html: 

```
uild failed.
    ENOENT, no such file or directory
    '/Users/katie/dev/test-addons/tmp/funnel-dest_DvqdRf.tmp/index.html'
    Error: ENOENT, no such file or directory
    '/Users/katie/dev/test-addons/tmp/funnel-dest_DvqdRf.tmp/index.html'
        at Object.fs.openSync (fs.js:438:18)
        at Object.fs.readFileSync (fs.js:289:15)
        at CustomReplace.processFile
    (/Users/katie/dev/test-addons/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:58:21)
        at CustomReplace.process
    (/Users/katie/dev/test-addons/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:53:10)
        at $$$internal$$tryCatch
    (/Users/katie/dev/test-addons/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
        at $$$internal$$invokeCallback
    (/Users/katie/dev/test-addons/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
        at $$$internal$$publish
    (/Users/katie/dev/test-addons/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
        at Object.$$rsvp$asap$$flush [as _onImmediate]
    (/Users/katie/dev/test-addons/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
        at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by stefanpenner** [comment]
i believe this is a duplicate and may be fixed on master. @jgwhite c/d?

**Comment by kategengler** [comment]
Shoot, sorry. I looked through issues but think I was still filtering on open, oops. Found it this time https://github.com/ember-cli/ember-cli/issues/2980
