### ISSUE TITLE
Unable to resolve root (watchman)

### ISSUE THREAD

**Issue by oskarrough** [ember-cli/ember-cli#3017]
Hi, I just ran brew update/upgrade, npm update -g etc. and tried a new `ember new my-app`. Watchman is installed. I'm on OS X 10.10.1 and npm v0.10.35. This is what I get with watchman:

```
version: 0.1.7
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: unable to resolve root /Users/oskar/Sites/my-app/my-app/app: directory /Users/oskar/Sites/my-app/my-app/app is not watched
    at null.<anonymous> (/Users/oskar/Sites/my-app/my-app/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:765:14)
    at emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Readable.push (_stream_readable.js:128:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/oskar/Sites/my-app/my-app/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
```

This is what I get without watchman:

```
2015-01-17 17:30 ember[12178] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
2015-01-17 17:30 ember[12178] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by stefanpenner** [comment]
> npm update -g

is absolutely not a good idea, even the NPM team advises against it. Please follow the upgrade steps we have detailed in the release notes. https://github.com/ember-cli/ember-cli/releases/tag/v0.1.7 as time permits we will continue to improve the upgrade flow.

**Comment by oskarrough** [comment]
Ok, thank you! Yes I do use Sublime.

The 0.1.7 release notes says to install ember-cli@0.1.5 - is this correct?

**Comment by chadhietala** [comment]
@oskarrough I updated the release. It should be `ember-cli@0.1.7`. Sorry about the confusion.

**Comment by oskarrough** [comment]
And then I got it working. Thank you both.
