### ISSUE TITLE
Running node --debug for ember test throws error:   throw new Error('can\'t set raw mode on non-tty');

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#3038]
I'm trying to debug a qunit ember integration test. But am coming up against a deprecation on the ```View``` export:

I'm running like so:

```/usr/local/bin/node --debug-brk=59771 --nolazy --harmony /Users/me/github/app/node_modules/ember-cli/bin/ember test -s```

The output:

```
debugger listening on port 59771
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
BuildingBuilding.Building..Building...Building...

Build successful - 1853ms.
c[?25l[8;NaNrtty.setRawMode: Use `process.stdin.setRawMode()` instead.

tty.js:37
    throw new Error('can\'t set raw mode on non-tty');
          ^
Error: can't set raw mode on non-tty
    at tty.js:37:11
    at deprecated (util.js:77:15)
    at module.exports.View.extend.cleanup (/Users/me/github/app/node_modules/app/node_modules/testem/lib/dev/ui/appview.js:260:5)
```

**Comment by joostdevries** [comment]
@QuantumInformation From your trace this looks like a problem with testem and not ember.

**Comment by QuantumInformation** [comment]
@joostdevries  Ok, will I close it and raise it over at testem?

**Comment by joostdevries** [comment]
@QuantumInformation I think that's probably best.

**Comment by QuantumInformation** [comment]
Yeah its defo testem, will raise it over there..
```
node_modules/ember-cli/node_modules/testem/testem.js test -s
debugger listening on port 60937
c[?25l[8;NaNr[r[?25htty.setRawMode: Use `process.stdin.setRawMode()` instead.```
