### ISSUE TITLE
Cleanup error ENOTEMPTY

### ISSUE THREAD

**Issue by raytiley** [ember-cli/ember-cli#3044]
Creating an issue to keep track of where I get with this. The `ember build` command seems to fail sporadically on windows. The builds don't necessarily "fail" but the writing to stderr seems to trip up our CI server. I've seen this on two machines now and its pretty regular 1 out of 10 builds seem have the cleanup error. 

I've confirmed that there is no search indexing or ant-virus running on ether machines. Also the source of the failure isn't consistent. I've seen it in funnel-dest, merge_trees_dest, and broccoli_asset_rewrite tmp folders.

My only idea is that our CI (Jenkins / MSBuild) might be monitoring the files, or there is some sort of race condition in the cleanup code.

As a workaround I might add an option to ember-cli to disable cleanup since for CI we don't care since the project gets `git clean` run against it anyway.

```
D:\code\cablecast\Web\cablecast-ui>ember build --output-path D:\build-test --p
roduction
version: 0.1.5
The option '--production' is not supported by the build command. Run `ember buil
d --help` for a list of supported options.
Cleanup error.
ENOTEMPTY, directory not empty 'D:\code\cablecast\Web\cablecast-ui\tmp\funnel-de
st_835aAw.tmp'
Error: ENOTEMPTY, directory not empty 'D:\code\cablecast\Web\cablecast-ui\tmp\fu
nnel-dest_835aAw.tmp'
    at Object.fs.rmdirSync (fs.js:623:18)
    at rmkidsSync (D:\code\cablecast\Web\cablecast-ui\node_modules\ember-cli\nod
e_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (D:\code\cablecast\Web\cablecast-ui\node_modules\ember-cli\node
_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (D:\code\cablecast\Web\cablecast-ui\node_modules\ember-cl
i\node_modules\rimraf\rimraf.js:150:5)
    at Function.rimrafSync [as sync] (D:\code\cablecast\Web\cablecast-ui\node_mo
dules\ember-cli\node_modules\rimraf\rimraf.js:216:26)
    at Funnel.cleanup (D:\code\cablecast\Web\cablecast-ui\node_modules\ember-cli
\node_modules\broccoli-funnel\index.js:96:19)
    at cleanupTree (D:\code\cablecast\Web\cablecast-ui\node_modules\ember-cli\no
de_modules\broccoli\lib\builder.js:128:19)
    at promise.then.then.results.(anonymous function) (D:\code\cablecast\Web\cab
lecast-ui\node_modules\ember-cli\node_modules\broccoli\node_modules\promise-map-
series\index.js:8:27)
    at $$$internal$$tryCatch (D:\code\cablecast\Web\cablecast-ui\node_modules\em
ber-cli\node_modules\rsvp\dist\rsvp.js:490:16)
    at $$$internal$$invokeCallback (D:\code\cablecast\Web\cablecast-ui\node_modu
les\ember-cli\node_modules\rsvp\dist\rsvp.js:502:17)
Built project successfully. Stored in "D:\build-test".

D:\code\cablecast\Web\cablecast-ui>
```

**Comment by kellyselden** [comment]
Here is a sample of my build script that puts a band-aid on this issue. Hopefully it helps someone.

```batch
set count=0
:restart-build
ember build --environment=%1 >stdout.txt
findstr /C:"Cleanup error" stdout.txt
if %errorlevel%==0 goto :error
goto :success
:error
set /a count+=1
if %count% lss 10 (
	goto :restart-build
) else (
	exit /b 1
)
:success
del stdout.txt
```

**Comment by raytiley** [comment]
Nice. I'm still looking into making this a non issue, but I think some of the issues will need to wait on the broccoli api changes to centralize temp directory.

**Comment by stefanpenner** [comment]
@raytiley yes, those same changes seem to also enable async cleanup, which would allow for a more "resilient" sync.

**Comment by csprocket777** [comment]
I'm also experiencing a similar issue, however I'm on a linux server running an automated build from TeamCity.

OS:
```
Red Hat Enterprise Linux Server release 5.5 (Tikanga)
```

Error:
```
Cleanup error.
ENOTEMPTY, directory not empty '/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/tmp/class-tmp_cache_dir-SZ7EFFV1.tmp/assets'
Error: ENOTEMPTY, directory not empty '/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/tmp/class-tmp_cache_dir-SZ7EFFV1.tmp/assets'
    at Object.fs.rmdirSync (fs.js:612:18)
    at rmkidsSync (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:247:11)
    at rmdirSync (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:237:7)
    at rimrafSync (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:219:5)
    at /ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:244:26)
    at rmdirSync (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:237:7)
    at Function.rimrafSync [as sync] (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:219:5)
    at Object.remove (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/quick-temp/index.js:26:12)
Build failed.
Path or pattern "bower_components/loader.js/loader.js" did not match any files
Error: Path or pattern "bower_components/loader.js/loader.js" did not match any files
    at Object.multiGlob (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at $$$internal$$tryCatch (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/ls/teamcity-ci/TeamCity/buildAgent/work/ef3cf965c964a927/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```


Any workaround?

**Comment by stefanpenner** [comment]
broccoli issue (and this one appears to not be directly an issue right now)

I have WIP that aims to address this in broccoli, it will likely take about a month or so to land all the pieces.
