### ISSUE TITLE
EPERM, operation not permitted ... funnel-dest_BFZ6vs.tmp

### ISSUE THREAD

**Issue by corsen2000** [ember-cli/ember-cli#3066]
Hello,

I am using ember-cli to create an addon and everything usually works great.  Occasionally I get the following error, which results in my screen not refreshing with the changes when making a save.

```
EPERM, operation not permitted 'C:\Users\USER\Documents\hello\tmp\funnel-dest_PU0h8p.tmp'
Error: EPERM, operation not permitted 'C:\Users\USER\Documents\hello\tmp\funnel-dest_PU0h8p.tmp'
    at Object.fs.mkdirSync (fs.js:642:18)
    at Function.sync (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\mkdirp\index.js:70:13)
    at Funnel.handleReadTree (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:85:12)
    at $$$internal$$tryCatch (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:490:16)
    at $$$internal$$invokeCallback (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:502:17)
    at $$$internal$$publish (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (C:\Users\USER\Documents\hello\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
file changed components\tf-my-item.js
```

If I make another file edit and save everything is fine and my page reloads again.

I am running on Windows 7 and have followed the windows steps excluding the defender changes which I can not do.  Those steps greatly increased performance, but I still run into this issue occasionally.

Node v0.10.28

Seems similar to #3044 , but not exactly the same error.

Is there anything I can do to get more information?

Thank you.

**Comment by stefanpenner** [comment]
@corsen2000 this is the result of a deficiency in windows file-systems + unlinking files. Their is another effort coming to help mitigate this further. The issue will be solved deep in broccoli.

As this isn't ideal, but ember-cli recovers. I am going to close this. If you want you are welcome to open the issue up on broccoli, but i do know it is a point we are aware of, and an effort already exists to address.

**Comment by corsen2000** [comment]
Thanks for the information.  Happy to hear it is on the radar.  Definitely manageable for now.

**Comment by Larivact** [comment]
Apparently still an issue. I am experiencing exactly the same as @corsen2000 described (using Windows 7). I  occasionally get ```EPERM, unlink``` or ```EPERM, operation not permitted``` but after saving a file it recovers.
