### ISSUE TITLE
0.1.8 fails with `Cannot call method 'bind' of undefined`

### ISSUE THREAD

**Issue by zeppelin** [ember-cli/ember-cli#3075]
Both `ember server` & `npm test` fails

npm: 2.2.0
node: v0.10.33
osx 10.10

`ember-server`

```
~/tc/client  ± minor-enhancements   ember server
version: 0.1.8
Cannot call method 'bind' of undefined
TypeError: Cannot call method 'bind' of undefined
  at Function.Watcher (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/sane/index.js:64:33)
  at Class.module.exports.Task.extend.init (/Users/Zeppelin/tc/client/node_modules/ember-cli/lib/models/server-watcher.js:9:56)
  at new Class (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
  at Class.module.exports.Task.extend.run (/Users/Zeppelin/tc/client/node_modules/ember-cli/lib/tasks/serve.js:32:23)
  at Class.module.exports.Command.extend.run (/Users/Zeppelin/tc/client/node_modules/ember-cli/lib/commands/serve.js:47:18)
  at Class.<anonymous> (/Users/Zeppelin/tc/client/node_modules/ember-cli/lib/models/command.js:131:17)
  at $$$internal$$tryCatch (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

`npm test`

```
 ✘  ~/tc/client  ± minor-enhancements   npm test

> terracycle@0.0.1 test /Users/Zeppelin/tc/client
> ember test

version: 0.1.8
Built project successfully. Stored in "/Users/Zeppelin/tc/client/tmp/class-tests_dist-tyioNlMM.tmp".
not ok 1 PhantomJS 1.9 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Parse error
        Log: >
    ...

1..1
# tests 1
# pass  0
# fail  1
npm ERR! Test failed.  See above for more details.
```

**Comment by stefanpenner** [comment]
what version of node, npm, what os.

**Comment by stefanpenner** [comment]
seems like an old version of sane, https://github.com/amasad/sane/blob/master/index.js does not contain a line 64.

**Comment by zeppelin** [comment]
sorry, edited

**Comment by stefanpenner** [comment]
can you cat this file /Users/Zeppelin/tc/client/node_modules/ember-cli/node_modules/sane/index.js ?

**Comment by zeppelin** [comment]
here you are sir: http://cl.ly/code/0K2L2u3p3d3n

**Comment by stefanpenner** [comment]
yes this is the wrong sane

**Comment by zeppelin** [comment]
shouldn't `nom` take care of this?

**Comment by stefanpenner** [comment]
```sh
wget http://registry.npmjs.org/ember-cli/-/ember-cli-0.1.8.tgz
tar -tvf  ember-cli-0.1.8.tgz | grep node_modules/sane
```

yields 2 installations of sane, 

  "sane": "1.0.0-rc1"
  "sane": "0.8.0",

**Comment by stefanpenner** [comment]
find . -iname package.json  | xargs jq '{name: .name, deps: .dependencies}' yields ember-cli is for some reason including it

**Comment by jgwhite** [comment]
Looks like sane is a bundled dependency and has been for a while:
https://github.com/ember-cli/ember-cli/blob/master/package.json#L81

**Comment by stefanpenner** [comment]
@jgwhite ya its fixed https://github.com/ember-cli/ember-cli/commit/52623293ad95

**Comment by stefanpenner** [comment]
looks like sane in broccoli-sane-watcher also needs to be updated, but i don't have time for that right now I can do that this weekend (unless someone can beet me)

**Comment by stefanpenner** [comment]
@zeppelin can you cat `node_modules/broccoli-sane-watcher/node_modules/sane/index.js` for me?

**Comment by zeppelin** [comment]
I don't even have `node_modules/broccoli-sane-watcher`

**Comment by stefanpenner** [comment]
sorry edited

**Comment by zeppelin** [comment]
```js
'use strict';

var NodeWatcher = require('./src/node_watcher');
var PollWatcher = require('./src/poll_watcher');
var WatchmanWatcher = require('./src/watchman_watcher');

function sane(dir, options) {
  if (options.poll) {
    return new PollWatcher(dir, options);
  } else if (options.watchman) {
    return new WatchmanWatcher(dir, options);
  } else {
    return new NodeWatcher(dir, options);
  }
}

module.exports = sane;
sane.NodeWatcher = NodeWatcher;
sane.PollWatcher = PollWatcher;
sane.WatchmanWatcher = WatchmanWatcher;
```

looks a lot like https://github.com/amasad/sane/blob/master/index.js

**Comment by jgwhite** [comment]
@zeppelin do you have time for a quick screenshare? Would be great to know exactly what conditions trigger this.

**Comment by jgwhite** [comment]
@zeppelin I’m jamie@jgwhite.co.uk on Screenhero. Ping me if you have a moment.

**Comment by zeppelin** [comment]
thanks a lot guys! if someone tells me again oss doesn't have proper support, I'll have him eat his hat :P

**Comment by jgwhite** [comment]
:smile:
