### ISSUE TITLE
Error with ember new on 0.1.8

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli#3080]
I'm getting an error trying to `ember new app-name` with 0.1.8. Here's what I tried to verify a clean reproduction (note that I did get some warnings below so maybe that is related to my issue?

Let me know if I can provide further info that would be helpful.

```
➜  npm uninstall -g ember-cli
unbuild ember-cli@0.1.8
npm %                                                                                                             
➜  npm cache clean
➜  olo  npm install -g ember-cli
/usr/local/bin/ember -> /usr/local/lib/node_modules/ember-cli/bin/ember
npm WARN unmet dependency /usr/local/lib/node_modules/cli-test/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cli-test/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
npm WARN unmet dependency /usr/local/lib/node_modules/cli-test/node_modules/ember-cli/node_modules/broccoli-replace/node_modules/applause/node_modules/cson/node_modules/js2coffee/node_modules/docpad/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cli-test/node_modules/ember-cli/node_modules/broccoli-replace/node_modules/applause/node_modules/cson/node_modules/js2coffee/node_modules/docpad/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/cookie-parser requires cookie@'0.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie,
npm WARN unmet dependency which is version 0.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/cookie-parser requires cookie-signature@'1.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie-signature,
npm WARN unmet dependency which is version 0.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/finalhandler requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/method-override requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/method-override requires methods@'1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/methods,
npm WARN unmet dependency which is version 0.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/connect-timeout requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/serve-static requires send@'0.9.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/send,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/serve-favicon requires fresh@'0.2.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/fresh,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/body-parser requires bytes@'1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/bytes,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/body-parser requires qs@'2.2.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/qs,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/compression requires bytes@'1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/bytes,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/compression requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/express-session requires cookie@'0.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie,
npm WARN unmet dependency which is version 0.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/express-session requires cookie-signature@'1.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie-signature,
npm WARN unmet dependency which is version 0.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/express-session requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/serve-index requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/csurf requires cookie@'0.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie,
npm WARN unmet dependency which is version 0.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/csurf requires cookie-signature@'1.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/cookie-signature,
npm WARN unmet dependency which is version 0.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body requires bytes@'1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/yapp-jslib/node_modules/testem/node_modules/express/node_modules/connect/node_modules/bytes,
npm WARN unmet dependency which is version 0.1.0
ember-cli@0.1.8 /usr/local/lib/node_modules/ember-cli
├── abbrev@1.0.5
├── js-string-escape@1.0.0
├── exit@0.1.2
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
├── debug@2.1.1 (ms@0.6.2)
├── temp@0.8.1 (rimraf@2.2.8)
├── http-proxy@1.8.1 (requires-port@0.0.0, eventemitter3@0.1.6)
├── broccoli-writer@0.1.1 (rsvp@3.0.16, quick-temp@0.1.2)
├── yam@0.0.17 (findup@0.1.5, fs-extra@0.8.1, lodash@2.4.1)
├── broccoli-sourcemap-concat@0.4.3 (combined-stream@0.0.7, mkdirp@0.5.0, rsvp@3.0.16, broccoli-caching-writer@0.5.3, broccoli-kitchen-sink-helpers@0.2.6, fast-sourcemap-concat@0.2.1, lodash-node@2.4.1)
├── broccoli-caching-writer@0.5.1 (promise-map-series@0.2.1, rimraf@2.2.8, rsvp@3.0.16, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6, core-object@0.0.2)
└── broccoli-es6modules@0.4.0 (walk-sync@0.1.3, mkdirp@0.5.0, broccoli-kitchen-sink-helpers@0.2.6, broccoli-caching-writer@0.5.3, esperanto@0.6.3)

➜  ember new my-app

module.js:340
    throw err;
          ^
Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lmelia/p/node_modules/ember-cli/node_modules/nopt/lib/nopt.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by jgwhite** [comment]
Which versions of node and npm are you running?

**Comment by lukemelia** [comment]
```
➜    node -v
v0.10.33
➜    npm -v
2.1.11
```

I just tried the same thing with 0.1.7 though and and am getting the same error, so it seems likely to be a configuration issue on my machine.

**Comment by jgwhite** [comment]
Any `npm link`’d modules?

**Comment by lukemelia** [comment]
A bunch of my own ember-components are npm linked, but nothing used by ember-cli

**Comment by lukemelia** [comment]
It looks like ember-cli/node_modules/nopt/node_modules doesn't exist in my install. I assume it should?

**Comment by jgwhite** [comment]
I’m a little confused by that. The abbrev dependency must be satisfied elsewhere.

**Comment by jgwhite** [comment]
@lukemelia do you have `ember-cli/node_modules/abbrev`?

**Comment by lukemelia** [comment]
@jgwhite yes, the package does exist there. the line that is failing is nopt trying to call `require("abbrev")`

**Comment by lukemelia** [comment]
I figured it out. I somehow had a rogue `node_modules` dir higher up in the tree I was running the command in. Sorry for the distraction!

**Comment by jgwhite** [comment]
Phew! :relieved:
