### ISSUE TITLE
Cannot reassign imported binding `Config`

### ISSUE THREAD

**Issue by kimf** [ember-cli/ember-cli#3104]
Just upgraded to 0.1.9, and get this weird error.. the funny part is I dont even have a backbone/initializers folder...

```
File: backbone/initializers/config
Cannot reassign imported binding `Config`
Error: Cannot reassign imported binding `Config`
    at disallowIllegalReassignment (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:1009:9)
    at Controller.estraverse.traverse.enter (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:1099:4)
    at Controller.__execute (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/estraverse/estraverse.js:495:28)
    at Object.traverse (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/estraverse/estraverse.js:707:27)
    at traverseAst (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:1075:13)
    at utils_transformBody__transformBody (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:1917:2)
    at strictMode_amd__amd (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:2043:2)
    at Object.toAmd (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/esperanto.js:2435:10)
    at Class.module.exports.CachingWriter.extend.transpileThroughCache (/backbone/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:50:24)```

ember -v
version: 0.1.9
node: 0.10.35
npm: 2.1.8

npm -v
2.3.0

**Comment by rwjblue** [comment]
The first part is usually the name of your app (in this case `backbone`), but it is referencing `app/initializers/config`.  My guess is that you are doing something that reassigns an imported `Config` variable:

**Comment by rwjblue** [comment]
Perhaps something like:

```javascript
import Config from "../config/environment";

Config = "adsf";
```

**Comment by kimf** [comment]
Found it, I was using the addon ember-idx-modal, and that one had this:
https://github.com/indexiatech/ember-idx-modal/blob/master/app/initializers/config.js

Closing this and opening issue there instead..

Thanks for the help pointing me in the right direction..

**Comment by rwjblue** [comment]
Awesome, glad you tracked it down!
