### ISSUE TITLE
Use `stderr` for warnings instead of `stdout`

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli#3108]
Would it be possible to print warnings with `stderr` instead of `stdout`? I'm in a situation where I'm running my tests on CircleCI and have Testem set up to output my test results in an XML format that Circle can then parse.  The only issue is that, because warnings are printed through `stdout` as well as the test results, the XML data is messed up and Circle can't parse it.  Even running `ember test --silent` doesn't suppress the warnings.

What I would really like to be able to do is output the test results to a file while keep the warnings printed to the "screen" and therefore actually visible in the CircleCI report.

**Comment by stefanpenner** [comment]
please provide the output that is causing you grief

**Comment by alexlafroscia** [comment]
Yeah, of course.  Here's the `.xml` file that Circle is attempting to parse.

```xml
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/Users/alex/Projects/qualaris/audit-webapp-client/tmp/tree_merger-tmp_dest_dir-IIwJhrPQ.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
<testsuite name="Testem Tests" tests="240" failures="0" timestamp="Mon Jan 26 2015 14:51:51 GMT-0500 (EST)" time="5">
  <testcase name="PhantomJS 1.9 Acceptance: Left Panel: Left panel is initialized to &quot;open&quot;"/>
  <testcase name="PhantomJS 1.9 Acceptance: Left Panel: Left panel closes on button press if it was open"/>
  <testcase name="PhantomJS 1.9 Acceptance: Left Panel: Left panel opens on button press if it was closed"/>
  <testcase name="PhantomJS 1.9 JSHint - adapters: adapters/application.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - adapters: adapters/hc-category.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - .: app.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/crunch-data-default.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/crunch-data-division-metric.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/crunch-data-object-adherence.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/crunch-data-object-blame-rep.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/crunch-data-object-blame.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-compliance-combiner.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-compliance-compress-points.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-count-combiner.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-default.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-object-combiner.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-object-compliance-combiner.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-object-compliance-compress-points.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/load-data-trim-series.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-default.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-grid.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-object-grid.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-raw-highcharts.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-simple-charts-area-rep.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - augmentations: augmentations/render-data-simple-charts.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - components: components/date-picker.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - components: components/file-upload.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - components: components/help-popover.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/application.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/audit.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/audit: controllers/audit/project.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/audit/project: controllers/audit/project/audit-form.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/card.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/dashboard.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/dashboard: controllers/dashboard/view.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/detail.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/entity.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/explore.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/explore: controllers/explore/audit-form.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/help: controllers/help/ticket.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/ob-entity.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/report: controllers/report/dropbox.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/reports.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/reports: controllers/reports/report.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers/settings: controllers/settings/profile.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/users.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/view.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - controllers: controllers/widget.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - extra: extra/highcharts-sparkline.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - helpers: helpers/date-formatter.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - helpers: helpers/file-size-formatter.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - helpers: helpers/json-format.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - helpers: helpers/report-object-icon.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/ajax-setup.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/analytics-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/augmentations-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/highcharts-sparkline.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/legacy-check.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/logger-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/measures-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/notifications-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/phantom_adapter.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/polyfills.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/rsvp.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/session-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - initializers: initializers/utilities-service.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - measures: measures/compliance-measure.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - measures: measures/count-average-sum-general-measure.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - measures: measures/object-blame-measure.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - measures: measures/object-measure.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - mixins: mixins/attribute-element-container.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - mixins: mixins/config-object-model.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - mixins: mixins/export-action.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - mixins: mixins/rkey-model.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - mixins: mixins/route-preload.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/admin-user.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/attribute-value.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/attribute.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/audit-form.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/category.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/entity.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/group.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/hc-category.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/institution.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/project.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/report.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/rollout.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/user.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/view.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - models: models/widget.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/acceptance: qualaris-mantra/tests/acceptance/dashboard-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/acceptance: qualaris-mantra/tests/acceptance/left-panel-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/attribute-values.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/attributes.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/files.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/groups.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/help.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/projects.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/views.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/fixtures: qualaris-mantra/tests/fixtures/widgets.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/helpers: qualaris-mantra/tests/helpers/does-not-have-class.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/helpers: qualaris-mantra/tests/helpers/has-class.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/helpers: qualaris-mantra/tests/helpers/has-css.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/helpers: qualaris-mantra/tests/helpers/resolver.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/helpers: qualaris-mantra/tests/helpers/start-app.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/pretender: qualaris-mantra/tests/pretender/basic.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests: qualaris-mantra/tests/test-helper.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/components: qualaris-mantra/tests/unit/components/date-picker-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/controllers: qualaris-mantra/tests/unit/controllers/card-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/initializers: qualaris-mantra/tests/unit/initializers/ajax-setup-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/initializers: qualaris-mantra/tests/unit/initializers/highcharts-sparkline-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/initializers: qualaris-mantra/tests/unit/initializers/legacy-check-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/initializers: qualaris-mantra/tests/unit/initializers/polyfills-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/initializers: qualaris-mantra/tests/unit/initializers/rsvp-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/mixins: qualaris-mantra/tests/unit/mixins/export-action-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/analytics-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/augmentations-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/logger-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/measures-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/notifications-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/session-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - qualaris-mantra/tests/unit/services: qualaris-mantra/tests/unit/services/utilities-test.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - .: router.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/admin.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/application.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/audit.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/audit: routes/audit/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/audit: routes/audit/project.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/audit/project: routes/audit/project/auditform.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/audit/project: routes/audit/project/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/dashboard.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/dashboard: routes/dashboard/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/dashboard: routes/dashboard/view.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/data-event.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/data.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/detail.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/entity.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/explore.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/explore: routes/explore/audit-form.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/explore: routes/explore/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/help.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/help: routes/help/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/help: routes/help/knowledge.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/help: routes/help/rollout.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/masquerade.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/ob-entity.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/onboarding.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/report: routes/report/dropbox.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/report: routes/report/dropboxredir.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/report: routes/report/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/reports.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/reports: routes/reports/report.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/settings.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes/settings: routes/settings/index.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/users.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - routes: routes/widget.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/analytics.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/augmentations.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/logger.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/measures.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/notifications.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/session.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - services: services/utilities.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - transforms: transforms/isodate.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - transforms: transforms/object.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 DatePickerComponent: it renders"/>
  <testcase name="PhantomJS 1.9 DatePickerComponent: it should insert a text field into the DOM"/>
  <testcase name="PhantomJS 1.9 CardController: it exists"/>
  <testcase name="PhantomJS 1.9 CardController: callAugmentationChain allows for any number of augmentations to execute"/>
  <testcase name="PhantomJS 1.9 CardController: callAugmentationChain called with non existent augmentation key returns a &apos;bubble&apos; stage that is a promise that passes the data through"/>
  <testcase name="PhantomJS 1.9 AjaxSetupInitializer: it works"/>
  <testcase name="PhantomJS 1.9 LegacyCheckInitializer: it works"/>
  <testcase name="PhantomJS 1.9 PolyfillsInitializer: it works"/>
  <testcase name="PhantomJS 1.9 RsvpInitializer: it works"/>
  <testcase name="PhantomJS 1.9 ExportActionMixin: it works"/>
  <testcase name="PhantomJS 1.9 AnalyticsService: it exists"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: it exists"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Default Sorting: Condensed Sort"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Default Sorting: Skip sorting with data from object measure"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Division Metric: With explode"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Divison Metric: No explode"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Object Blame Report: Label created as expect"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Object Blame Report: labelCollapse* default options exist"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Object Blame Report: labelCollapse* options can be set"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Crunch Data Object Blame Report: can detect if data is from objectBlameMeasure or an objectMeasure"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Compliance Combiner: Combine non-exploded data"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Compliance Combiner: Combine exploded data"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Compliance Compress Points: Combines data"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Count Combiner: Combiner non-exploded data"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Count Combiner: Combiner exploded data"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Object Combiner: Combine differently named attributes into one"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Object Combiner: copy any remaining key/balues that are not explicitly specified in the mapping config"/>
  <testcase name="PhantomJS 1.9 AugmentationsService: Load Data Object Combiner: No 0 count records should be present in output"/>
  <testcase name="PhantomJS 1.9 LoggerService: it exists"/>
  <testcase name="PhantomJS 1.9 MeasuresService: it exists"/>
  <testcase name="PhantomJS 1.9 MeasuresService: sum general measure: count"/>
  <testcase name="PhantomJS 1.9 MeasuresService: sum general measure: average"/>
  <testcase name="PhantomJS 1.9 MeasuresService: sum general measure: sum"/>
  <testcase name="PhantomJS 1.9 MeasuresService: compliance measure"/>
  <testcase name="PhantomJS 1.9 NotificationsService: it exists"/>
  <testcase name="PhantomJS 1.9 SessionService: it exists"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow users parentStartDate when userParent = true"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow uses startDate when useParent = false and startDate and endDate are supplied"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow timeUnit=&apos;day&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow timeUnit=&apos;week&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow timeUnit=&apos;week&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=false, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow timeUnit=&apos;month&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow timeUnit=&apos;year&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow should handle invalid dates - timeUnit=&apos;year&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow should handle invalid dates - timeUnit=&apos;year&apos; when useParent=false, startDate=undefined, endDate=undefined, isTodate=true, timeUnit and windowWidth are specified "/>
  <testcase name="PhantomJS 1.9 UtilitiesService: startDateFromWindow uses startDate when useParent=false, startDate specified, and isTodate=true"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: endDateFromWindow uses parentEndDate when useParent = true"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: endDateFromWindow uses endDate when useParent = false and startDate and endDate are supplied"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: endDateFromWindow endDate is currentDate when calculating time windows and not using parent start/end dates or supplies start/end dates"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: endDateFromWindow should handle invalid dates - endDate is currentDate when calculating time windows and not using parent start/end dates or supplies start/end dates"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: dateToHumanReadable has correct leading 0s on minutes"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: dateToHumanReadable only includes date when prompted"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: momentToHumanReadable has correct leading 0s on minutes"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: momentToHumanReadable only includes date when prompted"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: creating a partial application allows holes"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: isNumber: Integer Literals"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: isNumber: Non-Numeric values"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: rkey: parse string w/ no property"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: rkey: parse string with property"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: rkey: resolve w/ no property"/>
  <testcase name="PhantomJS 1.9 UtilitiesService: rkey: resolve w/ property"/>
  <testcase name="PhantomJS 1.9 JSHint - utils: utils/redirect-to-login.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/application.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-element.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-number.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-object.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-radio-button.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-radio-buttons.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-select.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form-timestamp.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/attribute-form.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/card.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/highcharts.js should pass jshint"/>
  <testcase name="PhantomJS 1.9 JSHint - views: views/select.js should pass jshint"/>
</testsuite>
```

Because that warning if the first thing that gets output to the file, the parsing fails.  I'd love to be able to redirect that warning elsewhere.

**Comment by stefanpenner** [comment]
we typically consider jshint failures test-failures

**Comment by alexlafroscia** [comment]
Yeah, I totally get that, but the actual problem with the file is the first line:

```
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/Users/alex/Projects/qualaris/audit-webapp-client/tmp/tree_merger-tmp_dest_dir-IIwJhrPQ.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
```

Unless I'm mistaken, that's not a JSHint problem.

**Comment by rwjblue** [comment]
@alexlafroscia - It is also not an error condition. It means that sourcemaps will not be used for that particular file.

**Comment by alexlafroscia** [comment]
@rwjblue That's true.  Is there some way to suppress warnings from the output, the way I can use `--silent` to remove the information about building?  In the case of be running my tests, I don't particularly care that that file won't have source maps used.

**Comment by kimroen** [comment]
Do we know where the warning is coming from? If that's something we can control, we should make it respect the `--silent`-flag.

**Comment by alexlafroscia** [comment]
I think it's Broccoli complaining that a file defines a sourcemap that doesn't actually exist.  This is the actual line https://github.com/tildeio/route-recognizer/blob/master/dist/route-recognizer.js#L648

**Comment by abuiles** [comment]
@ef4 It looks like before if the sourcemaps was not found then the build will continue anyways, I'm not exactly sure what changed but now if the sourcemap is not found, then the whole build just fails, see

```
@terminus-2 ~/code/mims $ es
version: 0.1.12-master-ec6c424613
Livereload server on port 35729
Serving on http:/0.0.0.0:4200/
ENOENT, no such file or directory '/Users/adolfo/code/mims/tmp/tree_merger-tmp_dest_dir-nYNGg7Yq.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
Error: ENOENT, no such file or directory '/Users/adolfo/code/mims/tmp/tree_merger-tmp_dest_dir-nYNGg7Yq.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at SourceMap._resolveSourcemap (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:183:17)
    at SourceMap._assimilateExistingMap (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:216:21)
    at SourceMap._addMap (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:196:8)
    at SourceMap.<anonymous> (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:82:21)
    at SourceMap._cacheEncoderResults (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:116:16)
    at SourceMap.addFile (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:80:8)
    at Class.<anonymous> (/Users/adolfo/code/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
    at Array.forEach (native)
```

**Comment by abuiles** [comment]
It happens when using ember-cli-pretender.

**Comment by alexlafroscia** [comment]
@abuiles I'm not seeing the build fail, just the warning produced.

**Comment by rduque1** [comment]
Hello, I have the same problem. Because of the warning my xunit xml can not be parsed with jenkins.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/3391 updates to make sure jshint errors are not logged via `console.log`.  We need to do the same treatment as https://github.com/rwjblue/broccoli-jshint/commit/1dec89db43d76ef3de3f76309a78023cc295d846 to broccoli-sourcemap-concat I think...
