### ISSUE TITLE
Error: FSEventStreamStart failed on 0.1.11

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#3141]
```
Lawrences-iMac:InboxDashboard JoshuaCope$ ember serve
version: 0.1.11
Livereload server on port 35729
Serving on http://0.0.0.0:4200/provider/

FSEventStreamStart failed
Error: FSEventStreamStart failed
    at null.<anonymous> (/Users/JoshuaCope/Desktop/InboxDashboard/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Readable.push (_stream_readable.js:125:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/JoshuaCope/Desktop/InboxDashboard/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:183:22)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:265:12)
    at writeOrBuffer (_stream_writable.js:252:5)
    at Writable.write (_stream_writable.js:197:11)
    at Socket.ondata (_stream_readable.js:539:20)
    at Socket.emit (events.js:107:17)
```

never seen this one before, closed sublime and restarted my server and it seems to be working fine again for now

Versions

ember - 1.9.1
ember-cli - 0.1.11
node - 0.11.14
npm - 2.0.0
OS X - 10.10

**Comment by stefanpenner** [comment]
seems like a duplicate: https://github.com/ember-cli/ember-cli/search?q=FSEventStreamStart&type=Issues&utf8=✓ please be sure to search before posting.

**Comment by jcope2013** [comment]
@stefanpenner my bad, was thinking this would fix it, restarting sublime still seems to be the fix though

https://github.com/ember-cli/ember-cli/pull/3106
