### ISSUE TITLE
can't build for production from windows machine 

### ISSUE THREAD

**Issue by newtonianb** [ember-cli/ember-cli#3147]
`ember build` works
`ember build --environment=production` gives error
My brocfile does nothing special only uses pickFiles to copy some images

```
ember -v
version: 0.1.2
node: 0.10.33
npm: 2.1.3
Windows 8.1
```

```
ember build --environment=production
version: 0.1.2
Build failed.
File: vendor/loader.js/loader.js
ENOENT, no such file or directory 'd:\app_dd\tmp\fingerprint-tmp_dest_dir-lWTywlfr.tmp\vendor\loader-414f8b07a37aae42602202d9aa3cfb58.js\loader.js'
Error: ENOENT, no such file or directory 'd:\app_dd\tmp\fingerprint-tmp_dest_dir-lWTywlfr.tmp\vendor\loader-414f8b07a37aae42602202d9aa3cfb58.js\loader.js'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at d:\app_dd\node_modules\broccoli-asset-rev\lib\fingerprint.js:44:8
    at $$$internal$$tryCatch (d:\app_dd\node_modules\broccoli-asset-rev\node_modules\rsvp\dist\rsvp.js:470:16)
    at $$$internal$$invokeCallback (d:\app_dd\node_modules\broccoli-asset-rev\node_modules\rsvp\dist\rsvp.js:482:17)
    at d:\app_dd\node_modules\broccoli-asset-rev\node_modules\rsvp\dist\rsvp.js:1066:13
    at $$rsvp$asap$$flush (d:\app_dd\node_modules\broccoli-asset-rev\node_modules\rsvp\dist\rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```

**Comment by stefanpenner** [comment]
`\loader-414f8b07a37aae42602202d9aa3cfb58.js\loader.j` looks like the it may be the issue, maybe broccoli-asset-rev related?

**Comment by newtonianb** [comment]
Actually it might not even be related to windows, I just tried on ubuntu 14.04 and the same error!

**Comment by newtonianb** [comment]
Sorry offending code was cornered to this which I forgot was some snippet added

```
app.styles = function() {
   var vendor = this._processedVendorTree();
   var styles = pickFiles(this.trees.styles, {
     srcDir: '/',
     destDir: '/app/styles'
   });

   var stylesAndVendor = mergeTrees([vendor, styles, 'public']);

   return compileCompass(stylesAndVendor, {
     files: ['app/styles/app.scss'],
     config: process.cwd() + "/config.rb"
   });
};
```
