### ISSUE TITLE
Using es6 syntax in an ember-cli (v0.1.12) addon breaks builds and prevents tests from running

### ISSUE THREAD

**Issue by poteto** [ember-cli/ember-cli#3174]
I'm building an `ember-cli` addon with `v0.1.12`, and encountered problems when I use es6 syntax.

As a test, I initialized a new empty `ember-addon`, and added one component in `components/component-name.js`. No other changes were made.

- When using destructuring and es6 syntax in my component:

```javascript
import Ember from 'ember';

var { computed, get } = Ember;

export default Ember.Component.extend({
  // es6 syntax used here 
});
```

I get this error:

```javascript
version: 0.1.12
Build failed.
File: testymctest/components/flash-message
Unexpected token (3:20)
SyntaxError: Unexpected token (3:20)
    at raise (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at parseIdent (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2471:7)
    at parsePropertyName (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2250:78)
    at parseObj (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2225:9)
    at parseExprAtom (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2136:14)
    at parseVar (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1875:57)
    at parseVarStatement (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1763:5)
    at parseStatement (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1569:47)
    at parseTopLevel (/Users/lauren/Code/testymctest/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1526:18)
```

- When I don't use destructuring and use es6 syntax in my component, it builds successfully, but hangs and eventually timeouts:

```javascript
version: 0.1.12
Built project successfully. Stored in "/Users/lauren/Code/testymctest/tmp/class-tests_dist-fxkpe8Zs.tmp".
```

- When running `ember test -s` with es6 syntax:

![screenshot 2015-02-01 22 58 09](https://cloud.githubusercontent.com/assets/1390709/5991989/df7b71a6-aa65-11e4-8ac1-5c13c0e21977.png)

- But when I switch over to plain es5:

```javascript

import Ember from 'ember';

var computed = Ember.computed;
var get      = Ember.get;

export default Ember.Component.extend({
  // es5 syntax
});
```

It builds and tests run fine with no es6.

Again, this was tested with a blank addon and only one component file in `addon/components/flash-message.js`.

**Comment by stefanpenner** [comment]
thanks for the bug report, https://github.com/ember-cli/ember-cli/pull/3166 will help address this.

**Comment by rwjblue** [comment]
#3166 addresses the underlying issue.  Currently addons cannot use addons to add preprocessor steps (in this case we need ember-cli-6to5 in the addon to preprocess the JS).

**Comment by stefanpenner** [comment]
should be fixed now.

**Comment by rwjblue** [comment]
@poteto - Please test with master and let us know if you run into any issues....

**Comment by QuantumInformation** [comment]
I'm getting this output in the console after upgrading to 2.0:
I'm not clear how to proceed on this.
```

unit/models/register-test.js: line 14, col 3, 'ok' is not defined.

1 error







ules/acorn-babel/acorn_csp.js:2259:47)
    at parseVarStatement (/Users/centrica001/github/ember-commons/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2843:5)


```

**Comment by danny-andrews** [comment]
I'm still a bit of a Git n00b, but what is the earliest version this fix is in?
