### ISSUE TITLE
Using Ember Canary: Cannot read property 'template' of undefined

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#3177]
Using v0.1.12 with Ember Canary (commit- #d454d4bd1b)

`Ember.HTMLBars` is undefined in the compiled application template.

```
error.stack
"TypeError: Cannot read property 'template' of undefined
    at http://localhost:4200/assets/pixelhandler-blog.js:2886:38
    at requireModule (http://localhost:4200/assets/vendor.js:77:29)
    at resolveOther (http://localhost:4200/assets/vendor.js:58391:20)
    at superWrapper [as resolveTemplate] (http://localhost:4200/assets/vendor.js:26793:20)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:14261:43)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:14027:23)
    at resolve (http://localhost:4200/assets/vendor.js:11558:29)
    at Object.Registry.resolve (http://localhost:4200/assets/vendor.js:11100:21)
    at factoryFor (http://localhost:4200/assets/vendor.js:10673:28)
    at instantiate (http://localhost:4200/assets/vendor.js:10734:19)"
```

code for assets/pixelhandler-blog.js:2886:38 is the compiled application template
```
   exports['default'] = Ember.HTMLBars.template((function() {
```

**Comment by rwjblue** [comment]
I believe that this is an Ember build bug, but I'll leave this open just in case.  I'm working on it now...

**Comment by pixelhandler** [comment]
@rwjblue Steps to reproduce:

```
ember new htmlbars-test
cd htmlbars-test/
bower uninstall ember
bower install ember#canary --save
bower uninstall handlebars
npm uninstall --save-dev broccoli-ember-hbs-template-compiler
npm install --save-dev ember-cli-htmlbars
ember server
```

**Comment by rwjblue** [comment]
@pixelhandler - Yep, its an Ember build issue.  Essentially `Ember.FEATURES.isEnabled('ember-htmlbars')` is false, causing all of the normal `Ember.HTMLBars.*` exports to be missing.

**Comment by rwjblue** [comment]
Fixed with https://github.com/thomasboyt/defeatureify/pull/13, please `rm -rf bower_components/ember && bower install` to get the lates build.

**Comment by pixelhandler** [comment]
@rwjblue thanks for the quick response :) I was able to finish up my perf test / comparison today https://gist.github.com/pixelhandler/3dca1b288874d2e96b3e
