### ISSUE TITLE
Unexpected end of input in package.json prohibits use of ember-cli

### ISSUE THREAD

**Issue by seasonedgeek** [ember-cli/ember-cli#3238]
Hello,

I purchased a promising tutorial via Leanpub: [Ember-CLI 101](https://leanpub.com/ember-cli-101); however, I can't use it because I can't create an Ember application.  I am using node 0.12.0, bower 1.3.12, ember-cli 0.1.12, and phantomjs 1.9.13 on OS X Yosemite 10.10.2. When I use Terminal to run `ember` or `ember new project-name`, the following stack trace displays.
```
MacBook:embers seasonedgeek$ ember new borrowers
/package.json: Unexpected end of input
SyntaxError: /package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/models/project.js:595:14
    at $$$internal$$tryCatch (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
```
Just to be clear, I follow the "Set Up" instructions as found under the [Upgrading Ember-CLI](http://www.ember-cli.com/#upgrading) section when a new version of ember-cli is announced.

Obviously ember-cli works on other machines, but not mine. Why???  For me, this issue spans several versions of ember-cli. Last year, I added a [tracer](https://github.com/baryon/tracer) to ember-cli 0.1.4, along with a trace statement just before the exception occurs in the ember-cli/lib/models/project.js file, and concatenates package.json to the value of pathName.  When trying to run `ember new project-name` on the command line, the trace prints:
```
2014-12-25T06:49:20 <trace> project.js:331 ()
  closestPackageJSON(pathName).findup(pathName, package.json) ->
  required: /Users/seasonedgeek/Projects/embers/package.json
```  
When trying to run `ember` on the command line (with the hope that a list of available commands will display), the trace prints:
```
2014-12-25T07:52:56 <trace> project.js:331 ()
  closestPackageJSON(pathName).findup(pathName, package.json) ->
  required: /Users/seasonedgeek/package.json
```
Why is ember looking for a package.json file in these locations???  I am truely baffled.

Thanks for your help.

**Comment by rwjblue** [comment]
Check for a stray 'package.json' in a parent directory of where you are running 'ember new' from.

**Comment by seasonedgeek** [comment]
Thank you for your reply.  I checked for 'package.son' strays, earlier this morning, in the parent directories wherein I run 'ember new'.  I forgot to mention this in my statement above. I found no strays.
 
Perhaps ember-cli expects a 'package.son' file where there is none, and returns this syntax error message rather than returning a file not found message.  Also, is there a logging mechanism built into ember-cli? If so, how do I enable it?

**Comment by seasonedgeek** [comment]
Here's proof regarding the possible stray...
```
MacBook:~ seasonedgeek$ ls /Users/seasonedgeek/package.json
ls: /Users/seasonedgeek/package.json: No such file or directory
MacBook:~ seasonedgeek$ ember
/package.json: Unexpected end of input
SyntaxError: /package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/models/project.js:595:14
    at $$$internal$$tryCatch (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
MacBook:~ seasonedgeek$ ls /Users/seasonedgeek/package.json
ls: /Users/seasonedgeek/package.json: No such file or directory
```
Also, I used/use Homebrew to install node.js.  Any past issues with Homebrew?

**Comment by seasonedgeek** [comment]
**Very interesting...**

I copied 'ember_cli_pkg.json' into my parent directory, and renamed it 'package.json'.
I ran 'ember' within that directory, and da-da, I see a list of ember commands as promised.

```
MacBook:seasonedgeek$ cd ~/projects/embers
MacBook:embers seasonedgeek$ ember
2015-02-10T10:49:18 <info> project.js:598 () closestPackageJSON:pathName: /Users/seasonedgeek/Projects/embers/package.json
version: 0.1.12
Usage: ember <command (Default: help)>

Available commands in ember-cli:

ember addon <addon-name> <options...>
  Generates a new folder structure for building an addon, complete with test harness.
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --blueprint (Path) (Default: addon)
    aliases: -b <value>
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --skip-bower (Boolean) (Default: false)
    aliases: -sb
  --skip-git (Boolean) (Default: false)
    aliases: -sg
.
.
.
ember update
  Updates ember-cli to the newest available version.

ember version <options...>
  outputs ember-cli version
  aliases: v, version, -v, --version
  --verbose (Boolean) (Default: false)
```

**Next, I tried 'ember new'. Oh, happy day! A workaround!**

```
MacBook:embers seasonedgeek$ ember new borrowers --dry-run
2015-02-10T10:54:48 <info> project.js:598 () closestPackageJSON:pathName: /Users/seasonedgeek/Projects/embers/package.json
version: 0.1.12
installing
You specified the dry-run flag, so no changes will be written.
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/.gitkeep
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
```

**Comment by abuiles** [comment]
@seasonedgeek hey, is this still an issue?

**Comment by stefanpenner** [comment]
> Also, is there a logging mechanism built into ember-cli? If so, how do I enable it?

```
DEBUG=ember-cli* ember <command>
```

**Comment by stefanpenner** [comment]
@seasonedgeek I am curious what is causing you pain here. Although this sort of total failure seems to be rare, it still frustrates me that users have to deal with it. If we can narrow it down, we can hopefully mitigate it entirely.

**Comment by stefanpenner** [comment]
this seems to have gone stale. I have not personally been able to replicate, nor has anyone else reported this issue.

If we can get steps to reproduce or a remote pairing session I'll gladly reopen.

**Comment by seasonedgeek** [comment]
Sorry, to have gone MIA.  I’ll try the DEBUG setting and see what happens. This is still an issue for me if I do not utilize the work around.




Thanks,

Tom


—

**Comment by seasonedgeek** [comment]
Thank you for the info on how to debug ember-cli. Here are my attempts to create an Ember app with DEBUG turned off and on.

1. Attempt to create project as usual:
```
MacBook-2:debug seasonedgeek$ pwd
/Users/seasonedgeek/projects/debug

MacBook-2:debug seasonedgeek$ ember new replicat
2015-02-23T18:44:40 <info> project.js:598 () closestPackageJSON:pathName: /package.json
/package.json: Unexpected end of input
SyntaxError: /package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/models/project.js:602:14
    at $$$internal$$tryCatch (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
```

2. Using DEBUG, Attempt to create project:
```
MacBook-2:debug seasonedgeek$ DEBUG=ember-cli* ember new replicat
  ember-cli:project init root: /Users/seasonedgeek/Projects/debug +0ms
  ember-cli:project bowerrc path: /Users/seasonedgeek/Projects/debug/.bowerrc +4ms
  ember-cli:project bowerDirectory: bower_components +2ms
  ember-cli:cli/index leek: { trackingCode: 'UA-49225444-1', globalName: 'ember-cli', name: '883856f3-fff1-4475-9535-b4c06bcaa49e', version: '0.1.12', silent: undefined } +447ms
  ember-cli:cli testing false +7ms
2015-02-23T18:47:31 <info> project.js:598 () closestPackageJSON:pathName: /package.json
/package.json: Unexpected end of input
SyntaxError: /package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/models/project.js:602:14
    at $$$internal$$tryCatch (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/seasonedgeek/.node/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
```
My thoughts:
* It appears that the ember-cli app expects to find, and does not find /package.json in the init root directory: /Users/seasonedgeek/Projects/debug.
* However, when I manually place the ember-cli@0.1.12's package.json file in /Users/seasonedgeek/Projects/debug (the init root directory), the new ember project is generated:
```
MacBook-2:debug seasonedgeek$ ls
MacBook-2:debug seasonedgeek$ cp ~/projects/embers/package.json .
MacBook-2:debug seasonedgeek$ ls
package.json
MacBook-2:debug seasonedgeek$ DEBUG=ember-cli* ember new replicat
  ember-cli:project init root: /Users/seasonedgeek/Projects/debug +0ms
  ember-cli:project bowerrc path: /Users/seasonedgeek/Projects/debug/.bowerrc +5ms
  ember-cli:project bowerDirectory: bower_components +3ms
  ember-cli:cli/index leek: { trackingCode: 'UA-49225444-1', globalName: 'ember-cli', name: '883856f3-fff1-4475-9535-b4c06bcaa49e', version: '0.1.12', silent: undefined } +585ms
  ember-cli:cli testing false +7ms
2015-02-23T19:12:34 <info> project.js:598 () closestPackageJSON:pathName: /Users/seasonedgeek/Projects/debug/package.json
  ember-cli:project closest /Users/seasonedgeek/Projects/debug -> [object Object] +15ms
version: 0.1.12
  ember-cli:project initializeAddons for: debug +3ms
  ember-cli:project attemping to add: /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/tasks/server/middleware/tests-server +1ms
  ember-cli:project  - module found: tests-server-middleware +1ms
  ember-cli:project  - is addon, adding... +0ms
  ember-cli:project attemping to add: /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/tasks/server/middleware/history-support +0ms
  ember-cli:project  - module found: history-support-middleware +2ms
  ember-cli:project  - is addon, adding... +0ms
  ember-cli:project attemping to add: /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/tasks/server/middleware/serve-files +0ms
  ember-cli:project  - module found: serve-files-middleware +1ms
  ember-cli:project  - is addon, adding... +1ms
  ember-cli:project attemping to add: /Users/seasonedgeek/.node/lib/node_modules/ember-cli/lib/tasks/server/middleware/proxy-server +0ms
  ember-cli:project  - module found: proxy-server-middleware +0ms
  ember-cli:project  - is addon, adding... +0ms
  ember-cli:project addon: tests-server-middleware +10ms
  ember-cli:project addon: history-support-middleware +0ms
  ember-cli:project addon: serve-files-middleware +1ms
  ember-cli:project addon: proxy-server-middleware +0ms
  ember-cli:command initialize: name: new, name: %s +1ms
  ember-cli:cli command: new +3ms
  ember-cli:update-checker version: 0.1.12 +1ms
  ember-cli:update-checker version: {} +0ms
  ember-cli:update-checker checkingcheckForUpdates: undefined +0ms
  ember-cli:watcher detecting watchman +222ms
  ember-cli:watcher detected watchman: 3.0.0 +46ms
  ember-cli:watcher watchman 3.0.0 does satisfy: ^3.0.0 +14ms
  ember-cli:command initialize: name: init, name: %s +1ms
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/.gitkeep
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
MacBook-2:debug seasonedgeek$ ls
package.json	replicat
```
* **Wondering**, why can't ember-cli use its own package.json when the closestPackageJSON file can't be found in the init root directory?

**Comment by stefanpenner** [comment]
> Wondering, why can't ember-cli use its own package.json when the closestPackageJSON file can't be found in the init root directory?

the package.json in ember-cli is not the same as the one in an app the users ember-cli. 
I suspect the package.json at the root of your directory is malformed, please remove it.

**Comment by stefanpenner** [comment]
more specifically

```
rm -rf /package.json
```

**Comment by seasonedgeek** [comment]
Okay, thanks, that was my issue: /package.json was an empty file. It's gone.  ember-cli works as advertised.

**Comment by stefanpenner** [comment]
> Okay, thanks, that was my issue: /package.json was an empty file. It's gone. ember-cli works as advertised.

I'm going to improve the error message, so it is more actionable. Sorry it wasn't already.
