### ISSUE TITLE
Addon Discovery: Shared Nested Addons Cannot be Found

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#3240]
I am trying out ember-cli with ember@1.9.1 which needs handlebars@2. Unfortunately the broccoli-ember-hbs-template-compiler@1.7.1-alpha, which uses also handlebars@2, is not pushed to npmjs, so I had to install manually from source. To avoid conflicts, I removed the requirement from my application's package.json for broccoli-ember-hbs-template-compiler, since I am not managing it with npm.

So, the package is installed in node_modules, but not listed in package.json. In this situation, ember-cli warns with:

```
 DEBUG=express*,ember-cli:watcher* ember server --live-reload-port 35730 --port 4200
version: 0.1.12
  ember-cli:watcher detecting watchman +0ms
  ember-cli:watcher detected watchman: 3.0.0 +28ms
  ember-cli:watcher watchman 3.0.0 does satisfy: ^3.0.0 +9ms
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/home/user1/myapp/node_modules/ember-cli/lib/preprocessors.js:83:11)
    at EmberApp._processedTemplatesTree (/home/user1/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:523:10)
    at EmberApp.appAndDependencies (/home/user1/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:698:24)
    at EmberApp.javascript (/home/user1/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:758:34)
    at EmberApp.toArray (/home/user1/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1041:10)
    at EmberApp.toTree (/home/user1/myapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1063:30)
    at Object.<anonymous> (/home/user1/myapp/Brocfile.js:149:34)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

To solve the issue I had to enter again the broccoli-ember-hbs-template-compiler dependency in package.json.

It is misleading, because the module is already present in node_modules, and I was **sure** it was installed (since I had done it manually), so it took me a while to understand what was going on.

**Comment by alvincrespo** [comment]
I'm also encountering this issue when creating a new addon:

http://stackoverflow.com/questions/28592719/missing-template-processor-after-updating-ember-cli-addon

**Comment by rwjblue** [comment]
Using ember-cli 0.2.0-beta.1 and above, you just have to add `ember-cli-htmlbars` to your addon's dependencies.  Prior to this, you could not have nested addons doing preprocessing (which is why we stagnated on Ember 1.8 for so long).

**Comment by alvincrespo** [comment]
@rwjblue Yup. I did an `ember addon test-templates` to test out the use of templates in an addon but still getting "Missing template processor" error when doing `ember server --port=4300`

https://github.com/alvincrespo/test-templates/blob/master/package.json#L27

**Comment by rwjblue** [comment]
@alvincrespo - ember-cli-htmlbars must be in `dependencies` *NOT* `devDependencies` if you want consumers of your addon to have templates.

**Comment by alvincrespo** [comment]
Whoa! That fixed running the dummy app for the addon. Thanks so much dude! Is this something in the docs that I missed - would love to have a link to it.

**Comment by rwjblue** [comment]
@alvincrespo - This is mostly just how NPM works.  Anything included in `dependencies` is installed and available when that package is added to another, anything in `devDependencies` is available when developing the package itself.  Until 0.2.0 it was simply not possible to use an addon that needed to augment/modify the preprocessor registry, that is the primary change in 0.2.0 (and is documented in the CHANGELOG.md).

**Comment by alvincrespo** [comment]
Ahh gotcha - so basically some lack of understanding of npm. Thanks for explaining this to me.

But... I did encounter another issue. So even though I can run the addon by itself - I now see the "missing template processor" error in the app. I can reproduce this with a boilerplate version of an ember-cli based app:

```
➜  test-new-app git:(master) ember server
version: 0.2.0-beta.1
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/preprocessors.js:149:11)
    at Class.Addon.compileTemplates (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/models/addon.js:434:12)
    at Class.Addon.compileAddon (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/models/addon.js:456:28)
    at Class.Addon.treeForAddon (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/models/addon.js:382:24)
    at Class._treeFor (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/models/addon.js:282:31)
    at Class.treeFor (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/models/addon.js:253:19)
    at EmberApp.<anonymous> (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/broccoli/ember-app.js:307:20)
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/broccoli/ember-app.js:305:30)
    at EmberApp._addonTree (/Users/alvincrespo/Desktop/test-new-app/node_modules/ember-cli/lib/broccoli/ember-app.js:597:38)
```

Here is the app repo: 
https://github.com/alvincrespo/test-new-app

package.json: https://github.com/alvincrespo/test-new-app/blob/master/package.json
bower.json: https://github.com/alvincrespo/test-new-app/blob/master/bower.json

Here is the addon repo: https://github.com/alvincrespo/test-templates

package.json: https://github.com/alvincrespo/test-templates/blob/master/package.json
bower.json: https://github.com/alvincrespo/test-templates/blob/master/bower.json

**Comment by alvincrespo** [comment]
Also, I forgot to add that if I remove the test-templates addon - the app runs perfectly.

**Comment by alvincrespo** [comment]
Nevermind. I misunderstood the CHANGELOG. I thought that by making ember-cli-htmlbars a dependency of the addon that it would automatically be understood by the main project. But it looks like we need to use the hooks in order to manually export the template preprocessor. That makes sense now after digging through the code of ember-cli's preprocessor.js.

**Comment by slindberg** [comment]
@alvincrespo Your example app/addon is the exact use case I'm trying to solve with my app: an addon that includes templates for its components.

> But it looks like we need to use the hooks in order to manually use the template preprocessor

What do you mean by this? Are you saying that the addon must implement the `setupPreprocessorRegistry` hook and do something like what the [`ember-cli-htmlbars` addon does](https://github.com/ember-cli/ember-cli-htmlbars/blob/v0.7.4/ember-addon-main.js#L24-L33)?

**Comment by alvincrespo** [comment]
@slindberg Correct! Thats exactly what I meant.

I basically copied over ember-addon-main.js into our addon. Just remember to specify it in you package.json:

https://github.com/ember-cli/ember-cli-htmlbars/blob/v0.7.4/package.json#L19

**Comment by rwjblue** [comment]
There is a bug here, it should *not* be required to relay the `setupPreprocessorRegistry` call...

**Comment by rwjblue** [comment]
The issue is with `AddonDiscovery` checking for the `package.json` in `node_modules/<dep-name>/node_modules/<sub-dep-name>/package.json`.  Specifically, with recent versions of NPM a shared package that meets version requirements will be shared (and not vendored again inside `node_modules/test-templates` in the case of Alvin's repo).

**Comment by stefanpenner** [comment]
@rwjblue <3
