### ISSUE TITLE
Sends asset request to proxy if asset missing

### ISSUE THREAD

**Issue by adibsaad** [ember-cli/ember-cli#3259]
Version: 0.1.12

To replicate

1. Have a backend running on the port of your choice (say localhost, port 3000)
1. Create a new ember project: ``` ember new appname ```
1. Make sure app/styles is empty (have no styles whatsoever)
1. Run ```ember server --proxy http://localhost:3000```
1. Observe that dist/assets does not contain appname.css
1. Open app in browser (localhost:4200)
1. Observe ember console sending the request for /assets/appname.css to the proxy target. Example output:

```GET /assets/appname.css 404 309.122 ms - 47426```

404 since API doesn't have serve this asset.

Rails output for proof:
```
Started GET "/assets/appname.css" for 127.0.0.1 at 2015-02-11 13:11:54 -0500
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"

ActionController::RoutingError (No route matches [GET] "/assets/appname.css"):
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /home/adib/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/adib/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/adib/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

Suggestion: appname.css be generated and be empty if project has no styles.

**Comment by trabus** [comment]
Seems this was somehow introduced by #3152

**Comment by rwjblue** [comment]
Yes, the app.css file should exist, just be empty.
