### ISSUE TITLE
Getting EEXIST from reexporter

### ISSUE THREAD

**Issue by csantero** [ember-cli/ember-cli#3265]
Using ember CLI 0.1.13, if I do:

```
ember new foo
cd foo
ember install:addon liquid-fire
ember serve
```
Wait for it to build and then save any watched file (such as `app/app.js`), I get the following error:

```
EEXIST, file already exists '/home/chris/Projects/foo/tmp/reexporter-tmp_cache_dir-mYGSJHZI.tmp/reexports'
Error: EEXIST, file already exists '/home/chris/Projects/foo/tmp/reexporter-tmp_cache_dir-mYGSJHZI.tmp/reexports'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Reexporter.read (/home/chris/Projects/foo/node_modules/ember-cli/lib/utilities/reexport.js:24:6)
    at /home/chris/Projects/foo/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at $$$internal$$tryCatch (/home/chris/Projects/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/home/chris/Projects/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at /home/chris/Projects/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1096:13
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/chris/Projects/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I haven't figured out what it is about certain addons that causes this to happen, liquid-fire was just an example, but I've gotten the same error with several other addons. It can't be a property of addons in general, because the app blueprint comes with certain addons enabled and it works fine by default.

I've reproduced this on both Ubuntu and OS X, using node 0.10.35 and 0.10.36.

**Comment by ToddSmithSalter** [comment]
Getting the same error when any watched file changes.
```
EEXIST, file already exists '/Users/Todd/code/candidio-app/tmp/reexporter-tmp_cache_dir-MbHa2hdc.tmp/reexports'
Error: EEXIST, file already exists '/Users/Todd/code/candidio-app/tmp/reexporter-tmp_cache_dir-MbHa2hdc.tmp/reexports'
    at Object.fs.mkdirSync (fs.js:647:18)
    at Reexporter.read (/Users/Todd/code/candidio-app/node_modules/ember-cli/lib/utilities/reexport.js:24:6)
    at /Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at $$$internal$$tryCatch (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at /Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1096:13
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by mayatron** [comment]
+1

**Comment by andrewobrien** [comment]
I'm experiencing this as well same error pattern as ToddSmithSalter, experiencing it on any file change after updating to Ember-cli 0.1.13

**Comment by rwjblue** [comment]
Working on it...

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/ember-cli/ember-cli/pull/3267.

**Comment by ToddSmithSalter** [comment]
Thanks @rwjblue!

**Comment by ghedamat** [comment]
not even the time to open the issue! thanks @rwjblue !

**Comment by chuckpeck** [comment]
This is now happening to me.  Just upgraded to ember-cli 0.1.15.

**Comment by chuckpeck** [comment]
Got it working again.  See

http://stackoverflow.com/questions/28853668/running-ember-server-causes-builds-to-fail-with-an-eexist-error

**Comment by joshuairl** [comment]
Experiencing this again... strange...

**Comment by ToddSmithSalter** [comment]
Did you add rimraf as in the SO article linked above?

On Thursday, March 19, 2015, Joshua Rountree <notifications@github.com>
wrote:

> Experiencing this again... strange...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3265#issuecomment-83740808>
> .
>


-- 

*Todd Smith-Salter*
Precise Pixels & gpjobs.ca
Twitter: @ToddSmithSalter <http://twitter.com/ToddSmithSalter>

**Comment by dylan947** [comment]
I'm also still getting this issue. I manually added `rimraf: 2.2.8` to my `package.json` dependencies, removed `tmp/`, `/dist`, `node_modules`, and `bower_components` and reinstalled everything just to be safe.

`Ember-cli V 0.1.13`

**Comment by rwjblue** [comment]
@dylan947 - Update to 0.1.15.

**Comment by rwjblue** [comment]
But you should probably use 0.2.0 (as it is the latest, and contains many bug fixes)

**Comment by dylan947** [comment]
@rwjblue Updated to 0.2.0 which took care of the issues. Thanks.
