### ISSUE TITLE
ember-cli v0.1.13 and v0.1.12 install fail after updating node to v0.12.0

### ISSUE THREAD

**Issue by msalahz** [ember-cli/ember-cli#3266]
I was look forward to have a better build time for ember build on my windows machine so I went an installed the last version from node v0.12.0 and then I tried to update ember-cli to [v0.1.13](https://github.com/ember-cli/ember-cli/releases/tag/v0.1.13) more than 3 times and I always get the following error 
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_module
s\\npm\\bin\\npm-cli.js" "install" "-g" "ember-cli"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for C:\Users\Mohamed\AppData\Local\Temp\npm-7108-352269bd\regist
ry.npmjs.org\ember-cli\-\ember-cli-0.1.13.tgz
npm ERR! Expected: 4d380b9a5e493aa3c16b42bb8036310e0b25281d
npm ERR! Actual:   db1194cec922cbe44dc028266884e6b1956e9834
npm ERR! From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\tugg-dashboard\npm-debug.log
```
here is C:\xampp\htdocs\tugg-dashboard\npm-debug.log content :
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ember-cli' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'ember-cli', null ]
6 verbose cache add spec ember-cli
7 silly cache add parsed spec { raw: 'ember-cli',
7 silly cache add   scope: null,
7 silly cache add   name: 'ember-cli',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed ember-cli@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'ember-cli', range: '*', hasData: false }
12 silly mapToRegistry name ember-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ember-cli
16 verbose addNameRange registry:https://registry.npmjs.org/ember-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ember-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:40:09 PM
20 verbose request id f8a83436a8d84cad
21 http request GET https://registry.npmjs.org/ember-cli
22 http 200 https://registry.npmjs.org/ember-cli
23 silly get cb [ 200,
23 silly get   { date: 'Wed, 11 Feb 2015 21:40:12 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"85CBFT3G2DO60YT172BD5CQJ6"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '166229',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-ams4137-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1423690812.142485,VS0,VE405',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving ember-cli to C:\Users\Mohamed\AppData\Roaming\npm-cache\registry.npmjs.org\ember-cli\.cache.json
25 verbose getCacheStat cache creation not in flight; initializing
26 verbose makeCacheDir UID & GID are irrelevant on win32
27 silly addNameRange number 2 { name: 'ember-cli', range: '*', hasData: true }
28 silly addNameRange versions [ 'ember-cli',
28 silly addNameRange   [ '0.0.0',
28 silly addNameRange     '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.0.10',
28 silly addNameRange     '0.0.11',
28 silly addNameRange     '0.0.12',
28 silly addNameRange     '0.0.13',
28 silly addNameRange     '0.0.14',
28 silly addNameRange     '0.0.15',
28 silly addNameRange     '0.0.16',
28 silly addNameRange     '0.0.18',
28 silly addNameRange     '0.0.19',
28 silly addNameRange     '0.0.20',
28 silly addNameRange     '0.0.21',
28 silly addNameRange     '0.0.22',
28 silly addNameRange     '0.0.23',
28 silly addNameRange     '0.0.24',
28 silly addNameRange     '0.0.25',
28 silly addNameRange     '0.0.27',
28 silly addNameRange     '0.0.28',
28 silly addNameRange     '0.0.29',
28 silly addNameRange     '0.0.32',
28 silly addNameRange     '0.0.33',
28 silly addNameRange     '0.0.34',
28 silly addNameRange     '0.0.35',
28 silly addNameRange     '0.0.36',
28 silly addNameRange     '0.0.37',
28 silly addNameRange     '0.0.38',
28 silly addNameRange     '0.0.39',
28 silly addNameRange     '0.0.40',
28 silly addNameRange     '0.0.41',
28 silly addNameRange     '0.0.42',
28 silly addNameRange     '0.0.43',
28 silly addNameRange     '0.0.44',
28 silly addNameRange     '0.0.45',
28 silly addNameRange     '0.0.46',
28 silly addNameRange     '0.0.47',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13' ] ]
29 verbose addNamed ember-cli@0.1.13
30 silly addNamed semver.valid 0.1.13
31 silly addNamed semver.validRange 0.1.13
32 silly mapToRegistry name ember-cli
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/ember-cli
36 verbose addRemoteTarball https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz',
37 verbose addRemoteTarball   '4d380b9a5e493aa3c16b42bb8036310e0b25281d' ]
38 info retry fetch attempt 1 at 11:40:21 PM
39 info attempt registry request try #1 at 11:40:21 PM
40 http fetch GET https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
41 http fetch 200 https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
42 silly fetchAndShaCheck shasum 4d380b9a5e493aa3c16b42bb8036310e0b25281d
43 verbose stack Error: shasum check failed for C:\Users\Mohamed\AppData\Local\Temp\npm-7108-352269bd\registry.npmjs.org\ember-cli\-\ember-cli-0.1.13.tgz
43 verbose stack Expected: 4d380b9a5e493aa3c16b42bb8036310e0b25281d
43 verbose stack Actual:   db1194cec922cbe44dc028266884e6b1956e9834
43 verbose stack From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
43 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
43 verbose stack     at ReadStream.emit (events.js:129:20)
43 verbose stack     at _stream_readable.js:908:16
43 verbose stack     at process._tickCallback (node.js:355:11)
44 verbose cwd C:\xampp\htdocs\tugg-dashboard
45 error Windows_NT 6.3.9600
46 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ember-cli"
47 error node v0.12.0
48 error npm  v2.5.1
49 error shasum check failed for C:\Users\Mohamed\AppData\Local\Temp\npm-7108-352269bd\registry.npmjs.org\ember-cli\-\ember-cli-0.1.13.tgz
49 error Expected: 4d380b9a5e493aa3c16b42bb8036310e0b25281d
49 error Actual:   db1194cec922cbe44dc028266884e6b1956e9834
49 error From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
50 error If you need help, you may report this error at:
50 error     <http://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

any help ?

**Comment by msalahz** [comment]
I tried to clean my \AppData\Local\Temp\ folder and try to reinstall ember cli again and I got another error 
```
C:\xampp\htdocs\tugg-dashboard>npm install -g ember-cli
C:\Users\Mohamed\AppData\Roaming\npm\ember -> C:\Users\Mohamed\AppData\Roaming\npm\node_modul
es\ember-cli\bin\ember
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_module
s\\npm\\bin\\npm-cli.js" "install" "-g" "ember-cli"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package ember-template-compiler does not satisfy its siblings' peerD
ependencies requirements!
npm ERR! peerinvalid Peer grunt-ember-templates@0.4.21 wants ember-template-compiler@>=1 <2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\tugg-dashboard\npm-debug.log
``` 
here is the npm-debug.log [file](https://drive.google.com/file/d/0B94L2_ct-WARVVhpV2NycVBwaTA/view?usp=sharing)

**Comment by msalahz** [comment]
I rollback node installation to v0.10.36 and managed to install ember-cli@0.1.13 successfully but I got the same error here #3265 so I think my issue is related to node v0.12.0

**Comment by stefanpenner** [comment]
that appears like your NPM cache is corrupted, likely do to a partial or borked NPM download.

try:

```
npm cache clear
rm -rf node_modules
npm install -g ember-cli
```

**Comment by stefanpenner** [comment]
I am closing this, as the error message clearly indicates this is an NPM issue, it even suggests reporting to the npm issue tracker. Clearly this is unfortunate, we have been working with the npm folks to help raise awareness of our pains.

> npm ERR! Expected: 4d380b9a5e493aa3c16b42bb8036310e0b25281d
> npm ERR! Actual:   db1194cec922cbe44dc028266884e6b1956e9834
> npm ERR! From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.1.13.tgz
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\xampp\htdocs\tugg-dashboard\npm-debug.log

**Comment by msalahz** [comment]
FYI, I installed node v0.12.0 again after upgrading to ember-cli v0.2.0-beta.1 and everything worked well and I didn't get this error.
