### ISSUE TITLE
Can't save file during ember test -s

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3270]
If I update my acceptance test code for example login-text.coffee and save it during ember test -s running I get an error(EEXIST):
~~~~
TEST'EM 'SCRIPTS!                                                          
Open the URL below in a browser to connect.                                
http://localhost:7357/                                                     
━━━━━━━━━━━━━━┓                                                            
 PhantomJS 1.9┃  Chrome 40.0                                               
  198/199 ✘   ┃  198/199 ✘                                                 
              ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━











Acceptance: Login: user can login
    ✘ Promise rejected during user can login: Element .sub-header .column:f
irst-child span:first-child not found.
        
[object Object]
[object Object]
[object Object]












[Press ENTER to run tests; q to quit; p to pause]                         EEXIST, file already exists '/home/kuzi/Projects/grruca-beta/tmp/tree_merger-tmp_dest_dir-N1yXPDB4.tmp/modules'
Error: EEXIST, file already exists '/home/kuzi/Projects/grruca-beta/tmp/tree_merger-tmp_dest_dir-N1yXPDB4.tmp/modules'
  at Object.fs.symlinkSync (fs.js:741:18)
  at symlink (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)
  at Function.symlinkOrCopySync [as sync] (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
  at Funnel._copy (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:243:17)
  at Funnel.handleReadTree (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:122:12)
  at $$$internal$$tryCatch (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/kuzi/Projects/grruca-beta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
~~~~
Ember CLI 0.1.14. All npm and bower packages updated to latest. Editor: Sublime Text 3.

**Comment by ToddSmithSalter** [comment]
@rwjblue I don't know if this is an extension of #3265, but I'm also getting this same error as @Kuzirashi rebuilding on any save.

```
Error: EEXIST, file already exists '/Users/Todd/code/candidio-app/tmp/tree_merger-tmp_dest_dir-3Wx5NR6f.tmp/modules'
    at Object.fs.symlinkSync (fs.js:735:18)
    at symlink (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)
    at Function.symlinkOrCopySync [as sync] (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:243:17)
    at Funnel.handleReadTree (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:122:12)
    at $$$internal$$tryCatch (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/Todd/code/candidio-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by csantero** [comment]
Same here.

**Comment by rwjblue** [comment]
Ugh

**Comment by rwjblue** [comment]
Looking at it now....
