### ISSUE TITLE
EEXIST, file already exists (from coffee script filter) after upgrade to 0.1.15

### ISSUE THREAD

**Issue by drogus** [ember-cli/ember-cli#3282]
I've tried upgrading ember-cli and I get the following backtrace when trying to run `ember serve`:

```
version: 0.1.15
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
EEXIST, file already exists '/Users/drogus/code/travis/travis-web/tmp/coffee_script_filter-tmp_dest_dir-8zzCrAE5.tmp/travis/app.js'
Error: EEXIST, file already exists '/Users/drogus/code/travis/travis-web/tmp/coffee_script_filter-tmp_dest_dir-8zzCrAE5.tmp/travis/app.js'
  at Object.fs.openSync (fs.js:438:18)
  at Object.fs.writeFileSync (fs.js:977:15)
  at Object.copyPreserveSync (/Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/broccoli-kitchen-sink-helpers/index.js:150:8)
  at /Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/index.js:41:19
  at /Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:11:14
  at $$$internal$$tryCatch (/Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/drogus/code/travis/travis-web/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I've removed `tmp` dir before running the command. If anyone wants to play with it, I pushed the app to a branch: https://github.com/travis-ci/travis-web/tree/ember-cli-0.1.15, this is a commit from the upgrade: https://github.com/travis-ci/travis-web/commit/09785d308c201c7f218c384243d2d692bc146eda

**Comment by drogus** [comment]
I have no idea what needs to be remove other than `node_modules` and `bower_components`, but for some reason it works after a clean clone. I'm closing this, but if anyone has a good explanation of this issue, I'd appreciate it, I would like to understand where the problem might be.
