### ISSUE TITLE
afterEach failed on it exists

### ISSUE THREAD

**Issue by givanse** [ember-cli/ember-cli#3292]
I'm trying out new library versions with ember-cli and all my unit tests for the models are giving  me this error:

    afterEach failed on it exists: Cannot convert undefined or null to object

    TypeError: Cannot convert undefined or null to object
    at Object.keys (native)
    at ember$data$lib$system$record_array_manager$$values (http://localhost:4200/assets/vendor.js:68303:24)
    at Ember.Object.extend.willDestroy (http://localhost:4200/assets/vendor.js:68296:113)

Even for the test of this model `ember generate model foobar` The default/empty test.

The libraries:

    "ember-cli": "0.1.15",
    "ember-cli-qunit": "0.3.7",

    "ember": "1.11.0-beta.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-qunit": "0.2.8",
    "qunit": "~1.17.1",

**Comment by givanse** [comment]
https://github.com/emberjs/ember.js/issues/10459
