### ISSUE TITLE
Fails to detect correct Watchman version, and crashes

### ISSUE THREAD

**Issue by robertolicious** [ember-cli/ember-cli#3323]
I am migrating from `ember-tools` and creating an existing project into ember-cli compatible like so

    $ cd ~/ember-project/
    $ ember init

However, the result is as follows:

    version: 0.2.0-beta.1
    invalid watchman found, version: [2.9.8] did not satisfy [^3.0.0], falling back to NodeWatcher
    Cannot read property 'toLowerCase' of undefined
    TypeError: Cannot read property 'toLowerCase' of undefined
        at module.exports (/usr/local/lib/node_modules/ember-cli/lib/utilities/valid-project-name.js:4:14)
        at Class.module.exports.Command.extend.run (/usr/local/lib/node_modules/ember-cli/lib/commands/init.js:71:10)
        at Class.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/models/command.js:131:17)
        at $$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
        at $$$internal$$invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
        at $$$internal$$publish (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
        at $$rsvp$asap$$flush (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
        at process._tickCallback (node.js:355:11)

**I am running the following node environment:**
    
    $ node -v
    v0.12.0
    $ npm -v
    2.5.1

**System**

    $ sw_vers 
    ProductName:    Mac OS X
    ProductVersion: 10.9.3
    BuildVersion:   13D65

**And most importantly, the exact expected watchmen version:**

    $ which watchman
    /usr/local/bin/watchman
    $ watchman -v
    3.0.0
    $ brew list --versions | grep watchman
    watchman 3.0.0

Neither of `ember init` or `ember init .` or `ember init existing-directory` performed as expected

**Comment by robertolicious** [comment]
After looking around I found that #2595 had a working suggestion to run: `watchman shutdown-server` which fixed the issue regarding a warning, but not the crash. Documentation is also unclear as it mentions to run this *"before re-starting your ember server"*. In this case server was not started even once.

The crashing on `ember init` still remains an issue.

**Comment by jrm2k6** [comment]
I do have the same issue right now, when running ember init in an empty folder.

**Comment by stefanpenner** [comment]
> I do have the same issue right now, when running ember init in an empty folder.

can you provide steps to reproduce on another machine? Otherwise I am unsure how to approach this problem without something actionable.

**Comment by jrm2k6** [comment]
I opened another issue, I can give you more info on there
