### ISSUE TITLE
A flag to disable registering generated routes with the router?

### ISSUE THREAD

**Issue by misteroneill** [ember-cli/ember-cli#3357]
Our application makes use of an internally-defined set of feature flags, which are set in configuration. Certain routes in the router are only included in the presence of these feature flags:

```javascript
Router.map(function () {
  if (features.foo) {
    this.route('foos', function () {
      // etc...
    });
  }
});
```

This works great for our purposes - being able to turn on/off entire sections of the application and develop features without exposing them (purposefully or accidentally) to users in production.

But it causes the generator (e.g. `ember g route bar`) to fail:

```
installing
  create app/routes/bar.js
  create app/templates/bar.hbs
Cannot read property 'arguments' of undefined
TypeError: Cannot read property 'arguments' of undefined
    at hasRoute (/path/to/project/node_modules/ember-cli/node_modules/ember-router-generator/lib/helpers/has-route.js:7:25)
    at EmberRouterGenerator._remove (/path/to/project/node_modules/ember-cli/node_modules/ember-router-generator/lib/ember-router-generator.js:138:18)
    at EmberRouterGenerator.remove (/path/to/project/node_modules/ember-cli/node_modules/ember-router-generator/lib/ember-router-generator.js:119:33)
    at removeRouteFromRouter (/path/to/project/node_modules/ember-cli/blueprints/route/index.js:99:26)
    at Class.module.exports.afterUninstall (/path/to/project/node_modules/ember-cli/blueprints/route/index.js:86:7)
    at $$$internal$$tryCatch (/path/to/project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/path/to/project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/path/to/project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/path/to/project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

This seems to be coming from [ember-router-generator](https://github.com/ember-cli/ember-router-generator), but thought I'd raise it here as it might get more eyes.

This unlikely to be a condition ember-cli/ember-router-generator wants to concern itself with, but it might make sense to have a command line flag to disable registering the generated route with the router: `ember g route bar --no-register` or something.

**Comment by stefanpenner** [comment]
> This unlikely to be a condition ember-cli/ember-router-generator wants to concern itself with,

actually, I think this is something we should support.

**Comment by abuiles** [comment]
@misteroneill  thanks! @stefanpenner  I'll check why this is throwing the error (that shouldn't  be the case) and add support to opt-out on the route generator.

**Comment by rwjblue** [comment]
I think that we should gracefully handle route generator failures (though we should fix them if we can).  So if the route generator throws an error we should still generate the files on disk and print a warning that  we couldn't insert into `router.js`.

**Comment by stefanpenner** [comment]
Agreed

**Comment by abuiles** [comment]
The bug should be gone with https://github.com/ember-cli/ember-router-generator/pull/8 and @jgwhite added support so we don't fail if we can't add or remove a route.

**Comment by abuiles** [comment]
I just release ember-router-generator@0.3.2 so this shouldn't fail any more, we might still add a rescue in case someone is doing crazy stuff in their router.

**Comment by misteroneill** [comment]
:+1:

**Comment by stefanpenner** [comment]
> we might still add a rescue in case someone is doing crazy stuff in their router.

this will likely just hide bugs we can fix, lets not yet.

**Comment by abuiles** [comment]
@stefanpenner perfect, so we can close, new version will be picked up automatically when bundling ember-cli.
