### ISSUE TITLE
ember-cli project failing because project name is 'query'

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3403]
Do `ember new query` and then `ember server` and you'll get:

```
version: 0.2.0-beta.1
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: bower_components/jquery/src/intro
Unexpected token (45:0)
SyntaxError: Unexpected token (45:0)
    at raise (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at parseExprAtom (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2153:7)
    at parseExprSubscripts (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
    at parseMaybeUnary (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
    at parseExprOps (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
    at parseMaybeConditional (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
    at parseMaybeAssign (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
    at parseExpression (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
    at parseStatement (/Users/btecu/Desktop/query/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
```

I just spent two hours trying on multiple computers, both Windows and Mac to realize that the problem was name of the project. Somehow `ember-cli` doesn't like the name `query` and I'm not aware of any reserved keywords other than `store` and JS keywords.

Funny thing, I was trying to create a small project to reproduce a bug in `queryParams`...

**Comment by stefanpenner** [comment]
Bonkers.

**Comment by chaoszcat** [comment]
I did this:

    $ mkdir src
    $ cd src
    $ ember init
    $ ember server

And I got this:

	version: 0.2.2
	Livereload server on port 35729
	Serving on http://localhost:4200/
	File: bower_components/jquery/src/intro
	Unexpected token (45:0)
	SyntaxError: Unexpected token (45:0)
	    at Parser.pp.raise (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:1021:13)
	    at Parser.pp.unexpected (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:1512:8)
	    at Parser.pp.parseExprAtom (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:428:12)
	    at Parser.pp.parseExprSubscripts (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:323:19)
	    at Parser.pp.parseMaybeUnary (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:305:19)
	    at Parser.pp.parseExprOps (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:261:19)
	    at Parser.pp.parseMaybeConditional (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:244:19)
	    at Parser.pp.parseMaybeAssign (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:224:19)
	    at Parser.pp.parseExpression (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:200:19)
	    at Parser.pp.parseStatement (c:\wamp\www\gevme\plugins\Campaign\src\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:1707:23)

Then after I found this thread I tried changing it to `webroot_src` and wow, it works. I think `src` is one of the reserved word then. Should have been told in the ember-cli documentation

**Comment by rwjblue** [comment]
@twokul and I looked at this a few days ago, and he has a fix.

**Comment by Zatvobor** [comment]
The same true for `ember new rc`
```shell
/tmp/rc$ ember server
version: 0.2.2
Livereload server on port 35729
Serving on http://localhost:4200/
File: bower_components/jquery/src/intro
Unexpected token (45:0)
SyntaxError: Unexpected token (45:0)
    at Parser.pp.raise (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:1021:13)
    at Parser.pp.unexpected (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:1512:8)
    at Parser.pp.parseExprAtom (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:428:12)
    at Parser.pp.parseExprSubscripts (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:323:19)
    at Parser.pp.parseMaybeUnary (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:305:19)
    at Parser.pp.parseExprOps (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:261:19)
    at Parser.pp.parseMaybeConditional (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:244:19)
    at Parser.pp.parseMaybeAssign (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:224:19)
    at Parser.pp.parseExpression (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:200:19)
    at Parser.pp.parseStatement (/private/tmp/rc/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:1707:23)
Content Security Policy violation: {"csp-report":{"document-uri":"http://localhost:4200/","referrer":"http://localhost:4200/","violated-directive":"style-src 'self'","effective-directive":"style-src","original-policy":"default-src 'none'; script-src 'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729; font-src 'self'; connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729 http://0.0.0.0:4200/csp-report; img-src 'self'; style-src 'self'; media-src 'self'; report-uri http://0.0.0.0:4200/csp-report;","blocked-uri":"","status-code":500}}
```
