### ISSUE TITLE
ENOENT: no such file

### ISSUE THREAD

**Issue by marvinosswald** [ember-cli/ember-cli#3425]
Keep getting this when deploying to heroku, local it works quite well...
Besides ember server stopped reloading on file changes recently but I'm pretty sure I've broke it myself somehow..
```
remote: -----> Building Ember CLI application production distribution
remote:        version: 0.1.9
remote:        Could not find watchman, falling back to NodeWatcher for file system events
remote:        BuildingBuilding.Building..Building...BuildingBuild failed.
remote:        File: vendors/loader.js/loader.js
remote:        ENOENT, no such file or directory '/tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/tmp/fingerprint-tmp_dest_dir-qnGCSoz3.tmp/vendors/loader-414f8b07a37aae42602202d9aa3cfb58.js/loader.js'
remote:        Error: ENOENT, no such file or directory '/tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/tmp/fingerprint-tmp_dest_dir-qnGCSoz3.tmp/vendors/loader-414f8b07a37aae42602202d9aa3cfb58.js/loader.js'
remote:            at Object.fs.openSync (fs.js:439:18)
remote:            at Object.fs.writeFileSync (fs.js:978:15)
remote:            at /tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/node_modules/broccoli-asset-rev/lib/fingerprint.js:53:8
remote:            at lib$rsvp$$internal$$tryCatch (/tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:489:16)
remote:            at lib$rsvp$$internal$$invokeCallback (/tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:501:17)
remote:            at /tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:1095:13
remote:            at Object.lib$rsvp$asap$$flush [as _onImmediate] (/tmp/build_99b1557eb9f1d0d897dcb88d5769d13c/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:1290:9)
remote:            at processImmediate [as _immediateCallback] (timers.js:354:15)
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
remote: 
```

**Comment by stefanpenner** [comment]
I suspect `bower install` was not run.

**Comment by marvinosswald** [comment]
Sadly no, bower install runs just fine. Here is my output after the bower install command finished:

```

**Comment by marvinosswald** [comment]
Fixed it by updating to newest ember-cli but now I'm getting a "EOF (undefined)" error but I'm pretty sure it's just the cache.
