### ISSUE TITLE
ember build --watch fails to rebuild when template is broken

### ISSUE THREAD

**Issue by rondale-sc** [ember-cli/ember-cli#3444]
Testing on ember-cli 0.2.0-beta.1

If template is broken (ie invalid html) when you initially fire off the `ember build --watch` command it fails to start the deamon process.  

If the template is valid when the `ember build --watch` command is executed the deamon will fire and will retrigger builds, but fails to successfully complete the build getting the following error:

```sh
file changed templates/presentations.hbs
EEXIST, file already exists '/Users/dev/hashrocket/compton/frontend/tmp/class-tmp_cache_dir-zAtCrcJm.tmp'
Error: EEXIST, file already exists '/Users/dev/hashrocket/compton/frontend/tmp/class-tmp_cache_dir-zAtCrcJm.tmp'
    at Object.fs.symlinkSync (fs.js:742:18)
    at symlink (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:82:14)
    at Function.symlinkOrCopySync [as sync] (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at /Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:103:21
    at lib$rsvp$$internal$$tryCatch (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/dev/hashrocket/compton/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by okket** [comment]
see https://github.com/ember-cli/ember-cli/issues/3413

**Comment by rondale-sc** [comment]
@okket Okay.  thanks!  will close for now.  <3

**Comment by stefanpenner** [comment]
yes, npm is trolling us hard..
