### ISSUE TITLE
Cannot read property 'writeLine' of undefined

### ISSUE THREAD

**Issue by kenips** [ember-cli/ember-cli#3468]
Getting this after upgrading to 0.2.0.

Error:
```
Cannot read property 'writeLine' of undefined
TypeError: Cannot read property 'writeLine' of undefined
  at AddonDiscovery.<anonymous> (/Users/Ken/Code/impulse/impulse-ember/node_modules/ember-cli/lib/models/addon-discovery.js:109:21)
  at Array.map (native)
  at AddonDiscovery.discoverFromDependencies (/Users/Ken/Code/impulse/impulse-ember/node_modules/ember-cli/lib/models/addon-discovery.js:94:68)
  at AddonDiscovery.discoverChildAddons (/Users/Ken/Code/impulse/impulse-ember/node_modules/ember-cli/lib/models/addon-discovery.js:61:31)
  at Class.Addon.discoverAddons (/Users/Ken/Code/impulse/impulse-ember/node_modules/ember-cli/lib/models/addon.js:172:40)
...
```

**Comment by zigomir** [comment]
Same issue is also happening here https://github.com/simplabs/ember-cli-simple-auth-torii/issues/7
