### ISSUE TITLE
has no method hasMagic

### ISSUE THREAD

**Issue by googya** [ember-cli/ember-cli#3516]
version: 0.1.12
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at rimraf (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/private/tmp/ember_demo/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by kiwiupover** [comment]
The npm module `glob` was updated so you need to change the `package.json` to use

`"glob": "4.4.0"`

Cheers

**Comment by googya** [comment]
@kiwiupover yeap!

**Comment by pwfisher** [comment]
After setting `package.json` to use `"glob": "4.4.0"`, it still wouldn't work for me without removing and reinstalling the package:

```
npm rm glob && npm up
```

**Comment by jalbertcory** [comment]
Still not working for me with 4.4.0

**Comment by raycohen** [comment]
after hitting this issue, inside my project directory I ran `rm -rf node_modules/ember-cli/node_modules/glob` and then `npm install` again, and after that `ember server` worked

**Comment by jalbertcory** [comment]
I had to perform npm cache clean but now it works

**Comment by sukima** [comment]
Your problem is that ember-cli requires glob version 4.0.5 but rimraf requires version 4.5.3.

```console
npm WARN unmet dependency /Users/suki/source/SeeClickFix/test-select-picker/node_modules/ember-cli requires glob@'4.0.5' but will load
npm WARN unmet dependency /Users/suki/source/SeeClickFix/test-select-picker/node_modules/glob,
npm WARN unmet dependency which is version 4.5.3
```

By removing ember-cli's glob and then reinstalling will force npm to load 4.5.3: `rm -rf node_modules/ember-cli/node_modules/glob && npm install`

NPM will get angry about this but least it will work. The bigger question is why doesn't ember-cli use the later version? The even more meta question is why doesn't NPM manage this since doesn't it nest dependencies under each project for just this very problem?

**Comment by sheriffderek** [comment]
Unknown combinations of the above suggestions worked for me, but I don't feel super awesome about it. Just wanted to get involved in this thread... so I can keep things working when this changes.

**Comment by dylanfoster** [comment]
The issue is with `rimraf`. You can install `rimraf@2.2.8` in your project which should take care of it, or you can update to `ember-cli 0.2.x` which also takes care of it.

**Comment by sheriffderek** [comment]
This is how I'm rolling on the latest project:

flow/ : ember version
version: 0.2.0-beta.1
node: 0.10.33
npm: 2.1.8

...
    "rimraf": "2.2.8",
    "glob": "4.4.0"
}


It'll build... but jsHint is pissed about ES6 now : (

**Comment by kemoycampbell** [comment]
another easy fix is to remove both nodejs and npm then reinstall. This way you get the most updated version
