### ISSUE TITLE
Syntax error when port already in use

### ISSUE THREAD

**Issue by bdvholmes** [ember-cli/ember-cli#3519]
version: 0.2.0
    The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/ben/src/live-ops/node_modules/ember-data`. This is generally
    caused by an addon not having a `main` entry point (or `index.js`).
    Livereload server on port 36029
    Cannot read property 'displayHost' of undefined
    TypeError: Cannot read property 'displayHost' of undefined
        at /Users/ben/src/live-ops/node_modules/ember-cli/lib/tasks/server/express-server.js:179:70
        at lib$rsvp$$internal$$tryCatch (/Users/ben/src/live-ops/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
        at lib$rsvp$$internal$$invokeCallback (/Users/ben/src/live-ops/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
        at lib$rsvp$$internal$$publish (/Users/ben/src/live-ops/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
        at lib$rsvp$$internal$$publishRejection (/Users/ben/src/live-ops/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:415:7)
        at lib$rsvp$asap$$flush (/Users/ben/src/live-ops/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
        at process._tickCallback (node.js:355:11)

**Comment by stefanpenner** [comment]
hmm thats a new one.

**Comment by lightblade** [comment]
Encountered the same issue. For future reference, check if there's another instance of ember-cli running.
