### ISSUE TITLE
Ember CLI fails to compile this JavaScript.

### ISSUE THREAD

**Issue by Kerrick** [ember-cli/ember-cli#3520]
Sorry for the vague title, but the following JavaScript fails to compile in Ember CLI 0.2.0

```js
import Ember from 'ember';

const { get, computed } = Ember;

export default Ember.Controller.extend({
  foo: computed('bar', function() {
    return [].indexOf(get(this, 'bar'));
  })
});
```

Note that it _will_ compile if you change the destructuring line to `const { get: get, computed } = Ember;`. It will _also_ compile if you change the computed property line to `return get(this, 'bar')`, even without changing the destructuring line.

Here is the stack trace:

```
Build failed.
File: destructuring-shortcut/controllers/sample-controller.js
Line 3: Unexpected identifier
Error: Line 3: Unexpected identifier
    at throwError (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:2038:21)
    at throwUnexpected (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:2082:13)
    at expect (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:2109:13)
    at parseObjectProperty (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:2348:17)
    at /Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:5120:38
    at parseObjectInitialiser (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:2400:24)
    at parseVariableDeclaration (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:3190:18)
    at /Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:5120:38
    at parseVariableDeclarationList (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:3225:23)
    at parseConstLetDeclaration (/Users/kerrick/Temporary/destructuring-shortcut/node_modules/ember-cli/node_modules/broccoli-es3-safe-recast/node_modules/es3-safe-recast/node_modules/esprima/esprima.js:3256:24)
```

[Kerrick/destructuring-shortcut](https://github.com/Kerrick/destructuring-shortcut) is a repo with the compilation failure if you'd like to see it for yourself

---

One interesting thing is that either of the following _will_ compile just fine.

```js
import Ember from 'ember';

const { get: get, computed } = Ember;

export default Ember.Controller.extend({
  foo: computed('bar', function() {
    return [].indexOf(get(this, 'bar'));
  })
});
```

```js
import Ember from 'ember';

const { get, computed } = Ember;

export default Ember.Controller.extend({
  foo: computed('bar', function() {
    return get(this, 'bar');
  })
});
```

**Comment by stefanpenner** [comment]
you can disable es3recast

**Comment by stefanpenner** [comment]
opened an issue on the offending repo

**Comment by poteto** [comment]
Also #3174

**Comment by stefanpenner** [comment]
thanks for the bug report, both es3-safe and ember-cli have been updated. As a bonus, if you have babel installed, no es3-safe needs to be run, and now it doesnt. :)
