### ISSUE TITLE
Tests failing on fresh clone

### ISSUE THREAD

**Issue by pzuraq** [ember-cli/ember-cli#3524]
I cloned the repo, reinstalled node, made sure to remove `.node_modules-tmp` and `.bower_components-tmp` and I'm still unable to get all the tests working. Currently, this one is failing every single time:

```
 1) Acceptance: smoke-test ember new foo, build development, and verify generated files:
     AssertionError: expected fewer than 21 files in dist, found 21: expected [ Array(21) ] to have a length below 21 but got 21
      at /Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/smoke-test-slow.js:141:38
      at lib$rsvp$$internal$$tryCatch (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$asap$$flush (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)
```

A few others fail sporadically as well, I'll add them if I can get them to show.

**Comment by stefanpenner** [comment]
> I cloned the repo,

which repo?

**Comment by pzuraq** [comment]
repo: ember-cli/ember-cli
OS: Mac OSX 10.9.5 Build 13F34
node: v0.12.0 and iojs-1.5.1
npm: v2.5.1

**Comment by stefanpenner** [comment]
sorry, I cannot replicate this...

**Comment by stefanpenner** [comment]
@rwjblue r?

**Comment by pzuraq** [comment]
@stefanpenner Are there any dependencies that I need to have installed that I could be missing? Some tests were failing before I installed phantomjs, so I was thinking it might be something along those lines.

**Comment by rwjblue** [comment]
Can you also do `rm -rf node_modules .node_modules-tmp .bower_components-tmp && npm cache clear && npm install`?

**Comment by pzuraq** [comment]
@rwjblue I've run that and unfortunately it didn't work. I just tried again with `bower cache clean` as well, tests are still running I'll let you know if that did it.

**Comment by pzuraq** [comment]
Managed to get the other tests to fail as well, cleared the cache and then re-cloned. I think I may just wipe my system soon haha.

Note: This started happening after I installed `nvm`, I've switched back from it since then and I'm not sure how it could be causing this, but it may be related.

```
1) Acceptance: express server restart Server restarts successfully on copy1:

      Test file has correct contents after first copy.
      + expected - actual

      +"Copy1 contents of A."
      -"Initial contents of A."

      at ensureTestFileContents (/Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:59:25)
      at /Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:72:11
      at lib$rsvp$$internal$$tryCatch (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$asap$$flush (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)

  2) Acceptance: express server restart Server restarts successfully on copy2:

      Test file has correct contents after first copy.
      + expected - actual

      +"Copy2 contents of A. Copy2 contents of B."
      -"Initial contents of A."

      at ensureTestFileContents (/Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:59:25)
      at /Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:72:11
      at lib$rsvp$$internal$$tryCatch (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$asap$$flush (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)

  3) Acceptance: express server restart Server restarts successfully on multiple copies:

      Test file has correct contents after first copy.
      + expected - actual

      +"Copy1 contents of A."
      -"Initial contents of A."

      at ensureTestFileContents (/Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:59:25)
      at /Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/express-server-restart-slow.js:87:11
      at lib$rsvp$$internal$$tryCatch (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$asap$$flush (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)

  4) Acceptance: smoke-test ember new foo, build development, and verify generated files:
     AssertionError: expected fewer than 21 files in dist, found 21: expected [ Array(21) ] to have a length below 21 but got 21
      at /Users/pzuraq/Code/ember/ember-cli-master/tests/acceptance/smoke-test-slow.js:140:38
      at lib$rsvp$$internal$$tryCatch (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$asap$$flush (/Users/pzuraq/Code/ember/ember-cli-master/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)
```

**Comment by stefanpenner** [comment]
on of my co-workers also demonstrated this.

**Comment by stefanpenner** [comment]
@thoorv

**Comment by stefanpenner** [comment]
```
rm -rf .node_modules-tmp
rm -rf .bower_components-tmp
```
may do the trick ( was saying the same)
