### ISSUE TITLE
Invalid tar file during npm install of ember-cli 0.2.0

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#3526]
I've noticed my ci server occasionally gets the fun npm error shown below

```
00:05:31.454 npm ERR! tar.unpack untar error /var/lib/jenkins/.npm/ember-cli/0.2.0/package.tgz
00:05:31.471 npm ERR! addPlacedTarball Could not unpack "/var/lib/jenkins/.npm/ember-cli/0.2.0/package.tgz" to "/var/lib/jenkins/.npm/ember-cli/0.2.0"
00:05:31.481 npm ERR! Error: invalid tar file
00:05:31.481 npm ERR!     at Extract.Parse._startEntry (/usr/lib/node_modules/tar/lib/parse.js:144:13)
00:05:31.484 npm ERR!     at Extract.Parse._process (/usr/lib/node_modules/tar/lib/parse.js:125:12)
00:05:31.485 npm ERR!     at BlockStream.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:46:8)
00:05:31.485 npm ERR!     at BlockStream.emit (events.js:95:17)
00:05:31.487 npm ERR!     at BlockStream._emitChunk (/usr/lib/node_modules/block-stream/block-stream.js:145:10)
00:05:31.488 npm ERR!     at BlockStream.resume (/usr/lib/node_modules/block-stream/block-stream.js:58:15)
00:05:31.488 npm ERR!     at Extract.Reader.resume (/usr/lib/node_modules/fstream/lib/reader.js:252:34)
00:05:31.498 npm ERR!     at Entry.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:256:8)
00:05:31.498 npm ERR!     at Entry.emit (events.js:92:17)
00:05:31.501 npm ERR!     at Entry.resume (/usr/lib/node_modules/tar/lib/entry.js:92:8)
```

Is it safe to assume this is purely a dist issue w/ npm and not a real ember-cli issue?

```
addPlacedTarball Could not unpack "/var/lib/jenkins/.npm/ember-cli/0.2.0/package.tgz" to "/var/lib/jenkins/.npm/ember-cli/0.2.0"
```

**Comment by stefanpenner** [comment]
> Is it safe to assume this is purely a dist issue w/ npm and not a real ember-cli issue?

I am 80% certain this is an NPM issue :(.

Which version of `npm` is your CI using?

**Comment by toranb** [comment]
Looks like v0.10.33 (but looking to update it today so it's what our dev machines are using => v0.10.36)

**Comment by toranb** [comment]
npm version == 1.3.6

**Comment by toranb** [comment]
Is this a known npm issue for older versions (as I showed above)? Does switching to node v0.12 help in any way (assuming a new version of npm comes with)

**Comment by stefanpenner** [comment]
> npm version == 1.3.6

get on `> 2.6.0` and report back, `1.x` series has many issues, `2.x` feels much better.

**Comment by toranb** [comment]
Excellent! Thanks for the quick reply @stefanpenner
