### ISSUE TITLE
Build failure when creating sourcemaps in non-production environment

### ISSUE THREAD

**Issue by MattNguyen** [ember-cli/ember-cli#3527]
I'm currently using ember-cli-deploy for deployments. However, when I attempt to deploy to a staging environment, I receive the following build error:

```
Build failed.
Invalid mapping: {"generated":{"line":77080,"column":-50},"source":"bower_components/ember-i18n/lib/i18n.js","original":{"line":1,"column":0},"name":null}
Error: Invalid mapping: {"generated":{"line":77080,"column":-50},"source":"bower_components/ember-i18n/lib/i18n.js","original":{"line":1,"column":0},"name":null}
  at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:272:15)
  at SourceMapGenerator_addMapping [as addMapping] (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:102:12)
  at /Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:74:19
  at Array.forEach (native)
  at SourceMapConsumer_eachMapping [as eachMapping] (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-consumer.js:473:10)
  at Function.SourceMapGenerator_fromSourceMap (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:50:26)
  at Object.SourceMap (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/sourcemap.js:59:52)
  at Object.exports.minify (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:112:38)
  at UglifyWriter.processFile (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:98:25)
  at /Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:46:14
  at Array.forEach (native)
  at /Users/mattnguyen/Code/guest-flow/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:38:21
  at $$$internal$$tryCatch (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at $$rsvp$asap$$flush (/Users/mattnguyen/Code/guest-flow/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at process._tickCallback (node.js:355:11)
```

This is in my Brocfile:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var HtmlbarsCompiler = require('ember-cli-htmlbars');
var env = EmberApp.env();
var isProductionLikeBuild = ['production', 'staging'].indexOf(env) > -1;

var detereminePrepend = function() {
  if (env === 'production') {
    return process.env.PROD_CLOUDFRONT_URL;
  } else if (env === 'staging') {
    console.log(process.env.STAGING_CLOUDFRONT_URL);
    return process.env.STAGING_CLOUDFRONT_URL;
  } else {
    return process.env.DEV_ASSET_URL;
  }
};

var app = new EmberApp({
  vendorFiles: {
    'handlebars.js': null
  },
  fingerprint: {
    prepend: detereminePrepend()
  },
  minifyAssets: { enabled: isProductionLikeBuild },
  minifyJS: { enabled: isProductionLikeBuild }
});

var templateTree = new HtmlbarsCompiler('app/templates', {
  isHTMLBars: true,
  templateCompiler: require('./bower_components/ember/ember-template-compiler')
});

app.import({
  development: 'bower_components/ember/ember.debug.js',
  production:  'bower_components/ember/ember.prod.js'
});
app.import('bower_components/jquery.cookie/jquery.cookie.js');
app.import('bower_components/ember-i18n/lib/i18n.js');
app.import('bower_components/ember-i18n/lib/i18n-plurals.js');

module.exports = app.toTree();
```

Any help would be appreciated. Thanks!

**Comment by rwjblue** [comment]
Due to https://github.com/emberjs/data/issues/2871

**Comment by fivetanley** [comment]
@rwjblue Sourcemaps have been removed on ember data, so if people are still having issues it's likely that https://github.com/ember-cli/ember-cli-uglify/issues/4 has not actually been fixed.

**Comment by stefanpenner** [comment]
@fivetanley has it been released?

**Comment by fivetanley** [comment]
I edited the source files in the bower repository. If you go look at them none of the .prod.js files should have source mapping url comments.

**Comment by stefanpenner** [comment]
@fivetanley sounds good, thanks.

**Comment by vsymguysung** [comment]
I think this is still an issue with the ```version 0.2.1``` and ```ember-data 1.0.0-beta.16.1```.
Please see the following issue report.
https://github.com/ember-cli/ember-cli/issues/3657

**Comment by davewasmer** [comment]
Seeing the same here, for staging builds. Happy to supply more debug info if helpful, or even a pointer in the right direction for where to try fixing this one.

**Comment by stefanpenner** [comment]
@davewasmer this is likely an issue with one of the dependencies. Although source map stuff is tricky and annoying to debug

**Comment by jamesarosen** [comment]
On ember-cli 0.2.7, we get this with `d3`, which unlike ember-data, doesn't ship with its own `d3.js.map` file.

```
Build failed.
File: assets/vendor.js
Invalid mapping: {"generated":{"line":81847,"column":-50},"source":"bower_components/d3/d3.js","original":{"line":1,"column":0},"name":null}
Error: Invalid mapping: {"generated":{"line":81847,"column":-50},"source":"bower_components/d3/d3.js","original":{"line":1,"column":0},"name":null}
```

**Comment by stefanpenner** [comment]
> ember build -e staging

FYI, this isn't supported. Please stay within the dev/prod/test environments. Yes this is crazy, but we are still internally coupled to these concepts.
