### ISSUE TITLE
Running ember test --server exits when Sublime Text is open with the current project.

### ISSUE THREAD

**Issue by mewben** [ember-cli/ember-cli#3536]
Running `ember test --server` with Sublime Text opened with the current project produces the following:

```
{ [Error: watch EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'watch' }er_with_server: ERROR: f2Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1161:26)
```

Info:
OS: Yosemite
Node: v0.12.0
EmberCLI: v0.2.0

**Comment by stefanpenner** [comment]
likely related: https://github.com/ember-cli/ember-cli/issues/2643

**Comment by tubia** [comment]
I experienced a similar problem. When Sublime Text is open, `ember server` returns this error:
```
watch ENOSPC
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/home/tubia/embertest/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/tubia/embertest/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/home/tubia/embertest/node_modules/ember-cli/node_modules/sane/index.js:13:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/tubia/embertest/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /home/tubia/embertest/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:67:35
    at lib$rsvp$$internal$$tryCatch (/home/tubia/embertest/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/tubia/embertest/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
```

Clearing `tmp` helped one time to solve the problem but today only closing Sublime Text.

**Comment by stefanpenner** [comment]
Please be sure to read the website section that discusses sublime as it recommends ignoreing the temp for from sublime.

**Comment by tubia** [comment]
Ok I found what you're referring to for the [configuration of Sublime Text](http://www.ember-cli.com/#sublime-text).  
I'm testing it and I'll report back if I found any problems.

**Comment by stefanpenner** [comment]
> I'm testing it and I'll report back if I found any problems.

thanks :)
