### ISSUE TITLE
Addon error: included hook get wrong parametr

### ISSUE THREAD

**Issue by vvs-code** [ember-cli/ember-cli#3567]
As i know addons included hook should get application as param 

But i've got en error 
```
Cannot read property 'fingerprint' of undefined
TypeError: Cannot read property 'fingerprint' of undefined
    at Class.module.exports.initializeOptions (/Users/vvs/repo/apollo/node_modules/broccoli-asset-rev/index.js:17:25)
    at Class.module.exports.included (/Users/vvs/repo/apollo/node_modules/broccoli-asset-rev/index.js:38:10)
    at /Users/vvs/repo/apollo/node_modules/ember-cli/lib/models/addon.js:211:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/vvs/repo/apollo/node_modules/ember-cli/lib/models/addon.js:209:22)
    at Class.Addon.included (/Users/vvs/repo/apollo/node_modules/ember-cli/lib/models/addon.js:315:8)
    at EmberApp.<anonymous> (/Users/vvs/repo/apollo/node_modules/ember-cli/lib/broccoli/ember-app.js:277:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/vvs/repo/apollo/node_modules/ember-cli/lib/broccoli/ember-app.js:272:45)
    at new EmberApp (/Users/vvs/repo/apollo/node_modules/ember-cli/lib/broccoli/ember-app.js:236:8)
```

After debug i found that to invoke passed not application instance but addon self
Cause app still can be find in addon.app but fix all that addons is ugly hack

**Comment by vvs-code** [comment]
The main question is
why at https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L308
we have
```
this.eachAddonInvoke('included', [this]);
```
instead of 
```
this.eachAddonInvoke('included', [arguments[0]]);
```

**Comment by rwjblue** [comment]
A nested addon gets `included` called with its parent addon, not the top level app.

**Comment by rwjblue** [comment]
It sounds like you are trying to access the top level app, from a nested addon.  This is not intended to work, as a nested addon should be isolated to accessing its direct parent (we don't want addons at N depth modifying the top level app).

**Comment by vvs-code** [comment]
It looks i have an error on migrating project. After using official way - it's ok.

**Comment by sky-coding** [comment]
I accidentally moved `broccoli-asset-rev` from `devDependencies` to `dependencies` in my addon and it was causing this error when the parent builds. Posting this here in case anyone finds themselves in a similar situation.
