### ISSUE TITLE
I'm unable to start `ember server` on a new project

### ISSUE THREAD

**Issue by marclundgren** [ember-cli/ember-cli#3573]
## Update
It looks like when `rimraf`requires `glob`, it's `undefined`.

## Node dependancies:
```
~ node --version
v0.12.0
~ npm --version
2.6.0
~  which bower
/usr/local/bin/bower
~  which phantomjs
/usr/local/bin/phantomjs
```

### Create a new project
```
~  ember new my-new-app
version: 0.1.15
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
```

Once the generation process finishes, launch the app:
```
~  cd my-new-app
my-new-app [master] ember server
version: 0.1.15
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
undefined is not a function
TypeError: undefined is not a function
    at rimraf (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/marc/Dev/EMBER/my-new-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by stefanpenner** [comment]
`npm ls rimraf`

**Comment by bndw** [comment]
related: https://github.com/ember-cli/ember-cli/issues/3492

**Comment by marclundgren** [comment]
thanks
