### ISSUE TITLE
serve keeps crashing on parsing error for a file that has been changed to remove offending line

### ISSUE THREAD

**Issue by justin-hackin** [ember-cli/ember-cli#3608]
So, I was messing around with a template and I couldn't get a list of models to render so I tried to access one of the models from the hasMany array to see if I could render it.  Well, it looks like the template compiler hated that. so I removed the offending line but the serve command still keeps giving me the same error.  I even removed the file from the tree, and it still keeps giving me the same error.  I also tried deleting the /tmp directory.  

```
version: 0.2.0
Could not find watchman, falling back to NodeWatcher for file system events
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Livereload server on port 35729
Serving on http://localhost:4200/
File: floorplan-viewer/templates/page-layout.hbs
Parse error on line 2:
... "regional" regions.0}}<h2>Page layout
-----------------------^
Expecting 'ID', got 'NUMBER'
Error: Parse error on line 2:
... "regional" regions.0}}<h2>Page layout
-----------------------^
Expecting 'ID', got 'NUMBER'
  at Object.parseError (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:2514:15)
  at Object.parse (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:2566:26)
  at parse (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:2262:34)
  at preprocess (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:3550:53)
  at compileSpec (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:741:17)
  at TemplateCompiler.__exports__.default [as precompile] (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/ember/ember-template-compiler.js:643:14)
  at TemplateCompiler.processString (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/index.js:50:59)
  at TemplateCompiler.Filter.processFile (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:139:31)
  at Promise.resolve.then.catch.err.file (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:85:21)
  at lib$rsvp$$internal$$tryCatch (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
  at /home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1095:13
  at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
  at processImmediate [as _immediateCallback] (timers.js:354:15)

```

**Comment by justin-hackin** [comment]
I used ember g template page-layout to create a new template of the same name and that solved the problem... but it would seem rather odd that this was somehow remembered....

**Comment by justin-hackin** [comment]
I can't reproduce this... please ignore :/

**Comment by stefanpenner** [comment]
> I can't reproduce this... please ignore :/

best bug fix!

Actually, if you do discover this again, report back. Would be curious what you ran into.

**Comment by justin-hackin** [comment]
Yes, I'll keep an eye out ...
