### ISSUE TITLE
ember new - exit code of #128

### ISSUE THREAD

**Issue by kumavis** [ember-cli/ember-cli#3612]
Error: `git ls-remote --tags --heads git://github.com/ember-cli/loader.js.git", exit code of #128`
```
╭─{🎍 } kumavis in ~/Development/Node
╰─± ember new hydra  
Future versions of Ember CLI will not support v0.10.35. Please update to Node 0.12 or io.js.
version: 0.2.0
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Failed to execute "git ls-remote --tags --heads git://github.com/ember-cli/loader.js.git", exit code of #128
Error: Failed to execute "git ls-remote --tags --heads git://github.com/ember-cli/loader.js.git", exit code of #128
    at createError (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/util/cmd.js:102:21)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```
```
╭─{🎍 } kumavis in ~/Development/Node
╰─± ember -v
Future versions of Ember CLI will not support v0.10.35. Please update to Node 0.12 or io.js.
version: 0.2.0
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.35
npm: 2.7.0
╭─{🎍 } kumavis in ~/Development/Node
╰─± node -v
v0.10.35
╭─{🎍 } kumavis in ~/Development/Node
╰─± npm -v
2.5.1
```

**Comment by stefanpenner** [comment]
@kumavis seems like this is firewall related, have you tried?

http://stackoverflow.com/questions/21544803/git-bower-errors-exit-code-128-failed-connect

**Comment by kumavis** [comment]
On stanford campus, and it seems to indeed be something with their network. Using a proxy everything installed correctly. ¯\_(ツ)_/¯

**Comment by stefanpenner** [comment]
> On stanford campus, and it seems to indeed be something with their network. Using a proxy everything installed correctly. ¯\_(ツ)_/¯

that sucks. :(

At some point, I hope to (or hope someone else can) circle back and try to polish the error messages for these types of issues.

**Comment by SeaBassTian** [comment]
I'm getting the same error message (Future versions of Ember CLI will not support v0.10.35. Please update to Node 0.12 or io.js.version: 0.2.0)and I'm on my home network. I'm running Avast Pro. Do I need to disable it or somehow allow it through the Firewall? Please help!
