### ISSUE TITLE
Build error with 0.2.1

### ISSUE THREAD

**Issue by CreativLogic** [ember-cli/ember-cli#3624]
I'm receiving this error:

```bash
version: 0.2.1
Buildingpaths { app: '/assets/gozooga.css' }
Build failed.
self is not defined
ReferenceError: self is not defined
    at JSHinter.getConfig (/www/html/gozooga/ember/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:114:7)
    at /www/html/gozooga/ember/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:37:28
    at lib$rsvp$$internal$$tryCatch (/www/html/gozooga/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/www/html/gozooga/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/www/html/gozooga/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/www/html/gozooga/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

```json
// package.json
{
  //...
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "broccoli-static-compiler": "^0.2.1",
    "ember-cli": "0.2.1",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-sass": "3.2.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16",
    "ember-export-application-global": "^1.0.2",
    "ember-truth-helpers": "0.0.5",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}
```

```json
// bower.json
{
  //...
  "dependencies": {
    "jquery": "^1.11.1",
    "ember": "1.10.0",
    "ember-data": "1.0.0-beta.16",
    "ember-resolver": "~0.1.14",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.2.8",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "~1.17.1",
    //...
  }
}
```

**Comment by rwjblue** [comment]
Fixed by https://github.com/rwjblue/broccoli-jshint/pull/18, but the issue is that your `.jshintrc` is an invalid format.

**Comment by rwjblue** [comment]
I will release a new version of broccoli-jshint shortly, and get things updated soon to prevent other folks from hitting this...

**Comment by CreativLogic** [comment]
> the issue is that your .jshintrc is an invalid format.

I'm able to build successfully now.

New item that's popping up is:

```
unit/helpers/format-date-test.js: line 5, col 1, 'module' is not defined.
unit/helpers/format-date-test.js: line 8, col 1, 'test' is not defined.
unit/helpers/format-date-test.js: line 10, col 3, 'ok' is not defined.
```

I remember hitting this before but it resolved itself after going to ember-cli@0.2.0-beta.1

**Comment by stefanpenner** [comment]
for reference this was the fix: https://github.com/rwjblue/broccoli-jshint/commit/e088cf910dac1e3f8404f13ac881de1c9eddff99

**Comment by stefanpenner** [comment]
@CreativLogic it seems like we forgot proper release notes for 0.2, but you can use https://github.com/abuiles/ember-watson to auto-upgrade your tests. 

Basically the latest QUnit has deprecated global usage of module/test/ok

**Comment by CreativLogic** [comment]
> you can use https://github.com/abuiles/ember-watson to auto-upgrade your tests.

Bingo. Thanks for the help!
