### ISSUE TITLE
has no method 'hasMagic' with ember-cli 0.1.15 while building

### ISSUE THREAD

**Issue by mszoernyi** [ember-cli/ember-cli#3633]
I've got a strange error which I can't fix and looking for some help.

I did a mistake upgarding to node 0.12.x and reverted this change with `nvm` and went back to `node 0.10.30`.

I removed all node modules and did a clean install. My colleagues with the same version has no issue at all.

**ember -v**
```
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.30
npm: 2.1.8
```

**ember build**
```
Serving on http://0.0.0.0:3002/
Object function glob(pattern, options, cb) {
 if (typeof options === "function") cb = options, options = {}
 if (!options) options = {}
 
 if (typeof options === "number") {
   deprecated()
   return
 }
 
 var g = new Glob(pattern, options, cb)
 return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
 if (typeof options === "function") cb = options, options = {}
 if (!options) options = {}
 
 if (typeof options === "number") {
   deprecated()
   return
 }
 
 var g = new Glob(pattern, options, cb)
 return g.sync ? g.found : g
} has no method 'hasMagic'
 at rimraf (/Users/foo/ui/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
 at lib$rsvp$node$$tryApply (/Users/foo/ui/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
 at lib$rsvp$node$$handleValueInput (/Users/foo/ui/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
 at fn (/Users/foo/ui/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
 at /Users/foo/ui/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
 at lib$rsvp$$internal$$tryCatch (/Users/foo/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
 at lib$rsvp$$internal$$invokeCallback (/Users/foo/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
 at lib$rsvp$$internal$$publish (/Users/foo/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
 at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/foo/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
 at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by dylan947** [comment]
That's an issue with rimraf. You can update to 0.2.0 or install rimraf 2.2.8 in your project as a dependency.

**Comment by mszoernyi** [comment]
ah thats a direction at least. Thanks! Upgrading to 0.2.0 doesn't work right now due to some other dependencies which are not working with the latest version. Had no time to update them myself yet.

**Comment by stefanpenner** [comment]
unfortunately we are not going to be fixing older versions. This issue is a bummer, as it is an upstream dependency that changed behaviour in semver.

As @dylan947 mentioned, this is mitigated in 0.2.x.
