### ISSUE TITLE
0.2.1 moduleForModel does not resolve second this.subject()

### ISSUE THREAD

**Issue by ryanere** [ember-cli/ember-cli#3649]
**Steps to reproduce:**
1. `ember new blah`
2. `ember g model post`
3. Add the specs below to `post-test.js`
4. Observe stacktrace on *second* identical test

**Example repo:** 
* https://github.com/ryanere/ember-cli-blah

```javascript
import {
  moduleForModel,
  test
} from 'ember-qunit';

moduleForModel('post', {
  // Specify the other units that are required for this test.
  needs: []
});

test('it exists', function(assert) {
  var model = this.subject();
  // var store = this.store();
  assert.ok(!!model);
});

test('it exists', function(assert) {
  var model = this.subject();
  // var store = this.store();
  assert.ok(!!model);
});
```
![](https://s3.amazonaws.com/f.cl.ly/items/290u0t2A2K2y1d080N2K/Screen%20Shot%202015-03-25%20at%2011.56.19%20AM.png)

```
Died on test #1     at Object.test (http://localhost:4200/assets/test-support.js:1693:11)
    at http://localhost:4200/assets/blah.js:254:15
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18): Cannot read property 'adapter:post' of undefined@ 10 ms
Source: 	
TypeError: Cannot read property 'adapter:post' of undefined
    at ember$data$lib$system$store$$Service.extend.retrieveManagedInstance (http://localhost:4200/assets/vendor.js:75111:34)
    at ember$data$lib$system$store$$Service.extend.lookupAdapter (http://localhost:4200/assets/vendor.js:75124:21)
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:4200/assets/vendor.js:75043:28)
    at ember$data$lib$system$store$$Service.extend._generateId (http://localhost:4200/assets/vendor.js:73569:28)
    at ember$data$lib$system$store$$Service.extend.createRecord (http://localhost:4200/assets/vendor.js:73540:32)
    at http://localhost:4200/assets/test-support.js:1911:51
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10749:27)
    at Object.run (http://localhost:4200/assets/vendor.js:27187:29)
    at callbacks.subject (http://localhost:4200/assets/test-support.js:1910:35)
    at Object.context.(anonymous function) [as subject] (http://localhost:4200/assets/test-support.js:2085:41)
```

Am I missing something here?  I downgraded to 0.2.0 and ran the same thing and both identical tests passed.

**Comment by stefanpenner** [comment]
i believe this is was a bug in the test framework, should be fixed in the next release.

**Comment by rwjblue** [comment]
Submitted https://github.com/ryanere/ember-cli-blah/pull/1 with updates for ember-data and ember-qunit (both of which had bugs fixed in them since 0.2.1 was released).  Please test with those updates and let us know.

**Comment by ryanere** [comment]
You guys are fast... @rwjblue's updates to `bower.json` fixed the issue.  Thanks!

**Comment by rwjblue** [comment]
Thanks confirming.
