### ISSUE TITLE
Test failure with `git clone`: "Unable to read current working directory:"

### ISSUE THREAD

**Issue by joliss** [ember-cli/ember-cli#3671]
I'm getting the following test failure on master:

```
    1) ember new with git blueprint uses checks out the blueprint and uses it
    ✓ ember new without skip-git flag creates .git dir (56ms)
    ✓ ember new with --dry-run does not create new directory

  Acceptance: ember destroy pod
    ✓ .ember-cli usePods setting destroys in pod structure without --pod flag (69ms)
    ✓ .ember-cli usePods setting destroys in basic structure with --pod flag (78ms)
Command failed: /bin/sh -c git clone https://github.com/trek/app-blueprint-test.git /tmp/ember-cli115227-56239-1oalbbo
Cloning into '/tmp/ember-cli115227-56239-1oalbbo'...
fatal: Unable to read current working directory: No such file or directory
fatal: remote did not send all necessary objects
Unexpected end of command stream

Error: Command failed: /bin/sh -c git clone https://github.com/trek/app-blueprint-test.git /tmp/ember-cli115227-56239-1oalbbo
Cloning into '/tmp/ember-cli115227-56239-1oalbbo'...
fatal: Unable to read current working directory: No such file or directory
fatal: remote did not send all necessary objects
Unexpected end of command stream

    at ChildProcess.exithandler (child_process.js:716:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Socket.<anonymous> (child_process.js:1153:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
    ✓ .ember-cli usePods setting correctly destroys component (92ms)
    ✓ controller foo --pod (83ms)

...

  829 passing (1m)
  4 pending
  1 failing

  1) Acceptance: ember new ember new with git blueprint uses checks out the blueprint and uses it:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/home/ubuntu/src/ember-cli/node_modules/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:88:15)
```

**Comment by stefanpenner** [comment]
@joliss seems like something with git + your setup is being funky.

**Comment by joliss** [comment]
This is on Linux; error messages like `Unable to read current working directory: No such file or directory` tend to happen when the working directory is deleted.

**Comment by joliss** [comment]
@stefanpenner Running `git` myself works fine:

```
$ git clone https://github.com/trek/app-blueprint-test.git /tmp/ember-cli115227-56239-1oalbbo
Cloning into '/tmp/ember-cli115227-56239-1oalbbo'...
remote: Counting objects: 79, done.
remote: Total 79 (delta 0), reused 0 (delta 0), pack-reused 79
Unpacking objects: 100% (79/79), done.
Checking connectivity... done.
```

Could it be that something deletes the current working directory of the test?

**Comment by stefanpenner** [comment]
hmm i wonder if some race exists where the new setup task of a test occurs before the teardown of a previous test completes. Last time we ran into this, it was one of our deps that had a horrible race.

**Comment by stefanpenner** [comment]
ya, last time it was NCP I think

**Comment by stefanpenner** [comment]
the pod destroy tests are somewhat recent maybe there is a race there, looking...

**Comment by stefanpenner** [comment]
i have also seen `process.chdir` be racy in linux.
 https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/pods-destroy-test.js#L37-L40

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/pods-destroy-test.js#L46 is also dubious

**Comment by stefanpenner** [comment]
fs-extra which does remove was just updated ... https://github.com/ember-cli/ember-cli/commit/ac151430631fd335c5e7529206c49a9dfe373851#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R111

**Comment by stefanpenner** [comment]
I can also confirm an somewhat related issue that did not exist an hour ago.

```
  1 failing

  1) Blueprint basic blueprint installation "after each" hook:
     Error: ENOTEMPTY: directory not empty, rmdir '/Users/stefanpenner/src/ember-cli/tmp'
      at Error (native)
```

**Comment by stefanpenner** [comment]
@joliss can you share

* npm version
* node version
* git version
* what sha of master are you on?

**Comment by joliss** [comment]
```
$ npm --version; node --version; git --version; git rev-parse HEAD
2.7.1
v1.6.2
git version 1.9.1
3f75df0a099638ab58933f4804c5c1dcc7eadf8e
```

**Comment by joliss** [comment]
I think this might be Linux-specific. Mac OS X seems to be more forgiving when the cwd goes away; on Linux, when cwd is deleted from the file system, `getcwd` will return an error.

**Comment by stefanpenner** [comment]
@joliss i think the races exist on both, buy yes OSX is more forgiving. Although having linux would make this easier to debug.

**Comment by stefanpenner** [comment]
anyone with linux handy got time to dig into this race?

**Comment by stefanpenner** [comment]
seems to have gone stale
