### ISSUE TITLE
ember-cli 0.2.1 breaks model unit tests

### ISSUE THREAD

**Issue by blakeley** [ember-cli/ember-cli#3683]
Steps to reproduce:

1. `ember g adafter`
2. `ember g model mm`
3. Visit [http://localhost:4200/tests](http://localhost:4200/tests) and note all tests passing
4. Add a second test to `tests/unit/models/mm-test.js` (Could just copy/paste the default test)
5. Visit [http://localhost:4200/tests](http://localhost:4200/tests) and note the second (identical) test fails

**Comment by stefanpenner** [comment]
please provide test output

also, I can't be sure without the output but I believe this is fixed upstream in our test helpers.

**Comment by stefanpenner** [comment]
potentially https://github.com/switchfly/ember-test-helpers/commit/94d3c221e4e9cf6926a2303cbb74b3703cabe2b5

**Comment by blakeley** [comment]
```
Died on test #1     at Object.test (http://localhost:4200/assets/test-support.js:1693:11)
    at http://localhost:4200/assets/adafter.js:254:15
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18): Cannot read property 'adapter:mm' of undefined@ 2 ms
Source: 	
TypeError: Cannot read property 'adapter:mm' of undefined
    at ember$data$lib$system$store$$Service.extend.retrieveManagedInstance (http://localhost:4200/assets/vendor.js:75111:34)
    at ember$data$lib$system$store$$Service.extend.lookupAdapter (http://localhost:4200/assets/vendor.js:75124:21)
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:4200/assets/vendor.js:75043:28)
    at ember$data$lib$system$store$$Service.extend._generateId (http://localhost:4200/assets/vendor.js:73569:28)
    at ember$data$lib$system$store$$Service.extend.createRecord (http://localhost:4200/assets/vendor.js:73540:32)
    at http://localhost:4200/assets/test-support.js:1911:51
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10749:27)
    at Object.run (http://localhost:4200/assets/vendor.js:27187:29)
    at callbacks.subject (http://localhost:4200/assets/test-support.js:1910:35)
    at Object.context.(anonymous function) [as subject] (http://localhost:4200/assets/test-support.js:2085:41)
```

**Comment by blakeley** [comment]
[Here](https://github.com/blakeley/adafter) is an example repo you can clone to reproduce the bug

**Comment by blakeley** [comment]
`ember -v` produces

```
version: 0.2.1
node: 0.12.1
npm: 2.7.3
```

**Comment by rwjblue** [comment]
Almost certainly fixed by ember-qunit 0.3.0

**Comment by rwjblue** [comment]
https://github.com/blakeley/adafter/pull/1 should fix

**Comment by blakeley** [comment]
That fixed it. Thanks so much!

**Comment by stefanpenner** [comment]
@blakeley it will be part of the next release as well. I'm working on validating it as we speak.

**Comment by blakeley** [comment]
Great!
