### ISSUE TITLE
v0.2.2 Cannot have both inputTree and inputTrees: CoreObject

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3721]
Getting this twice on `ember build --watch`

```no-highlight
ember build --watch
version: 0.2.2
Building...
Cannot have both inputTree and inputTrees: CoreObject
Error: Cannot have both inputTree and inputTrees: CoreObject
    at NewStyleTreeWrapper.read (/Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:30:11)
    at /Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at lib$rsvp$$internal$$tryCatch (/Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/iradchenko/workspace/bwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:349:13)
```

```no-highlight
version: 0.2.2
node: 1.5.1 (iojs)
npm: 2.7.4
```

Here's my `Brocfile.js`

```js
/* global require, module */

var path = require('path');
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var mergeTrees = require('broccoli-merge-trees');
var pickFiles = require('broccoli-static-compiler');

var app = new EmberApp();

importAssets(app, app.bowerDirectory, [
  'event-source-polyfill/eventsource.js',
  'bootstrap/dist/js/bootstrap.js'
]);

// Copy fontawesome fonts
var fonts = pickFiles(app.bowerDirectory + '/fontawesome/fonts', {
  srcDir: '/',
  files: ['**/*'],
  destDir: '/assets/fonts'
});

module.exports = mergeTrees([app.toTree(), fonts]);

function importAssets(app, baseUrl, urls) {
  urls.forEach(function (url) {
    app.import(path.join(baseUrl, url));
  });
}
```

**Comment by stefanpenner** [comment]
can you provide a working reproduction?

**Comment by knownasilya** [comment]
@stefanpenner It's `ember-browserify` cc @ef4

**Comment by ef4** [comment]
https://github.com/ef4/ember-browserify/issues/25

**Comment by knownasilya** [comment]
Closing in favor of that issue.
