### ISSUE TITLE
http-proxy generator is broken

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3754]
When generating a `http-proxy`, the output contains:
```
var proxyPath = '/<%=camelizedModuleName %>';
...
proxy.web(req, res, { target: '<%=proxyUrl %>' });
```

I think does should have been *expanded* to actual strings.
I've only tested on `0.2.2`.

**Comment by davewasmer** [comment]
You might try with the PR I just created (#3786). Without the PR, when the CLI attempts to expand those variables, it will swallow and errors (like a ReferenceError if you reference a variable that isn't defined) and abort the expansion (returning the template source itself, what you pasted above).

With the PR, any errors during the variable expansion will abort the entire process, and dump the error to the console.

**Comment by btecu** [comment]
This is still broken in **0.2.5**.

**Comment by stefanpenner** [comment]
can confirm.

**Comment by btecu** [comment]
No, it doesn't seem to work:

```
proxyUrl is not defined (Error in blueprint template: /../ember-cli/blueprints/http-proxy/files/server/proxies/__name__.js)
ReferenceError: proxyUrl is not defined (Error in blueprint template: /../ember-cli/blueprints/http-proxy/files/server/proxies/__name__.js)
    at eval (eval at <anonymous> (/../ember-cli/node_modules/lodash/string/template.js:214:56), <anonymous>:8:10)
    at processTemplate (/../ember-cli/lib/models/file-info.js:13:52)
    at /../ember-cli/lib/models/file-info.js:94:20
    at lib$rsvp$$internal$$tryCatch (/../ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/../ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/../ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/../ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

**Comment by marcioj** [comment]
It's working fine for me in 0.2.7
