### ISSUE TITLE
Addon acceptance tests breaking on 0.2.3

### ISSUE THREAD

**Issue by dustinfarris** [ember-cli/ember-cli#3863]
This might be related to #3690.

I am seeing this a lot in my existing acceptance tests for my addon project:

```
beforeEach failed on Permission denied error: undefined is not a function@ 12 ms
Source: 	
TypeError: undefined is not a function
    at EmberApplication.reopen.setupForTesting (http://localhost:7357/assets/vendor.js:48568:21)
    at http://localhost:7357/assets/dummy.js:779:19
    at Object.Backburner.run (http://localhost:7357/assets/vendor.js:10749:27)
    at Object.run (http://localhost:7357/assets/vendor.js:27187:29)
    at Object.startApp [as default] (http://localhost:7357/assets/dummy.js:777:22)
    at Object.beforeEach (http://localhost:7357/assets/dummy.js:215:40)
    at runHook (http://localhost:7357/assets/test-support.js:3404:20)
    at process (http://localhost:7357/assets/test-support.js:3061:24)
    at begin (http://localhost:7357/assets/test-support.js:3106:2)
    at http://localhost:7357/assets/test-support.js:3122:4
```

Here: https://github.com/dustinfarris/ember-django-adapter/pull/81
CI Output: https://circleci.com/gh/dustinfarris/ember-django-adapter/134
(on a side note, the new `ember try:testall` hangs)

**Comment by trabus** [comment]
That PR you sited should have only affected generating blueprints when developing an addon. I don't think it would affect setting up a test though.

This seems like something else to me:
```
not ok 3 PhantomJS 1.9 - Acceptance: CRUD Failure: Permission denied error
    ---
        actual: >
            null
        message: >
            beforeEach failed on Permission denied error: 'undefined' is not a function (evaluating 'this.Router.reopen({
                      location: 'none'
                    })')
```

**Comment by stefanpenner** [comment]
seems to work fine in the browser tests

**Comment by stefanpenner** [comment]
figured it out.

Ember 1.11 is the only one that supports: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/router.js#L8-L9
