### ISSUE TITLE
Deprecation warning does not give enough context

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#3877]
I get lots of deprecation warnings after moving to `ember@canary`:

```
» ember server --live-reload-port 35730 --port 4200
version: 0.2.3
Livereload server on port 35730
Serving on http://localhost:4200/
DEPRECATION: Using {{with}} without block syntax is deprecated. Please use standard block form (`{{#with foo as |bar|}}`) instead. See http://emberjs.com/deprecations/v1.x/#toc_code-as-code-sytnax-for-code-with-code for more details.
        at /home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:9311:15
        at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12943:9)
        at visitors.ElementNode (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12959:18)
        at Walker.children (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12976:9)
        at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12944:14)
        at visitors.Program (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12953:18)
        at Walker.children (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12976:9)
        at Walker.visit (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12944:14)
        at visitors.BlockStatement (/home/user1/projects/frontend-app/bower/ember/ember-template-compiler.js:12964:16)
```

I am using:

```
» ember --version
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```

But this does not tell me anything about the template file affected by the deprecation. Would it be possible to have this info displayed too?

**Comment by stefanpenner** [comment]
its possible, but needs some refactoring across several libraries. Let me compile exactly what needs to be done.

**Comment by stefanpenner** [comment]
* we need to pass the relativePath to https://github.com/ember-cli/ember-cli-htmlbars/blob/master/index.js#L51
* then thread it or an extra context object that contains it all the way into the transformers
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-with-as-to-hash.js#L34
* then we have the path here: https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-with-as-to-hash.js#L45-L50

**Comment by rwjblue** [comment]
I had started this a little while back in https://github.com/tildeio/htmlbars/pull/310.  That allows the options passed in to `compile` to be passed through to the transform.

I'll pick this up...

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/10868 to allow Ember to access the module name provided to compile.

**Comment by rwjblue** [comment]
Updated ember-cli-htmlbars in https://github.com/ember-cli/ember-cli-htmlbars/pull/50.

**Comment by stefanpenner** [comment]
fixed: https://github.com/emberjs/ember.js/pull/10868/files

**Comment by rwjblue** [comment]
Using ember-cli-htmlbars@0.7.6 and latest canary build, the module name should now be included in the deprecation notice.  This should land in 1.12.0-beta.2 today/tomorrow also.
