### ISSUE TITLE
Generated initializer test fails with undefined function 'initialize' in addon in 0.2.3

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3886]
Example of minimal addon here:
https://github.com/Twinkletoes/ember-cli-browser-update

Initializer test fails with
```
Died on test #1     at http://localhost:7357/assets/dummy.js:276:9
    at mod.state (http://localhost:7357/assets/vendor.js:150:29)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:40:24): undefined is not a function@ 7 ms
Source: 	
TypeError: undefined is not a function
    at Object.<anonymous> (http://localhost:7357/assets/dummy.js:277:20)
    at Object.Test.run (http://localhost:7357/assets/test-support.js:3443:28)
    at http://localhost:7357/assets/test-support.js:3572:11
    at process (http://localhost:7357/assets/test-support.js:3131:24)
    at begin (http://localhost:7357/assets/test-support.js:3176:2)
    at http://localhost:7357/assets/test-support.js:3192:4
```

Initializer in question is:
```
// in initializers/browser-update.js
export function initialize(/* container, application */) {
  // application.inject('route', 'foo', 'service:foo');
  console.log('initialized');
}

export default {
  name: 'browser-update',
  initialize: initialize
};
```

**Comment by Twinkletoes** [comment]
Test is as generated:

```
import Ember from 'ember';
import { initialize } from '../../../initializers/browser-update';
import { module, test } from 'qunit';

var container, application;

module('BrowserUpdateInitializer', {
  beforeEach: function() {
    Ember.run(function() {
      application = Ember.Application.create();
      container = application.__container__;
      application.deferReadiness();
    });
  }
});

// Replace this with your real tests.
test('it works', function(assert) {
  initialize(container, application);

  // you would normally confirm the results of the initializer here
  assert.ok(true);
});
```

**Comment by marcioj** [comment]
I believe this is a bug. The reexport in [browser-update.js](in https://github.com/Twinkletoes/ember-cli-browser-update/blob/master/app/initializers/browser-update.js) is just exporting the default object which is the initializer hash. But your [browser-update-test.js](https://github.com/Twinkletoes/ember-cli-browser-update/blob/master/tests/unit/initializers/browser-update-test.js#L2) is looking up the initializer function which is undefined.
The quick fix is to change your test and probably the ember-cli initializer-test blueprint to use the exported hash and call the `initialize` function:

```js
import initializer from '../../../initializers/browser-update'; // import the initializer hash
// ... other things ...

test('it works', function(assert) {
  initializer.initialize(container, application); // call initialize

  assert.ok(true);
});
 ```

But the better approach would be to use the `export * from 'path/to/something';` to reexport all. However I think it's not supported by esperanto yet.

**Comment by Twinkletoes** [comment]
Great! That fixed it
