### ISSUE TITLE
app.import doesn't work  for files outside  vendor and bower_components folder

### ISSUE THREAD

**Issue by tsing80** [ember-cli/ember-cli#3890]
I try to add the following line in Brocfile.js in order to copy runtime configuration file verbatim into the dist folder:

app.import('config/myapp.json')

However, the following error occur in the ember-cli:
```
Error: ENOENT, no such file or directory '/home/tsing80/myapp/tmp/tree_merger-tmp_dest_dir-viHmY5qQ.tmp/config/'
  at Error (native)
  at Object.fs.readdirSync (fs.js:765:18)
  at walkSync (/home/tsing80/myapp/node_modules/ember-cli/node_modules/walk-sync/index.js:14:20)
  at Funnel.processFilters (/home/tsing80/myapp/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:140:15)
  at Funnel.handleReadTree (/home/tsing80/myapp/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:129:10)
  at lib$rsvp$$internal$$tryCatch (/home/tsing80/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/tsing80/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/tsing80/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/tsing80/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```
looking into tree_merger-tmp_dest_dir-viHmY5qQ.tmp directory, only two directory is inside:
```
 bower_components -> /home/tsing80/myapp/bower_components
 vendor -> /home/tsing80/myapp/tmp/tree_merger-tmp_dest_dir-oJfEkvQI.tmp
```
so app.import for other folder is not possible.

**Comment by stefanpenner** [comment]
> so app.import for other folder is not possible.

this is by design. Feel free to symlink in if thats the behavior you want. Some-day we may open this up further, but not really something we support today.

**Comment by tsing80** [comment]
@stefanpenner Should it treat as documentation bug? It is not mentioned in http://www.ember-cli.com/#managing-dependencies

**Comment by lightblade** [comment]
@stefanpenner I though `ember-cli` is moving off of bower dependencies. How do we import files hosted through npm?

**Comment by lightblade** [comment]
Found the solution.

ember-cli/ember-cli#1984

**Comment by stefanpenner** [comment]
@lightblade once the `bower` removal lands we will natively support `npm:package-name` and a sort of auto-browserify step. 

cc @chadhietala

**Comment by mshindal** [comment]
Sorry for commenting on a dead thread but shouldn't this be made more obvious? It doesn't say anything about it in the docs.

**Comment by stefanpenner** [comment]
i believe it is documented, but if you see a better place for this to be mentioned (or a warning) please feel free to submit a patch/propose a change. Would love to improve the usability.

**Comment by kellyselden** [comment]
@mshindal It should be if it isn't. Tracked here if you want to check it out. https://github.com/ember-cli/ember-cli.github.io/issues/52

**Comment by runspired** [comment]
I opened an RFC issue to discuss a solution for this: https://github.com/ember-cli/rfcs/issues/84
