### ISSUE TITLE
In-Repo Add-On Component Template Swap/Undo files swept up by Broccoli, causes error

### ISSUE THREAD

**Issue by noslouch** [ember-cli/ember-cli#3941]
I think #3585 caused a regression to #2329. Here are simple steps to reproduce.

First, output of `ember --version`:

```
$ ember --version
Future versions of Ember CLI will not support v0.10.33. Please update to Node 0.12 or io.js.
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.10.33
npm: 2.7.6
```

To reproduce:

```
$ ember new blank
$ cd blank
$ ember generate in-repo-addon calendar
$ ember generate component foo-bar --in-repo-addon calendar
$ vim lib/calendar/addon/templates/components/foo-bar.hbs
<edit edit save>
$ ember s
```

Output:

```
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
An `addon/templates` tree was detected, but there are no template compilers registered for `calendar`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `calendar`'s `package.json`.
```

So...
```
$ cd lib/calendar
$ npm install ember-cli-htmlbars --save
$ cd ../..
$ ember s
```

Output:
```
Future versions of Ember CLI will not support v0.10.33. Please update to Node 0.12 or io.js.
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Livereload server on port 35729
Serving on http://localhost:4200/
File: calendar/templates/components/.foo-bar.hbs.un~
Unexpected character '�' (1:3)
SyntaxError: Unexpected character '�' (1:3)
    at Parser.pp.raise (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:1009:13)
    at Parser.pp.getTokenFromCode (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:2682:8)
    at Parser.pp.readToken (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:2385:15)
    at Parser.pp.nextToken (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:2377:71)
    at Parser.pp.next (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:2326:8)
    at Parser.pp.parseIdent (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:737:8)
    at Parser.pp.parseExprAtom (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:373:21)
    at Parser.pp.parseExprSubscripts (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:321:19)
    at Parser.pp.parseMaybeUnary (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:303:19)
    at Parser.pp.parseExprOps (/home/bwhitton/blank/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/dist/acorn.js:259:19)
```

**Comment by marcioj** [comment]
Hi @noslouch, this issue is fixed on master. And will be available in the next release.

**Comment by noslouch** [comment]
:+1: thanks guys
