### ISSUE TITLE
ES6 object literal syntax in In Repo Addon chokes production build

### ISSUE THREAD

**Issue by noslouch** [ember-cli/ember-cli#4015]
Another In Repo Addon bug. Using ES6 shorthand for object methods chokes on production builds.

```
$ ember --version
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.12.0
npm: 2.7.6

$ ember new blank
$ ember g in-repo-addon calendar
$ ember g component x-foo --in-repo-addon calendar
```
Contents of `lib/calendar/addon/components/x-foo.js`:

```
import Ember from 'ember';
import layout from '../templates/components/x-foo';

export default Ember.Component.extend({
  layout: layout,
    fooMethod() { // ES6 syntax
        console.log('hello world')
    }
});  
```

Add htmlbars compiler and build
```
$ cd lib/calendar
$ npm install ember-cli-htmlbars --save
$ cd ../..
$ ember build --environment production
```

Output: 
```
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Build failed.
Unexpected token punc «(», expected punc «:»
Error
    at new JS_Parse_Error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:688:9)
    at expect_token (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:701:9)
    at expect (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:704:36)
    at /Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1257:13
    at /Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:727:24
    at expr_atom (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1187:35)
    at maybe_unary (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1363:19)
```

**Comment by stefanpenner** [comment]
you need to include babel in the in-repo addons package.json in the dependencies section.

**Comment by noslouch** [comment]
getting the same error. 

```
$ cd lib/calendar
$ npm install babel --save
$ cd ../../
$ ember build --environment production
```

contents of `lib/calendar/package.json`:

```
{
  "name": "calendar",
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "babel": "^5.2.15",
    "ember-cli-htmlbars": "^0.7.6"
  }
}
```

output:
```
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Build failed.
Unexpected token punc «(», expected punc «:»
Error
    at new JS_Parse_Error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:688:9)
    at expect_token (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:701:9)
    at expect (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:704:36)
    at /Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1257:13
    at /Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:727:24
    at expr_atom (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1187:35)
    at maybe_unary (/Users/bwhitton/blank/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1363:19)
```

**Comment by noslouch** [comment]
ah, not babel, `ember-cli-babel`.

```
$ cd lib/calendar
$ npm uninstall babel --save
$ npm install ember-cli-babel --save
$ cd ../..
$ ember build --environment production
```
works!

:100:
