### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by lifeinafolder** [ember-cli/ember-cli#4048]
```
npm cache clean
npm install -g ember-cli
```

```
npm http GET https://registry.npmjs.org/ember-cli
npm http 200 https://registry.npmjs.org/ember-cli
npm http GET https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.3.tgz
npm http 200 https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.3.tgz
npm http GET https://registry.npmjs.org/broccoli-merge-trees/0.2.1
npm http GET https://registry.npmjs.org/broccoli-unwatched-tree/0.1.1
npm http GET https://registry.npmjs.org/broccoli-sane-watcher
npm http GET https://registry.npmjs.org/broccoli-writer/0.1.1
npm http GET https://registry.npmjs.org/broccoli-sourcemap-concat
npm http GET https://registry.npmjs.org/core-object/0.0.2
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ember-cli-copy-dereference
npm http GET https://registry.npmjs.org/ember-router-generator
npm http GET https://registry.npmjs.org/exit
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/is-git-url
npm http GET https://registry.npmjs.org/js-string-escape
npm http GET https://registry.npmjs.org/markdown-it/4.0.3
npm http GET https://registry.npmjs.org/markdown-it-terminal/0.0.2
npm http GET https://registry.npmjs.org/rimraf/2.3.2
npm http GET https://registry.npmjs.org/promise-map-series
npm http GET https://registry.npmjs.org/pleasant-progress
npm http GET https://registry.npmjs.org/sane
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/rsvp
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/symlink-or-copy
npm http GET https://registry.npmjs.org/temp/0.8.1
npm http GET https://registry.npmjs.org/yam/0.0.18
npm http GET https://registry.npmjs.org/testem
npm http GET https://registry.npmjs.org/walk-sync/0.1.3
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/broccoli-caching-writer/0.5.5
npm http GET https://registry.npmjs.org/broccoli-filter/0.1.12
npm http GET https://registry.npmjs.org/broccoli-funnel/0.2.2
npm http GET https://registry.npmjs.org/broccoli-kitchen-sink-helpers/0.2.6
npm http GET https://registry.npmjs.org/broccoli-es3-safe-recast
npm http GET https://registry.npmjs.org/broccoli-es6modules
npm http 200 https://registry.npmjs.org/broccoli-merge-trees/0.2.1
npm http 200 https://registry.npmjs.org/broccoli-unwatched-tree/0.1.1
npm http GET https://registry.npmjs.org/broccoli-unwatched-tree/-/broccoli-unwatched-tree-0.1.1.tgz
npm http GET https://registry.npmjs.org/broccoli-merge-trees/-/broccoli-merge-trees-0.2.1.tgz
npm http 200 https://registry.npmjs.org/broccoli-sane-watcher
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/broccoli-unwatched-tree/-/broccoli-unwatched-tree-0.1.1.tgz
npm http 200 https://registry.npmjs.org/broccoli-merge-trees/-/broccoli-merge-trees-0.2.1.tgz
npm http 200 https://registry.npmjs.org/ember-cli-copy-dereference
npm http 200 https://registry.npmjs.org/ember-router-generator
npm http 200 https://registry.npmjs.org/exit
npm http 200 https://registry.npmjs.org/http-proxy
npm http 200 https://registry.npmjs.org/is-git-url
npm http 200 https://registry.npmjs.org/broccoli-writer/0.1.1
npm http 200 https://registry.npmjs.org/broccoli-sourcemap-concat
npm http 200 https://registry.npmjs.org/js-string-escape
npm http 200 https://registry.npmjs.org/core-object/0.0.2
npm http 200 https://registry.npmjs.org/markdown-it-terminal/0.0.2
npm http 200 https://registry.npmjs.org/markdown-it/4.0.3
npm http 200 https://registry.npmjs.org/sane
npm http 200 https://registry.npmjs.org/rimraf/2.3.2
npm http 200 https://registry.npmjs.org/semver
npm http 200 https://registry.npmjs.org/strip-ansi
npm http 200 https://registry.npmjs.org/rsvp
npm http 200 https://registry.npmjs.org/symlink-or-copy
npm http 200 https://registry.npmjs.org/promise-map-series
npm http 200 https://registry.npmjs.org/pleasant-progress
npm http 200 https://registry.npmjs.org/temp/0.8.1
npm http 200 https://registry.npmjs.org/abbrev
npm http 200 https://registry.npmjs.org/yam/0.0.18
npm http 200 https://registry.npmjs.org/broccoli-caching-writer/0.5.5
npm http 200 https://registry.npmjs.org/broccoli-filter/0.1.12
npm http 200 https://registry.npmjs.org/walk-sync/0.1.3
npm http 200 https://registry.npmjs.org/broccoli-funnel/0.2.2
npm http 200 https://registry.npmjs.org/broccoli-es3-safe-recast
npm http 200 https://registry.npmjs.org/testem
npm http 200 https://registry.npmjs.org/broccoli-es6modules
npm http 200 https://registry.npmjs.org/broccoli-kitchen-sink-helpers/0.2.6
npm http GET https://registry.npmjs.org/broccoli-writer/-/broccoli-writer-0.1.1.tgz
npm http 200 https://registry.npmjs.org/broccoli-writer/-/broccoli-writer-0.1.1.tgz
npm http GET https://registry.npmjs.org/markdown-it-terminal/-/markdown-it-terminal-0.0.2.tgz
npm http GET https://registry.npmjs.org/core-object/-/core-object-0.0.2.tgz
npm http 200 https://registry.npmjs.org/markdown-it-terminal/-/markdown-it-terminal-0.0.2.tgz
npm http 200 https://registry.npmjs.org/core-object/-/core-object-0.0.2.tgz
npm http GET https://registry.npmjs.org/markdown-it/-/markdown-it-4.0.3.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.3.2.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.3.2.tgz
npm http 200 https://registry.npmjs.org/markdown-it/-/markdown-it-4.0.3.tgz
npm http GET https://registry.npmjs.org/broccoli-filter/-/broccoli-filter-0.1.12.tgz
npm http GET https://registry.npmjs.org/yam/-/yam-0.0.18.tgz
npm http GET https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http GET https://registry.npmjs.org/broccoli-caching-writer/-/broccoli-caching-writer-0.5.5.tgz
npm http 200 https://registry.npmjs.org/broccoli-filter/-/broccoli-filter-0.1.12.tgz
npm http 200 https://registry.npmjs.org/yam/-/yam-0.0.18.tgz
npm http 200 https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http GET https://registry.npmjs.org/broccoli-funnel/-/broccoli-funnel-0.2.2.tgz
npm http GET https://registry.npmjs.org/walk-sync/-/walk-sync-0.1.3.tgz
npm http GET https://registry.npmjs.org/broccoli-kitchen-sink-helpers/-/broccoli-kitchen-sink-helpers-0.2.6.tgz
npm http 200 https://registry.npmjs.org/broccoli-caching-writer/-/broccoli-caching-writer-0.5.5.tgz
npm http 200 https://registry.npmjs.org/walk-sync/-/walk-sync-0.1.3.tgz
npm http 200 https://registry.npmjs.org/broccoli-funnel/-/broccoli-funnel-0.2.2.tgz
npm http 200 https://registry.npmjs.org/broccoli-kitchen-sink-helpers/-/broccoli-kitchen-sink-helpers-0.2.6.tgz
npm ERR! Error: No compatible version found: broccoli-sane-watcher@'^1.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.1.1","1.0.0","1.0.1","1.0.2","1.1.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! 
```

Has anyone experienced this before?

**Comment by lifeinafolder** [comment]
It was happening because my nodejs version was old.
