### ISSUE TITLE
failing test for components

### ISSUE THREAD

**Issue by spruce** [ember-cli/ember-cli#4051]
Hey,
I starting to test my complete app. I use ember-rapid-forms. There we have some components like say em-form and em-select. These are the only components which I use in my components template. Internally ember-rapid-forms relies on some other components (namely: form-group).

When I try to it with the default test. It throws an assertion failed error which reads:
```
Died on test #2 	at test (http://localhost:7357/assets/test-support.js:1803:15)
            	at http://localhost:7357/assets/gerald.js:16367:19
            	at http://localhost:7357/assets/vendor.js:150:34
            	at tryFinally (http://localhost:7357/assets/vendor.js:30:21)
            	at requireModule (http://localhost:7357/assets/vendor.js:148:15)
            	at require (http://localhost:7357/assets/test-loader.js:29:16)
            	at loadModules (http://localhost:7357/assets/test-loader.js:21:25)
            	at load (http://localhost:7357/assets/test-loader.js:40:35)
            	at http://localhost:7357/assets/test-support.js:5578:20: Assertion Failed: A helper named 'form-group' could not be found
```
when adding `component:form-group` to the needs array it throws nearly the same error again only this time with em-form-label (which is used in form-group) 
```
Died on test #2 	at test (http://localhost:7357/assets/test-support.js:1803:15)
            	at http://localhost:7357/assets/gerald.js:16371:19
            	at http://localhost:7357/assets/vendor.js:150:34
            	at tryFinally (http://localhost:7357/assets/vendor.js:30:21)
            	at requireModule (http://localhost:7357/assets/vendor.js:148:15)
            	at require (http://localhost:7357/assets/test-loader.js:29:16)
            	at loadModules (http://localhost:7357/assets/test-loader.js:21:25)
            	at load (http://localhost:7357/assets/test-loader.js:40:35)
            	at http://localhost:7357/assets/test-support.js:5578:20: Assertion Failed: A helper named 'em-form-label' could not be found
```

Is this an error by me?

**Comment by stefanpenner** [comment]
This doesn't appear to be ember cli related. Likely something with the test helped module
