### ISSUE TITLE
Mixins tests aren't isolate

### ISSUE THREAD

**Issue by Fed03** [ember-cli/ember-cli#4071]
Hi all,
I hope this is my fault and not a bug

The problem is that if I run the test suite twice, the first time I've green, the second red and so on in alternation.
When is red, is the second test of the module that fails with an exception that is tested (and threw) in the first one, like it keeps a previous state

Given this test
```js
import Ember from 'ember';
import FilterControllerMixin from 'ocelot-filter-core/mixins/filter-controller-mixin';
import FiltersManager from 'ocelot-filter-core/services/filters-manager';
import { module, test } from 'qunit';
 
module('FilterControllerMixin');
 
test('it throws an error if every entry in the filterable array is not present also in the queryParams',
function(assert) {
  var FilterControllerMixinObject = Ember.Controller.extend(FilterControllerMixin, {
    queryParams: ['foo'],
    filters: {
      filterName: ['foo', 'bar'],
      filter2: ['john']
    }
  });
 
  assert.throws(function() {
    FilterControllerMixinObject.create();
  }, /The following filters are not included into the `queryParams` array: `bar`, `john`/);
});
 
test('Proxies himself to the filter manager',
function(assert) {
  var filtersManager = FiltersManager.create();
  var stub = sinon.stub(filtersManager, 'setContext');
 
  var FilterControllerMixinObject = Ember.Controller.extend(FilterControllerMixin, {
    queryParams: ['foo', 'bar'],
    filters: {
      filterName: ['foo', 'bar']
    },
    _filtersManager: filtersManager
  });
 
  var obj = FilterControllerMixinObject.create();
  assert.ok(stub.calledWithExactly(obj));
});
```
and the mixin code
```js
import Ember from 'ember';

export default Ember.Mixin.create({
  
  filters: {},

  _filtersManager: Ember.inject.service('filters-manager'),

  _qpValidationErrors: Ember.A([]),

  _initMixin: Ember.on('init', function() {
    this._validateQueryParams();
    this.get('_filtersManager').setContext(this);
  }),

  _validateQueryParams() {
    var filtersQP = this._getFiltersQP();
    var qp = this.get('queryParams');

    var validationErrors = this.get('_qpValidationErrors');
    filtersQP.forEach((item) => {
      if(qp.indexOf(item) === -1) {
        validationErrors.push(item);
      }
    });

    if(!Ember.isEmpty(validationErrors)) {
      throw new Error(
        `The following filters are not included into the \`queryParams\` array: ${this._getQPValidationErrors()}`
      );
    }
  },

  _getFiltersQP() {
    var filtersHash = this.get('filters');
    var filtersName = Ember.keys(filtersHash);

    var filtersQP = Ember.A([]);
    filtersName.forEach((filterName) => {
      Array.prototype.push.apply(filtersQP, filtersHash[filterName]);
    });

    return filtersQP;
  },

  _getQPValidationErrors() {
    var errors = this.get('_qpValidationErrors').map((item) => {
      return `\`${item}\``;
    });

    return errors.join(', ');
  }
});
```
ad this is the error
```
FilterControllerMixin: Proxies himself to the filter manager (1, 0, 1)
1.Died on test #1     at http://localhost:4200/assets/dummy.js:377:9
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:40:24): The following filters are not included into the `queryParams` array: `bar`, `john`@ 6 ms
Source: 	
Error: The following filters are not included into the `queryParams` array: `bar`, `john`
    at _validateQueryParams (http://localhost:4200/assets/vendor.js:73800:15)
    at null._initMixin (http://localhost:4200/assets/vendor.js:73784:12)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:22935:25)
    at new Class (http://localhost:4200/assets/vendor.js:42399:14)
    at Function.ClassMixinProps.create (http://localhost:4200/assets/vendor.js:42853:14)
    at Object.<anonymous> (http://localhost:4200/assets/dummy.js:389:43)
    at Object.Test.run (http://localhost:4200/assets/test-support.js:3443:28)
    at http://localhost:4200/assets/test-support.js:3572:11
    at process (http://localhost:4200/assets/test-support.js:3131:24)
    at begin (http://localhost:4200/assets/test-support.js:3176:2)
```

**Comment by stefanpenner** [comment]
`filters: {}`
`_qpValidationErrors: Ember.A([])` should be set in `init` or they are shared between all descendent of the mixin.

**Comment by Fed03** [comment]
@stefanpenner moving the `_qpValidationErrors: Ember.A([])` property declariation into the `init` method resolved the issue.
I knew that the property are shared between the instances that use the same mixin, but I didn't thought about that especially in tests where I was expecting that every test is a separate world....
thank you @stefanpenner , for your help and kindness also on twitter

**Comment by stefanpenner** [comment]
:)
