### ISSUE TITLE
After running ember new with ember-cli 0.2.4, cannot install ember-cli-sass

### ISSUE THREAD

**Issue by KurtRMueller** [ember-cli/ember-cli#4085]
```
ember -v
version: 0.2.4
node: 0.12.2
npm: 2.9.1
```
I'm on OS/X Yosemite.

I upgraded ember-cli to 0.2.4 and ran `ember new` to create  a new project. After creating a new project, I went into the app directory and ran `ember install ember-cli-sass`. When I ran this yesterday with ember-cli 0.2.3, it ran fine.

Here's the stack-trace:

```
ember install ember-cli-sass
version: 0.2.4
Installing packages for tooling via npm...Binary downloaded and installed at /Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-14/binding.node
` /Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/mueller.128/repos/klc/dogfinder-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by coladarci** [comment]
:+1: - same thing I'm seeing when trying to install emblem:
```
ember install ember-cli-emblem
version: 0.2.4
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/gcoladarci/lib/pro-ember-cli-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by coladarci** [comment]
@KurtRMueller  - I did some digging. For me, if I revert the dependency checker back to what it was in the previous release, the world becomes a better place: ` "ember-cli-dependency-checker": "0.0.8",`

**Comment by abuiles** [comment]
Can you please make sure your ember-cli-dependency-checker looks like the following `"ember-cli-dependency-checker": "^1.0.0"` we'll do a second release tomorrow morning fixing this.

**Comment by coladarci** [comment]
That did the trick - thanks @abuiles. 

Totally unrelated, but if you have a second, out of curiosity, how come when I run `ember install ember-cli-emblem` from inside an addon project, it installs it inside `devDependencies` versus `dependencies`? Had a cryptic bug that I just solved by moving it.

**Comment by abuiles** [comment]
This is fixed now, thanks!
