### ISSUE TITLE
ember [generate|delete] component fails

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#4099]
```
$ ember --version
version: 0.2.5
node: 2.0.2
npm: 2.10.0
```

```
$ ember g component application-background
version: 0.2.5
installing
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:467:13)
  at __path__ (/home/jan/code/veltro/veltro/node_modules/ember-cli/blueprints/component/index.js:27:23)
  at /home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:628:66
  at Array.map (native)
  at Class.Blueprint.generateFileMap (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:628:37)
  at Class.Blueprint._locals (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:814:22)
  at Class.Blueprint._process (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:458:22)
  at Class.Blueprint.install (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:491:15)
  at Class.module.exports.Task.extend.run (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
  at Class.module.exports.Command.extend.run (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/commands/generate.js:79:17)
  at Class.<anonymous> (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/command.js:136:17)
  at lib$rsvp$$internal$$tryCatch (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

I looked into this and `options.locals.path` is indeed undefined. `options.locals` looks like this:
`{ importTemplate: '', contents: '', path: undefined }`

I am using the new pod structure. These are my installed addons:

```json
{
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.5",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-autoprefixer": "0.3.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-coffees6": "0.2.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-emblem": "0.2.6",
    "ember-cli-gzip": "1.1.1",
    "ember-cli-html-minifier": "0.1.2",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-i18n": "0.0.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-meta-tags": "0.1.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-sass": "4.0.0",
    "ember-cli-segment": "0.0.5",
    "ember-cli-simple-auth": "0.8.0-beta.2",
    "ember-cli-uglify": "^1.0.1",
    "ember-cli-version-checker": "^1.0.2",
    "ember-component-css": "0.1.1",
    "ember-data": "1.0.0-beta.17",
    "ember-disable-proxy-controllers": "^0.7.0",
    "ember-document-title": "1.1.11",
    "ember-export-application-global": "^1.0.2",
    "ember-feature-flags": "1.0.0",
    "ember-infinity": "0.0.5",
    "ember-moment": "1.1.1",
    "liquid-fire": "0.19.3"
  }
}
```

**Comment by buschtoens** [comment]
I'll test this on a clean slate and ping back.

**Comment by buschtoens** [comment]
So, I've tested this with a fresh new Ember app and the problem persists, kind of.

`ember d component my-component` *always* fails, with the error described above.
`ember g component my-component` seems to work fine though.

Keep in mind, that this *only* happens, when I set `"usePods": true` in `.ember-cli`.

**Comment by buschtoens** [comment]
I've tracked the problem back to `ember-cli/lib/commands/[destroy|generate].js`. The problem lies within the [`run(commandOptions, rawArgs)`](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/destroy.js#L26) method, or more precisely how it is called.

In a *fresh* Ember app running `ember g component my-component` calls run with these `commandOptions`:
```js
{ dryRun: false,
  verbose: false,
  pod: false,
  inRepoAddon: null,
  path: 'components',    // <--- there it is
  checkForUpdates: true,
  disableAnalytics: false,
  usePods: true,
  watcher: 'watchman' }
```

However, running `ember d component my-component` calls run with these `commandOptions`:

```js
{ dryRun: false,
  verbose: false,
  pod: false,
  inRepoAddon: null,
                                      // <--- *poof*
  checkForUpdates: true,
  disableAnalytics: false,
  usePods: true,
  watcher: 'watchman' }
```

**Comment by abuiles** [comment]
@buschtoens this is working fine for me, can you try with `"pod": true` instead of `usePod` in your .ember-cli.  Also could you try with node 0.12.3.

**Comment by buschtoens** [comment]
`"pod": true` still fails. I'll install node and give that a try.

**Comment by abuiles** [comment]
@buschtoens are you using nvm?

**Comment by buschtoens** [comment]
Nope, just switching the PPAs and reinstalling.

**Comment by buschtoens** [comment]
Still the same problem with:
```
$ ember -v
version: 0.2.5
node: 0.12.3
npm: 2.10.0
```

**Comment by abuiles** [comment]
@buschtoens can you paste your .ember-cli?

**Comment by buschtoens** [comment]
```
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": false,
  "pod": true
}
```

**Comment by buschtoens** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by buschtoens** [comment]
Same error on a different remote system:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```

**Comment by trabus** [comment]
I'll look into this shortly. `path` in locals should not be undefined.

**Comment by buschtoens** [comment]
@trabus thank you very much. If you need further information or perhaps SSH access to the remote system in order to reproduce or debug, just let me know.

**Comment by trabus** [comment]
Just verified this locally on a fresh project, not sure how this wasn't caught by the tests. They generate and destroy components in the same way, it should be breaking on destroy as well.

**Comment by buschtoens** [comment]
It *does* break on destory. But it doesn't on generate.
Funny enough, it fails on both in a more complex app with some addons.

**Comment by trabus** [comment]
>It does break on destory. But it doesn't on generate.
Funny enough, it fails on both in a more complex app with some addons.

I'm referring to the internal ember-cli tests.

**Comment by buschtoens** [comment]
Ah okay. Sorry. Btw, going through the travis logs I can see this error multiple times. But I guess you already knew that. :smiley:

**Comment by trabus** [comment]
Figured it out. Destroy doesn't register custom options from the blueprint like generate does. I'll make a PR to fix this later today. I'm also going to investigate how we can make our destroy tests properly fail when an exception like this is thrown.

Thanks for reporting this!

**Comment by buschtoens** [comment]
Thank *you* for fixing this! :beers:

**Comment by trabus** [comment]
> Thank you for fixing this! :beers:

Sorry for breaking it! ;)

**Comment by buschtoens** [comment]
Sorry to bother again, but I'm now working against master and I still get the same problem

```
jan@ubuntu:~/code/citb$ ember g component news-shwowcase
version: 0.2.5-master-6eec996343
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
installing
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at __path__ (/home/jan/code/ember-cli/blueprints/component/index.js:26:23)
    at /home/jan/code/ember-cli/lib/models/blueprint.js:629:66
    at Array.map (native)
    at Class.Blueprint.generateFileMap (/home/jan/code/ember-cli/lib/models/blueprint.js:629:37)
    at Class.Blueprint._locals (/home/jan/code/ember-cli/lib/models/blueprint.js:815:22)
    at Class.Blueprint._process (/home/jan/code/ember-cli/lib/models/blueprint.js:459:22)
    at Class.Blueprint.install (/home/jan/code/ember-cli/lib/models/blueprint.js:492:15)
    at Class.module.exports.Task.extend.run (/home/jan/code/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
    at Class.module.exports.Command.extend.run (/home/jan/code/ember-cli/lib/commands/generate.js:76:17)
jan@ubuntu:~/code/citb$ ember version
version: 0.2.5-master-6eec996343
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 2.1.0
npm: 2.11.0
```

**Comment by buschtoens** [comment]
Doesn't happen in a fresh app. It seems like an addon or a combination of addons causes this error. I'll investigate this and ping back.

**Comment by buschtoens** [comment]
`ember-cli-emblem` causes this error. I'll see if there are more offending addons in my stack.

**Comment by mattbeedle** [comment]
I've been running into the same issue. Caused by ember-cli-coffeescript.

**Comment by buschtoens** [comment]
@mattbeedle The issue should have been resolved by now. Have you updated to the most recent ember-cli version?

**Comment by mattbeedle** [comment]
I'm on the latest version. I can try master.

**Comment by buschtoens** [comment]
Maybe report it here then: https://github.com/ember-cli/ember-cli/issues/4183

**Comment by mattbeedle** [comment]
From the changelog and that PR, it looks like it's been fixed in master. I'll wait for now. Thx
