### ISSUE TITLE
EExist on new laptop

### ISSUE THREAD

**Issue by onlymejosh** [ember-cli/ember-cli#4109]
I'm setting up a new laptop and can't get my application to run, it looks like im having the same issues as #3413 but none of solutions are workings for me.

Node: 0.12.2
Npm: 2.7.5
Ember: 0.2.0-beta.1

```
{
  "name": "matterhorn",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "https://github.com/stefanpenner/ember-cli",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.2.0",
    "broccoli-asset-rev": "2.0.0",
    "broccoli-funnel": "^0.2.3",
    "broccoli-sass": "^0.4.0",
    "connect-restreamer": "^1.0.0",
    "ember-cli": "^0.2.0-beta.1",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-coffeescript": "^0.2.0",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-datepicker": "2.0.1",
    "ember-cli-dependency-checker": "0.0.6",
    "ember-cli-divshot": "^0.1.6",
    "ember-cli-htmlbars": "^0.6.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-cli-simple-auth": "^0.7.1",
    "ember-cli-simple-auth-devise": "^0.7.1",
    "ember-cli-simple-auth-testing": "0.8.0-beta.2",
    "ember-cli-stripe": "^0.2.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-data-route": "0.0.4",
    "ember-export-application-global": "^1.0.2",
    "ember-ion-sound-es6-shim": "0.0.2",
    "ember-localstorage-adapter": "^0.5.0",
    "ember-multiselect-checkboxes": "0.0.5",
    "ember-notify": "^3.1.4",
    "ember-spin-button": "^0.1.2",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "http-proxy": "^1.2.0"
  },
  "dependencies": {
    "rails-csrf": "^0.1.2",
    "rimraf": "2.2.8"
  }
}

```

This is the error from ember serve

```
version: 0.2.0-beta.1
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
EEXIST, file already exists '/Users/josh/matterhorn-ember/frontend/tmp/coffee_script_filter-tmp_dest_dir-971OlGOE.tmp/matterhorn/app.js'
Error: EEXIST, file already exists '/Users/josh/matterhorn-ember/frontend/tmp/coffee_script_filter-tmp_dest_dir-971OlGOE.tmp/matterhorn/app.js'
  at Error (native)
  at Object.fs.symlinkSync (fs.js:848:18)
  at symlink (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/symlink-or-copy/index.js:82:14)
  at symlinkOrCopySync (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/symlink-or-copy/index.js:58:5)
  at /Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/index.js:45:11
  at /Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:11:14
  at lib$rsvp$$internal$$tryCatch (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/josh/matterhorn-ember/frontend/node_modules/ember-cli-coffeescript/node_modules/broccoli-coffee/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by onlymejosh** [comment]
I've managed to solve this.. I'm unsure how at the moment
