### ISSUE TITLE
Ember build environment=production is failing

### ISSUE THREAD

**Issue by clov3rly** [ember-cli/ember-cli#4135]
My repo is [here](https://github.com/clov3rly/JoyFarmTest), and I have a [branch](https://github.com/clov3rly/JoyFarmTest/tree/js-not-em) that is using JS instead of EmberScript, in case that was the problem. Hopefully if you clone the repo, you'll see the same problem I'm experiencing (I'm getting it on OSX and my Ubuntu server).

`ember build` runs just fine, and builds the app successfully.

`ember build --environment=production` (or `ember build --environment="production"`) is failing with the following stack trace:

```
version: 0.2.5
Build failed.
File: ? (3:13)
Unexpected token: punc (.)
Error
    at new JS_Parse_Error (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:688:9)
    at unexpected (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:694:9)
    at semicolon (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:714:43)
    at /Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:848:38
    at /Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:727:24
    at block_ (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1007:20)
    at /Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:980:25
```

I was getting the same stack trace with v0.2.3.

I have no JSHint errors or errors of any kind when running `ember build` on either branch.

I'd love to be able to fix this error, but it isn't pointing me anywhere helpful... (same line/column number on both branches, don't have a `.` at column 13 of line 3 in any of my JS files.

Any ideas?

EDITED to update the repo urls to point to a test repo that doesn't contain 3Gb of images for you to download.

**Comment by stefanpenner** [comment]
the embedded angular app has invalid JavaScript https://github.com/clov3rly/JoyFarmTest/blob/master/app/public/javascripts/application.js#L3-L5

**Comment by clov3rly** [comment]
Ah gee, I forgot that was in there. Did not decide to go with angular :p 

Thanks, pebkac.

**Comment by stefanpenner** [comment]
the error was still terrible, so this will likely help future travelers https://github.com/ef4/broccoli-uglify-sourcemap/pull/4
