### ISSUE TITLE
path is undefined when destroying component with --pod

### ISSUE THREAD

**Issue by typeoneerror** [ember-cli/ember-cli#4169]
REPRO:

    ember new project
    ember generate component my-component --pod
    ember destroy component my-component --pod

RESULT:

    version: 0.2.5
    uninstalling
    Arguments to path.join must be strings
    TypeError: Arguments to path.join must be strings
        at Object.posix.join (path.js:488:13)
        at __path__ (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/blueprints/component/index.js:26:23)
        at /Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/models/blueprint.js:628:66
        at Array.map (native)
        at Class.Blueprint.generateFileMap (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/models/blueprint.js:628:37)
        at Class.Blueprint._locals (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/models/blueprint.js:814:22)
        at Class.Blueprint._process (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/models/blueprint.js:458:22)
        at Class.Blueprint.uninstall (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/models/blueprint.js:522:15)
        at Class.module.exports.Task.extend.run (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
        at Class.module.exports.Command.extend.run (/Users/typeoneerror/Dev/Ember/test/project/node_modules/ember-cli/lib/commands/destroy.js:64:17)

Pretty sure this is related to [this commit here](https://github.com/ember-cli/ember-cli/commit/cf0c29fcb19afb2ef28c2c7b4cbd99328edeb1c0#diff-22511a29d6be2c46005d679096478f8aR27), specifically [this line](https://github.com/ember-cli/ember-cli/commit/cf0c29fcb19afb2ef28c2c7b4cbd99328edeb1c0#diff-22511a29d6be2c46005d679096478f8aR14) because when you run destroy, the `options.path` is "undefined". I'm not sure why the value isn't defaulted to "components" since it is set in the `availableOptions` and is passed through in the generate command.

Simple fix might be [here](https://github.com/ember-cli/ember-cli/commit/cf0c29fcb19afb2ef28c2c7b4cbd99328edeb1c0#diff-e159ff865005bc80b4a53b96a7386514R58):

    path: options.path || 'components'

but I think it'd be better to get the availableOptions.path to be set to components if it isn't set.

Happy to work on a fix if someone can point me in the right direction.

**Comment by stefanpenner** [comment]
cc @trabus

**Comment by trabus** [comment]
Already fixed via #4104

**Comment by stefanpenner** [comment]
@typeoneerror are you able to confirm master solves this?

[steps for using master](https://github.com/ember-cli/ember-cli#development-hints)

**Comment by typeoneerror** [comment]
@stefanpenner @trabus linked and confirmed fixed.

**Comment by stefanpenner** [comment]
woohoo, thanks all :)

**Comment by erichonkanen** [comment]
Im getting this error with ember-cli 1.13.1

**Comment by trabus** [comment]
@erichonkanen are you using any addons that override the default blueprints?

**Comment by stefanpenner** [comment]
> Im getting this error with ember-cli 1.13.1

reproduction + more details if possible please.

**Comment by stefanpenner** [comment]
> Im getting this error with ember-cli 1.13.1
> reproduction + more details if possible please.
