### ISSUE TITLE
Unable to install ember-cli without manually running `npm install`

### ISSUE THREAD

**Issue by mmwtsn** [ember-cli/ember-cli#4186]
After installing ember-cli the `ember` command was throwing an error every time it was run. When installing ember-cli, npm threw a few warnings at the top but appeared to finish successfully. I was able to resolve the issue by manually running `npm install` inside my system's ember-cli installation:

```
$ cd /usr/local/lib/node_modules/ember-cli
$ npm install
```

Any idea why `npm install` needed to be run manually?

**Software Versions**

``` sh
$ node -v
v0.12.2
$ npm -v
2.7.5
```

**Output From npm**

```
$ npm install -g ember-cli
npm WARN installMany bower was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany bower-config was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany broccoli was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany broccoli-clean-css was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany chalk was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany concat-stream was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany configstore was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany diff was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany express was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany findup was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany fs-extra was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany git-repo-info was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany glob was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany inflection was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany inquirer was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany leek was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany lodash was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany minimatch was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany morgan was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany node-uuid was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany nopt was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany npm was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany proxy-middleware was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany quick-temp was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany readline2 was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany resolve was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany through was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
npm WARN installMany tiny-lr was bundled with ember-cli@0.2.5, but bundled package wasn't found in unpacked tree
 
> ws@0.5.0 install /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> ws@0.4.31 install /usr/local/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/usr/local/bin/ember -> /usr/local/lib/node_modules/ember-cli/bin/ember
ember-cli@0.2.5 /usr/local/lib/node_modules/ember-cli
├── broccoli-unwatched-tree@0.1.1
├── escape-string-regexp@1.0.3
├── pleasant-progress@1.1.0
├── is-git-url@0.2.0
├── abbrev@1.0.6
├── ember-cli-copy-dereference@1.0.0
├── proxy-middleware@0.11.0
├── broccoli-writer@0.1.1
├── diff@1.4.0
├── promise-map-series@0.2.1
├── js-string-escape@1.0.0
├── through@2.3.7
├── walk-sync@0.1.3
├── nopt@3.0.2
├── broccoli-merge-trees@0.2.1
├── strip-ansi@2.0.1 (ansi-regex@1.1.1)
├── inflection@1.7.1
├── readline2@0.1.1 (mute-stream@0.0.4)
├── broccoli-sane-watcher@1.1.1 (broccoli-slow-trees@1.1.0)
├── node-uuid@1.4.3
├── exit@0.1.2
├── debug@2.2.0 (ms@0.7.1)
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
├── temp@0.8.1 (rimraf@2.2.8)
├── broccoli-filter@0.1.12 (mkdirp@0.3.5)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── morgan@1.5.3 (basic-auth@1.0.1, depd@1.0.1, on-finished@2.2.1)
├── chalk@1.0.0 (ansi-styles@2.0.1, supports-color@1.3.1, has-ansi@1.0.3)
├── glob@5.0.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2)
├── http-proxy@1.11.1 (eventemitter3@1.1.0, requires-port@0.0.1)
├── rimraf@2.3.2 (glob@4.5.3)
├── fs-extra@0.16.5 (jsonfile@2.0.1, graceful-fs@3.0.7)
├── broccoli-funnel@0.2.2 (mkdirp@0.5.1)
├── git-repo-info@1.1.1
├── resolve@1.1.6
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── broccoli-clean-css@0.2.0 (clean-css@2.2.23)
├── broccoli-kitchen-sink-helpers@0.2.6 (mkdirp@0.3.5, glob@4.0.4)
├── compression@1.4.4 (vary@1.0.0, on-headers@1.0.0, bytes@1.0.0, compressible@2.0.2, accepts@1.2.7)
├── express@4.12.4 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1, range-parser@1.0.2, finalhandler@0.3.6, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, serve-static@1.9.3, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, on-finished@2.2.1, qs@2.4.2, send@0.12.3, proxy-addr@1.0.8, etag@1.6.0, accepts@1.2.7, type-is@1.6.2)
├── quick-temp@0.1.2 (mktemp@0.3.5, rimraf@2.2.8, underscore.string@2.3.3)
├── yam@0.0.18 (lodash.merge@3.3.1)
├── sane@1.1.2 (watch@0.10.0, minimist@1.1.1, exec-sh@0.2.0, fb-watchman@0.0.0, minimatch@0.2.14, walker@1.0.7)
├── tiny-lr@0.1.5 (parseurl@1.3.0, qs@2.2.5, debug@2.0.0, livereload-js@2.2.2, body-parser@1.8.4, faye-websocket@0.7.3)
├── rsvp@3.0.18
├── github@0.2.4 (mime@1.3.4)
├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── markdown-it@4.0.3 (linkify-it@1.0.1, uc.micro@1.0.0, mdurl@1.0.0, entities@1.1.1, argparse@1.0.2)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, user-home@1.1.1, osenv@0.1.1, graceful-fs@3.0.7, uuid@2.0.1, mkdirp@0.5.1, js-yaml@3.3.1)
├── semver@4.3.5
├── ember-router-generator@1.0.0 (recast@0.9.18)
├── broccoli-es3-safe-recast@2.0.0 (es3-safe-recast@2.0.1)
├── lodash@3.9.3
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── broccoli@0.15.4 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, mime@1.3.4, commander@2.8.1, findup-sync@0.2.1, connect@3.3.5, handlebars@3.0.3)
├── broccoli-es6modules@0.6.0 (broccoli-caching-writer@0.5.3, mkdirp@0.5.1, esperanto@0.6.34)
├── core-object@0.0.2 (lodash-node@2.4.1)
├── broccoli-caching-writer@0.5.5 (core-object@0.0.3, lodash-node@2.4.1)
├── broccoli-sourcemap-concat@0.4.4 (broccoli-caching-writer@0.5.3, combined-stream@0.0.7, mkdirp@0.5.1, fast-sourcemap-concat@0.2.5, lodash-node@2.4.1)
├── inquirer@0.5.1 (mute-stream@0.0.4, async@0.8.0, chalk@0.4.0, lodash@2.4.2, cli-color@0.3.3)
├── markdown-it-terminal@0.0.2 (ansi-styles@2.0.1, cli-table@0.3.1, cardinal@0.5.0, lodash-node@3.9.3)
├── leek@0.0.18
├── testem@0.8.3 (growl@1.8.1, styled_string@0.0.1, did_it_work@0.0.6, consolidate@0.12.1, charm@1.0.0, colors@1.1.0, xmldom@0.1.19, commander@2.8.1, async@0.9.2, cross-spawn@0.2.9, mustache@2.0.0, mkdirp@0.5.1, glob@5.0.10, fileset@0.1.5, backbone@1.2.0, js-yaml@3.3.1, fireworm@0.6.6, npmlog@1.2.1, tap@0.7.1, socket.io@1.3.5)
├── bower@1.4.1 (is-root@1.0.0, junk@1.0.1, stringify-object@1.0.1, user-home@1.1.1, chmodr@0.1.0, archy@1.0.0, opn@1.0.2, bower-logger@0.2.2, graceful-fs@3.0.7, bower-endpoint-parser@0.2.2, lru-cache@2.6.4, lockfile@1.0.1, retry@0.6.1, tmp@0.0.24, request-progress@0.3.1, q@1.4.1, fstream-ignore@1.0.2, semver@2.3.2, fstream@1.0.6, p-throttler@0.1.1, which@1.1.1, promptly@0.2.0, shell-quote@1.4.3, glob@4.5.3, mkdirp@0.5.0, bower-json@0.4.0, insight@0.5.3, tar-fs@1.5.1, request@2.53.0, bower-registry-client@0.3.0, decompress-zip@0.1.0, update-notifier@0.3.2, cardinal@0.4.4, mout@0.11.0, bower-config@0.6.1, inquirer@0.8.0, handlebars@2.0.0)
└── npm@2.11.0
```

**Ember Error**

```
$ ember -v
module.js:338
    throw err;
          ^
Error: Cannot find module 'isbinaryfile'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/models/file-info.js:10:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by stefanpenner** [comment]
which version of ember-cli is that?

**Comment by stefanpenner** [comment]
> $ npm -v
> 2.7.5

is abit old, may have some issues. (currently the latest is 2.11.0)

**Comment by stefanpenner** [comment]
ah, i am able to replicate

**Comment by stefanpenner** [comment]
ember-cli 0.2.5 doesn't appear to have that line of code:

https://github.com/ember-cli/ember-cli/blob/v0.2.5/lib/models/file-info.js

**Comment by stefanpenner** [comment]
I have confirmed the released version doesn't have isbinaryfile requirement

```
wget http://registry.npmjs.org/ember-cli/-/ember-cli-0.2.5.tgz
tar --extract package/lib/models/file-info.js --file ember-cli-0.2.5.tgz
tar -O --extract --file=ember-cli-0.2.5.tgz package/lib/models/file-info.js | grep isbinaryfile
```

I suspect you have actually polluted your npm cache/locals with a git checkout

**Comment by mmwtsn** [comment]
Thanks for moving so quickly on this.

It looks like my local version of npm was indeed causing some issues. I deleted and re-installed Node then upgraded npm. Ember installed successfully and now runs happily.
