### ISSUE TITLE
Components in PODS with templates are broken in Ember CLI 0.2.6

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#4205]
Steps to reproduce:

1. ember addon new-addon
2. cd new-addon
3. ember generate component --pod my-component
4. ember s

Get error:

Addon templates were detected, but there are no template compilers registered for `new-addon`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `new-addon`'s `package.json`.

5. Edit package.json, moving "ember-cli-htmlbars" from dev-dependencies to dependencies
6. ember s

Get errors:

```
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: new-addon]
Livereload server on port 35729
Serving on http://localhost:4200/
Cannot read property 'rebuild' of undefined
TypeError: Cannot read property 'rebuild' of undefined
    at Builder.wrapIfNecessary (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:136:18)
    at readAndReturnNodeFor (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:44:17)
    at RSVP.resolve.then.then.finally.readTreeRunning (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24)
    at lib$rsvp$$internal$$tryCatch (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/gmunjal/code/new-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

This breaks addon ember-cli-jquery-ui

**Comment by stefanpenner** [comment]
the deprecation should be fixed by: https://github.com/ember-cli/ember-cli/pull/4206

The rebuild is the result of a undefined tree entering the build process, this will need more investigation (going to the gym shortly, but will look closely today)
