### ISSUE TITLE
DEPRECATION: `lookup` was called on a Registry.

### ISSUE THREAD

**Issue by ReyAyanami** [ember-cli/ember-cli#4216]
DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookupFactory (http://localhost:4200/assets/vendor.js:12183:26)
        at ember$data$lib$initializers$store$$initializeStore (http://localhost:4200/assets/vendor.js:70659:48)
        at Object.ember$data$lib$setup$container$$setupContainer [as initialize] (http://localhost:4200/assets/vendor.js:70969:7)
        at http://localhost:4200/assets/vendor.js:14662:23
        at http://localhost:4200/assets/vendor.js:14685:9
        at visit (http://localhost:4200/assets/vendor.js:12701:7)
        at visit (http://localhost:4200/assets/vendor.js:12699:9)
        at visit (http://localhost:4200/assets/vendor.js:12699:9)
        at DAG.topsort (http://localhost:4200/assets/vendor.js:12813:11)

DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookup (http://localhost:4200/assets/vendor.js:12173:26)
        at ember$data$lib$initializers$store$$initializeStore (http://localhost:4200/assets/vendor.js:70677:28)
        at Object.ember$data$lib$setup$container$$setupContainer [as initialize] (http://localhost:4200/assets/vendor.js:70969:7)
        at http://localhost:4200/assets/vendor.js:14662:23
        at http://localhost:4200/assets/vendor.js:14685:9
        at visit (http://localhost:4200/assets/vendor.js:12701:7)
        at visit (http://localhost:4200/assets/vendor.js:12699:9)
        at visit (http://localhost:4200/assets/vendor.js:12699:9)
        at DAG.topsort (http://localhost:4200/assets/vendor.js:12813:11)

**Comment by twokul** [comment]
@ReyAyanami this is not `ember-cli` issue but Ember Data/Ember related quirk. https://github.com/emberjs/data/pull/3136 and https://github.com/emberjs/data/pull/3070
