### ISSUE TITLE
EPERM, operation not permitted 'dist/'

### ISSUE THREAD

**Issue by shareit** [ember-cli/ember-cli#4230]
my environment (a virtual machine of ubuntu lts 14.04 with VMware Player):
ember-cli 0.2.2
ember 1.9.1
ember data 1.0.0 beta 12
handlebars 2.0

When I am starting the ember server or I'm trying to make the build (ember build), the following error is shown:

Error: EPERM, operation not permitted 'dist/'
  at Error (native)
  at Object.fs.utimesSync (fs.js:1026:11)
  at Function.copyDereferenceSync (/var/www/dev1/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:39:6)
  at /var/www/dev1/node_modules/ember-cli/lib/models/builder.js:76:19
  at lib$rsvp$$internal$$initializePromise (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:537:9)
  at PromiseExt.lib$rsvp$promise$$Promise [as _superConstructor] (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:850:9)
  at new PromiseExt (/var/www/dev1/node_modules/ember-cli/lib/ext/promise.js:32:8)
  at Class.module.exports.Task.extend.copyToOutputPath (/var/www/dev1/node_modules/ember-cli/lib/models/builder.js:71:12)
  at /var/www/dev1/node_modules/ember-cli/lib/models/builder.js:85:21
  at lib$rsvp$$internal$$tryCatch (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/var/www/dev1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)

I do not know if it matters or not but the folder /var/www/dev1/ is shared (using a samba server).

**Comment by shareit** [comment]
It seems that the error was caused by the permissions that were set on that folder. Sources were copied from my local environment ( a windows machine) using the shared folder from the virtual machine, including the dist folder.
The problem was solved after I have deleted the dist/ folder and I recreated it directly from the ubuntu machine. So the issue was related with the permissions on that folder.
