### ISSUE TITLE
ember build fails due to conflicting capitalizations

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4244]
```
ember build
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Build failed.
Merge error: conflicting capitalizations:
pickadate/lib/translations/fa_IR.js in /my-app/tmp/funnel-dest_Appdgl.tmp
pickadate/lib/translations/fa_ir.js in /my-app/tmp/funnel-dest_Appdgl.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
Error: Merge error: conflicting capitalizations:
pickadate/lib/translations/fa_IR.js in /my-app/tmp/funnel-dest_Appdgl.tmp
pickadate/lib/translations/fa_ir.js in /my-app/tmp/funnel-dest_Appdgl.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
    at mergeRelativePath (/my-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:53:21)
    at mergeRelativePath (/my-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
    at mergeRelativePath (/my-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
    at mergeRelativePath (/my-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
    at /my-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
    at lib$rsvp$$internal$$tryCatch (/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

While `pickadate` package is listed in my `bower.json`. I do not import the file `pickadate/lib/translations/fa_IR.js` in my Brocfile.js. 

I'm surprise broccoli is going through this file at all.

**Comment by stefanpenner** [comment]
Can you provide a repo that demonstrates this issue?

**Comment by olivierlesnicki** [comment]
I'll create one ... note that it works fine on Mac/Windows ... but fails when it reaches our CI servers.

**Comment by olivierlesnicki** [comment]
Repository
https://github.com/olivierlesnicki/conflicting-capitalizations-issue

Travis Build
https://travis-ci.org/olivierlesnicki/conflicting-capitalizations-issue/builds/65569309

**Comment by olivierlesnicki** [comment]
@stefanpenner submitted response

**Comment by olivierlesnicki** [comment]
It's probably due to the caching of the bower dependencies folder:
https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L683

**Comment by olivierlesnicki** [comment]
@stefanpenner any updates?

**Comment by dukex** [comment]
Related with https://github.com/amsul/pickadate.js/pull/689 and https://github.com/amsul/pickadate.js/issues/685

**Comment by olivierlesnicki** [comment]
@dukex thanks for the link. 
I still think it's also an ember-cli issue. These files aren't being used in the app and yet are being parsed and validated by the ember build process.

**Comment by dukex** [comment]
@olivierlesnicki I don't know if it's a ember-cli issue, maybe a broccoli-merge-trees issue, but you can see the pull request https://github.com/broccolijs/broccoli-merge-trees/pull/12 where your problem was introduced, I think it's intencional behaviour to protect the users, like the error message said:

> We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux."

**Comment by olivierlesnicki** [comment]
@dukex broccoli-merge-trees is doing the right thing (although I think the warning should be thrown in Windows and Mac instead of Linux).

It's ember-cli that controls which trees are passed to broccoli-merge-trees. As a standalone library broccoli-merge-trees will not parse my bower components if they're not part of my tree.

**Comment by jfelchner** [comment]
@stefanpenner I'm getting this "same" error on a fresh bower install.  I'm adding my package.json and bower.json in hopes it will help repro the issue.  Obviously since `npm` doesn't have a "lock" file I can't guarantee the versions will be the same and therefore can't guarantee that you'll get the same errors I did.

```
Merge error: conflicting capitalizations:
moment/readme.md in /Users/jfelchner/Projects/goodscout/web-client/tmp/funnel-output_path-QGapymck.tmp
moment/README.md in /Users/jfelchner/Projects/goodscout/web-client/tmp/tree_merger-tmp_dest_dir-nskg8jeN.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
```

[package.json](https://gist.github.com/jfelchner/5ebdb98335f24baa669b)
[bower.json](https://gist.github.com/jfelchner/829aaedf20b44ae5af38)

**Comment by mohamnag** [comment]
I have exactly the same problem as the very first reporter. Interestingly enough the problem only happens on the CI machine which is a linux machine. When I build locally on a MAC the problem does not appear.

**Comment by marnen** [comment]
Suddenly having the same problem on Mac OS. (This application built fine before, but I've been messing around with Lockdown and Shrinkwrap in this branch, so I've been reinstalling NPM packages a lot.)

**Comment by marnen** [comment]
I should mention that I'm having it choke on the same files as @jfelchner.

**Comment by olivierlesnicki** [comment]
@stefanpenner any updates?

**Comment by netes** [comment]
+1, problem still exists.

**Comment by stefanpenner** [comment]
> @stefanpenner any updates?

Nope, the provided error message explains the reasoning:

```
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
```

If people wish to remove specific cases, we recommend they funnel them out, or remove them from the build

**Comment by olivierlesnicki** [comment]
@stefanpenner I still think it's an actual issue. These files shouldn't be added in the tree in the first place - I imagine it has performance impact (why include in this funnel the whole bower_components directory) and secondary-effects that the user had no way of anticipating.

**Comment by stefanpenner** [comment]
@olivierlesnicki I think its fine that those files are included, I'm surprised bower_components get merged with anything else in a way that results in this error. I suspect however that is happening that is the error.

If someone could provide such an example, I'll gladly debug it.

**Comment by knownasilya** [comment]
I'm seeing this issue with ember-rollup in an engine.

```
The Broccoli Plugin: [BroccoliMergeTrees: Engine#treeFor (dashboard - vendor)] failed with:
Error: Merge error: conflicting capitalizations:
README.md in /Users/iradchenko/workspace/mapgeo2/map/tmp/broccoli_merge_trees-input_base_path-iJSD6dRt.tmp/1
Readme.md in /Users/iradchenko/workspace/mapgeo2/map/tmp/broccoli_merge_trees-input_base_path-iJSD6dRt.tmp/13
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
    at MergeTrees._mergeRelativePath (/Users/iradchenko/workspace/mapgeo2/map/node_modules/merge-trees/index.js:193:19)
    at MergeTrees.merge (/Users/iradchenko/workspace/mapgeo2/map/node_modules/merge-trees/index.js:53:26)
    at BroccoliMergeTrees.build (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/node_modules/broccoli-merge-t
rees/index.js:34:19)
    at /Users/iradchenko/workspace/mapgeo2/map/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/iradchenko/workspace/mapgeo2/map/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/iradchenko/workspace/mapgeo2/map/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/node_modules/broccoli-merge-tre
es/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/n
ode_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at Class.treeFor (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-engines/lib/engine-addon.js:870:24)
    at project.addons.map.addon (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:547
:22)
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:545:3
2)
    at EmberApp._processedVendorTree (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.j
s:969:24)
    at EmberApp._processedExternalTree (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app
.js:997:25)
    at EmberApp.appAndDependencies (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:
1109:25)
    at EmberApp.javascript (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:1225:30)
    at EmberApp.toArray (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:12)
    at EmberApp.toTree (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/broccoli/ember-app.js:1684:38)
    at module.exports (/Users/iradchenko/workspace/mapgeo2/map/ember-cli-build.js:51:26)
    at Builder.setupBroccoliBuilder (/Users/iradchenko/workspace/mapgeo2/map/node_modules/ember-cli/lib/models/builder.js:56:
19)
```

**Comment by knownasilya** [comment]
In my case, I'm not using any bower components, but am running in an engine with ember-rollup. I only see this issue when using ember-rollup.

**Comment by w96k** [comment]
Same problem here, the capitalized files was placed in /public folder and for some reason some of them (not all) capitalized.

**Comment by akapetzoglou** [comment]
Hello! So I was able to resolve this problem for me. Although it was with another plugin I believe someone will find this helpful so I am going to drop this here.

My error came after I installed a new plug-in, which I later found had a dependency on jquery. The error: 
 
```shell
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeFor (Ember CLI ic-ajax - vendor)] failed with:
Error: Merge error: conflicting capitalizations:
jQuery in /home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/tmp/broccoli_merge_trees-input_base_path-YkHICLZr.tmp
jquery in /home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/tmp/broccoli_merge_trees-input_base_path-YkHICLZr.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
   at BroccoliMergeTrees._mergeRelativePath (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-merge-trees/index.js:224:17)
   at BroccoliMergeTrees.build (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-merge-trees/index.js:83:24)
   at /home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-plugin/read_compat.js:93:34
   at tryCatch (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/rsvp/dist/rsvp.js:525:12)
   at invokeCallback (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/rsvp/dist/rsvp.js:538:13)
   at publish (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/rsvp/dist/rsvp.js:508:7)
   at flush (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/rsvp/dist/rsvp.js:2415:5)
   at _combinedTickCallback (internal/process/next_tick.js:73:7)
   at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
   at BroccoliMergeTrees.Plugin (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-plugin/index.js:7:31)
   at new BroccoliMergeTrees (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-merge-trees/index.js:42:10)
   at BroccoliMergeTrees (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/broccoli-merge-trees/index.js:36:53)
   at mergeTrees (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/models/addon.js:35:14)
   at Class.treeFor (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/models/addon.js:300:10)
   at /home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
   at Array.map (native)
   at EmberApp.addonTreesFor (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
   at EmberApp._processedVendorTree (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/broccoli/ember-app.js:917:29)
   at EmberApp._processedExternalTree (/home/tasosdev/Desktop/Dev/Civocracy/clonedFe2/civf/node_modules/ember-cli/lib/broccoli/ember-app.js:947:21)
```
In my case we found out that there was a forgotten plug-in ( [jquery-color](https://github.com/jquery/jquery-color) ) which had a dependency on jQuery as well, although this one was referring to it as 'jQuery' and not 'jquery'.

I suggest then to take a look at the dependencies loaded during your npm install.  

 1. `rm -rf node_modules/ `
 2. `npm cache clean`
 3. [npm prune](https://docs.npmjs.com/cli/prune)
 3. `bower cache clean `
 5. `npm install && bower install`
 
 Then have a look at the tree structure after installing npm and try to find the plug-in that has the issue (in your case `pickadate`).

 example: 
![bildschirmfoto 2017-12-07 um 16 05 30](https://user-images.githubusercontent.com/13741777/33725389-48ffffbc-db72-11e7-8984-ef472479d6b7.png)

 
So after you have established that it is a specific plug-in that causes the problem, you are not left with too many solutions. Either you support the plug-in and fix the issue either you find a different one that will cover your needs.
