### ISSUE TITLE
Trying to include socket.io-client in Brocfile.js breaks the build

### ISSUE THREAD

**Issue by emilhem** [ember-cli/ember-cli#4259]
**NOTE:** This issue might be for the broccoli project.

Trying to include socket.io-client fails the build.

socket.io is installed with `npm install socket.io`

**NOTE:** using the socket.io-client package results in the same issue.

socket.io-client is included in  `Brocfile.js` using:
```
app.import('node_modules/socket.io/node_modules/socket.io-client/socket.io.js');
```
The error when building is:
```
Path or pattern "node_modules/socket.io/node_modules/socket.io-client/socket.io.js" did not match any files
Error: Path or pattern "node_modules/socket.io/node_modules/socket.io-client/socket.io.js" did not match any files
    at Object.multiGlob (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/hememi/aaron/aaron/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```
Typing `cat node_modules/socket.io/node_modules/socket.io-client/socket.io.js` returns the source for the socket.io-client file.

Versions (using `ember --version`):
```
version: 0.2.7
node: 0.12.4
npm: 2.11.0
```

**Comment by dylanfoster** [comment]
Have you tried installing it with bower?

**Comment by stefanpenner** [comment]
We do not support app.import via this api. Please consider using ember-browserify
