### ISSUE TITLE
[BUG] Build process failing (broccoli-funnel) in ember-cli@master

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/ember-cli#4299]
I've been building a project with the `master` branch for a few days, and the build process now fails intermittently (but always on the same file).

``` bash
EINVAL, invalid argument 'c:\Users\gmurphey\git\ember-project\tmp\babel-tmp_dest_dir-aI0dFHaT.tmp\dummy\ember-project\tests\modules\ember-project\admin\profiles\profile\data-sources\data-source\data-fields\data-field\statistics\index\controller.jshint.js'
Error: EINVAL, invalid argument 'c:\Users\gmurphey\git\ember-project\tmp\babel-tmp_dest_dir-aI0dFHaT.tmp\dummy\ember-project\tests\modules\ember-project\admin\profiles\profile\data-sources\data-source\data-fields\data-field\statistics\index\controller.jshint.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:848:18)
    at symlinkWindows (c:\Users\gmurphey\git\ember-cli\node_modules\symlink-or-copy\index.js:90:16)
    at Function.symlinkOrCopySync (c:\Users\gmurphey\git\ember-cli\node_modules\symlink-or-copy\index.js:56:5)
    at Funnel._copy (c:\Users\gmurphey\git\ember-cli\node_modules\broccoli-funnel\index.js:241:17)
    at Funnel.processFile (c:\Users\gmurphey\git\ember-cli\node_modules\broccoli-funnel\index.js:232:8)
    at Funnel.processFilters (c:\Users\gmurphey\git\ember-cli\node_modules\broccoli-funnel\index.js:151:12)
    at Funnel.handleReadTree (c:\Users\gmurphey\git\ember-cli\node_modules\broccoli-funnel\index.js:129:10)
    at lib$rsvp$$internal$$tryCatch (c:\Users\gmurphey\git\ember-cli\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (c:\Users\gmurphey\git\ember-cli\node_modules\rsvp\dist\rsvp.js:501:17)
```

Because the error's intermittent, I'm led to believe it's an issue with a symlink being made before a dependent file exists. This works consistently with `ember-cli@0.2.7`, though. I've tried to create a test repo to demonstrate this issue without an luck. I haven't been able to test this on a non-Windows machine yet.

**Comment by gmurphey** [comment]
Looking into this further, it may be related to Windows `MAX_PATH` length of 260, in which case I'm not sure much can be done on the ember-cli front.

**Comment by olivierlesnicki** [comment]
@gmurphey that's quite a nested structure you have here!

**Comment by stefanpenner** [comment]
will reopen if this fails with latest + latest broccoli-filter...
