### ISSUE TITLE
Ember serve not running because of missing dependencies

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli#4303]
Travis is failing my tests with the following error message: `Path or pattern "bower_components/jquery-mockjax/dist/jquery.mockjax.js" did not match any files`. It doesn't seem to be related to anything in my app, but rather a problem with the default dependencies. Might this be related to the [mockjax 2 beta](https://github.com/jakerella/jquery-mockjax/releases) release using the wrong name in their `package.json`? Or is there something else going on?

```bash
# Complete error message
Path or pattern "bower_components/jquery-mockjax/dist/jquery.mockjax.js" did not match any files
Error: Path or pattern "bower_components/jquery-mockjax/dist/jquery.mockjax.js" did not match any files
    at Object.multiGlob (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/my_name/Projects/my_project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
```
With these dependencies:

```json
// package.json
{
  "name": "my-project",
  "version": "0.1.0",
  "description": "description",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "autoprefixer-core": "^5.2.0",
    "broccoli-asset-rev": "^2.0.5",
    "broccoli-funnel": "^0.2.3",
    "broccoli-jscs": "0.0.22",
    "broccoli-merge-trees": "^0.2.1",
    "broccoli-static-compiler": "^0.2.1",
    "ember-cli": "^0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-csslint": "^1.0.1",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-dotenv": "0.4.0",
    "ember-cli-flash": "1.1.4",
    "ember-cli-htmlbars": "^0.7.7",
    "ember-cli-i18n": "0.0.6",
    "ember-cli-ic-ajax": "0.1.2",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-postcss": "^1.1.0",
    "ember-cli-qunit": "0.3.14",
    "ember-cli-svgstore": "^0.1.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-data-factory-guy": "^1.0.10",
    "ember-export-application-global": "^1.0.2",
    "ember-json-api": "togglepro/ember-json-api#jsonapi_1_dot_0",
    "express": "^4.12.4",
    "glob": "5.0.10",
    "moment": "2.10.3",
    "phantomjs": "^1.9.17",
    "postcss-calc": "^4.0.1",
    "postcss-color-function": "^1.2.0",
    "postcss-custom-media": "^3.0.0",
    "postcss-custom-properties": "^3.3.0",
    "postcss-discard-comments": "^1.1.2",
    "postcss-discard-empty": "^1.1.0",
    "postcss-import": "^5.2.2"
  },
  "dependencies": {
    "suitcss-base": "0.8.0",
    "suitcss-components-button": "^4.0.0",
    "suitcss-components-grid": "^2.0.2",
    "suitcss-utils": "^0.10.3"
  }
}
```

```json
// bower.json
{
  "name": "my-project",
  "dependencies": {
    "chance": "0.7.5",
    "ember": "1.12.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "0.1.3",
    "ember-data": "1.0.0-beta.18",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.4.0",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^2.1.4",
    "jquery-mockjax": "~1.6.2",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "moment": "2.10.3",
    "qunit": "1.18.0"
  }
}

```

**Comment by ismay** [comment]
Fixed by upgrading two packages in my bower.json:

```json
...
    "ember": "1.13.1",
    "jquery-mockjax": "~2.0.1",
...
```

**Comment by stefanpenner** [comment]
:)
