### ISSUE TITLE
Faker.js missing

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#4314]
Any idea why I am seeing this error message when I run `ember server` ?

```
 ember s
version: 0.2.7
Livereload server on port 35729
Serving on http://localhost:4200/
Path or pattern "bower_components/Faker/build/build/faker.js" did not match any files
Error: Path or pattern "bower_components/Faker/build/build/faker.js" did not match any files
    at Object.multiGlob (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by stefanpenner** [comment]
I suspect that the file in question js missing? Or maybe some case related problem

**Comment by kgish** [comment]
Problem seems to go away if I do the following:
```
ember install ember-faker
```

**Comment by stefanpenner** [comment]
Sounds like somehow you had a missing dep. maybe something wasn't saved correctly

**Comment by kgish** [comment]
Turns out that the root cause had to do with ember-cli-mirage. Problem is corrected by running:
```
ember g ember-cli-mirage
```
The claim is that there's a bug in `ember-cli`.

See: http://www.ember-cli-mirage.com/docs/v0.1.x/installation/
