### ISSUE TITLE
Generating Components throws an error

### ISSUE THREAD

**Issue by quantumlicht** [ember-cli/ember-cli#4353]
I try to run the generator to create a component with : `ember g component my-component`, I get the following error:

TypeError: Cannot read property 'path' of undefined
  at __path__ (/<PROJECT_ROOT>/node_modules/ember-cli/blueprints/component/index.js:26:59)
  at /<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:629:66
  at Array.map (native)
  at Class.Blueprint.generateFileMap (/<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:629:37)
  at Class.Blueprint._locals (/<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:815:22)
  at Class.Blueprint._process (/<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:459:22)
  at Class.Blueprint.install (/<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:492:15)
  at Class.module.exports.Task.extend.run (/<PROJECT_ROOT>/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
  at Class.module.exports.Command.extend.run (/<PROJECT_ROOT>/node_modules/ember-cli/lib/commands/generate.js:76:17)
  at Class.<anonymous> (/<PROJECT_ROOT>/node_modules/ember-cli/lib/models/command.js:136:17)
  at lib$rsvp$$internal$$tryCatch (/<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at /<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
  at lib$rsvp$asap$$flush (/<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:341:15)

Here's an exerpt of my package.json file:
    "ember-cli": "0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-blanket": "0.5.2",
    "ember-cli-coffeescript": "0.10.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.10",
    "ember-cli-uglify": "1.0.1",
    "ember-cli-yuidoc": "0.7.0",
    "ember-data": "1.0.0-beta.18"

I tried looking at the code and it seems like the culprit is in: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L805
It's defined as an empty function, so it always return `undefined`.

Is there some additional information I need to pass to generate a component ?

I am willing to help to provide a fix, but I would probably need some pointers about what's the best place to fix it.

**Comment by stefanpenner** [comment]
can you share a repo that demonstrates this, i (And the test suite) are unable to reproduce.

**Comment by quantumlicht** [comment]
Unfortunately the repo is not hosted in github. Is it sufficient if I only give you access (stefan.penner@gmail.com) or I need to make the repo public?

**Comment by stefanpenner** [comment]
@quantumlicht it a perfect world, I would accept access to your repo. But that likely isn't the best bet, as I suspect our respective employers would disagree with us.

Is it possible for you to provide a reduced example? If not, maybe we can figure something out.

**Comment by quantumlicht** [comment]
Well I can output a tree of the project. That's really only what's relevant anyways. I am the owner of said repo, so that's all right.

**Comment by quantumlicht** [comment]
Here's the output of running `tree ./app` in my repo:

├── app.js
├── components
│   └── modal-picker
│       ├── component.coffee
│       └── template.hbs
├── controllers
├── helpers
│   └── offset-index.coffee
├── index.html
├── initializers
│   ├── api.coffee
│   ├── auth.coffee
│   ├── config.coffee
│   ├── fb-api.coffee
│   ├── google-api.coffee
│   └── utils.coffee
├── locales
│   ├── en.coffee
│   └── fr.coffee
├── mixins
│   └── auth.coffee
├── models
│   ├── action.coffee
│   ├── energy.coffee
│   ├── profile.coffee
│   ├── protein.coffee
│   ├── transport.coffee
│   └── user.coffee
├── pods
│   ├── application
│   │   ├── controller.coffee
│   │   ├── route.coffee
│   │   └── template.hbs
│   ├── callback
│   │   └── route.coffee
│   ├── components
│   │   ├── action-box
│   │   │   ├── component.coffee
│   │   │   └── template.hbs
│   │   ├── action-box-list
│   │   │   ├── component.coffee
│   │   │   └── template.hbs
│   │   ├── fb-login
│   │   │   ├── component.coffee
│   │   │   └── template.hbs
│   │   ├── modal-picker
│   │   │   ├── component.coffee
│   │   │   └── template.hbs
│   │   └── radio-button
│   │       └── component.coffee
│   ├── login
│   │   ├── controller.coffee
│   │   ├── route.coffee
│   │   └── template.hbs
│   ├── profile
│   │   ├── action
│   │   │   ├── route.coffee
│   │   │   └── template.hbs
│   │   ├── controller.coffee
│   │   ├── energy
│   │   │   ├── controller.coffee
│   │   │   ├── route.coffee
│   │   │   ├── source
│   │   │   │   └── controller.coffee
│   │   │   └── template.hbs
│   │   ├── food
│   │   │   ├── controller.coffee
│   │   │   ├── route.coffee
│   │   │   └── template.hbs
│   │   ├── route.coffee
│   │   ├── template.hbs
│   │   ├── transport
│   │   │   ├── controller.coffee
│   │   │   ├── route.coffee
│   │   │   └── template.hbs
│   │   ├── travel
│   │   │   ├── controller.coffee
│   │   │   ├── route.coffee
│   │   │   └── template.hbs
│   │   └── user
│   │       ├── controller.coffee
│   │       ├── route.coffee
│   │       └── template.hbs
│   └── register
│       ├── controller.coffee
│       ├── route.coffee
│       └── template.hbs
├── router.coffee
├── routes
├── styles
│   ├── app.css
│   └── utils.scss
├── templates
│   ├── application.hbs
│   ├── components
│   └── modal-wrapper.hbs
├── transforms
│   ├── array.coffee
│   └── coordinates.coffee
└── views

**Comment by quantumlicht** [comment]
Don't know if it's relevant, but here's my .ember-cli file's content:

{
  "disableAnalytics": false,
  "usePods": true,
  "watcher": "polling",
  "environment": "development"
}

**Comment by stefanpenner** [comment]
maybe a pods bug.

cc @trabus

**Comment by stefanpenner** [comment]
> "environment": "development"

seems redundant?

**Comment by trabus** [comment]
This is a [known issue](https://github.com/ember-cli/ember-cli/issues/4099) in `ember-cli-coffeescript`, try bumping to 0.11.0, I believe it's been fixed there.

**Comment by stefanpenner** [comment]
thanks @trabus

**Comment by quantumlicht** [comment]
If I update to 0.11.0 I get a new error. Should I open an issue with them instead ? 
`ember g component my-component`
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:467:13)
  at __path__ (<PROJECT_ROOT>/node_modules/ember-cli/blueprints/component/index.js:26:23)
  at <PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:629:66
  at Array.map (native)
  at Class.Blueprint.generateFileMap (<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:629:37)
  at Class.Blueprint._locals (<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:815:22)
  at Class.Blueprint._process (<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:459:22)
  at Class.Blueprint.install (<PROJECT_ROOT>/node_modules/ember-cli/lib/models/blueprint.js:492:15)
  at Class.module.exports.Task.extend.run (<PROJECT_ROOT>/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
  at Class.module.exports.Command.extend.run (<PROJECT_ROOT>/node_modules/ember-cli/lib/commands/generate.js:76:17)
  at Class.<anonymous> (<PROJECT_ROOT>/node_modules/ember-cli/lib/models/command.js:136:17)
  at lib$rsvp$$internal$$tryCatch (<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at <PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
  at lib$rsvp$asap$$flush (<PROJECT_ROOT>/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:341:15)

**Comment by afomi** [comment]
perhaps try `ember g component my-component -p`? for the `--pod` option

**Comment by quantumlicht** [comment]
This works, but does not put the component in the correct folder. don't know if I should review my project's folder structure or just wait for a potential fix.

**Comment by afomi** [comment]
ah, okay. fwiw, I'm seeing the error on `ember generate component` too.
Happy to share the repo as well.

**Comment by stefanpenner** [comment]
> Happy to share the repo as well.

please do

**Comment by afomi** [comment]
Hi @stefanpenner, I've added you as a Collaborator.  From `/frontend`, I run the command:

`ember g component something-new`

and get:

```
version: 0.2.7
installing
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
  at __path__ (/Users/ryan/workspace/project/frontend/node_modules/ember-cli/blueprints/component/index.js:26:59)
  at /Users/ryan/workspace/project/frontend/node_modules/ember-cli/lib/models/blueprint.js:629:66
  at Array.map (native)
  at Class.Blueprint.generateFileMap (/Users/ryan/workspace/project/frontend/node_modules/ember-cli/lib/models/blueprint.js:629:37)
  at Class.Blueprint._locals (/Users/ryan/workspace/project/frontend/node_modules/ember-cli/lib/models/blueprint.js:815:22)
```

**Comment by trabus** [comment]
@afomi are you using ember-cli-coffeescript as well?

**Comment by afomi** [comment]
yep - `ember-cli-coffescript ~0.4.0`

**Comment by stefanpenner** [comment]
> yep - `ember-cli-coffescript ~0.4.0`

i suspect this is a CS bug
