### ISSUE TITLE
coffeescript inclusion fails with broccoli-sourcemap-concat

### ISSUE THREAD

**Issue by basz** [ember-cli/ember-cli#4369]
Hi,

I think I found an issue in the 'broccoli-sourcemap-concat' module (looking at the error). But since I have no idea how to confirm that I present it here...

- create new project
- bower install nanoscroller

add to broccoli
```
app.import(app.bowerDirectory + '/nanoscroller/bin/javascripts/jquery.nanoscroller.js');
```

run `ember serve`

```
ENOENT, no such file or directory '...../my-app/tmp/tree_merger-tmp_dest_dir-CPrXEtjY.tmp/bower_components/nanoscroller/bin/javascripts/jquery.nanoscroller.coffee'
Error: ENOENT, no such file or directory '...../my-app/tmp/tree_merger-tmp_dest_dir-CPrXEtjY.tmp/bower_components/nanoscroller/bin/javascripts/jquery.nanoscroller.coffee'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at SourceMap.<anonymous> (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:268:17)
    at Array.map (native)
    at SourceMap._resolveSourcesContent (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:261:27)
    at SourceMap._assimilateExistingMap (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:240:63)
    at SourceMap.<anonymous> (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:211:12)
    at SourceMap._cacheEncoderResults (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:119:16)
    at SourceMap._addMap (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:210:10)
    at SourceMap.addFileSource (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:91:19)
    at SourceMap.addFile (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:15)
    at Class.<anonymous> (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
    at Array.forEach (native)
    at Class.module.exports.CachingWriter.extend.addFiles (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:78:8)
    at Class.module.exports.CachingWriter.extend.updateCache (...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at ...../my-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (...../my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (...../my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (...../my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (...../my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

```
now looking at `/nanoscroller/bin/javascripts/jquery.nanoscroller.js.map` i do find a reference to the coffeescript file.
```
{
  "version": 3,
  "file": "jquery.nanoscroller.js",
  "sourceRoot": "../../coffeescripts/",
  "sources": [
    "jquery.nanoscroller.coffee"
  ],
  "names": [],
  "mappings": "...."
}
```

I've tried to update (editing the package.json and running npm install - dunno if that is even possible) to the 1.0.0 release of broccoli-sourcemap-concat but that did not help, but the error stays the same.

**Comment by basz** [comment]
I have confirmed that changing the map resolves this, so definitely something in way the map is resolved.
```
  "sourceRoot": "",
  "sources": [
    "../../coffeescripts/jquery.nanoscroller.coffee"
  ],
```

**Comment by stefanpenner** [comment]
maybe a bug with the coffeescript tooling?  Can you try without?

An isolated repo that demonstrates this issue would aide in debugging

**Comment by basz** [comment]
I don't know how to do this without coffeescript tooling...

demo repo https://github.com/basz/ember-test-app

**Comment by stefanpenner** [comment]
this is an issue with nanoscroller, it must truthfully inform us where its sourcemap sources are. It currently does not.

I dont believe this is something we can fix on our end, as there does not appear to be any resolvable logic between specified sourceFile location and its actual location.

Im going to close this, and recommend the issue be taken up with the input library.

**Comment by turboMaCk** [comment]
@stefanpenner I do not think so. I looks like broccoli-sourcemap-concat ignores `sourceRoot` attribute.

```
  "sourceRoot": "../../coffeescripts/", <- ignored
  "sources": [
    "jquery.nanoscroller.coffee" <- looking for "./jquery.nanoscroller.coffee" instead of "../../jquery.nanoscroller.coffee"
  ],

```
