### ISSUE TITLE
Fails to run after installing ember-cli on OSX

### ISSUE THREAD

**Issue by kenkendk** [ember-cli/ember-cli#4379]
After running `sudo npm install -g ember-cli` I get this error when I try to run `ember new myapp`:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash-node/modern/objects/assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/core-object/core-object.js:4:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

If was able to "fix" it by editing `node_modules/core-object/core-object.js` and changing line `3` from:
```javascript
var assign = require('lodash-node/modern/objects/assign');
```

to

```javascript
var assign = require('lodash/object/assign');
```

Install info (after fixing):
```
version: 0.2.7
node: 0.12.6
npm: 2.11.0
```

**Comment by stefanpenner** [comment]
it appears your node_modules are not correctly installed, as core_object, does have a dependency on https://github.com/ember-cli/core-object/blob/0.4.x/package.json#L23

**Comment by kenkendk** [comment]
Yes, that seems right. Here is my package.json from the core-object folder:
```json
{
  "name": "core-object",
  "version": "0.0.2",
  "description": "A lightweight implementation of OOP Class in JavaScript",
  "main": "core-object.js",
  "scripts": {
    "test": "mocha tests/**/*-test.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/stefanpenner/core_object.git"
  },
  "author": {
    "name": "Ember core team and ember cli contributors"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/stefanpenner/core_object/issues"
  },
  "homepage": "https://github.com/stefanpenner/core_object",
  "devDependencies": {
    "mocha": "^1.21.4"
  },
  "dependencies": {
    "lodash-node": "^2.4.1"
  },
  "readme": "### CoreObject\n\nA lightweight implementation of OOP Class in JavaScript. It is currently used in\n[ember-cli](https://github.com/stefanpenner/ember-cli).\n",
  "readmeFilename": "README.md",
  "_id": "core-object@0.0.2",
  "dist": {
    "shasum": "0b9fdae4c399ab59ffe26ac3c586d29ccbee22a2"
  },
  "_from": "core-object@0.0.2",
  "_resolved": "https://registry.npmjs.org/core-object/-/core-object-0.0.2.tgz"
}
```

And as you stated, there is a dependency on loadash-node. The lodash-node subfolder also has the needed file:
```
ls  /usr/local/lib/node_modules/ember-cli/node_modules/core-object/node_modules/lodash-node/modern/object
assign.js
create.js
defaults.js
defaultsDeep.js
extend.js
findKey.js
findLastKey.js
forIn.js
forInRight.js
forOwn.js
forOwnRight.js
functions.js
get.js
has.js
invert.js
keys.js
keysIn.js
mapKeys.js
mapValues.js
merge.js
methods.js
omit.js
pairs.js
pick.js
result.js
set.js
transform.js
values.js
valuesIn.js
```

I am not familiar with the node resolve process, but it appears that the lodash-node module is not loaded from the core-object folder, even though it is present.

**Comment by stefanpenner** [comment]
Please do a nom as described above and report back. This just looks like a bug in npm during install

**Comment by kenkendk** [comment]
That works, which is strange considering that I uninstalled, cleared cache and re-installed with the same result.

**Comment by stefanpenner** [comment]
> That works, which is strange considering that I uninstalled, cleared cache and re-installed with the same result.

NPM has issues...

**Comment by trong291990** [comment]
So what's sulution pls ?
