### ISSUE TITLE
Cannot set property 'ember-cli' of undefined

### ISSUE THREAD

**Issue by halogenandtoast** [ember-cli/ember-cli#4407]
Whenever I run any ember command I see the following

    A new version of ember-cli is available (1.13.0). To install it, type ember update.

When I try to run `ember update` I get this error:

```
Updating ember-cli...
There was an error – possibly a permissions issue. You may need to manually run npm install -g ember-cli.
Cannot set property 'ember-cli' of undefined
TypeError: Cannot set property 'ember-cli' of undefined
    at Class.<anonymous> (/usr/local/share/npm/lib/node_modules/ember-cli/lib/tasks/update.js:71:40)
    at lib$rsvp$$internal$$tryCatch (/usr/local/share/npm/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/usr/local/share/npm/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/usr/local/share/npm/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/usr/local/share/npm/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

Stats:

```
 ember -v
version: 0.2.7

A new version of ember-cli is available (1.13.0). To install it, type ember update.
node: 0.12.6
npm: 2.11.0
```

On OSX 10.10.2, node installed via homebrew

**Comment by stefanpenner** [comment]
Sorry that message is wrong. Please upgrade via the website or release notes upgrade instructions.

**Comment by halogenandtoast** [comment]
The Cannot set property error message is from the fact that I was running ember update outside of ember app, but it seems like the global ember bin always thinks there is a new version, but running the project commands I don't see that error message anymore. So basically I just see it when I run `ember new myapp` and before I run the commands in the release notes.

**Comment by stefanpenner** [comment]
> ember update

it no more

> So basically I just see it when I run ember new myapp and before I run the commands in the release notes.

```
npm uninstall -g ember-cli

npm cache clear
npm install -g ember-cli
```

**Comment by halogenandtoast** [comment]
I felt like I tried that and it didn't work, but now it seems to no longer be a problem. Closing.
