### ISSUE TITLE
Brocfile.js -> ember-cli-build.js transition improvements

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#4410]
I had to remove `Brocfile.js` and put that content into `ember-cli-build.js` Also, need to use the `defaults` when I created the `new EmberApp(defaults, {`

```
ultimatemonty [10:52 AM] 
any reason I’m getting `TypeError: object is not a function` after updating to ember-cli 1.13.1?
ultimatemonty 
[10:53 AM] 
Added Full Trace in #ember-cli  
TypeError: object is not a function
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/lib/models/builder.js:30:19)
    at Class.module.exports.Task.extend.init (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/lib/models/builder.js:48:10)
    at new Class (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Class.module.exports.Command.extend.run (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/lib/commands/build.js:25:22)
    at Class.<anonymous> (/Users/cmcculler/Projects/Pardot/pardot/web/assets/nurtureStudio/node_modules/ember-cli/lib/models/command.js:136:17)
+ 4 more lines...
2KB JavaScript/JSON • New window • View raw • Add comment

ultimatemonty [10:55 AM] 
upgrading from 0.2.7

pixelhandler [11:02 AM] 
@ultimatemonty I think you need to use the new build file instead of Brocfile.js see my upgrade from 0.2.7 to 1.13.1 here https://github.com/pixelhandler/blog/pull/14/files (edited)

pixelhandler [11:02 AM]
I had to remove Brocfile.js and put that content into ember-cli-build.js

ultimatemonty [11:05 AM] 
I did

ultimatemonty [11:05 AM]
*I’m pretty sure I did

ultimatemonty [11:06 AM]
yep I did

ultimatemonty [11:08 AM]
might be my environment checking

pixelhandler [11:08 AM] 
For me it wasn’t a straight copy paste I had to use the format in the new file. well that was by best guess.
ultimatemonty 
[11:08 AM] 
Added Untitled in #ember-cli  
var EmberApp = require('ember-cli/lib/broccoli/ember-app'),
	isProduction = ( process.env.EMBER_ENV || 'development' ) === 'production';
137b JavaScript/JSON • New window • View raw • Add comment

pixelhandler [11:09 AM] 
I did recall seeing something like that error until I put the contents of my Brocfile inside the exported function in the new build.js file https://github.com/pixelhandler/blog/pull/14/files#diff-2fe2a7faee7de1e0d5d82e032498d84c

locks [11:09 AM] 
why don't you ignore tmp altogether

locks [11:09 AM]
oops

ultimatemonty [11:09 AM] 
yeah that’s what I’m doing now

ultimatemonty [11:09 AM]
re: module,exports

pixelhandler [11:12 AM] 
had to use the `defaults` when I created the `new EmberApp(defaults, {`

pixelhandler [11:13 AM]
my old build didn’t have that https://github.com/pixelhandler/blog/blob/c7addef405050856a9fcab702218daf245f85ebb/Brocfile.js#L8 vs https://github.com/pixelhandler/blog/blob/dba4ec45140cffaa35a3ad8cae943191592edfbb/ember-cli-build.js#L7 (edited)

ultimatemonty [11:14 AM] 
@pixelhandler: that did the trick thanks!

pixelhandler [11:15 AM] 
Prolly need to tell @rwjblue about adding this to the release notes it’s a gotcha

ultimatemonty [11:15 AM] 
agreed
```

**Comment by stefanpenner** [comment]
this does seem non-obvious for migrations. Do you have any suggestions on what to say/document etc. ?

**Comment by pixelhandler** [comment]
@stefanpenner 2 points: 

* Remove Brocfile.js and put that content into ember-cli-build.js 
* Be sure to need to use the `defaults` when creating the `new EmberApp(defaults, {`

**Comment by stefanpenner** [comment]
@pixelhandler where would be best to document this?

Maybe, a link to the site?

**Comment by pixelhandler** [comment]
@stefanpenner here on the release notes: https://github.com/ember-cli/ember-cli/releases/tag/v1.13.1 under "The following changes are required if you are upgrading from the previous
version:"

**Comment by pixelhandler** [comment]
Well I do see it here https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md listed under 1.13.0 but I think many people will skip that and go from 0.2.7 to 1.13.1 Well is was easy to miss. perhaps some duplication in the 1.13.1 release notes for the link to TRANSITION.md would help.

**Comment by stefanpenner** [comment]
- [ ] Ideally, it would be nice to have a deprecation or warning thrown on bootup that detects the presence of both files and makes reference to the transition guide. (source: https://github.com/ember-cli/ember-cli/issues/4412)

**Comment by kellyselden** [comment]
Something like this may of use to you folks https://github.com/kellyselden/ember-cli-output/compare/v0.2.7...master
Unfortunately it would get stale pretty quick after the next feature release.

**Comment by stefanpenner** [comment]
maybe for rapid releases, we display the individual one, and then one with changes rolled up?

**Comment by gmurphey** [comment]
The first point in @stefanpenner's task list may be ticked off by #4454 now that it's merged?
