### ISSUE TITLE
New component generates failing integration test in CLI 1.13.1

### ISSUE THREAD

**Issue by adam-knights** [ember-cli/ember-cli#4422]
I create a component

    ember generate component some-comp

And then browse to http://localhost:4200/tests, the new test 'Integration | Component | some comp: it renders (1, 1, 2)' fails by default.

Firstly is it a bug and second how do I fix this? Full error details below:

1. failed@ 68 ms
Expected: 	
""
Result: 	
"
"
Diff: 	
"" "
" 
Source: 	
    at Object.<anonymous> (http://localhost:4200/assets/orders-app.js:7439:12)
    at Object.wrapper (http://localhost:4200/assets/test-support.js:1790:29)
    at Object.Test.run (http://localhost:4200/assets/test-support.js:3471:28)
    at http://localhost:4200/assets/test-support.js:3600:11
    at process (http://localhost:4200/assets/test-support.js:3159:24)
    at begin (http://localhost:4200/assets/test-support.js:3204:2)

Chrome/Win7 as fyi

**Comment by stefanpenner** [comment]
should be fixed as of: https://github.com/ember-cli/ember-cli/commit/b8d0f324eae54c70be13857577285bde4cc5eb0c

will be part of the next release

**Comment by adam-knights** [comment]
Yes makes sense, added the .trim() to the first assert and the test passes
