### ISSUE TITLE
Cannot read property of 'Undefined' 

### ISSUE THREAD

**Issue by marcrd** [ember-cli/ember-cli#4424]
Getting an error after NPM install Ember-CLI. I'm on OS X Yosemite and have the latest version on Node (12.7). 

Here is the log: 

Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at Addon.Class (/Users/marcrd/node_modules/core-object/core-object.js:32:37)
    at /Users/marcrd/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/marcrd/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at visit (/Users/marcrd/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at visit (/Users/marcrd/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at visit (/Users/marcrd/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at DAG.topsort (/Users/marcrd/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/marcrd/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/Users/marcrd/node_modules/ember-cli/lib/models/project.js:336:36)
    at Project.eachAddonCommand (/Users/marcrd/node_modules/ember-cli/lib/models/project.js:387:10)

Tell me if you need any other logs.

**Comment by stefanpenner** [comment]
A running reproduction of this would be great. Otherwise is isn't terribly actionable. So link such a gh repo if you can

**Comment by stefanpenner** [comment]
I suspect some add-on is broken, unfortunately without a reproduction we can't really do much.

Will gladly reopen if such a reproduction can be provided.

**Comment by marcrd** [comment]
The issue isn't on a specific repo, ember-cli won't work at all system wide on install. How can I replicate that?

**Comment by stefanpenner** [comment]
try removing `/Users/marcrd/node_modules/` upgrading npm to the latest, and reinstalling ember-cli.
