### ISSUE TITLE
Cannot find module './key-for-file'

### ISSUE THREAD

**Issue by al3x-edge** [ember-cli/ember-cli#4547]
Noticed this error a bit ago. Had to rebuild a project a bit ago, and thought maybe I had an old dependency still lying around somewhere (still trying to get everything migrated from 1.12 to 1.13) and was bouncing between branches.  Saw ember-cli had updated. Updated. Same error.

Cannot find module './key-for-file'

```
version: 1.13.5
Cannot find module './key-for-file'
Error: Cannot find module './key-for-file'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alexa/code/ember/fti-pump-selector/ember/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/filter.js:14:18)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
```

**Comment by al3x-edge** [comment]
Nevermind. After some more digging -- https://github.com/caitp/cauliflower-filter/pull/17

**Comment by rwjblue** [comment]
Thanks for raising the issue here, looks like @mmun and @stefanpenner are already on the case and have submitted and merged https://github.com/caitp/cauliflower-filter/pull/17 to fix the underlying issue.

We need a release of cauliflower-filter before its all fixed though.

**Comment by rwjblue** [comment]
Reopening as a tracking issue until this is fixed upstream.

**Comment by al3x-edge** [comment]
Thanks @rwjblue =]

**Comment by stefanpenner** [comment]
waiting on the maintainer of cauliflower-filter to release, if it doesn't happen in the next little bit i'll fork and re-release under a different package and release an update broccoli-babel-transpiler.

**Comment by stefanpenner** [comment]
temp fix, locked broccoli-babel-transpiler to a slightly older version and republished:

```
➜  broccoli-babel-transpiler git:(master) npm publish
+ broccoli-babel-transpiler@5.4.2
```

the following steps should resolve the issue
```
rm -rf node_modules/ember-cli-babel
npm cache clear
npm install
```

**Comment by diogomafra** [comment]
Thank you @stefanpenner, this resolved the problem.
