### ISSUE TITLE
Can't install 1.13.7 Cannot find module 'isbinaryfile'

### ISSUE THREAD

**Issue by givanse** [ember-cli/ember-cli#4614]
`1.13.6` works just fine in my system:

```bash
npm install -g ember-cli@'1.13.6'
ember -v
version: 1.13.6
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.2
npm: 2.13.2
os: linux x64
```

Not specifying a version and defaulting to the latest causes the failure:

```bash
npm uninstall -g ember-cli
npm install -g ember-cli
ember -v
module.js:338
    throw err;
          ^
Error: Cannot find module 'isbinaryfile'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ivan/.nvm/versions/node/v0.12.2/lib/node_modules/ember-cli/lib/models/file-info.js:10:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by stefanpenner** [comment]
Looks like your local install is broken. Be sure to clear your npm cache and reinstall

**Comment by givanse** [comment]
Right, sorry, several `npm cache clear`s after and it worked.
