### ISSUE TITLE
Error: ENOTEMPTY - 1.13.8

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#4657]
After updating from 1.13.6 to version 1.13.8 I started to get errors like these:

```
Error: ENOTEMPTY: directory not empty, rmdir 'D:\Ember\tmp\funnel-input_base_path-6DyQQ2rH.tmp\0'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:763:18)
    at rmkidsSync (D:\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (D:\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync (D:\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\rimraf\rimraf.js:293:9)
    at D:\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\node_modules\broccoli-plugin\read_compat.js:57:16
    at lib$rsvp$$internal$$tryCatch (D:\Ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (D:\Ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (D:\Ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

```
ember -v
version: 1.13.8
node: 2.5.0
npm: 2.13.4
```

I'm on Windows 10.

**Comment by stefanpenner** [comment]
@btecu that happens when something else is watching `tmp`

* an editor
* window search indexer
* etc

running ember-cli-windows helps mitigate some of these issues.

cc @fel

**Comment by btecu** [comment]
That seems to be the issue. I've forgot I had open the entire folder in the editor instead of just app.

**Comment by stefanpenner** [comment]
Soon the tmp dir will reside in the system tmp which should mitigate this
