### ISSUE TITLE
build cycling issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4674]
source: https://twitter.com/brittanystoroz/status/631856813764411393

addon: https://github.com/mozilla/ember-cli-fxos.git

- [ ] pending reproduction

**Comment by stefanpenner** [comment]
tests in ember-cli-fxos seem to be failing, may or may not be related though:

```js
A new version of ember-cli is available (1.13.8). To install it, type ember update.
Build failed.
ENOENT: no such file or directory, lstat '/Users/stefanpenner/tmp/ember-cli-fxos/tmp/funnel-input_base_path-d0hGrrH4.tmp/0/public/manifest.webapp'
Error: ENOENT: no such file or directory, lstat '/Users/stefanpenner/tmp/ember-cli-fxos/tmp/funnel-input_base_path-d0hGrrH4.tmp/0/public/manifest.webapp'
  at Error (native)
  at Object.fs.lstatSync (fs.js:841:18)
  at symlink (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:63:26)
  at Function.symlinkOrCopySync (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:58:5)
  at Funnel._copy (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/index.js:252:17)
  at Funnel.processFile (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/index.js:243:8)
  at Funnel.processFilters (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/index.js:154:12)
  at Funnel.build (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/index.js:118:10)
  at /Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:61:34
  at lib$rsvp$$internal$$tryCatch (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/
rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp
/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/r
svp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/stefanpenner/tmp/ember-cli-fxos/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:
1198:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

**Comment by brittanystoroz** [comment]
Problem should be reproducible by running the ember-cli-conversion branch of this app locally: https://github.com/mozilla/high-fidelity/tree/ember-cli-conversion

**Comment by stefanpenner** [comment]
was able to replicate, as suspected it appears `dist` is part of the input to the build. Since it is also the output, a cycle was created.

Now to figure out why.

**Comment by stefanpenner** [comment]
it appears to be related to:
    "ember-cli-fxos": "0.1.3",

**Comment by stefanpenner** [comment]
@brittanystoroz it appears ember-cli-fxos is watching the root dir [here](https://github.com/mozilla/ember-cli-fxos/blob/master/lib/tasks/sync-manifest.js#L29)

**Comment by brittanystoroz** [comment]
@stefanpenner  -_-

**Comment by stefanpenner** [comment]
I suspect I can hard-code filtering explicitly for `dist` to prevent this exact issue, unfortunately there are still some downsides for now.

On a positive note, when all of https://github.com/ember-cli/ember-cli/issues/4562 lands, we will be able to remove one of the largest watched trees: `tmp`. Which will open some options for us, especially users of watchman.

**Comment by brittanystoroz** [comment]
@stefanpenner thanks friend.

**Comment by stefanpenner** [comment]
@brittanystoroz NP. This is a crappy limitation today, I hope given the above mentioned work, and the future of watchman on windows. We will remove this limitation.

In the interim, I believe this issue has 1 action item for today:

- [ ] detect watching root / dist / tmp 
  - [ ] inform the user via error / warn
  - [ ] never ever ever allow these to be watched.
