### ISSUE TITLE
Access rights error when generating new app

### ISSUE THREAD

**Issue by mimiflynn** [ember-cli/ember-cli#4704]
Steps to reproduce:
- `npm install -g ember-cli`
- `ember new ember-test`

Full output:
```
[Mon Aug 17 02:48 PM] $ ember new ember-test
version: 1.13.8
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Failed to execute "git ls-remote --tags --heads git://github.com/ember-cli/ember-load-initializers.git", exit code of #128
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error: Failed to execute "git ls-remote --tags --heads git://github.com/ember-cli/ember-load-initializers.git", exit code of #128
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at createError (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/util/cmd.js:102:21)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

Mac OS 10.10.5
Node 0.12.7
Ember-cli 1.13.8

**Comment by gdub22** [comment]
I noticed this yesterday, late afternoon EST.  Github had a [partial outage](https://status.github.com/messages) and that particular repo (https://github.com/ember-cli/ember-load-initializers) was affected by the outage.  It should work now.

**Comment by stefanpenner** [comment]
Yes, unfortunately this issue appears related to the recent GH outages.

Long term, we plan to move all our core deps to `npm` which may or may not improve this particular situation.

**Comment by mimiflynn** [comment]
Sorry for the delay, finally got around to trying again and it worked.

Thanks for the explanation. Looking forward to experimenting with Ember.

**Comment by stefanpenner** [comment]
@mimiflynn happy adventures!
