### ISSUE TITLE
Cannot generate new project with Ember CLI 1.13.8

### ISSUE THREAD

**Issue by SimonKaluza** [ember-cli/ember-cli#4760]
I'm seeing a funny error running Ember CLI's `new` command with v1.13.8
```
npm ERR! git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 broccoli-peristent-filter: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 broccoli-peristent-filter: 'git <command> [<revision>...] -- [<file>...]'
```

which then seems to fail to install necessary dependencies and prevent subsequent attempts to run `npm install` in the project.  At that point running npm install results in errors similar to those described in https://github.com/babel/ember-cli-babel/issues/53.

Removing the caret on version of ember-cli-babel lets me rerun `npm install` in the fresh project...  Is this just a problem in the flexible versioning of ember-cli-babel in the default package.json file?

Detailed output:

```
$ ember new hello-ember-cli-1-13-8
version: 1.13.8
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installing packages for tooling via npm...
npm ERR! git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 broccoli-peristent-filter: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 broccoli-peristent-filter: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 broccoli-peristent-filter: 
npm ERR! git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 broccoli-peristent-filter: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 broccoli-peristent-filter: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 broccoli-peristent-filter: 
npm ERR! git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 broccoli-peristent-filter: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 broccoli-peristent-filter: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 broccoli-peristent-filter: 
Command failed: git rev-list -n1 broccoli-peristent-filter
fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Error: Command failed: git rev-list -n1 broccoli-peristent-filter
fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by rwjblue** [comment]
Fixed by https://github.com/babel/ember-cli-babel/pull/56 and released as 5.1.5.
