### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by RuslanZavacky** [ember-cli/ember-cli#4804]
Kinda unexpected error.

```javascript
Uploading `tmp/deploy-dist/index.html`...

Cannot read property 'slice' of null
TypeError: Cannot read property 'slice' of null
    at Class.module.exports.CoreObject.extend._generateKey (/opt/www/vetoza/ui/node_modules/ember-cli-deploy/lib/utilities/tagging/sha.js:14:49)
    at Class.module.exports.CoreObject.extend.createTag (/opt/www/vetoza/ui/node_modules/ember-cli-deploy/lib/utilities/tagging/sha.js:10:17)
    at CoreObject.module.exports.CoreObject.extend.upload (/opt/www/vetoza/ui/node_modules/ember-deploy-redis/lib/redis.js:25:35)
    at /opt/www/vetoza/ui/node_modules/ember-cli-deploy/lib/tasks/deploy-index.js:53:25
    at lib$rsvp$$internal$$tryCatch (/opt/www/vetoza/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/opt/www/vetoza/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/opt/www/vetoza/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/opt/www/vetoza/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickDomainCallback (node.js:381:11)
```

`ember -v` produces
```
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.7
npm: 2.13.4
os: linux x64
```

**Comment by RuslanZavacky** [comment]
Seems like my fault, `npm install` quietly failed and skipped some dependencies.
