### ISSUE TITLE
brittle CI test

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4847]
```js
  1) Acceptance: addon-smoke-test npm pack does not include unnecessary files:
     AssertionError: expected packaged addon to not contain file or folder 'ember-cli-build.js': expected 'package/package.json\npackage/README.md\npackage/ember-cli-build.js\npackage/index.js\npackage/config/ember-try.js\npackage/config/environment.js\npackage/.watchmanconfig\npackage/LICENSE.md\npackage/.jshintrc\n' not to match /ember-cli-build.js/
      at tests/acceptance/addon-smoke-test-slow.js:189:33
      at Array.forEach (native)
      at tests/acceptance/addon-smoke-test-slow.js:188:53
      at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:505:17)
      at lib$rsvp$$internal$$publish (node_modules/rsvp/dist/rsvp.js:476:11)
      at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198
```

This one fails randomly, we should investigate. (I plan to this afternoon)

**Comment by kellyselden** [comment]
I've seen it either more likely, or exclusively fail on iojs.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/commit/7bef5d9ad00059fb0468b294f4802d99c23e68d4
