### ISSUE TITLE
Error: ConcatWithMaps: nothing matched when running ember server

### ISSUE THREAD

**Issue by codedbypaul** [ember-cli/ember-cli#4950]
I'm having an issue running ember server after a clean Ember install.

Here's the output:

```
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ConcatWithMaps: nothing matched [vendor/ember-cli/vendor-prefix.js,bower_components/loader.js/loader.js,bower_components/jquery/dist/jquery.js,bower_components/ember/ember.debug.js,bower_components/ember-cli-shims/app-shims.js,bower_components/ember-resolver/dist/modules/ember-resolver.js,bower_components/ember-load-initializers/ember-load-initializers.js,vendor/ic-ajax/dist/named-amd/main.js,bower_components/ember-data/ember-data.js,vendor/addons.js,vendor/ember-cli/vendor-suffix.js]
Error: ConcatWithMaps: nothing matched [vendor/ember-cli/vendor-prefix.js,bower_components/loader.js/loader.js,bower_components/jquery/dist/jquery.js,bower_components/ember/ember.debug.js,bower_components/ember-cli-shims/app-shims.js,bower_components/ember-resolver/dist/modules/ember-resolver.js,bower_components/ember-load-initializers/ember-load-initializers.js,vendor/ic-ajax/dist/named-amd/main.js,bower_components/ember-data/ember-data.js,vendor/addons.js,vendor/ember-cli/vendor-suffix.js]
    at ConcatWithMaps.addFiles (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:90:11)
    at ConcatWithMaps.build (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:65:8)
    at /Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:151:21
    at lib$rsvp$$internal$$tryCatch (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Applications/MAMP/htdocs/clients/unesco/ict/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```
When I set up Ember a few weeks back I didn't run into this problem.

Any ideas?

**Comment by mhenley-uk** [comment]
+1 I've just started getting this on a new application in the last hour or so.

**Comment by artych** [comment]
+1

**Comment by gaborsar** [comment]
+1

**Comment by gannetson** [comment]
+1

**Comment by mmarignoli** [comment]
+1

**Comment by Miz85** [comment]
+1

**Comment by maxrb** [comment]
+1

**Comment by ibrayem** [comment]
+1

**Comment by ianwalter** [comment]
More +1's are not necessary, a lot of people are having this problem.

**Comment by jimmityglick** [comment]
+1

**Comment by YoranBrondsema** [comment]
I'm not sure if it's this but I compared the results of `npm install` when it worked and when it doesn't work. The package `broccoli-caching-writer` updated two hours ago to 2.0.2.

**Comment by PavelBastov** [comment]
+1

**Comment by Sinled** [comment]
+1

**Comment by DCKT** [comment]
+1

**Comment by gannetson** [comment]
Switching to broccoli-caching-writer 2.0.1 or 0.6.1 doesn't seem to fix it.

**Comment by AnthonyLiu** [comment]
me too, and only for new apps.

I guess some issue with source

**Comment by gaborsar** [comment]
The error comes from the following package: `broccoli-sourcemap-concat`
Installed version: `1.1.5`
Latest version: `2.0.1`

**Comment by Sinled** [comment]
+1 I`ve got this problem after removing node modules\bower packages and reinstalling them in existing project.

**Comment by ballPointPenguin** [comment]
Band-Aid
adding this to my package.json fixed the issue for me:
```
    "broccoli-caching-writer": "2.0.1",
```

**Comment by rwjblue** [comment]
I reverted the changes that caused the issues in broccoli-caching-writer (in https://github.com/ember-cli/broccoli-caching-writer/pull/59) and released v2.0.3 (which is the same as the previously published 2.0.1).

Running the following should bring things back to a working state:

`rm -rf node_modules && npm cache clear && npm install`

**Comment by mmarignoli** [comment]
is there any way that this can be prevented? something like a gemfile.lock?

**Comment by YoranBrondsema** [comment]
@mmarignoli There's npm shrinkwrap (https://docs.npmjs.com/cli/shrinkwrap).

**Comment by ibrayem** [comment]
fixed the issue as follow:
$ ember new mysite --skip-npm --skip-bower
change package.json line 22:
"broccoli-asset-rev": "^2.1.1",
$ npm install && bower install

**Comment by Miz85** [comment]
Everything's working again, thanks a lot @rwjblue

**Comment by codedbypaul** [comment]
Working here too. Thanks @rwjblue

**Comment by heerqa** [comment]
I am still facing the same issue

**Comment by stefanpenner** [comment]
@heerqa https://github.com/ember-cli/ember-cli/issues/5055 \w fix https://github.com/ef4/broccoli-sourcemap-concat/pull/29 hopefully releasing in the next hour or two.

**Comment by kantecgee** [comment]
Hello I am new in EmberJS and sry for opening this thread.

Idk but I get this errormessage:

```
ENOENT: no such file or directory, stat 'D:\EmberJS\super-rentals\tmp\source_map_concat-input_base_path-qkwKZtmf.tmp\0\vendor\ember-components\vendor\ic-styled\main.js'
Error: ENOENT: no such file or directory, stat 'D:\EmberJS\super-rentals\tmp\source_map_concat-input_base_path-qkwKZtmf.tmp\0\vendor\ember-components\vendor\ic-styled\main.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:112:65)
    at D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

I try to reinstall the modules. I read some issues in github but I can't find the solution.
