### ISSUE TITLE
Blueprints fail anytime `this._super.<methodName>` is used.

### ISSUE THREAD

**Issue by rgbchris** [ember-cli/ember-cli#4953]
I'm trying to create a custom blueprint for an addon, however whenever trying to utilize `this.super`, the blueprint always seems to fail at `files()`. It looks like `this.path` becomes `undefined` when using super. Here's the stack trace.

```
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Blueprint.files (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/lib/models/blueprint.js:287:24)
    at Class.module.exports.files (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/blueprints/layout/index.js:19:17)
    at Class.Blueprint.supportsAddon (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/lib/models/blueprint.js:787:15)
    at Class.module.exports.Task.extend.run (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:25:98)
    at Class.module.exports.Command.extend.run (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/lib/commands/generate.js:77:17)
    at Class.<anonymous> (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/chris/Projects/JPMC/jpmaui/jpmaui-addon/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
```

Also ember info.

```
$ ember -v
version: 1.13.1
node: 0.12.4
npm: 2.12.1
```

Thanks in advance.

**Comment by stefanpenner** [comment]
In the Old version of core object that ember-cli uses you must explicitly bind the method with call or apply
