### ISSUE TITLE
ENOENT, no such file or directory tmp/concat_with_maps-input_base_path when using sourcemap

### ISSUE THREAD

**Issue by IAmJulianAcosta** [ember-cli/ember-cli#4992]
Hi, I'm trying to add library to ember, but I'm getting this:

```
julian@ubuntu:~/gc$ ember serve
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT, no such file or directory '/home/julian/gc/tmp/concat_with_maps-input_base_path-vUYQJGKj.tmp/0/vendor/libs/src/sprintf.js'
Error: ENOENT, no such file or directory '/home/julian/gc/tmp/concat_with_maps-input_base_path-vUYQJGKj.tmp/0/vendor/libs/src/sprintf.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at SourceMap.<anonymous> (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:281:17)
    at Array.map (native)
    at SourceMap._resolveSourcesContent (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:274:27)
    at SourceMap._assimilateExistingMap (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:247:63)
    at SourceMap.<anonymous> (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:218:12)
    at SourceMap._cacheEncoderResults (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:124:16)
    at SourceMap._addMap (/home/julian/gc/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:217:10)
```

This is what I have in ember-cli-build-js

```
/* global require, module */
var EmberApp = require ('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
	var app = new EmberApp (defaults, {
		// Add options here
	});

	app.import ('vendor/libs/loglevel.min.js');
	app.import ('vendor/libs/lscache.js');
	app.import ('vendor/libs/markerclustererplus.js');
	app.import ('vendor/libs/infobox.js');
	app.import ('vendor/libs/jquery.ui.widget.js');
	app.import ('vendor/libs/sprintf/sprintf.min.js');

	return app.toTree();
};
```

*The problem ocurrs when the file sprintf.min.map is present*

**Comment by stefanpenner** [comment]
@IAmJulianAcosta my guess is the sprintf sourcemap URI is wrong.

**Comment by IAmJulianAcosta** [comment]
This is what is in the .js file

```
//# sourceMappingURL=sprintf.min.map
```

**Comment by jimbeaudoin** [comment]
@IAmJulianAcosta I think your problem is related to this line: ` app.import ('vendor/libs/sprintf/sprintf.min.js');` in your `ember-cli-build.js`.

You probably don't have the file in your vendor folder and Ember CLI can't find it.

**Comment by jamesmgg** [comment]
I was having this issue when deploying on prod... but what was happening is I had a deployment ignore file which ignored vendor.

**Comment by stefanpenner** [comment]
will reopen if a reproduction on latest is provided
