### ISSUE TITLE
Error during ember dist/test in Windows

### ISSUE THREAD

**Issue by j-carvalho** [ember-cli/ember-cli#5011]
This process was working yesterday.

No new dependencies were added to the project.

ENOENT, no such file or directory '\client\tmp\funnel-output_path-wq4Xozv2.tmp\assets\intl'
Error: ENOENT, no such file or directory '\client\tmp\funnel-output_path-wq4Xozv2.tmp\assets\intl'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at Funnel.applyPatch [as _applyPatch] (\client\node_modules\broccoli-funnel\index.js:287:10)
    at Funnel.<anonymous> (\client\node_modules\broccoli-funnel\index.js:246:10)
    at Array.forEach (native)
    at Funnel.processFilters (\client\node_modules\broccoli-funnel\index.js:245:9)
    at Funnel.build (\client\node_modules\broccoli-funnel\index.js:167:10)
    at \client\node_modules\broccoli-funnel\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (\client\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (\client\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:505:17)
The system cannot find the path specified.

OS: Windows
node: 0.12.4
npm: 2.13.4
ember-cli: 1.13.8

**Comment by kellyselden** [comment]
Is it intermittent or constant?

**Comment by SlexAxton** [comment]
This appears to be intermittently happening on some of our machines as well. It's often a different file each time, so it feels related less to the actual error, and feels like something higher up the chain.

**Comment by SlexAxton** [comment]
Note: we're on OS X, Node 4.x and npm 2.x

**Comment by stefanpenner** [comment]
If someone can provide some reproduction, i can take a look. Our apps appear to be ok (and without issue) maybe we don't share some dependency others do?

**Comment by justinj** [comment]
Here's my stack trace, if that helps (OSX, Node 4.0.0, npm 2.14.2). It seems to often, but not always, be about jshint for me. This was shortly after I introduced a lint error in `my-component.js`, but it seemed to persist after fixing until I restarted my server.

```
Error: ENOENT: no such file or directory, unlink '/Users/jaffray/project/tmp/jshinter-output_path-ln3Ao02g.tmp/components/my-component.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:937:18)
    at JSHinter.<anonymous> (/Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/index.js:85:12)
    at /Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/jaffray/project/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by stefanpenner** [comment]
@justinj what is the result of `npm ls broccoli-persistent-filter`

**Comment by justinj** [comment]
@stefanpenner 
```
$ npm ls broccoli-persistent-filter
dashboard-ui@0.0.3 /Users/jaffray/stripe/dashboard-ui
├─┬ ember-cli-babel@5.1.5
│ └─┬ broccoli-babel-transpiler@5.4.5
│   └── broccoli-persistent-filter@1.1.2
└─┬ ember-cli-qunit@1.0.3
  └─┬ broccoli-jshint@1.1.0
    └── broccoli-persistent-filter@1.1.2
```

**Comment by stefanpenner** [comment]
@justinj you are on an old version 1.1.3 fixed an issue(extremely likely to be the one you demonstrate), and the current version is 1.1.4

**Comment by justinj** [comment]
Seems to have fixed things for me, thanks @stefanpenner!

**Comment by j-carvalho** [comment]
@stefanpenner updating broccoli-persistent-filter solved our issue. thanks for the help.
