### ISSUE TITLE
Unexpected token: name (path)

### ISSUE THREAD

**Issue by QuantumKing** [ember-cli/ember-cli#5042]
My project builds just fine when I run `ember build`, but whenever I try to run `ember build -prod` I get the following error:
```js
version: 1.13.8
Build failed.
File: assets/vendor.js (114670:10)
Unexpected token: name (path)
Error
  at new JS_Parse_Error (<anonymous>:1508:18)
  at js_error (<anonymous>:1516:11)
  at croak (<anonymous>:2008:9)
  at token_error (<anonymous>:2016:9)
  at unexpected (<anonymous>:2022:9)
  at semicolon (<anonymous>:2042:43)
  at simple_statement (<anonymous>:2222:73)
  at eval (<anonymous>:2095:19)
  at eval (<anonymous>:2055:24)
  at block_ (<anonymous>:2335:20)
  at eval (<anonymous>:2308:25)
  at function_ (<anonymous>:2313:15)
  at expr_atom (<anonymous>:2521:24)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at eval (<anonymous>:2590:25)
  at eval (<anonymous>:2055:24)
  at expr_atom (<anonymous>:2515:35)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_list (<anonymous>:2540:24)
  at subscripts (<anonymous>:2674:30)
  at subscripts (<anonymous>:2651:20)
  at subscripts (<anonymous>:2651:20)
  at subscripts (<anonymous>:2662:20)
  at expr_atom (<anonymous>:2527:20)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at maybe_assign (<anonymous>:2763:32)
  at expression (<anonymous>:2774:20)
  at simple_statement (<anonymous>:2222:55)
  at eval (<anonymous>:2095:19)
  at eval (<anonymous>:2055:24)
  at block_ (<anonymous>:2335:20)
  at eval (<anonymous>:2308:25)
  at function_ (<anonymous>:2313:15)
  at expr_atom (<anonymous>:2521:24)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at expr_list (<anonymous>:2540:24)
  at subscripts (<anonymous>:2674:30)
  at expr_atom (<anonymous>:2527:20)
  at maybe_unary (<anonymous>:2691:19)
  at expr_ops (<anonymous>:2726:24)
  at maybe_conditional (<anonymous>:2731:20)
  at maybe_assign (<anonymous>:2755:20)
  at expression (<anonymous>:2774:20)
  at simple_statement (<anonymous>:2222:55)
  at eval (<anonymous>:2095:19)
  at eval (<anonymous>:2055:24)
  at eval (<anonymous>:2802:23)
  at Object.parse (<anonymous>:2812:7)
```
which has something to do with uglifyJS. I have no idea what's going on. Can you guys help?

**Comment by twokul** [comment]
@QuantumKing can you give a bit more details? or provide a link to the repo?

**Comment by QuantumKing** [comment]
I can't share the repo as its private. But here is the rest of the error I forgot to share:

```js
  at /Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:62:33
  at Array.forEach (native)
  at Object.exports.minify (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:57:15)
  at UglifyWriter.processFile (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:99:27)
  at /Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:46:14
  at Array.forEach (native)
  at /Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:38:21
  at lib$rsvp$$internal$$tryCatch (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/quanta/Desktop/Mea/MeaWebBuilder/public/mea-organization/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)
```
Not sure what other details I can give...

**Comment by jcope2013** [comment]
can you disable minifyJs and see if that makes a difference?

``` 
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    minifyJS:  { enabled: false }
  });
  return app.toTree();
}; 
```

**Comment by QuantumKing** [comment]
@jcope2013 Everything works as expected

**Comment by twokul** [comment]
@QuantumKing source maps are tricky to debug unfortunately. `broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:62` suggests the code that was passed in to `uglify` wasn't correct. 

```javascript
toplevel = UglifyJS.parse(code, {});
```

given that it's `assets/vendor.js`, can you share a list of public dependencies so we can try to reproduce it?

**Comment by jcope2013** [comment]
@QuantumKing ok so it probably has something to do with the way the javascript is written, you might need to explicitly change an option so your code will properly build 

https://github.com/mishoo/UglifyJS2#compressor-options

```
 minifyJS:  { enabled: true, options: {  compress: { // list options in here } } }
```

**Comment by QuantumKing** [comment]
@twokul & @jcope2013 I just discovered another issue which may be related: when I build without minifying, the build is successful. But when I actually run my app, routes which require npm modules through `import marked from 'npm:marked'` receive the error `Uncaught Error: Could not find module 'npm:marked' imported from 'mea-web/helpers/parse-markdown'`.

I am using the `ember-browserify` addon.

**Comment by twokul** [comment]
@QuantumKing check if `npm:marked` is actually a correct name under `requirejs.entries`

**Comment by QuantumKing** [comment]
@twokul I'm not sure what you mean... at the bottom of the marked.js file I see
```js
if (typeof module !== 'undefined' && typeof exports === 'object') {
  module.exports = marked;
} else if (typeof define === 'function' && define.amd) {
  define(function() { return marked; });
} else {
  this.marked = marked;
}
```
which means it should be importable, right?

**Comment by QuantumKing** [comment]
Oups, nevermind. That had nothing to do with my problem. It was just a conflict of assets on my server.

**Comment by twokul** [comment]
@QuantumKing 

> given that it's assets/vendor.js, can you share a list of public dependencies so we can try to reproduce it?

**Comment by QuantumKing** [comment]
@twokul Sure

From npm
```js
"ember-monitorable": "^0.7.8",
"lodash": "^3.10.0",
"marked": "^0.3.5",
"react": "^0.13.3"
```
From bower
```js
"animate.css": "~3.4.0",
"autosize": "~3.0.8",
"ember": "~2.1.0",
"ember-cli-shims": "ember-cli/ember-cli-shims#~0.0.4",
"ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
"ember-load-initializers": "ember-cli/ember-load-initializers#~0.1.6",
"ember-qunit": "0.4.1",
"ember-qunit-notifications": "0.0.7",
"ember-resolver": "~0.1.18",
"fastclick": "~1.0.6",
"html2canvas": "~0.4.1",
"jquery": "^1.11.3",
"jspdf": "1.0.272",
"leaflet": "~0.7.3",
"loader.js": "ember-cli/loader.js#3.2.1",
"moment": "~2.10.3",
"nprogress": "~0.2.0",
"papaparse": "~4.1.2",
"pikaday": "~1.3.3",
"qunit": "~1.17.1",
"uikit": "~2.21.0",
"shufflejs": "~3.1.1"
```

**Comment by stefanpenner** [comment]
without a standalone reproduction we will not be able to diagnose this.

My suspicion is that there is legit invalid syntax, maybe some untranspiled ES6 code.

**Comment by QuantumKing** [comment]
@stefanpenner You're right, it was some untranspiled ES6 code. I found the line number of the error by manually trying to uglify the vendor.js file. The error was caused by some ES6 syntax in a custom addon.
