### ISSUE TITLE
Ember build results in Cannot find module 'broccoli-config-replace'

### ISSUE THREAD

**Issue by constantm** [ember-cli/ember-cli#5063]
Just upgraded to the newest Master to fix another issue (#5062), but now when I try and run tests or build the project, it says:

```
ember build
version: 1.13.8-master-71db5e67d0
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingCannot find module 'broccoli-config-replace'
Error: Cannot find module 'broccoli-config-replace'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/constantmeiring/other/ember-cli/lib/broccoli/ember-app.js:30:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by stefanpenner** [comment]
@constantm it shoulds like you node_modules may be out of sync, try removing them and running `npm install` again

**Comment by stefanpenner** [comment]
im pretty sure ^^ is the case, if not please provide a reproduction/steps and we can reopen.

**Comment by constantm** [comment]
Okay cool, I'll try and see if that sorts it out!
