### ISSUE TITLE
ember-cli 1.13.9 installation issue (Error: Cannot find module)

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli#5068]
on Nodejs 5.0.0 and npn 3.3.6 and getting this error:

```
$ ember s --live-reload=false --port=4555
module.js:339
    throw err;
    ^

Error: Cannot find module 'readline2'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at new UI (/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/lib/ui/index.js:35:19)
    at module.exports (/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/lib/cli/index.js:41:12)
    at /Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/bin/ember:26:3
    at /Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:46:14
    at process (/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:188:17)
```

**Comment by stefanpenner** [comment]
I believe we need to cut a new-release, something seemed to go sideways with our `npm publish`

**Comment by jgelens** [comment]
I'm also getting an error during installation of 1.13.9 regarding readline:

```
npm WARN install:strip-ansi@2.0.1 ENOENT: no  such file or directory, chmod  '/usr/local/lib/node_modules/ember-cli/node_modules/readline2/node_modules/strip-ansi/cli.js'
```
And after that the install just fails.

**Comment by stefanpenner** [comment]
Ya, we have confirmed something went sideways with our `npm publish` it appears a partial set of dependencies was bundled. Defeating `npm` clients from properly installing it.

I believe we have a new package that works, testing it out on multiple machines now. It will be released as 1.13.10

**Comment by miguelramos** [comment]
With node v4.2.1 after install npm install -g ember-cli got:

```
ember -v
module.js:339
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/miguelramos/.nvm/versions/node/v4.2.1/lib/node_modules/ember-cli/node_modules/fs-extra/lib/remove/index.js:1:76)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by twokul** [comment]
@mmahalwy @miguelramos do you mind trying [`1.13.10`](https://github.com/ember-cli/ember-cli/releases/tag/v1.13.10) and see if it works?

**Comment by martndemus** [comment]
@twokul you can follow https://travis-ci.org/martndemus/ember-cli-font-awesome/builds/90625604, if it turns green, it works.

**Comment by altrim** [comment]
@twokul Had the same issue as @jgelens. Tried `1.13.10` and it seems to work fine.

**Comment by miguelramos** [comment]
Working fine at the moment.

```
$ ember -v                 
version: 1.13.10
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 4.2.1
npm: 2.14.10
os: darwin x64
```

**Comment by twokul** [comment]
@altrim @martndemus kewl. 

@mmahalwy @miguelramos I'm closing this one for now, feel free to re-open if the issue persists.

**Comment by mmahalwy** [comment]
@twokul going to try now

**Comment by miguelramos** [comment]
After this i tried to run ember server and got other issue on compilation:

```
$ ember server
version: 1.13.10
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, stat '/Users/miguelramos/Public/thejsleaguesite/tmp/concat_with_maps-input_base_path-33DHCptO.tmp/0/bower_components/ember-resolver/dist/modules/ember-resolver.js'
Error: ENOENT: no such file or directory, stat '/Users/miguelramos/Public/thejsleaguesite/tmp/concat_with_maps-input_base_path-33DHCptO.tmp/0/bower_components/ember-resolver/dist/modules/ember-resolver.js'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at ConcatWithMaps.keyForFile (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/miguelramos/Public/thejsleaguesite/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by jgelens** [comment]
Same error as @miguelramos

**Comment by martndemus** [comment]
@miguelramos @jgelens  did you guys did `ember install ember-resolver` and `bower uninstall ember-resolver --save` ?

**Comment by jgelens** [comment]
Yep I ran `ember init`, but the resolver is removed from the dependencies. I guess it was removed from mistake in the latest release.

**Comment by martndemus** [comment]
So did you run `ember install ember-resolver` now, and does it work then?

**Comment by miguelramos** [comment]
Gonna try.

**Comment by jgelens** [comment]
Yes, that's what I said earlier.

**Comment by martndemus** [comment]
:+1:

**Comment by miguelramos** [comment]
@martndemus just run ```ember install ember-resolve``` and now is perfect.

```
$ ember server
version: 1.13.10
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 4105ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor                | 3509ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor (1)            | 3509ms  
```

**Comment by martndemus** [comment]
Perfect :100:

**Comment by twokul** [comment]
@mmahalwy @jgelens which version of `npm` are you guys using?

**Comment by jgelens** [comment]
» npm --version
3.3.9

**Comment by mmahalwy** [comment]
3.3.12

**Comment by mmahalwy** [comment]
I am getting this error:
```
 npm install -g ember-cli@1.13.10
npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN install:tap-parser@1.2.2 ENOENT: no such file or directory, chmod '/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib/node_modules/ember-cli/node_modules/tap-parser/bin/cmd.js'
/Users/mmahalwy/.nvm/versions/node/v5.0.0/lib
└── (empty)

npm WARN EBUNDLEOVERRIDE Replacing bundled ember-cli > tap-parser with new installed version
npm ERR! code 1
```

**Comment by mike-post** [comment]
Same.  Installing with the --no-optional flag fixes the problem so perhaps #4919 is not actually fixed?

**Comment by mmahalwy** [comment]
Yeah @mike-post not fixed....

**Comment by mike-post** [comment]
I replicated the same result on node 4.2.2 with npm 3.3.6.

**Comment by mmahalwy** [comment]
`--no-optional` does fix it!

**Comment by mmahalwy** [comment]
I also still get
```
Future versions of Ember CLI will not support v5.0.0. Please update to Node 0.12 or io.js.
```
lool

**Comment by stefanpenner** [comment]
@mmahalwy i am dubious of this claim https://github.com/ember-cli/ember-cli/blob/master/tests/unit/utilities/platform-checker-test.js#L50-L52

**Comment by mmahalwy** [comment]
@stefanpenner you're right - i actually have 1.13.8 running for some reason although i installed .10 globally. must be my project version

**Comment by martndemus** [comment]
It's the version in your `package.json` that counts.

**Comment by mike-post** [comment]
@stefanpenner I definitely saw the reported tap-parser issue using node 4.2.2 and node 5.0.0 with npm 3.3.6. (node 4.x with npm 2.x is fine) See my edits above for weird behavior re: installing and reinstalling the node binaries.

**Comment by stefanpenner** [comment]
@mike-post yes, and it should be fixed. bundling with v3 introduces this issue.

Also for the next release (later tonight) bundling is just thrown away, hopefully we wont overwhelm npm again: https://github.com/ember-cli/ember-cli/commit/5fdb5dba61c1d0938b25ef6f142a3dbba55b8b7c

**Comment by stefanpenner** [comment]
the issue causing this is fixed and released. There are some additional issues that have cropped up, they are currently being dealt with.

Following along here: https://github.com/ember-cli/ember-cli/issues/5076
