### ISSUE TITLE
cannot find module 'rimraf'

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-cli#5072]
Followed steps 1-4 of setup on OS X 10.10.5.
Executed `ember test` from a bash prompt and saw the  following:
```
[myhost tmp]$ ember test
module.js:338
    throw err;
          ^
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra/lib/remove/index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
FWIW, our travis builds failed on this same error. (ubuntu )

**Comment by stefanpenner** [comment]
dupe: https://github.com/ember-cli/ember-cli/issues/5068

**Comment by efx** [comment]
thanks, my bad!
