### ISSUE TITLE
ember s errors after upgrading to ember-cli 1.13.12

### ISSUE THREAD

**Issue by lmcardle** [ember-cli/ember-cli#5100]
Currently running ember-cli 1.13.8 and upgrading to 1.13.12, however, when starting the server I get the following error:

```
$ ember s
version: 1.13.12
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at symlink (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at /Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/LiamMcardle/Development/emberui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:417:9)

**Comment by lmcardle** [comment]
I have another ember app that upgraded fine. :( What possibility could cause cause the error "path must be a string" at ``` node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26 ```

**Comment by stefanpenner** [comment]
Can you share a reproduction ? I'm unsure how actionable it will be without.

**Comment by lmcardle** [comment]
I am trying to find a way to reproduce it within another app, but I haven't yet. I have 3 in-repo addons that might be the cause of this, as they are doing some fairly complicated things. What would potentially call "symlink" function within the "symlink-or-copy" node module?

**Comment by stefanpenner** [comment]
> What would potentially call "symlink" function within the "symlink-or-copy" node module?

every broccoli-plugin
