### ISSUE TITLE
Travis Failures on Node 5.1.0

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#5126]
Passing yesterday: https://travis-ci.org/ember-cli/ember-cli/jobs/91524334

```
Now using node v5.0.0
$ node --version
v5.0.0
$ npm --version
3.3.6
```

Failing today: https://travis-ci.org/ember-cli/ember-cli/jobs/91855141

```
Now using node v5.1.0
$ node --version
v5.1.0
$ npm --version
3.3.12
```

A few errors from the logs:

```
$ npm run-script test-all:cover
> ember-cli@1.13.8 test-all:cover /home/travis/build/ember-cli/ember-cli
> istanbul cover tests/runner.js all
Cannot find module 'minimatch'
Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/travis/build/ember-cli/ember-cli/node_modules/fileset/lib/fileset.js:2:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
/home/travis/build/ember-cli/ember-cli/node_modules/istanbul/lib/util/factory.js:60
                    throw new Error('Could not register ' + that.kind + ' from file ' + file);
                    ^
Error: Could not register command from file check-coverage.js
    at /home/travis/build/ember-cli/ember-cli/node_modules/istanbul/lib/util/factory.js:60:27
    at Array.forEach (native)
    at Object.Factory.loadStandard (/home/travis/build/ember-cli/ember-cli/node_modules/istanbul/lib/util/factory.js:53:29)
    at Object.<anonymous> (/home/travis/build/ember-cli/ember-cli/node_modules/istanbul/lib/register-plugins.js:12:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by rwjblue** [comment]
I am not certain if this is related to updating node from 5.0.0 to 5.1.0 or npm from 3.3.6 to 3.3.12 (or both).

**Comment by rwjblue** [comment]
@stefanpenner - Any quick ideas?

**Comment by stefanpenner** [comment]
let me attempt to replicate locally

**Comment by stefanpenner** [comment]
Was able to replicated, I suspect its NPM issue. Verifying..

**Comment by stefanpenner** [comment]
yup, downgrading to  `npm install -g npm@3.3.6` works, going to look for which version is pwning us and report.

**Comment by liquid** [comment]
Not sure if you guys are aware of this but I had to downgrade npm to even get embercli to install. The version 3.3.6 did the trick.

**Comment by rwjblue** [comment]
3.4.1/3.5.0 also work, but yes this is annoying

**Comment by stefanpenner** [comment]
upstream bugs, not much we can do. (issue have been reported)
