### ISSUE TITLE
Cannot read property "dummy" of undefined

### ISSUE THREAD

**Issue by JDillon522** [ember-cli/ember-cli#5129]
I've started getting this error when I generate a route:

```
silently_client git:(branchName) ember g route signup/credentials   
version: 1.13.12
installing route
  create app/pods/signup/credentials/route.coffee
  create app/pods/signup/credentials/template.hbs
Cannot read property 'dummy' of undefined
TypeError: Cannot read property 'dummy' of undefined
  at Class.module.exports.shouldTouchRouter (/Users/app_location/node_modules/ember-cli/blueprints/route/index.js:70:28)
  at Class.module.exports.shouldTouchRouter (/Users/app_location/node_modules/ember-cli-coffeescript/blueprints/route/index.js:31:42)
  at Class.module.exports.shouldTouchRouter (/Users/app_location/node_modules/ember-cli-coffeescript/blueprints/route/index.js:31:42)
  at Class.module.exports.afterInstall (/Users/app_location/node_modules/ember-cli-coffeescript/blueprints/route/index.js:37:14)
  at lib$rsvp$$internal$$tryCatch (/Users/app_location/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/app_location/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/app_location/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/app_location/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by gmurphey** [comment]
I wasn't able to reproduce this with a new app using ember-cli-coffeescript. Are there any other addons that might be culprits?

**Comment by stefanpenner** [comment]
if a reproduction can be provided on latest, I will gladly reopen
