### ISSUE TITLE
ENOENT after upgrade to 1.13.13

### ISSUE THREAD

**Issue by bkCDL** [ember-cli/ember-cli#5141]
I upgraded my ember-cli to 1.13.13 and get this error:

> version: 1.13.13
> Livereload server on http://localhost:49152
> Serving on http://localhost:4200/
> ENOENT, no such file or directory 'E:\CDL\ReportingWebsite\tmp\compass_compiler-output_path-OW19P78k.tmp\assets\app.css'
Error: ENOENT, no such file or directory 'E:\CDL\ReportingWebsite\tmp\compass_compiler-output_path-OW19P78k.tmp\assets\app.css'
  at Error (native)
  at Object.fs.lstatSync (fs.js:796:18)
  at Object.realpathSync (fs.js:1387:21)
  at symlinkWindows (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\symlink-or-copy\index.js:87:26)
  at Function.symlinkOrCopySync (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\symlink-or-copy\index.js:56:5)
  at Funnel._copy (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:393:19)
  at Funnel.processFile (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:376:8)
  at Funnel.applyPatch [as _applyPatch] (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:294:12)
  at Funnel.<anonymous> (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:246:10)
  at Array.forEach (native)
  at Funnel.processFilters (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:245:9)
  at Funnel.build (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\index.js:167:10)
  at E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\broccoli-plugin\read_compat.js:61:34
  at lib$rsvp$$internal$$tryCatch (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:476:11)
  at lib$rsvp$asap$$flush (E:\CDL\ReportingWebsite\node_modules\ember-cli-compass-compiler\node_modules\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)

My bower.js file is:

    {
      "name": "app-cdl",
      "dependencies": {
        "ember": "2.2.0",
        "ember-cli-shims": "0.0.6",
        "ember-cli-test-loader": "0.2.1",
        "ember-data": "^2.2.0",
        "ember-load-initializers": "0.1.7",
        "ember-qunit": "0.4.16",
        "ember-qunit-notifications": "0.1.0",
        "ember-resolver": "~0.1.18",
        "jquery": "^1.11.3",
        "loader.js": "3.3.0",
        "qunit": "~1.19.0",
        "bootstrap": "~3.3.4",
        "flexgrid": "https://github.com/ptb/flexgrid.git",
        "font-awesome": "~4.4.0",
        "bootstrap-daterangepicker": "*",
        "malihu-custom-scrollbar-plugin": "~3.0.8",
        "bootstrap-switch": "~3.3.2",
        "jquery-ui": "~1.11.4",
        "jquery.cookie": "~1.4.1",
        "jquery-number": "~2.1.5",
        "isotope": "~2.1.1",
        "moment": ">= 2.8.0",
        "moment-timezone": ">= 0.1.0",
        "twix": "~0.6.2",
        "velocity": "~1.2.2",
        "datatables": "~1.10.5",
        "datatables-plugins": "~1.10.5",
        "datatables-responsive": "~1.0.7",
        "raygun4js": "^2.0.3",
        "hammerjs": "~2.0.4",
        "flickity": "~1.1.0",
        "uri.js": "~1.15.1",
        "d3": "~3.5.8",
        "c3": "~0.4.10"
      },
      "devDependencies": {
        "bootstrap-contextmenu": "~0.3.3"
      },
      "resolutions": {
        "d3": "~3.5.8",
        "ember-data": "2.2.0",
        "qunit-notifications": "~0.1.0"
      }
    }

Any thoughts why this might occur?

-Bryan

**Comment by stefanpenner** [comment]
is likely: https://github.com/broccolijs/broccoli-funnel/issues/53

If you can provide a small example app that demonstrates this issue, i can look into it.

**Comment by bkCDL** [comment]
In prepping an example, I discovered that if I 
* removed `"ember-cli-compass-compiler"` from my package.json file
* renamed the ENV.modulePrefix value back to "app" in the environment.js file
* renamed my sass file back to "app.sass"
* adjusted the css/js references in index.html accordingly

Then my site builds again without error. It leads me to think maybe there's something in that compass dependency or my compass setup.

**Comment by bkCDL** [comment]
In prepping an example, I discovered that if I
* removed "ember-cli-compass-compiler" from my package.json file
* renamed the ENV.modulePrefix value back to "app" in the environment.js file
* renamed my sass file back to "app.sass"
* adjusted the css/js references in index.html accordingly
* added `sassOptions: { extension: "sass" } ` to ember-cli-build.js

Then my site builds again without error. It leads me to think maybe there's something in that compass dependency (or its respective dependency in broccoli as you mention) or my compass/sass setup.

**Comment by stefanpenner** [comment]
I have fixed all reproductions of related windows issues, If there is still an issue, please provide an isolated app that demonstrates the issue and i can reopen.
