### ISSUE TITLE
Can't generate acceptance tests

### ISSUE THREAD

**Issue by asermax** [ember-cli/ember-cli#5164]
Aparrently the accpetance test blueprint still tries to import a module that isn't on the codebase anymore:

```
kiira@kiira-lap .../frontend (git)-[feature/activity-stream] % ember g acceptance-test super-test

version: 1.13.13
Cannot find module 'ember-cli/lib/utilities/test-info'
Error: Cannot find module 'ember-cli/lib/utilities/test-info'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (.../frontend/blueprints/acceptance-test/index.js:3:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by asermax** [comment]
Sorry, after some digging I found out it was a problem in a custom blueprint, false alarm :>
