### ISSUE TITLE
Ember Build 1.13.13 runtime error

### ISSUE THREAD

**Issue by vinothwindows47** [ember-cli/ember-cli#5195]
https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L57

When I am running ember build in my new application .

version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingbuildFile is not a function
TypeError: buildFile is not a function
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/lib/models/builder.js:57:19)
    at Class.module.exports.Task.extend.init (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/lib/models/builder.js:91:10)
    at new Class (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at /home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/lib/commands/build.js:28:24
    at lib$rsvp$$internal$$tryCatch (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/home/local/ZOHOCORP/vinoth-1646/cide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)

**Comment by vinothwindows47** [comment]
Please help me ... @alexspeller @jakehow @tpitale

**Comment by rwjblue** [comment]
`buildFile` at that line, should be the function exported from `ember-cli-build.js`.  Can you share your `ember-cli-build.js` file?

**Comment by stefanpenner** [comment]
ya, i suspect the ember-cli-build.js file is malformed. We should likely improve that error message (invoke the function in a guard, so we can provide good feedback etc.)

**Comment by rwjblue** [comment]
@stefanpenner agreed

**Comment by vinothwindows47** [comment]
[ember-cli-build.js.txt](https://github.com/ember-cli/ember-cli/files/59033/ember-cli-build.js.txt)

**Comment by stefanpenner** [comment]
Yup. That is malformed. Are you upgrading from a much older cli? You should take a look at the fresh ember-cli-build.

Also I wonder what happened to the nice error message @chadhietala added

**Comment by vinothwindows47** [comment]
Ok.Thank you @stefanpenner  @rwjblue .I have missed this line in ember-cli-build.js module.exports = function(defaults) { };

**Comment by runspired** [comment]
Ugh, so I bumped into this, it was because I'd trolled myself and treated my `ember-cli-build` file as my `index.js` file. :troll:
