### ISSUE TITLE
Ember data upgrading new version error for me. 

### ISSUE THREAD

**Issue by vinothwindows47** [ember-cli/ember-cli#5199]
Now I am migrating from ember 1.7.0 and ember-data 1.1.0 using ember 1.13.11 and ember-data 1.13.15

Error while processing route: index Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
    at keys (native)
    at ember$data$lib$system$adapter$$default.extend.sortQueryParams (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:76691:20)
    at ember$data$lib$system$adapter$$default.extend.query (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:76911:24)
    at ember$data$lib$system$store$finders$$_query (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:83444:27)
    at ember$data$lib$system$store$$Service.extend.query (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:88108:68)
    at ember$data$lib$system$store$$Service.extend.findQuery (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:88157:21)
    at getUserProject (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/cide.js:12352:22)
    at model (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/cide.js:12334:24)
    at _emberRuntimeSystemObject.default.extend.deserialize (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:43745:19)
    at Object.applyHook (http://vinoth-1646.csez.zohocorpin.com:8080/development/cide/assets/vendor.js:71830:30)

**Comment by vinothwindows47** [comment]
![ember-data-error](https://cloud.githubusercontent.com/assets/3929019/11738993/dfeabb6c-a00d-11e5-814c-c277d615a820.png)

**Comment by vinothwindows47** [comment]
Error thrown in this file ... 

``` export default Ember.Route.extend({
	
	model: function() {
		if(window.currentPage ==="dashboard") {
			this.controllerFor('application').transitionToRoute("dashboard");
		} else {
			this.controllerFor('application').loadPreLoader('Loading Projects ...');
			return Ember.RSVP.hash({
				userProject: this.getUserProject()
			});
		}
	},
	
	afterModel: function() {
		this.controllerFor('application').clearPreLoader(); 
	},
	
	setupController: function(controller, model) {
		if(window.currentPage === "ide") {
			this._super(controller, model);
			controller.set('userprojects', model.userProject);
		}
	},
	
	/**will call get user project**/
	getUserProject: function() {
		return this.store.findQuery("project/userproject");
	},
	
	actions: {
		/**will call refresh user project on page**/
		refreshUserProject: function() {
			var self = this;
			var getUserProject = this.getUserProject();
			getUserProject.then(function(getuserprojResponse){
				self.get('controller').set('userprojects', getuserprojResponse);
			});
		},
		
		menuActions: function(menuAction) { // ide menubar actions
			var controller = this.get('controller');
			menubarActions.activatemenuAction(controller, menuAction);
		},
		
		connectOutlet: function(name, options) {
			  this._super(this, arguments);
		      this.render(name, options);
		},

		disconnectOutlet: function(options) {
			this._super(this, arguments);
			this.disconnectOutlet(options);
		},
		
		showModal: function(name, options) {
			options = options || {};
		      this.render(name, {
		        into: 'application',
		        outlet: 'modal',
		        view: 'common/modal',
		        controller: options.controller
		      });
		},

		closeModal: function() {
			this.disconnectOutlet({
		        outlet: 'modal',
		        parentView: 'application'
		    });
		}
		
	}
}); ```
