### ISSUE TITLE
Compilation error "path must be a string" with ember cli 1.13.10+

### ISSUE THREAD

**Issue by jludev1** [ember-cli/ember-cli#5222]
Got "path must be a string" error when executing "ember build" with ember cli 1.13.10. It couldn't be reproduced with 1.13.8. 
Attached is a sample app to reproduce the issue. The error is related to the following code in the in-repo addon of the sample app.
```
  treeForApp: function(tree) {
    return new UnwatchedTree(tree);
  },
```
The direct cause is line 58 of read_compat.js  
```
symlinkOrCopySync(outputPaths[i], self.inputPaths[i])
```
, where outputPaths[i] needs to be a string, but becomes an object ("WatchedDir") instead. 

Below is the output for "ember build." 
version: 1.13.10
Build failed.
path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.lstatSync (fs.js:796:18)
    at symlink (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
    at symlinkOrCopySync (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at /hg/ember_test/myapp/node_modules/ember-cli/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/hg/ember_test/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)

[test.tar.gz](https://github.com/ember-cli/ember-cli/files/61603/test.tar.gz)

**Comment by stefanpenner** [comment]
> treeForApp: function(tree) {
>     return new UnwatchedTree(tree);
>   },

The input to this must be a string, but the argument to treeForApp is polymorphic, string or tree. Although this may have happened to work in some cases the past, it was an accident that it did. A Tree is inherently watched, it cannot become unwatched.

I suppose the following could be done...
```js
return typeof tree === 'string' : new UnwatchedTree(tree) : tree
```
