### ISSUE TITLE
v2.2.0-beta.2 - empty tmp folder on Ubuntu 14.04

### ISSUE THREAD

**Issue by nanuxbe** [ember-cli/ember-cli#5276]
Build failed.
When attempting to run serve/test/build.
I believe this has to do with broccoli-concat as the tmp folder stays empty all along.

v2.2.0-beta.1 had the same behavior but not on all machine so it was hard to describe (maybe I did something wrong when upgrading on a particular machine).

This is on an upgraded project (upgrade from 1.13.x -> 2.2.0-beta.1 -> 2.2.0-beta.2)

Here is the full traceback:
 ```
$ ember build
version: 2.2.0-beta.2
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingSmoke-and-mirrors:: Including Vertical-Collection Debug CSS
Build failed.
ENOENT: no such file or directory, stat '/home/emma/intranet/front/tmp/source_map_concat-input_base_path-tuTVBTdN.tmp/0/bower_components/jquery-mockjax/dist/jquery.mockjax.js'
Error: ENOENT: no such file or directory, stat '/home/emma/intranet/front/tmp/source_map_concat-input_base_path-tuTVBTdN.tmp/0/bower_components/jquery-mockjax/dist/jquery.mockjax.js'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at ConcatWithMaps.keyForFile (/home/emma/intranet/front/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/emma/intranet/front/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /home/emma/intranet/front/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/emma/intranet/front/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/emma/intranet/front/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/emma/intranet/front/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/emma/intranet/front/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

package.json is:
```
{
  "name": "intranet-ng",
  "version": "0.0.0",
  "description": "Small description for intranet-ng goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.2.0-beta.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "^5.2.1",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "0.1.6",
    "ember-data": "^2.2.1",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-resolver": "^2.0.3",
    "ember-data-factory-guy": "2.1.2",
    "ember-django-adapter": "^1.1.1",
    "ember-href-to": "0.0.11",
    "ember-hypersearch": "0.1.0",
    "ember-inline-svg": "^0.1.5",
    "ember-simple-auth": "1.0.1",
    "ember-truth-helpers": "1.2.0",
    "ember-validations": "2.0.0-alpha.4",
    "liquid-fire": "0.22.1",
    "smoke-and-mirrors": "0.4.4"
  }
}
```

bower.json is:
```
{
  "name": "intranet-ng",
  "dependencies": {
    "ember": "2.2.0",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "^2.2.1",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "^2.1.4",
    "loader.js": "^3.5.0",
    "qunit": "~1.20.0"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

ember-cli-build.js is:
```
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    svg: {
      paths: [
        'public/assets/svgs'
      ]
    }    
  });
  
  app.import('vendor/bootstrap/bootstrap.js');
  app.import('vendor/jasny-bootstrap.js');

  return app.toTree();
};
```

repo demonstrating the problem: https://bitbucket.org/levit_scs/djember_front

**Comment by nanuxbe** [comment]
Sorry, my bad, found the solution to the problem while trying to add details to the bug report.
It was a missing dependency
