### ISSUE TITLE
Build fails only on reload - 1.13.13 - '.css' not found

### ISSUE THREAD

**Issue by omairvaiyani** [ember-cli/ember-cli#5285]
I've followed all steps to upgrade from ```1.13.8``` to ```1.13.12```, but I couldn't find a solution for this issue. So I went and upgraded further to ```1.13.13```, but the issue remains. The app builds first time, but subsequent reloads on any changes results in the following error:

```
ENOENT: no such file or directory, stat '/Users/~/Documents/github/app-name/tmp/broccoli_merge_trees-output_path-nEka5cYU.tmp/assets/app-name.css'
Error: ENOENT: no such file or directory, stat '/Users/~/Documents/github/app-name/tmp/broccoli_merge_trees-output_path-nEka5cYU.tmp/assets/app-name.css'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at copyDereferenceSync (/Users/~/Documents/github/app-name/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:13:21)
    at copyDereferenceSync (/Users/~/Documents/github/app-name/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at Function.copyDereferenceSync [as sync] (/Users/~/Documents/github/app-name/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at /Users/~/Documents/github/app-name/node_modules/ember-cli/lib/models/builder.js:144:19
    at lib$rsvp$$internal$$initializePromise (/Users/~/Documents/github/app-name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:541:9)
```

Weirdly, when I go into my ```tmp``` folder and locate that ```.css``` file, my IDE warns me that the "link is broken". 

I am using ```ember-cli-stylus```. Let me know if posting my ```package.json``` or ```ember-cli-build.js``` helps.

**Comment by stefanpenner** [comment]
You have an outdated dependency. Some older broccoli plugins have some bugs, which made them rely excess rebuilds to functiok correctl. So i suspect one of them is out of sync, please use `npm outdated` to track it down.

If you cannot. Please provide a isolated reproduction in the form of a github repo, and i will gladly in investigate further

**Comment by omairvaiyani** [comment]
Thanks Stefan,

This is what I get:

```
Omairs-MBP:synap-web omairvaiyani$ npm outdated
Package                 Current   Wanted  Latest  Location
ember-cli-async-button    0.3.1    0.3.1   0.6.1  ember-cli-async-button
ember-cli-chart           2.0.4    2.0.4   2.0.5  ember-cli-chart
ember-cli-sri             1.2.1    1.2.1   2.0.0  ember-cli-sri
ember-data              1.13.15  1.13.15   2.2.1  ember-data
ember-google-map          0.0.8    0.0.8  0.0.26  ember-google-map
ember-parse-adapter       0.5.3      git     git  ember-parse-adapter
ember-rl-year-picker     0.0.13   0.0.13   0.2.0  ember-rl-year-picker
ember-social              0.0.9    0.0.9   0.2.0  ember-social
grunt-redis               0.1.0      git     git  grunt-redis
stripe                    2.9.0    2.9.0   4.1.0  stripe
```

The two in red are forked repos, but neither uses broccoli. I'll create a repo for you thanks!

**Comment by omairvaiyani** [comment]
Okay before doing that I decided to fresh install everything (uninstalled and reinstalled node).

Now, I get this error when running ```ember init```:

```
Cannot find module './lib/asset-rev'
Error: Cannot find module './lib/asset-rev'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/~/Documents/github/app-name/node_modules/broccoli-asset-rev/index.js:3:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by omairvaiyani** [comment]
Here's a public repo I just made, removed all app code and made sure the error still occurs.

https://github.com/omairvaiyani/ember-cli-issue-5285

Let me know if you can replicate it!

**Comment by stefanpenner** [comment]
rebuilds appear to work fine for me.

**Comment by stefanpenner** [comment]
My guess is some transient dependency fixed it self. Try doing

```
rm -rf node_modules
npm cache clear
npm install
```

If that doesn't resolve it, try to provide some reproduction steps and I will gladly reopen/explore further
