### ISSUE TITLE
cannot find module 'rsvp'

### ISSUE THREAD

**Issue by shime** [ember-cli/ember-cli#5357]
Installing ember CLI with 

```
npm install -g ember-cli
```
and then trying to use it with 

```
ember
```
produces the following error
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hrvoje/node_modules/ember-cli/lib/ext/promise.js:3:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

NPM v2.14.4
Node v4.1.2

NPM v3.3.12
Node v5.4.1

**Comment by rwjblue** [comment]
Issue is with npm version. There is at least one other open issue for this. Use either <=3.3.6 or >=3.4.1.

**Comment by stefanpenner** [comment]
Unfortunately this is an npm issue, I believe it is fixed on a more recent version of npm

**Comment by shime** [comment]
Confirmed. Fixed by updating npm to the latest version.

**Comment by gvsro** [comment]
I still have the same problem even after updating.
I even removed node and npm and used nvm.

**Comment by devinrhode2** [comment]
I'm getting this again whenever I run any `ember` command on a freshly installed node-npm. I can't find the proper npm version/permission setup that doesn't have this error. I've tried the cleanest most predictable install methods except for installing node from the website, which I've enumerated below.
```
➤ ember new sympstruments                                                                                                                                   
module.js:327
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/devinrhode2/node_modules/ember-cli/node_modules/findup/index.js:4:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
~ ➤
```
 • Tried reinstalling the latest nvm, then installing node v4 (with npm): `nvm install 4 && nvm use 4`. This installs node 4.4.5 and npm 2.15.5. Then I do `npm install -g ember-cli` and `ember new sympstruments` still gives the error I pasted above.
 • Tried `nvm install stable && nvm use stable`. This installs node 6.2.1 and npm 3.9.5, `npm install -g ember-cli && ember version` gives the same error. I tried `npm install -g npm` to update npm because rwjblue mentioned above npm versions `<=3.3.6 or >=3.4.1` have a bug. Still doesn't work.
 • Tried [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) as mentioned in another thread, but this did not fix it either.
 • Tried a clean `brew install node` but this also did not work.

**Comment by devinrhode2** [comment]
Running:
```
cd $(npm config get prefix)/lib/node_modules/ember-cli
rm -rf node_modules && npm cache clear && npm install
```
fixed it

**Comment by stefanpenner** [comment]
> But presumably I'll have to do this for every time I change ember-cli versions

nope, sounds like a bug in npm (or and old version of npm)

**Comment by devinrhode2** [comment]
It could've been something funky going on with my `~/repos/ember` and `~/repos/ember-cli` directories. I was primarily testing if my `ember` commands work in `~/repos`.  It seems to be fixed now without needing to manually install ember-cli deps.
