### ISSUE TITLE
Generating a model generates a failing test in 2.2.0-beta.6

### ISSUE THREAD

**Issue by jagthedrummer** [ember-cli/ember-cli#5360]
When I generate a new project with 2.2.0-beta.6 and then generate a new model I end up with a failing test that gives me this stack trace:

```
not ok 9 PhantomJS 2.0 - Unit | Model | widget: it exists
    ---
        actual: >
            null
        message: >
            Died on test #1 	at testWrapper (http://localhost:7357/assets/test-support.js:6400:16)
            	at test (http://localhost:7357/assets/test-support.js:6413:44)
            	at http://localhost:7357/assets/tests.js:143:24
            	at exports (http://localhost:7357/assets/vendor.js:92:39)
            	at build (http://localhost:7357/assets/vendor.js:142:17)
            	at findModule (http://localhost:7357/assets/vendor.js:190:14)
            	at requireModule (http://localhost:7357/assets/vendor.js:177:22)
            	at require (http://localhost:7357/assets/test-loader.js:67:16)
            	at loadModules (http://localhost:7357/assets/test-loader.js:58:25)
            	at load (http://localhost:7357/assets/test-loader.js:89:35)
            	at http://localhost:7357/assets/test-support.js:6232:20: undefined is not an object (evaluating 'store.createRecord')
```

Steps to reproduce:

```
npm install -g ember-cli@2.2.0-beta.6
ember new embercli-beta-6-test
cd embercli-beta-6-test
ember g model widget name description
ember test
```

Here's a repo that demonstrates the issue: https://github.com/jagthedrummer/embercli-beta-6-test

**Comment by nfc036** [comment]
Same problem here. It seems that the first run of 
           var store = container.lookup('service:store') || container.lookup('store:main');
in ember-test-helpers/test-module-for-model.js (function setupModel) does not return a valid store. If you have two (or more) models in your project, the unit test of the second model will succeed, only the first test is always failing.

**Comment by nfc036** [comment]
Just found emberjs/data/issues/4071

**Comment by jsmestad** [comment]
^^ @nfc036 that was the culprit for me too.

**Comment by stefanpenner** [comment]
This is an ember-data bug
