### ISSUE TITLE
Cannot import vendor files from a npm package

### ISSUE THREAD

**Issue by josemarluedke** [ember-cli/ember-cli#5378]
Hi there. I'm trying to use `bootstrap-sass` from npm instead of bower. Everything is okay on the css side, however, when trying to import the js file in `ember-cli-build.js` using `app.import` does not work.

The error I get is:

```
ENOENT: no such file or directory, stat '/Users/josemarluedke/Projects/Temp/demo-app-import/tmp/source_map_concat-input_base_path-ABAzN1pm.tmp/0/node_modules/bootstrap-sass/assets/javascripts/bootstrap.js'
Error: ENOENT: no such file or directory, stat '/Users/josemarluedke/Projects/Temp/demo-app-import/tmp/source_map_concat-input_base_path-ABAzN1pm.tmp/0/node_modules/bootstrap-sass/assets/javascripts/bootstrap.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/josemarluedke/Projects/Temp/demo-app-import/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

```
$ ember -v
version: 2.3.0-beta.1
node: 4.2.2
npm: 2.14.10
os: darwin x64
```

The app demonstrating the error can be found at https://github.com/josemarluedke/demo-app-import.

Question: Am I out of mind trying to use bootstrap-sass from npm? My thinking was that since we will be moving away from bower one day I would already try to use everything that is possible from npm.

Thanks.

**Comment by stefanpenner** [comment]
> Question: Am I out of mind trying to use bootstrap-sass from npm?

You are not out of your mind, but do to file-watching usually exploding if all of node_modules is watched, we do not yet currently support the basically `app.import` from node_modules. It should be documented that `app.import` only pulls form vendor and bower_component.

Please note, we do plan to allow this (or a very similar feature in the future), but until then I recommend using something like broccoli-funnel to pull files from NPM.

**Comment by josemarluedke** [comment]
:+1: Thanks for the quick response.

**Comment by CHIEFnChowCombo** [comment]
@stefanpenner but isn't the `ember-cli-build.js` file only for use in configuring the dummy app in your addon's `/tests` folder?  

If I am developing an addon, and wanted to ensure my node module dependency made it into the consuming applications dependencies, would I have to use a hook in my index.js and use a trick similar to the one you linked to above?

(I thought that and npm dependencies of your addon were automatically installed to the consuming application during `ember install addon-name`)? Or does that only work if the dependency is an another addon?

**Comment by runspired** [comment]
I opened an RFC issue to discuss a solution for this: https://github.com/ember-cli/rfcs/issues/84
