### ISSUE TITLE
ENOENT: no such file or directory, lstat 

### ISSUE THREAD

**Issue by IsaiahJTurner** [ember-cli/ember-cli#5424]
I have no idea what's happening, how to reproduce, or where to look to debug. Is this an `ember-cli` issue?
```
ENOENT: no such file or directory, lstat '/Users/IsaiahJTurner/Repositories/Podium/App/Ember/tmp/funnel-input_base_path-lwJ5WOVG.tmp/0//index.html'
Error: ENOENT: no such file or directory, lstat '/Users/IsaiahJTurner/Repositories/Podium/App/Ember/tmp/funnel-input_base_path-lwJ5WOVG.tmp/0//index.html'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync [as sync] (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (/Users/IsaiahJTurner/Repositories/Podium/App/Ember/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:249:9)
```

**Comment by IsaiahJTurner** [comment]
Update: solved by un-deleted the testem.json and tests folder. Still, could this error be made more informative?

**Comment by stefanpenner** [comment]
Please provide additional information, our [CONTRIBUTING.md](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md) outlines this further.

**Comment by Turbo87** [comment]
closing due to inactivity

**Comment by pocockn** [comment]
We just got this today while upgrading ember

:site:ember
The Broccoli Plugin: [Funnel: Funnel (styles)] failed with:
Error: ENOENT: no such file or directory, lstat '//ember/app/styles'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (src/ember/node_modules/symlink-or-copy/index.js:79:26)

**Comment by p4win** [comment]
just run  > ember init
after doing this, you  will get a option 'do you want to over right .ember-cli ?'
make ember-cli as 'yes'.

**Comment by Turbo87** [comment]
@p4win that sounds like a quite different issue. can you open a new issue for that with the full stack trace and error information?
