### ISSUE TITLE
potential issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5449]
leaving this as a TODO, need to investigate if this is an issue on master or not.

```
➜  es6-promise git:(master) ember test --server
version: 2.3.0-beta.1
Cannot read property 'writeDeprecateLine' of undefined
TypeError: Cannot read property 'writeDeprecateLine' of undefined
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/stefanpenner/src/es6-promise/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Class.module.exports.Task.extend.init (/Users/stefanpenner/src/es6-promise/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/stefanpenner/src/es6-promise/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Command.extend.run (/Users/stefanpenner/src/es6-promise/node_modules/ember-cli/lib/commands/test.js:133:25)
    at Class.<anonymous> (/Users/stefanpenner/src/es6-promise/node_modules/ember-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/Users/stefanpenner/src/es6-promise/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/stefanpenner/src/es6-promise/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/stefanpenner/src/es6-promise/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/stefanpenner/src/es6-promise/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:452:9)
```

**Comment by chadhietala** [comment]
Ran into this today. Forgot to report, I was using it in an addon.

**Comment by rwjblue** [comment]
This seems to indicate that `this.ui` isn't being passed in (since `writeDeprecateLine` is on `ui`).

@stefanpenner - Do you have a repro?

**Comment by stefanpenner** [comment]
> @stefanpenner - Do you have a repro?

I do, just finishing up some other work (which actually involves the reproduction).

**Comment by gmurphey** [comment]
@rwjblue @stefanpenner  https://github.com/gmurphey/ui-test

Added `Brocfile.js` to a bare addon to reproduce.

`ember test`: Displays deprecation correctly
`ember test --server`: Fails due to `this.ui` not being passed correctly

**Comment by stefanpenner** [comment]
> ember test --server: Fails due to this.ui not being passed correctly

ya what i also say, thanks. I will have time tonight to fix

**Comment by Turbo87** [comment]
it looks like the issue is that `ui` is not being passed into the `Builder` constructor at https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L133

should we just add `ui: this.ui` to the `testOptions` hash or does that have any undesired side effects? I've tested that change with the repo supplied by @gmurphey and it seems to work fine.

**Comment by rwjblue** [comment]
Should be correct to pass UI to builder there.
