### ISSUE TITLE
ENOENT: no such file or directory source_map_concat-input_base_path-qkwKZtmf.tmp\0\vendor\ember-components\vendor\ic-styled\main.js

### ISSUE THREAD

**Issue by kantecgee** [ember-cli/ember-cli#5569]
Hello,

I don't know why but I want to start the ember server (ember s) and I get this errormessage:

```
ENOENT: no such file or directory, stat 'D:\EmberJS\super-rentals\tmp\source_map_concat-input_base_path-qkwKZtmf.tmp\0\vendor\ember-components\vendor\ic-styled\main.js'
Error: ENOENT: no such file or directory, stat 'D:\EmberJS\super-rentals\tmp\source_map_concat-input_base_path-qkwKZtmf.tmp\0\vendor\ember-components\vendor\ic-styled\main.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:112:65)
    at D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\EmberJS\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

I can reinstall the package modules and after that I don't know what to do.
Nothing helps..

Have someone an idea?

**Comment by Turbo87** [comment]
@kantecgee can you provide instructions to reproduce this problem?

**Comment by stefanpenner** [comment]
When posted a new issue, you are prompted with a yellow banner suggesting to read the contributing.md before posting an issue. I recommend you do that, and upgrade the issue with the information it requests:

https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md
