### ISSUE TITLE
ember server/build broken on Windows

### ISSUE THREAD

**Issue by john-griffin** [ember-cli/ember-cli#5571]
Not sure what happening but when I take our app that runs and compiles fine on OS X over to Windows 10 we see the following error when trying to run build or server:

```
version: 2.4.1
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [object Object] failed with:
undefined

The broccoli plugin was instantiated at:
undefined
```

Is there anything more I can do to debug the problem?

**Comment by rwjblue** [comment]
I recently dealt with a similar looking error message (though I'm sure that many things could be `[Object object]`) and it resulted from using a legacy preprocessor (`broccoli-sass`, `broccoli-ruby-sass`, and `broccoli-stylus` are the only ones AFAIK).  Once I identified that `broccoli-sass` was causing the issue (and was not really supported) I removed support for styles plugins that do not provide their own `.toTree` methods in https://github.com/ember-cli/ember-cli-preprocessor-registry/pull/10.

Are you using a preprocessor like this (either the legacy ones I listed or one of your own added via `registry.add('css', 'some-string-here'`)?

**Comment by stefanpenner** [comment]
Can you provide a reproduction please?

But sure to read the contributing.md (the big yellow banner presented when posting an issue) as it request very specific information to make issues for actionable for maintainers

**Comment by john-griffin** [comment]
@stefanpenner @rwjblue Spent a while trying to identify what was causing this. Turns it happens when installing the `ember-fetch` addon. On Windows 10 with ember-cli 2.4.1, node 5.7.1, npm 3.6.0 run:

```
ember new foo
cd foo
ember install ember-fetch
ember server
```

`ember-fetch` is currently on version `1.2.2`.

**Comment by stefanpenner** [comment]
related: https://github.com/stefanpenner/ember-fetch/pull/10

**Comment by rohansp** [comment]
I was getting the same error while setting up a github project using ember server.I got the same error.
I tried steps provided by john-griffin. But, it doesn't work for me

**Comment by vlascik** [comment]
Same here, same config (w10, cli 2.4.2), but with `ember-network` addon.

**Comment by Itagiba** [comment]
I am getting the same problem. Trying to get ember to work with sass. The error gives me nothing  and build fails. I managed to install watchman properly in case it was related but I am still getting:

The Broccoli Plugin: [object Object] failed with:
undefined

The broccoli plugin was instantiated at: 
undefined

**Comment by devlo** [comment]
Same here. But it builds on development branch.

version: 2.4.2
Build failed.
File: assets/vendor.js (64148:8)
The Broccoli Plugin: [object Object] failed with:
Error
    at new JS_Parse_Error (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:1508:18)
    at js_error (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:1516:11)
    at croak (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2008:9)
    at token_error (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2016:9)
    at unexpected (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2022:9)
    at semicolon (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2042:43)
    at simple_statement (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2222:73)
    at eval (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2095:19)
    at eval (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2055:24)
    at block_ (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2335:20)
    at eval (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2308:25)
    at function_ (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2313:15)
    at expr_atom (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2521:24)
    at maybe_unary (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2691:19)
    at expr_ops (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2726:24)
    at maybe_conditional (eval at <anonymous> (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2731:20)

The broccoli plugin was instantiated at:
undefined

**Comment by stefanpenner** [comment]
> at new JS_Parse_Error (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :1508:18)

This is telling you, that there is invalid syntax attempting to be uglified. This is unlikely to be an issue with ember-cli, rather an issue with the code in the project.

**Comment by stefanpenner** [comment]
@Itagiba please provide a reproduction if you can.

**Comment by devlo** [comment]
@stefanpenner 

Indeed, thx. I've traced this error to ember-electron.

https://github.com/felixrieseberg/ember-electron/issues/50

**Comment by stefanpenner** [comment]
looks fixed ? https://github.com/felixrieseberg/ember-electron/issues/50#issuecomment-202591430

Will reopen if i mistunderstood
