### ISSUE TITLE
Build failed: The Broccoli Plugin: [Babel] failed with: SyntaxError: /package.json: Error while parsing JSON

### ISSUE THREAD

**Issue by shinkarevgv** [ember-cli/ember-cli#5600]
Hi,

My OS is Ubuntu

I read [user-guide](http://ember-cli.com/user-guide/#guide) and tried to create ember project.
The project 'my-new-app' had been generated:
```
version: 2.4.2
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Successfully initialized git.
Installed packages for tooling via npm.
Installed browser packages via Bower.
```
Then I've done:
```
cd my-new-app
ember test
```

Result:
```
version: 2.4.2
Build failed.
File: modules/ember-ajax/errors.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: /package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:94:21)
    at Babel.processString (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:123:25)
    at Promise.then.result.output (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at lib$rsvp$$internal$$initializePromise (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1084:9)
    at new lib$rsvp$promise$$Promise (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:546:53)
    at /home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at lib$rsvp$$internal$$tryCatch (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1019:11)

> The broccoli plugin was instantiated at: 
    at Babel.Plugin (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new Babel (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/home/george/my-new-app/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/home/george/my-new-app/node_modules/ember-cli-babel/index.js:21:52)
    at /home/george/my-new-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/home/george/my-new-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/home/george/my-new-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at Class.Addon.preprocessJs (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:710:23)
    at Class.Addon.processedAddonJsFiles (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:722:15)
    at Class.Addon.compileAddon (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:632:22)
    at Class.Addon.treeForAddon (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:403:24)
    at Class._treeFor (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/home/george/my-new-app/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /home/george/my-new-app/node_modules/ember-cli/lib/broccoli/ember-app.js:446:20
```

Can you help me with this issue?

**Comment by rwjblue** [comment]
From the error message, it seems that there is a malformed package.json (likely in /).

**Comment by shinkarevgv** [comment]
Hi

This's my package.json from my-new-app folder:

> 
{
  "name": "my-new-app",
  "version": "0.0.0",
  "description": "Small description for my-new-app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.4.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-load-initializers": "^0.5.0",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.0"
  }
}

**Comment by shinkarevgv** [comment]
I validated package.json. It's syntactically valid.

**Comment by stefanpenner** [comment]
The error looks to be in Babel. You may have a malformed Babel config somewhere?

**Comment by rwjblue** [comment]
FWIW, I was suggesting that the file at /package.json may be wrong (not the one in the project root).

**Comment by shinkarevgv** [comment]
Hi Robert,

I uploaded the archive with generated files into Dropbox:
https://www.dropbox.com/s/48okhchk3bxmohg/my-new-app.7z?dl=0
It's size approximately 21Mb. Could you please have a look at it? I will be very grateful for the help.

Thanks

**Comment by marcemira** [comment]
Hey guys, my package.json is fine. But I'm having the following error while trying to run ember server:
```
ember s
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [object Object] failed with:
undefined

The broccoli plugin was instantiated at: 
undefined
```
my package.json:
```
{
  "name": "my-project",
  "version": "0.0.0",
  "description": "Small description for diezpe goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-sass": "0.7.0",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.6.0-beta.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-css-preprocess": "0.0.8",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-fastboot": "0.6.2",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.6.0-beta.1",
    "ember-engines": "0.2.2",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-network": "0.3.0",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  },
  "ember-addon": {
    "paths": [
      "lib/main",
      "lib/dashboard"
    ]
  },
  "dependencies": {
    "autoprefixer": "^6.3.6"
  }
}
```

**Comment by stefanpenner** [comment]
> Hey guys, my package.json is fine. But I'm having the following error while trying to run ember server:

can you provide a repo on github that demonstrates the issue please.

**Comment by marcemira** [comment]
Solved it removing `broccoli-sass`. Wasn't using it actually..

**Comment by stefanpenner** [comment]
@marcemira can you share a basic repro that demonstrates this? My quick attempt did not demonstrate.

**Comment by nathanhammond** [comment]
I can't reproduce this and with no activity since May I am closing the issue as resolved.

**Comment by oligriffiths** [comment]
I'm seeing this same error since trying 2.16 beta

```
DEPRECATION: Addon files were detected in `/Users/oli/Projects/ember/lib/ember-data-actions/addon`, but no JavaScript preprocessors were found for `ember-data-actions`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-data-actions`'s `package.json`.
Livereload server on http://localhost:7020
The Broccoli Plugin: [broccoli-persistent-filter:EslintValidationFilter] failed with:
Error: Attempting to watch missing directory: /Users/oli/Projects/ember/lib/ember-data-actions/app
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/oli/Projects/ember/node_modules/ember-cli-broccoli-sane-watcher/index.js:142:11)
    at /Users/oli/Projects/ember/node_modules/broccoli-builder/lib/builder.js:135:35
    at tryCatch (/Users/oli/Projects/ember/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/oli/Projects/ember/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/oli/Projects/ember/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/oli/Projects/ember/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at EslintValidationFilter.Plugin (/Users/oli/Projects/ember/node_modules/broccoli-plugin/index.js:7:31)
    at EslintValidationFilter.Filter [as constructor] (/Users/oli/Projects/ember/node_modules/broccoli-persistent-filter/index.js:64:10)
    at new EslintValidationFilter (/Users/oli/Projects/ember/node_modules/broccoli-lint-eslint/lib/index.js:58:10)
    at Function.EslintValidationFilter.create (/Users/oli/Projects/ember/node_modules/broccoli-lint-eslint/lib/index.js:215:16)
    at Class.lintTree (/Users/oli/Projects/ember/node_modules/ember-cli-eslint/index.js:44:19)
    at project.addons.reduce (/Users/oli/Projects/ember/node_modules/ember-cli/lib/models/addon.js:407:26)
    at Array.reduce (native)
    at Class._eachProjectAddonInvoke (/Users/oli/Projects/ember/node_modules/ember-cli/lib/models/addon.js:404:32)
    at Class.jshintAddonTree (/Users/oli/Projects/ember/node_modules/ember-cli/lib/models/addon.js:1116:31)
    at Class.treeFor (/Users/oli/Projects/ember/node_modules/ember-cli/lib/models/addon.js:524:23)
```

Any ideas?

**Comment by TechGladiator** [comment]
I'm getting this error when I try to run `ember serve` in `cmd` or `powershell`. Works in Linux, and I can get it to work in Windows by running `cmd` or `powershell` with admin rights. Seems to just be a permissions issue on Windows.
