### ISSUE TITLE
Broken caching of addon JS files

### ISSUE THREAD

**Issue by EWhite613** [ember-cli/ember-cli#5667]
I don't think the caching of addon javascript files works as intended added here @rwjblue https://github.com/rwjblue/ember-cli/blame/17619b8f949a200122df62b7a14c66ea7e68f932/lib/models/addon.js#L684 . I have the an instance of the issue illustrated here: https://github.com/ciena-frost/ember-frost-icons/issues/26 

Using this code:
```
/**
  Returns a tree containing the addon's js files

  @private
  @method addonJsFiles
  @return {Tree} The filtered addon js files
*/
Addon.prototype.addonJsFiles = function(tree) {
  this._requireBuildPackages();

//  if (this._cachedAddonJsFiles) {
//    return this._cachedAddonJsFiles;
//  }
  console.log("\n===================================\nBefore include pattern:")
  console.log(JSON.stringify(this._cachedAddonJsFiles))
  var includePatterns = this.registry.extensionsForType('js').map(function(extension) {
    return new RegExp(extension + '$');
  });

  this._cachedAddonJsFiles = new Funnel(tree, {
    include: includePatterns,
    destDir: 'modules/' + this.moduleName(),
    description: 'Funnel: Addon JS'
  });
  console.log("\n\n +++++++++++++++++++++++++++++++++++++++++++++++++++++\nAfter include pattern:")
  console.log(JSON.stringify(this._cachedAddonJsFiles))
  return this._cachedAddonJsFiles;
};
```

The logs come out as this:
```
===================================
Before include pattern:
undefined


 +++++++++++++++++++++++++++++++++++++++++++++++++++++
After include pattern:
{
  "_instantiationStack": "    at Funnel.Plugin (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:44:10)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.jshintAddonTree (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:658:22)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:297:21)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon.EmberApp._processedAppTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:744:25)\n    at EmberAddon.EmberApp.appAndDependencies (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1014:10)",
  "_name": "Funnel",
  "_baseConstructorCalled": true,
  "_inputNodes": [
    "\/localdisk\/workspace\/ember-frost-icons\/addon"
  ],
  "_persistentOutput": true,
  "_includeFileCache": {
    
  },
  "_destinationPathCache": {
    
  },
  "_currentTree": {
    "entries": {
      "__id__": "relativePath",
      "size": 0
    }
  },
  "include": [
    {
      
    }
  ],
  "destDir": "modules\/ember-frost-icons",
  "description": "Funnel: Addon JS",
  "count": 0,
  "_matchedWalk": false,
  "_instantiatedStack": "Error\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:89:30)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.jshintAddonTree (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:658:22)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:297:21)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon.EmberApp._processedAppTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:744:25)\n    at EmberAddon.EmberApp.appAndDependencies (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1014:10)\n    at EmberAddon.EmberApp.javascript (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1137:34)"
}
===================================
Before include pattern:
{
  "_instantiationStack": "    at Funnel.Plugin (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:44:10)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.jshintAddonTree (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:658:22)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:297:21)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon.EmberApp._processedAppTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:744:25)\n    at EmberAddon.EmberApp.appAndDependencies (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1014:10)",
  "_name": "Funnel",
  "_baseConstructorCalled": true,
  "_inputNodes": [
    "\/localdisk\/workspace\/ember-frost-icons\/addon"
  ],
  "_persistentOutput": true,
  "_includeFileCache": {
    
  },
  "_destinationPathCache": {
    
  },
  "_currentTree": {
    "entries": {
      "__id__": "relativePath",
      "size": 0
    }
  },
  "include": [
    {
      
    }
  ],
  "destDir": "modules\/ember-frost-icons",
  "description": "Funnel: Addon JS",
  "count": 0,
  "_matchedWalk": false,
  "_instantiatedStack": "Error\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:89:30)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.jshintAddonTree (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:658:22)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:297:21)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon.EmberApp._processedAppTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:744:25)\n    at EmberAddon.EmberApp.appAndDependencies (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1014:10)\n    at EmberAddon.EmberApp.javascript (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:1137:34)"
}

 +++++++++++++++++++++++++++++++++++++++++++++++++++++
After include pattern:
{
  "_instantiationStack": "    at Funnel.Plugin (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:44:10)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.processedAddonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:724:33)\n    at Class.Addon.compileAddon (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:632:22)\n    at Class.Addon.treeForAddon (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:403:24)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:53:37)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20",
  "_name": "Funnel",
  "_baseConstructorCalled": true,
  "_inputNodes": [
    {
      "_instantiationStack": "    at BroccoliMergeTrees.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:29:10)\n    at BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:23:53)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:50:14)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)",
      "_name": "BroccoliMergeTrees",
      "_baseConstructorCalled": true,
      "_inputNodes": [
        {
          "_directoryPath": "\/localdisk\/workspace\/ember-frost-icons\/addon",
          "_watched": true,
          "_name": "WatchedDir",
          "_instantiationStack": "    at WatchedDir.Directory (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-source\/index.js:14:31)\n    at new WatchedDir (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-source\/index.js:58:13)\n    at Class.Addon.treeGenerator (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:258:12)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:318:17)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)"
        },
        {
          "inputTree": {
            "_instantiationStack": "    at Funnel.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new Funnel (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-funnel\/index.js:44:10)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:23)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)",
            "_name": "Funnel",
            "_baseConstructorCalled": true,
            "_inputNodes": [
              {
                "_instantiationStack": "    at BroccoliMergeTrees.Plugin (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-plugin\/index.js:7:31)\n    at new BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:29:10)\n    at BroccoliMergeTrees (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-merge-trees\/index.js:23:53)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:34)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)",
                "_name": "BroccoliMergeTrees",
                "_baseConstructorCalled": true,
                "_inputNodes": [
                  "\/localdisk\/workspace\/ember-frost-icons\/public\/svgs",
                  "\/localdisk\/workspace\/ember-frost-icons\/tests\/dummy\/public\/svgs"
                ],
                "_persistentOutput": true,
                "options": {
                  "overwrite": true
                },
                "_buildCount": 0,
                "_currentTree": {
                  "entries": {
                    "__id__": "relativePath",
                    "size": 0
                  }
                }
              }
            ],
            "_persistentOutput": true,
            "_includeFileCache": {
              
            },
            "_destinationPathCache": {
              
            },
            "_currentTree": {
              "entries": {
                "__id__": "relativePath",
                "size": 0
              }
            },
            "include": [
              {
                
              }
            ],
            "destDir": "\/",
            "count": 0,
            "_matchedWalk": false,
            "_instantiatedStack": "Error\n    at new Funnel (\/localdisk\/workspace\/ember-frost-icons\/node_modules\/broccoli-funnel\/index.js:89:30)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:41:23)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)\n    at EmberAddon.EmberApp.addonTreesFor (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:444:30)\n    at EmberAddon._addonTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:849:36)\n    at EmberAddon.EmberApp._processedVendorTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:894:20)\n    at EmberAddon.EmberApp._processedExternalTree (\/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:925:21)"
          },
          "options": {
            "outputFile": "svgs.js",
            "trimExtensions": true
          }
        }
      ],
      "_persistentOutput": true,
      "options": {
        "overwrite": true
      },
      "_buildCount": 0,
      "_currentTree": {
        "entries": {
          "__id__": "relativePath",
          "size": 0
        }
      }
    }
  ],
  "_persistentOutput": true,
  "_includeFileCache": {
    
  },
  "_destinationPathCache": {
    
  },
  "_currentTree": {
    "entries": {
      "__id__": "relativePath",
      "size": 0
    }
  },
  "include": [
    {
      
    }
  ],
  "destDir": "modules\/ember-frost-icons",
  "description": "Funnel: Addon JS",
  "count": 0,
  "_matchedWalk": false,
  "_instantiatedStack": "Error\n    at new Funnel (\/localdisk\/workspace\/ember-cli\/node_modules\/broccoli-funnel\/index.js:89:30)\n    at Class.Addon.addonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:693:30)\n    at Class.Addon.processedAddonJsFiles (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:724:33)\n    at Class.Addon.compileAddon (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:632:22)\n    at Class.Addon.treeForAddon (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:403:24)\n    at Class.module.exports.treeForAddon (\/localdisk\/workspace\/ember-frost-icons\/index.js:53:37)\n    at Class._treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:322:31)\n    at Class.treeFor (\/localdisk\/workspace\/ember-cli\/lib\/models\/addon.js:290:19)\n    at \/localdisk\/workspace\/ember-cli\/lib\/broccoli\/ember-app.js:446:20\n    at Array.map (native)"
}
```

So when the caching takes effect, rather than taking the new AddonJSFiles it returns the cached version which don't include the required broccoli outputted files.

**Comment by Turbo87** [comment]
I think this has been solved by https://github.com/ember-cli/ember-cli/pull/5867
