### ISSUE TITLE
Fix `ember g template` when in an addon.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#5687]
We are currently generating the following structure:

```
addon/templates/foo.hbs
app/templates/foo.js // <- just imports/reexports
```

But this makes it impossible for the template compiler in an app to override the addon template in an app.

An error like the following is thrown:

```
Build failed.
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: EEXIST: file already exists, symlink '/Users/nathanhammond/Repos/ember-cli/tmp/some-cool-app/lib/my-addon/app/templates/foo.js' -> '/Users/nathanhammond/Repos/ember-cli/tmp/some-cool-app/tmp/template_compiler-output_path-PL2KRC70.tmp/some-cool-app/templates/foo.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at symlink (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/symlink-or-copy/index.js:82:14)
    at symlinkOrCopySync (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/symlink-or-copy/index.js:58:5)
    at TemplateCompiler.Filter._handleFile (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/index.js:101:12)
    at TemplateCompiler.<anonymous> (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/index.js:88:21)
    at /Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1019:11)
The broccoli plugin was instantiated at: 
    at TemplateCompiler.Plugin (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new TemplateCompiler (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/index.js:20:10)
    at TemplateCompiler (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/index.js:12:12)
    at Object.registry.add.toTree (/Users/nathanhammond/Repos/ember-cli/.node_modules-tmp/ember-cli-htmlbars/ember-addon-main.js:31:16)
    at /Users/nathanhammond/Repos/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/nathanhammond/Repos/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessTemplates (/Users/nathanhammond/Repos/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:165:10)
    at EmberApp._processedTemplatesTree (/Users/nathanhammond/Repos/ember-cli/lib/broccoli/ember-app.js:802:48)
```

Steps to reproduce the error (using ember-cli 2.4.2 + changes from #5591): 

```
ember new foo
cd foo
ember g template post
ember g in-repo-addon my-addon
ember g template post --in-repo-addon=my-addon
```

---

We can either change the way the generator works, or we can fix broccoli-persistent-filter (around [here](https://github.com/stefanpenner/broccoli-persistent-filter/blob/master/index.js#L101)) and broccoli-filter (around [here](https://github.com/broccolijs/broccoli-filter/blob/master/index.js#L72)) to detect `EEXIST` and remove the file then reattempt the symlink.

@stefanpenner - Which do you think is the correct path?  I'd say fixing broccoli-filter/broccoli-persistent-filter, but I'm not certain...

**Comment by trabus** [comment]
So regarding the generator, we have a way to "blacklist" blueprints from generating the addon-import. Currently we use [this array](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/generate-from-blueprint.js#L17) to determine if a blueprint shouldn't generate an addon import, and we could simply add `template` to this array and it would fix this.

However, I've been wanting to change the way a blueprint determines what gets generated in what context for a while, so this could be that opportunity to fix it. Either way, I'm down to pick up the work on this one.

**Comment by adam-bc** [comment]
Any more thoughts on a possible solution for this? As a workaround, moving templates into the app directory of my addon so they can be overwritten by the consuming application works fine. Still debating the best workaround for addons I don’t manage.

**Comment by ro0gr** [comment]
Looks like similar issue #5336 . In fact  it's applicable not only for `.hbs` but for  `.coffee`, `.ts`,.. files too. So I would vote on fixing of broccoli stuff proposed by @rwjblue .

**Comment by stefanpenner** [comment]
i believe this is addressed by https://github.com/stefanpenner/fs-tree-diff/pull/16/commits/8a8cf1560298f4e48f7746bbdc7a1898fe3460a2  Will reopen if it is not
