### ISSUE TITLE
missing tether bower dependency after upgrade from 2.4.2 to 2.4.3

### ISSUE THREAD

**Issue by bgentry** [ember-cli/ember-cli#5760]
I just tried to update a fairly new app from ember-cli 2.4.2 to 2.4.3. I followed the upgrade instructions, including the diffs (especially for `package.json` and `bower.json`). After all of that, I get this failure on `ember serve`:

```
➜  myapp-ember git:(master) ✗ ember serve 
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/bgentry/Code/myapp-ember/tmp/source_map_concat-input_base_path-BnBIGWHL.tmp/0/bower_components/tether/dist/js/tether.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at: 
    at ConcatWithMaps.Plugin (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
    at EmberApp.javascript (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
    at EmberApp.toArray (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/Users/bgentry/Code/myapp-ember/ember-cli-build.js:24:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/models/builder.js:55:19)
```

Here is my package.json:

```json
{
  "name": "myapp-ember",
  "version": "0.0.0",
  "description": "Small description for myapp-ember goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-bootstrap-4": "0.1.0",
    "ember-cli": "2.4.3",
    "ember-cli-active-link-wrapper": "0.1.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "0.6.0",
    "ember-cli-deploy-aws-pack": "0.3.4",
    "ember-cli-file-picker": "0.0.9",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-imgix": "0.3.0",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-mirage": "0.1.11",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "2.1.0",
    "ember-load-initializers": "^0.5.1",
    "ember-lodash": "levanto-financial/ember-lodash#lodash-es-4.6.1",
    "ember-moment": "6.1.0",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0-beta.3",
    "ember-suave": "2.0.1",
    "ember-uploader": "1.0.0",
    "loader.js": "^4.0.1",
    "torii": "^v0.8.0-beta.1"
  }
}
```

And my bower.json:

```json
{
  "name": "myapp-ember",
  "dependencies": {
    "ember": "~2.4.3",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "pretender": "~0.10.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "imgix-core-js": "1.0.3",
    "urijs": "~1.16.1",
    "font-awesome": "~4.5.0"
  }
}
```

Notably, if I `bower install --save tether`, everything works again. That results in the following bower.json:

```json
{
  "name": "myapp-ember",
  "dependencies": {
    "ember": "~2.4.3",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "tether": "^1.2.0",
    "pretender": "~0.10.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "imgix-core-js": "1.0.3",
    "urijs": "~1.16.1",
    "font-awesome": "~4.5.0"
  }
}
```

I've gone through the entire upgrade process step-by-step several times, and I still get the same results. Seems there's maybe a missing dependency declaration from one of the broccoli subpackages?

```
$ ember version
ember-cli: 2.4.3
node: 4.4.2
os: darwin x64
```

Please let me know if there's any other info you need from me to help sort this out :v:

**Comment by Turbo87** [comment]
@bgentry could you maybe find out which one of your dependencies is using/missing tether?

**Comment by stefanpenner** [comment]
reproduction would be quite handy.

**Comment by bgentry** [comment]
Very sorry for the trouble, this was due to https://github.com/bennycwong/ember-bootstrap-4 which has some dependencies set up improperly (asking folks to manually add dependencies instead of doing so when the addon is installed).
