### ISSUE TITLE
ENOENT after a restart

### ISSUE THREAD

**Issue by VincentMolinie** [ember-cli/ember-cli#5820]
Hi guys, 

I'm stuck on an issue. I can't run any ember project, even when I create a fresh new one.
Everything was working yesterday. The only thing I did is removing node_modules and bower_components on a project and installing everything again and since nothing work.
I tried to do:
```
rm -rf node_modules bower_components tmp dist
npm cache clear
bower cache clean
npminstall && bower install && ember serve
```
It didn't worked so I tried to reinstall NodeJS by removing first %appdata%/npm %appdata%/npm-cache and the nodejs folder. Still nothing. I also tried to restart my computer...

I'm just out of ideas, can someone save me ?

All the folders like template_* are not been created in tmp folder...

```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: modules/ember-cli-app-version/templates/app-version.hbs
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: ENOENT: no such file or directory, open 'D:\Project\test-node\tmp\template_compiler-input_base_path-wEbiY684.tmp\0\modules\ember-cli-app-version\templates\app-version.hbs'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at TemplateCompiler.Filter.processFile (D:\Project\test-node\node_modules\broccoli-persistent-filter\index.js:197:21)
    at asyncProcessFile (D:\Project\test-node\node_modules\broccoli-persistent-filter\index.js:169:23)
    at lib$rsvp$$internal$$tryCatch (D:\Project\test-node\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Project\test-node\node_modules\rsvp\dist\rsvp.js:505:17)
    at D:\Project\test-node\node_modules\rsvp\dist\rsvp.js:1001:13
    at lib$rsvp$asap$$flush (D:\Project\test-node\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

The broccoli plugin was instantiated at:
    at TemplateCompiler.Plugin (D:\Project\test-node\node_modules\broccoli-plugin\index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (D:\Project\test-node\node_modules\broccoli-persistent-filter\index.js:38:10)
    at new TemplateCompiler (D:\Project\test-node\node_modules\ember-cli-htmlbars\index.js:20:10)
    at TemplateCompiler (D:\Project\test-node\node_modules\ember-cli-htmlbars\index.js:12:12)
    at Object.registry.add.toTree (D:\Project\test-node\node_modules\ember-cli-htmlbars\ember-addon-main.js:31:16)
    at D:\Project\test-node\node_modules\ember-cli-preprocess-registry\preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (D:\Project\test-node\node_modules\ember-cli-preprocess-registry\preprocessors.js:182:11)
    at module.exports.preprocessTemplates (D:\Project\test-node\node_modules\ember-cli-preprocess-registry\preprocessors.js:165:10)
    at Class.Addon.compileTemplates (D:\Project\test-node\node_modules\ember-cli\lib\models\addon.js:632:12)
```
---

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: win32 x64
```

**Comment by stefanpenner** [comment]
> Error: ENOENT: no such file or directory, open 'D:\Project\test-node\tmp\template_compiler-input_base_path-wEbiY684.tmp\0\modules\ember-cli-app-version\templates\app-version.hbs'

does a file exists `ember-cli-app-version\templates\app-version.hbs` in your node_modules?

**Comment by ro0gr** [comment]
I've also noticed the same issue on the my team mate machine. It started to happen today(after update to ember-cli@2.4.3). Unfortunately I'd failed to reproduce it on my machine even after cleaning npm cache.

> does a file exists ember-cli-app-version\templates\app-version.hbs in your node_modules?

Yes it exists under the `node_modules/ember-cli-app-version/addon/templates/app-version.hbs` as expected.

**Comment by VincentMolinie** [comment]
Yeah the files is there ...

**Comment by VincentMolinie** [comment]
I tried to put a readdir before, the file is clearly here but on the read it crashed

**Comment by ro0gr** [comment]
Looks like the problem is somehow related to the latest release of `node-symlink-or-copy`. 
Locking it to `node-symlink-or-copy@1.0.1` fixed this issue for me

**Comment by VincentMolinie** [comment]
Oh my god it's that  ! 24hours on this bug ! Thank you @ro0gr you rock =)

**Comment by stefanpenner** [comment]
node-symlink-or-copy@1.1.2 should address

**Comment by tracyhyq** [comment]
what's the meaning?

**Comment by nathanhammond** [comment]
@tracyhyq We updated a dependency that fixed this underlying issue. `npm ls node-symlink-or-copy` in your application should tell you if you're using the updated and fixed version.
