### ISSUE TITLE
cant install new app

### ISSUE THREAD

**Issue by orgilnm11** [ember-cli/ember-cli#5825]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---
ember-cli: 2.5.0
node: 4.4.3
os: win32 x64

$ ember new myapp1
Cannot find module 'ini'
Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\owner.owner\AppData\Roaming\npm\node_modules\ember-cli\node_modules\npm\node_modules\config-chain\index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by nathanhammond** [comment]
This appears to be a broken installation. Can you reinstall ember-cli? If the issue persists clearing your npm cache may help as well. I'm going to close this as I don't believe that this is a persistent issue. If the problem still exists for you after reinstallation please feel encouraged to reopen!
