### ISSUE TITLE
Error: ENOENT: no such file or directory after live reload

### ISSUE THREAD

**Issue by julkiewicz** [ember-cli/ember-cli#5857]
I get the following build error after changing any file in my Ember-CLI project:

```
Build error

lex43/app/lex43/search/loading/route.js (in /Users/julk/Documents/Projects/mrcerti/mrcerti-lex/tmp/babel-input_base_path-udwPXmGS.tmp/0)

The Broccoli Plugin: [Babel] failed with:
Error: ENOENT: no such file or directory, open '/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/tmp/babel-output_path-0vhfldbY.tmp/lex43/app/lex43/search/loading/route.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Babel.asyncOutputFilteredFile (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:216:23)
    at lib$rsvp$$internal$$tryCatch (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new Babel (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:34:10)
    at Babel (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:29:12)
    at Object.registry.add.toTree (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli-babel/index.js:21:52)
    at /Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessJs (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at EmberApp.appAndDependencies (/Users/julk/Documents/Projects/mrcerti/mrcerti-lex/node_modules/ember-cli/lib/broccoli/ember-app.js:1044:25)
```

It's on OS X. I installed latest Node.js & NPM package installer from the node website (v 4.4.3 LTS)

The project has the following dependencies: 

```
npm ls --depth=0
mrcerti-lex@0.0.0 /Users/julk/Documents/Projects/mrcerti/mrcerti-lex
├── broccoli-asset-rev@2.4.2
├── broccoli-funnel@0.2.15
├── broccoli-merge-trees@1.1.1
├── broccoli-stew@1.2.0
├── broccoli-string-replace@0.1.1
├── ember-ajax@0.7.1
├── ember-cli@2.5.0
├── ember-cli-app-version@1.0.0
├── ember-cli-babel@5.1.6
├── ember-cli-dependency-checker@1.2.0
├── ember-cli-htmlbars@1.0.5
├── ember-cli-htmlbars-inline-precompile@0.3.1
├── ember-cli-inject-live-reload@1.4.0
├── ember-cli-jshint@1.0.0
├── ember-cli-qunit@1.4.1
├── ember-cli-release@0.2.8
├── ember-cli-sass@5.3.1
├── ember-cli-sri@2.1.0
├── ember-cli-uglify@1.2.0
├── ember-export-application-global@1.0.5
├── ember-load-initializers@0.5.1
├── ember-meta-meta@0.2.0
├── ember-model@0.0.18 (git+https://github.com/julkiewicz/ember-cli-ember-model.git#86b75ea0f55ea08d1107e9750126c6a75f9827d7)
├── ember-resolver@2.0.3
├── loader.js@4.0.3
└── optimist@0.6.1
```

The package installed from git is just some very slight modification of the latest vanilla ember-model that can be found online.

The Ember CLI version

```
ember --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.5.0
node: 4.4.3
os: darwin x64
```

**Comment by julkiewicz** [comment]
Not exactly sure if that was the root cause, however I found one missing dependency in ember-cli-build. After installing it, the build process seems to reload correctly after file changes.

**Comment by stefanpenner** [comment]
> After installing it, the build process seems to reload correctly after files change.

i suspect a broken or out of date node_modules tree. Good that you found a mysterious work around. If it comes up, please try to provide a reproduction (either publicly, or ping drop by dev-ember-cli on slack and maybe someone has time and you can provide the app privately so it can be debugged).

**Comment by maerten** [comment]
I get the same error when taking the following reproducible steps:

[starting with a ember project that compiles without problems]
1. create a little syntax error in a .js file e.g. "somefile.js" (i just removed a closing parenthesis somewhere)
2. start 'ember serve'

    The Broccoli Plugin: [Babel] failed with:
    SyntaxError: myproject/routes/somefile.js: Unexpected token (14:75)

3. fix the syntax mistake in somefile.js, ember reloads automatically and it shows a 'missing file error'

file changed routes/somefile.js
File: myproject/routes/somefile.js
The Broccoli Plugin: [Babel] failed with:
Error: ENOENT: no such file or directory, open ..................somefile.js


When i stop and start 'ember serve', it starts without problems.
Using ember-cli 2.4.3, node 5.10.1
This project was created with newest dependencies about 2 weeks ago, I will report back if the problems persist when dependencies will be updated (sometime next week).

**Comment by stefanpenner** [comment]
@maerten ya that's a different issue, I am aware of it. Hopefully will have time this week to address

**Comment by ob7** [comment]
Anyone know how to get ember server to stop throwing the broccoli 
Error: ENOENT: no such file or directory, unlink '/home/user/Ember Site/tmp/funnel-output_path-1wVDODbA.tmp/styles/.#app.scss'

everytime a file is deleted?

My text editor makes a swap file whenever the file is being edited, ember server picks up that there is a new file... then as soon as I'm done editing it and its saved, the swap is removed and ember throws a build error wanting the file to be unlinked.  Why cant the file unlink itself?  I have to force refresh the browser ( but not ember server itself)

**Comment by stefanpenner** [comment]
@rwjblue you also use emacs, which I believe does similar things.

**Comment by jacksonrayhamilton** [comment]
Hi, also seeing this error in Emacs when Ember picks up a ".#tempfile":

```
file changed templates/components/media-widget.hbs
ENOENT: no such file or directory, stat '/path/to/project/app/components/.#media-widget.js'
Error: ENOENT: no such file or directory, stat '/path/to/project/app/components/.#media-widget.js'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.realpathSync (fs.js:1679:12)
    at symlink (/path/to/project/node_modules/symlink-or-copy/index.js:68:26)
    at Function.symlinkOrCopySync [as sync] (/path/to/project/node_modules/symlink-or-copy/index.js:55:5)
    at Funnel._copy (/path/to/project/node_modules/broccoli-funnel/index.js:433:19)
    at Funnel.processFile (/path/to/project/node_modules/broccoli-funnel/index.js:416:8)
    at Funnel.applyPatch [as _applyPatch] (/path/to/project/node_modules/broccoli-funnel/index.js:333:12)
    at Funnel.<anonymous> (/path/to/project/node_modules/broccoli-funnel/index.js:287:10)
    at Array.forEach (native)
file changed components/media-widget.js
ENOENT: no such file or directory, unlink '/path/to/project/tmp/funnel-output_path-E2z8xcfM.tmp/components/.#media-widget.js'
Error: ENOENT: no such file or directory, unlink '/path/to/project/tmp/funnel-output_path-E2z8xcfM.tmp/components/.#media-widget.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at Funnel.applyPatch [as _applyPatch] (/path/to/project/node_modules/broccoli-funnel/index.js:311:10)
    at Funnel.<anonymous> (/path/to/project/node_modules/broccoli-funnel/index.js:287:10)
    at Array.forEach (native)
    at Funnel.processFilters (/path/to/project/node_modules/broccoli-funnel/index.js:286:11)
    at Funnel.build (/path/to/project/node_modules/broccoli-funnel/index.js:202:10)
    at /path/to/project/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/path/to/project/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/path/to/project/node_modules/rsvp/dist/rsvp.js:553:13)
```

Reminds me of [this problem](https://github.com/gruntjs/grunt-contrib-watch/issues/239).

**Comment by stefanpenner** [comment]
@rwjblue you use emacs, whats the magic enchantation to get emacs to not spew broken symlinks around?

**Comment by stefanpenner** [comment]
@rwjblue we could also make symlink-or-copy just noop failed stats like this, not much else it can do.

**Comment by stefanpenner** [comment]
@jacksonrayhamilton the issue above is closed, i believe configuring emacs to play nicely is documented here: https://ember-cli.com/user-guide/#emacs if that is not sufficient please open a new issue.
