### ISSUE TITLE
Unable to run `ember init` in v2.6.0-beta.2

### ISSUE THREAD

**Issue by stevenwu** [ember-cli/ember-cli#5866]
Running `ember init` gives me `Cannot read property 'discoverChildAddons' of undefined`
.

ember-cli: 2.6.0-beta.2
node: 6.0.0
os: darwin x64
npm: 3.8.8

---

Output from ember version --verbose:
```
Cannot read property 'discoverChildAddons' of undefined
TypeError: Cannot read property 'discoverChildAddons' of undefined
    at CoreObject.extend.discoverAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addon.js:205:41)
    at CoreObject.extend.initializeAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addon.js:218:10)
    at /Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addons-factory.js:48:17
    at visit (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at visit (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at DAG.topsort (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at CoreObject.extend.initializeAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addons-factory.js:42:11)
    at Project.initializeAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/project.js:379:36)
    at Project.eachAddonCommand (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/project.js:430:10)
    at module.exports (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)

```

**Comment by stefanpenner** [comment]
> Running ember init

in what context is this being run.

**Comment by stevenwu** [comment]
I'm running it as part of the Project Update steps in upgrading cli versions.

**Comment by Turbo87** [comment]
@stevenwu this most likely isn't related but could you check whether it works with node 5.x?

**Comment by stevenwu** [comment]
@Turbo87 I tried it with node 5.11.0 and npm 3.8.7, and it's the same error. There are no issues if I start a new project with beta1 and upgrade to `v2.6.0-beta.2`.

**Comment by Turbo87** [comment]
from what previous version did you upgrade?

**Comment by stevenwu** [comment]
v2.6.0-beta.1

**Comment by rwjblue** [comment]
@stevenwu - can you print the output of `npm ls core-object` for us?

**Comment by stevenwu** [comment]
@rwjblue 
```
noovis-app2-ember2@0.0.0 /Users/steve/work/noovis-ui
├─┬ ember-charts@1.0.0
│ └─┬ ember-cli-less@1.3.3
│   └─┬ broccoli-less-single@0.3.0
│     └─┬ broccoli-caching-writer@0.5.5
│       └── core-object@0.0.3
├─┬ ember-cli@2.6.0-beta.2
│ ├── core-object@2.0.0
│ └─┬ ember-try@0.2.2
│   └── core-object@1.1.0
├─┬ ember-cli-deploy@0.5.1
│ └── core-object@0.0.2
└─┬ ember-pagefront@0.11.1
  ├─┬ ember-cli-deploy-build@0.1.0
  │ └─┬ ember-cli-deploy-plugin@0.2.0
  │   └── core-object@0.0.2
  ├─┬ ember-cli-deploy-gzip@0.1.0 (git://github.com/pagefront/ember-cli-deploy-gzip.git#0a98e80768d089ea6488b36f2c9a79f95067d71d)
  │ └── core-object@1.1.0
  ├─┬ ember-cli-deploy-manifest@0.1.0 (git://github.com/pagefront/ember-cli-deploy-manifest.git#d6fdad23a5bf472317f1b46d9a4c3715c)
  │ └── core-object@1.1.0
  ├─┬ ember-cli-deploy-pagefront@0.5.5
  │ └── core-object@1.1.0
  └─┬ ember-cli-deploy-revision-data@0.1.0
    └── core-object@1.1.0
```

I've also created a project with the same packages here https://github.com/stevenwu/demo-2.6.0-beta.2

**Comment by rwjblue** [comment]
Can you tell me what the version is in `node_modules/core-object/package.json`?

**Comment by stevenwu** [comment]
0.0.3?
```
{
  "_args": [
    [
      "core-object@0.0.3",
      "/Users/steve/work/noovis-ui/node_modules/broccoli-caching-writer"
    ]
  ],
  "_from": "core-object@0.0.3",
  "_id": "core-object@0.0.3",
  "_inCache": true,
  "_installable": true,
  "_location": "/core-object",
  "_nodeVersion": "0.10.33",
  "_npmUser": {
    "email": "alex.navasardyan@gmail.com",
    "name": "twokul"
  },
  "_npmVersion": "2.1.9",
  "_phantomChildren": {},
  "_requested": {
    "name": "core-object",
    "raw": "core-object@0.0.3",
    "rawSpec": "0.0.3",
    "scope": null,
    "spec": "0.0.3",
    "type": "version"
  },
  "_requiredBy": [
    "/broccoli-caching-writer"
  ],
  "_resolved": "https://registry.npmjs.org/core-object/-/core-object-0.0.3.tgz",
  "_shasum": "550821598b258a33a8c2263afa072b0df5295321",
  "_shrinkwrap": null,
  "_spec": "core-object@0.0.3",
  "_where": "/Users/steve/work/noovis-ui/node_modules/broccoli-caching-writer",
  "author": {
    "name": "Ember core team and ember cli contributors"
  },
  "bugs": {
    "url": "https://github.com/stefanpenner/core_object/issues"
  },
  "dependencies": {
    "lodash-node": "^2.4.1"
  },
  "description": "A lightweight implementation of OOP Class in JavaScript",
  "devDependencies": {
    "mocha": "^1.21.4"
  },
  "directories": {},
  "dist": {
    "shasum": "550821598b258a33a8c2263afa072b0df5295321",
    "tarball": "https://registry.npmjs.org/core-object/-/core-object-0.0.3.tgz"
  },
  "gitHead": "a1fc46e1aec16bde53a0ec4580a893da3a4d9ae3",
  "homepage": "https://github.com/stefanpenner/core_object",
  "license": "MIT",
  "main": "core-object.js",
  "maintainers": [
    {
      "email": "alex.navasardyan@gmail.com",
      "name": "twokul"
    }
  ],
  "name": "core-object",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/stefanpenner/core_object.git"
  },
  "scripts": {
    "test": "mocha tests/**/*-test.js"
  },
  "version": "0.0.3"
}
```

**Comment by stefanpenner** [comment]
That looks ancient. Maybe some old/broken dep?

**Comment by rwjblue** [comment]
@stefanpenner - I believe that 0.0.3 was what was used by ember-cli through 2.6.0-beta.1 (we bumped to 2.0.0 in -beta.2).

@stevenwu - Can you clear node_modules and do a fresh npm install?

**Comment by stefanpenner** [comment]
> @stefanpenner - I believe that 0.0.3 was what was used by ember-cli through 2.6.0-beta.1 (we bumped to 2.0.0 in -beta.2).

ah ok

**Comment by stefanpenner** [comment]
seems like 0.0.2 https://github.com/ember-cli/ember-cli/blob/v2.6.0-beta.1/package.json#L60 ... still strange, cloning the example repo now.

**Comment by stefanpenner** [comment]
\w debugging flags it suggests the issue is something between ember-cli + ember-font-awesome (likely the core-object upgrade) going to look forward, but removing that dependency results in no issue..

```
  ...
  ember-cli:addon initializeAddons for: ember-font-awesome +1ms
Cannot read property 'discoverChildAddons' of undefined
TypeError: Cannot read property 'discoverChildAddons' of undefined
    at CoreObject.extend.discoverAddons (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/em
    at CoreObject.extend.initializeAddons (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/
    at /Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/ember-cli/lib/models/addons-factory.
    at visit (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/ember-cli/lib/utilities/DAG.j
    at visit (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/ember-cli/lib/utilities/DAG.j
    at DAG.topsort (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/ember-cli/lib/utilities
    at CoreObject.extend.initializeAddons (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/
    at Project.initializeAddons (/Users/stefanpenner/tmp/demo-2.6.0-beta.2/node_modules/ember-cli/
    at Project.eachAddonCommand (/Users/stefanpenner/tmp/dem
```

**Comment by stefanpenner** [comment]
https://github.com/martndemus/ember-font-awesome/pull/91 fixes the issue in font-awesome

**Comment by stefanpenner** [comment]
Alright, I think i've gotten to the bottom of it.

https://github.com/ember-cli/core-object/pull/32 but that has exposed some more issues, which i'm investigating now
