### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by luaecliper** [ember-cli/ember-cli#5871]
Serer set up log:
```
login as: root
root@107.170.6.151's password:
You are required to change your password immediately (root enforced)
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Apr 29 22:18:17 EDT 2016

  System load: 0.0               Memory usage: 9%   Processes:       53
  Usage of /:  7.6% of 19.56GB   Swap usage:   0%   Users logged in: 0

  Graph this data and manage this system at:
    https://landscape.canonical.com/

Changing password for root.
(current) UNIX password:
Enter new UNIX password:
Retype new UNIX password:
Bad: new password is too simple
Enter new UNIX password:
Retype new UNIX password:
root@node-512mb-nyc2-01:~# npm

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.1 /usr/lib/node_modules/npm
root@node-512mb-nyc2-01:~# npm install -g ember-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
Killed
root@node-512mb-nyc2-01:~# ember
No command 'ember' found, did you mean:
 Command 'enber' from package 'asn1c' (universe)
ember: command not found
root@node-512mb-nyc2-01:~# sudo npm install -g ember-cli
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/bin/ember -> /usr/lib/node_modules/ember-cli/bin/ember
ember-cli@2.5.0 /usr/lib/node_modules/ember-cli
├── ember-cli-test-info@1.0.0
├── ember-cli-path-utils@1.0.0
├── ember-cli-is-package-missing@1.0.0
├── ember-cli-string-utils@1.0.0
├── clean-base-url@1.0.0
├── ember-cli-normalize-entity-name@1.0.0
├── silent-error@1.0.0
├── fs-monitor-stack@1.1.0
├── broccoli-funnel-reducer@1.0.0
├── ember-cli-get-component-path-option@1.0.0
├── ember-cli-valid-component-name@1.0.0
├── escape-string-regexp@1.0.5
├── is-git-url@0.2.3
├── isbinaryfile@2.0.4
├── rimraf@2.5.2
├── broccoli-source@1.1.0
├── exists-sync@0.0.3
├── promise-map-series@0.2.2
├── get-caller-file@1.0.1
├── filesize@3.3.0
├── inflection@1.10.0
├── symlink-or-copy@1.1.3
├── tree-sync@1.1.1
├── bower-endpoint-parser@0.2.2
├── broccoli-viz@2.0.1
├── node-modules-path@1.0.1
├── through@2.3.8
├── semver@5.1.0
├── node-uuid@1.4.7
├── broccoli-sane-watcher@1.1.4 (broccoli-slow-trees@1.1.0)
├── exit@0.1.2
├── amd-name-resolver@0.0.5 (ensure-posix-path@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── nopt@3.0.6 (abbrev@1.0.7)
├── http-proxy@1.13.2 (eventemitter3@1.2.0, requires-port@1.0.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── chalk@1.1.3 (ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── readline2@0.1.1 (mute-stream@0.0.4, strip-ansi@2.0.1)
├── diff@2.2.2
├── portfinder@1.0.3 (async@1.5.2)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── morgan@1.7.0 (on-headers@1.0.1, basic-auth@1.0.3, depd@1.1.0, on-finished@2.3.0)
├── rsvp@3.2.1
├── glob@7.0.3 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4)
├── minimatch@3.0.0 (brace-expansion@1.1.3)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── configstore@2.0.0 (os-tmpdir@1.0.1, object-assign@4.0.1, graceful-fs@4.1.3, uuid@2.0.2, dot-prop@2.4.0, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.4)
├── ora@0.2.1 (object-assign@4.0.1, cli-spinners@0.1.2, cli-cursor@1.0.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── broccoli-kitchen-sink-helpers@0.3.1 (glob@5.0.15)
├── quick-temp@0.1.5 (mktemp@0.3.5, rimraf@2.2.8, underscore.string@2.3.3)
├── compression@1.6.1 (on-headers@1.0.1, bytes@2.2.0, vary@1.1.0, compressible@2.0.7, accepts@1.3.2)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, graceful-fs@4.1.3, klaw@1.2.0, jsonfile@2.3.0)
├── fs-tree-diff@0.4.4 (fast-ordered-set@1.0.2)
├── sane@1.3.4 (watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, minimatch@0.2.14, walker@1.0.7, fb-watchman@1.9.0)
├── yam@0.0.18 (lodash.merge@3.3.2, fs-extra@0.16.5)
├── walk-sync@0.2.6 (matcher-collection@1.0.1)
├── broccoli-funnel@1.0.1 (array-equal@1.0.0, blank-object@1.0.1, path-posix@1.0.0, fs-tree-diff@0.3.1, fast-ordered-set@1.0.2, minimatch@2.0.10)
├── findup-sync@0.2.1 (glob@4.3.5)
├── broccoli-config-replace@1.1.2 (fs-extra@0.24.0)
├── cpr@0.4.2 (graceful-fs@4.1.3, rimraf@2.4.5)
├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, vary@1.0.1, methods@1.1.2, merge-descriptors@1.0.1, content-type@1.0.1, cookie@0.1.5, range-parser@1.0.3, parseurl@1.3.1, etag@1.7.0, serve-static@1.10.2, content-disposition@0.5.1, fresh@0.3.0, path-to-regexp@0.1.7, cookie-signature@1.0.6, depd@1.1.0, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.1, proxy-addr@1.0.10, send@0.13.1, accepts@1.2.13, type-is@1.6.12)
├── inquirer@0.12.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.4.0, figures@1.5.0, rx-lite@3.1.2, cli-width@2.1.0, cli-cursor@1.0.2, readline2@1.0.1, string-width@1.0.1, run-async@0.1.0)
├── broccoli-plugin@1.2.1
├── resolve@1.1.7
├── git-repo-info@1.1.2
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── broccoli-config-loader@1.0.0 (broccoli-caching-writer@2.2.1)
├── ember-router-generator@1.2.1 (recast@0.11.5)
├── markdown-it@4.3.0 (linkify-it@1.2.1, mdurl@1.0.1, uc.micro@1.0.0, entities@1.1.1, argparse@1.0.7)
├── broccoli-merge-trees@1.1.1 (fast-ordered-set@1.0.2, can-symlink@1.0.0)
├── markdown-it-terminal@0.0.3 (ansi-styles@2.2.1, lodash.merge@3.3.2, cli-table@0.3.1, cardinal@0.5.0, markdown-it@4.4.0)
├── broccoli-concat@2.2.0 (lodash.merge@4.3.5, lodash.omit@4.2.1, lodash.uniq@4.2.1, minimatch@2.0.10, broccoli-kitchen-sink-helpers@0.2.9, broccoli-caching-writer@2.2.1, fast-sourcemap-concat@0.2.7)
├── leek@0.0.21 (lodash.assign@3.2.0, request@2.72.0)
├── testem@1.6.0 (styled_string@0.0.1, did_it_work@0.0.6, printf@0.2.3, async@1.5.2, xmldom@0.1.22, charm@1.0.0, mustache@2.2.1, commander@2.9.0, backbone@1.3.3, fireworm@0.7.0, tap-parser@1.2.2, fileset@0.2.1, cross-spawn-async@2.2.2, consolidate@0.14.1, npmlog@2.0.3, js-yaml@3.6.0, socket.io@1.4.5, node-notifier@4.5.0)
├── ember-cli-broccoli@0.16.9 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, mime@1.3.4, commander@2.9.0, connect@3.4.1, broccoli-kitchen-sink-helpers@0.2.9, handlebars@4.0.5)
├── ember-cli-preprocess-registry@2.0.0 (process-relative-require@1.0.0, broccoli-clean-css@1.1.0, lodash@3.10.1)
├── core-object@0.0.2 (lodash-node@2.4.1)
├── bower-config@1.4.0 (graceful-fs@4.1.3, untildify@2.1.0, osenv@0.1.3, optimist@0.6.1, mout@1.0.0)
├── lodash@4.11.1
├── broccoli-babel-transpiler@5.5.0 (clone@0.2.0, json-stable-stringify@1.0.1, broccoli-persistent-filter@1.2.0, babel-core@5.8.38)
├── npm@2.14.21
└── bower@1.7.9
root@node-512mb-nyc2-01:~# ember new limtoss
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
⠸ Installing packages for tooling via npmKilled
root@node-512mb-nyc2-01:~# ^Cber new limtoss
root@node-512mb-nyc2-01:~# sudo ember new limtoss
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Directory 'limtoss' already exists.
root@node-512mb-nyc2-01:~# del limtoss
No command 'del' found, did you mean:
 Command 'tel' from package 'orville-write' (universe)
 Command 'mdel' from package 'mtools' (main)
 Command 'delp' from package 'fp-utils-2.6.2' (universe)
 Command 'wdel' from package 'wput' (universe)
 Command 'hdel' from package 'hfsutils' (main)
 Command 'el' from package 'oneliner-el' (universe)
 Command 'qdel' from package 'gridengine-client' (universe)
 Command 'qdel' from package 'slurm-llnl-torque' (universe)
 Command 'qdel' from package 'torque-client-x11' (universe)
 Command 'qdel' from package 'torque-client' (universe)
 Command 'bel' from package 'belier' (universe)
 Command 'deal' from package 'deal' (universe)
del: command not found
root@node-512mb-nyc2-01:~# rm limtoss
rm: cannot remove ‘limtoss’: Is a directory
root@node-512mb-nyc2-01:~# sudo ember new limtossr
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
⠹ Installing packages for tooling via npmroot@node-512mb-nyc2-01:~# npm serve

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.1 /usr/lib/node_modules/npm
root@node-512mb-nyc2-01:~# cd limtossr
root@node-512mb-nyc2-01:~/limtossr# ember serve
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/find'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/limtossr/node_modules/ember-cli/lib/models/project.js:12:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@node-512mb-nyc2-01:~/limtossr# sudo ember server
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/find'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/limtossr/node_modules/ember-cli/lib/models/project.js:12:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@node-512mb-nyc2-01:~/limtossr#
root@node-512mb-nyc2-01:~/limtossr#
root@node-512mb-nyc2-01:~/limtossr#
```
Errors at the bottom.

Ubuntu 4.4.3
Current Ember Version
---

Output from ember version --verbose:
```
Throws same errors as above.
```

**Comment by stefanpenner** [comment]
Looks like you might have an old broken npm, please upgrade to 3.8.1 or newer and try again.

Our ci passes in Linux, so I suspect we are fine. Otherwise post upgrade if the problem exists, please provide steps to reproduce an we can reopen.
