### ISSUE TITLE
Can not import font that is located in node_modules subdirectory

### ISSUE THREAD

**Issue by LQtrio** [ember-cli/ember-cli#5930]
Steps to reproduce:
1. `npm install semantic-ui-sass --save-dev`
2.  Add this line to ember-cli-build.js
```
app.import('node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui/icons.ttf');
```

Error-Log:
```
The Broccoli Plugin: [Funnel: Funnel                                                                                                                                      [0/1918]
  node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui
  node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui
 include:1] failed with:
Error: ENOENT: no such file or directory, scandir '/var/www/dev07/frontend/tmp/funnel-input_base_path-DtjQNVsU.tmp/0/node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at _walkSync (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/walk-sync/index.js:66:20)
    at Function.entries (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/walk-sync/index.js:47:10)
    at Funnel.processFilters (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:231:26)
    at Funnel.build (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:172:10)
    at /var/www/dev07/frontend/node_modules/ember-cli/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/var/www/dev07/frontend/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:44:10)
    at /var/www/dev07/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1413:12
    at Array.map (native)
    at EmberApp.otherAssets (/var/www/dev07/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1407:61)
    at EmberApp.toArray (/var/www/dev07/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/var/www/dev07/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/var/www/dev07/frontend/ember-cli-build.js:63:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/var/www/dev07/frontend/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/var/www/dev07/frontend/node_modules/ember-cli/lib/models/builder.js:89:10)

```
---

Output from ember version --verbose:
```
ember-cli: 2.5.1
http_parser: 2.5.2
node: 4.4.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: linux x64

```

**Comment by stavarotti** [comment]
Hi @LQtrio.  This is a known limitation.  See https://github.com/ember-cli/ember-cli/issues/3890 for reference.  This _will_ be possible once bower support is removed.

**Comment by gskaplan** [comment]
Ember is already not using Bower, but I still can't seem to app.import anything from node_modules. Has this been fixed yet, or is it on a radar soon? I am using Foundation-Sites and I can't import that javascript from node_modules.

**Comment by kellyselden** [comment]
@gskaplan This will be released in a few days with ember-cli 2.15.

**Comment by gskaplan** [comment]
I'm looking for any documentation on this issue in the latest release but I can't find anything to support whether the change is in place or not or how it can be used. Can you please provide a link so I can try using this now? Thanks!

**Comment by Turbo87** [comment]
@gskaplan https://emberjs.com/blog/2017/09/01/ember-2-15-released.html#toc_app-import-files-within-node_modules

**Comment by sly7-7** [comment]
@kellyselden does this now makes your https://github.com/kellyselden/ember-cli-node-modules-to-vendor useless ?
