### ISSUE TITLE
Cannot read property '_watchmanInfo' of undefined

### ISSUE THREAD

**Issue by cesarizu** [ember-cli/ember-cli#5945]
After updating to ember-cli-2.6.0-beta.3 I'm getting this error when starting an app:

```
Cannot read property '_watchmanInfo' of undefined
TypeError: Cannot read property '_watchmanInfo' of undefined
    at CoreObject.extend.treeGenerator (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addon.js:276:21)
    at CoreObject._treeFor (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addon.js:337:19)
    at CoreObject.treeFor (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addon.js:309:21)
    at /home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:465:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:463:30)
    at EmberApp._processedAppTree (/home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:763:25)
    at EmberApp.appAndDependencies (/home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1038:10)
    at EmberApp.javascript (/home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1161:34)
    at EmberApp.toArray (/home/cesar/src/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
```

Output from ember version --verbose:
```
ember-cli: 2.6.0-beta.3
http_parser: 2.6.2
node: 5.8.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: linux x64
```

**Comment by Turbo87** [comment]
@cesarizu what version did you update from? 2.5.0 or 2.6.0-beta.2?

**Comment by cesarizu** [comment]
@Turbo87 from 2.6.0-beta.1

**Comment by Turbo87** [comment]
@nathanhammond @stefanpenner could this be related to the CoreObject update? IIRC that got introduced in beta2, right?

**Comment by cesarizu** [comment]
I just tried with beta.2 and got this error:

```
Cannot read property 'discoverChildAddons' of undefined
TypeError: Cannot read property 'discoverChildAddons' of undefined
    at CoreObject.extend.discoverAddons (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addon.js:205:41)
    at CoreObject.extend.initializeAddons (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addon.js:218:10)
    at /home/cesar/src/my-project/node_modules/ember-cli/lib/models/addons-factory.js:48:17
    at visit (/home/cesar/src/my-project/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at visit (/home/cesar/src/my-project/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at DAG.topsort (/home/cesar/src/my-project/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at CoreObject.extend.initializeAddons (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/addons-factory.js:42:11)
    at Project.initializeAddons (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/project.js:379:36)
    at Project.eachAddonCommand (/home/cesar/src/my-project/node_modules/ember-cli/lib/models/project.js:430:10)
    at module.exports (/home/cesar/src/my-project/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)

```

**Comment by cesarizu** [comment]
Changing the failing line (`node_modules/ember-cli/lib/models/addon.js:276`) from:

```
if (this.project._watchmanInfo.canNestRoots || this.isDevelopingAddon()) {
```
to
```
if (this.project && this.project._watchmanInfo.canNestRoots || this.isDevelopingAddon()) {
```
fixes the issue.

**Comment by nathanhammond** [comment]
Hey @cesarizu! Thank you for the report.

a. Is this a brand new project? If so, can you create a simple repo with a reproduction?
b. If it's not a new project, can you share your package.json?
c. Can you trace through and identify which addon it is trying to process here:

> `at visit (/home/cesar/src/my-project/node_modules/ember-cli/lib/utilities/DAG.js:23:3)`

It's likely that adding that `if` check just masks the underlying problem. We moved to a new version of core-object in the beta series at 2.6.0-beta.2 which has had a few issues.

**Comment by cesarizu** [comment]
Here's my `package.json` file: http://paste.opensuse.org/38550443

Checking the `DAG.js` file, the last plugin to be called there before the error is `loader.js`. I tried with versions 4.0.4 and 4.0.1 and both gave the same error.

**Comment by nathanhammond** [comment]
Hey @cesarizu! That paste has expired or something. Can you include it inline here?

**Comment by cesarizu** [comment]
Sure, here it is:
```
{
  "name": "my-project",
  "version": "0.0.0",
  "description": "My Project app",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "",
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-clean-css": "^1.1.0",
    "ember-ajax": "^2.3.2",
    "ember-api-actions": "0.1.4",
    "ember-body-class": "^0.3.9",
    "ember-cli": "2.6.0-beta.3",
    "ember-cli-active-link-wrapper": "^0.2.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-autoprefixer": "^0.6.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "^0.6.2",
    "ember-cli-deploy-build": "^0.1.1",
    "ember-cli-deploy-display-revisions": "^0.2.1",
    "ember-cli-deploy-gzip": "^0.2.3",
    "ember-cli-deploy-manifest": "^0.1.1",
    "ember-cli-deploy-revision-data": "^0.2.3",
    "ember-cli-deploy-s3": "^0.3.0",
    "ember-cli-deploy-s3-index": "^0.5.0",
    "ember-cli-document-title": "^0.3.1",
    "ember-cli-emblem": "^0.8.0",
    "ember-cli-eslint": "^1.4.1",
    "ember-cli-fastclick": "^1.2.0",
    "ember-cli-font-awesome": "^1.5.0",
    "ember-cli-foundation-6-sass": "~0.0.9",
    "ember-cli-google-fonts": "^2.3.0",
    "ember-cli-htmlbars": "^1.0.5",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-icheck": "mewben/ember-cli-icheck",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-moment-shim": "^1.2.0",
    "ember-cli-notifications": "^3.3.1",
    "ember-cli-pace": "^0.1.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^1.0.0-beta.1",
    "ember-cli-sass": "^5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-star-rating": "^0.4.1",
    "ember-cli-tooltipster": "^0.1.8",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "^0.2.0-beta.6",
    "ember-composable-helpers": "^0.26.0",
    "ember-computed-decorators": "^0.2.2",
    "ember-data": "cesarizu/data#mixed-adapter-coalesced-find-many",
    "ember-data-filter": "^1.13.0",
    "ember-data-has-many-query": "0.1.3",
    "ember-data-model-fragments": "2.3.1",
    "ember-data-preload": "levanto-financial/ember-data-preload",
    "ember-debounced-properties": "0.0.5",
    "ember-export-application-global": "^1.0.5",
    "ember-group-by": "^0.0.3",
    "ember-load-initializers": "^0.5.1",
    "ember-local-storage": "^1.1.0",
    "ember-moment": "^6.1.0",
    "ember-multiselect-checkboxes": "^0.9.0",
    "ember-pikaday": "^1.1.0",
    "ember-polyfill-for-tests": "^0.2.0",
    "ember-power-select": "~0.10.8",
    "ember-promise-helpers": "^1.0.2",
    "ember-radio-button": "^1.0.7",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "^1.1.0",
    "ember-sortable": "^1.8.1",
    "ember-truth-helpers": "^1.2.0",
    "emberx-select": "^2.1.2",
    "emblem": "^0.8.0",
    "eslint-config-ember": "^0.3.0",
    "loader.js": "^4.0.4",
    "moment": "^2.13.0",
    "moment-timezone": "^0.5.4"
  }
}
```

**Comment by nathanhammond** [comment]
@cesarizu Thanks! With that many dependencies it's unlikely that we're going to be able to diagnose this without a screen sharing session with you. Is that an option?

@ember-cli/core This is certainly a stress test, there's no way to tell what's actually breaking here. It's blowing up early in the DAG.

**Comment by cesarizu** [comment]
Yeah, that would work for me. But if it helps, I can start disabling some of the dependencies and see what happens, try to figure out if any specific one or some combination is causing this problem...

**Comment by cesarizu** [comment]
@nathanhammond  I think I've narrowed the error down to `ember-cli-font-awesome`. With a new project, installing that addon using `ember install ember-cli-font-awesome` and then running with `ember serve` gives that error.

**Comment by nathanhammond** [comment]
@cesarizu `ember-cli-font-awesome` is deprecated, trying it with `ember-font-awesome` works for me. Please update to that and everything should work!

**Comment by cesarizu** [comment]
Yes, that's true... using `ember-font-awesome` works :) thanks @nathanhammond  for your help.

**Comment by vlascik** [comment]
If anyone else has this problem, try to isolate the offending addon, and check whether it has `ember-cli-htmlbars` in addon's package.json `dependencies` instead of `devDependencies`, maybe also whether it overrides `init()` in `index.js` while forgetting to call `super()`, as was the case for me. Hope it helps.

**Comment by stefanpenner** [comment]
i think this can still be improved here, just ran into it

**Comment by Dhaulagiri** [comment]
We are seeing this as well in a relatively new project being upgrade to ember-cli 2.6.0

**Comment by rwjblue** [comment]
It generally happens when an addon doesn't call _super in its init, we need to track down these addons and update them to do:

    this._super.init && this._super.init.apply(this, arguments);

**Comment by stefanpenner** [comment]
@rwjblue we will likely need to release a patch version of CLI, that guards this (to ease the transition)
