### ISSUE TITLE
Broccoli errors when tests/ are deleted

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#5946]
According to this person on Reddit: https://www.reddit.com/r/emberjs/comments/4m49rv/disable_tests_with_ember_cli/

I would advocate that if someone decides to opt-out of the test suite for whatever reason and deletes the directory the build should not error.

I have not confirmed this as I'm on a plane and don't want it to crash due to npm install.

**Comment by stefanpenner** [comment]
thanks @bcardarella

**Comment by twokul** [comment]
```
$ ember t
Build failed.
The Broccoli Plugin: [Funnel: Funnel (test index)] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/alex/code/os/ember-cli/foobar/tests'
    at Error (native)
    at Object.fs.lstatSync (fs.js:976:18)
    at symlink (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:60:26)
    at symlinkOrCopySync (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:55:5)
    at /Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/alex/code/os/ember-cli/foobar/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rwjblue** [comment]
I believe that this should mostly do the trick:

* Update [this](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L201) to check `existsSync(this._resolveLocal('tests'))` and if not then use `null`
* Update this conditional in [EmberApp.prototype.toArray](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1610) to be `if (this.tests && this.trees.test)`

**Comment by v3ss0n** [comment]
this error still popups randomly
