### ISSUE TITLE
test-loader.js not found

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#5974]
I updated my addon to Ember-CLI 2.7.0-beta.1 and now I cannot run it or run tests or anything because it cannot find test-loader.js.

These are my versions:
```
"ember-cli": "2.7.0-beta.1",
"ember-cli-qunit": "^2.0.0",
"ember-cli-test-loader": "1.1.0",
```

Output from ember version --verbose:
```
ember-cli: 2.7.0-beta.1
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
os: darwin x64
```

I get an error that it cannot find test-loader.js. Is this possibly a rootURL issue? Not sure what's happening. 

This is in an addon by the way.

```
Error: ENOENT: no such file or directory, lstat '/Users/rwwagner/ember-math-helpers/tmp/funnel-input_base_path-fb3IkpRr.tmp/0/assets/test-loader.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/Users/rwwagner/ember-math-helpers/node_modules/symlink-or-copy/index.js:60:26)
    at Function.symlinkOrCopySync [as sync] (/Users/rwwagner/ember-math-helpers/node_modules/symlink-or-copy/index.js:55:5)
    at Funnel._copy (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:249:9)
    at Funnel.build (/Users/rwwagner/ember-math-helpers/node_modules/broccoli-funnel/index.js:172:10)
    at /Users/rwwagner/ember-math-helpers/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/rwwagner/ember-math-helpers/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/rwwagner/ember-math-helpers/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/rwwagner/ember-math-helpers/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/rwwagner/ember-math-helpers/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

You can find the broken addon in a branch at https://github.com/shipshapecode/ember-math-helpers/tree/broken-2.7.0

This could potentially be related to #5962

**Comment by stefanpenner** [comment]
@trentmwillis got cycles to take a look?

**Comment by rwwagner90** [comment]
@stefanpenner this is apparently an issue with ember-cli-blanket. Probably hasn't been updated to look for the new loader-js location.

**Comment by rwwagner90** [comment]
@ieugen are you using blanket?

**Comment by ieugen** [comment]
Not directly. 

````
"devDependencies": {
    "bower": "^1.7.2",
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-funnel": "^1.1.0",
    "ember-browserify": "1.1.13",
    "ember-cli": "2.10.0",
    "ember-cli-app-version": "^2.0.1",
    "ember-cli-autoprefixer": "^0.6.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-bootstrap-datepicker": "0.5.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "1.1.0",
    "ember-cli-htmlbars-inline-precompile": "0.3.5",
    "ember-cli-ic-ajax": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-mirage": "0.2.0",
    "ember-cli-moment-shim": "^3.0.1",
    "ember-cli-qunit": "^3.0.4",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^5.6.0",
    "ember-cli-svgstore": " ^0.3.0",
    "ember-cli-test-loader": "^1.1.1",
    "ember-cli-trackjs": "^1.1.2",
    "ember-cli-uglify": "^1.2.0",
    "ember-composable-helpers": "0.25.0",
    "ember-concurrency": "0.7.8",
    "ember-cp-validations": "3.1.4",
    "ember-crumbly": "1.0.2",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-fetch": "1.3.0",
    "ember-intl": "2.15.0",
    "ember-intl-cp-validations": "2.3.1",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "6.1.0",
    "ember-offline": "0.1.0",
    "ember-power-select": "0.10.0-beta.13",
    "ember-resolver": "^2.1.0",
    "ember-simple-auth": "1.1.0",
    "ember-simple-auth-token": "1.1.0",
    "ember-sortable": "1.6.1",
    "ember-truth-helpers": "1.2.0",
    "ember-validated-form-buffer": "0.0.1",
    "loader.js": "^4.1.0"
  },
  "dependencies": {
    "bcp-47": "^1.0.2",
    "broccoli-merge-trees": "^1.2.1",
    "cldr-core": "^30.0.2",
    "cldr-localenames-modern": "^30.0.2",
    "globalize": "^1.1.2"
  }
````

**Comment by ieugen** [comment]
@rwwagner90 : thanks.

**Comment by mekeor** [comment]
I'm experiencing the same. I'm not using `ember-cli-blanket`.
