### ISSUE TITLE
Deprecation warnings for new project

### ISSUE THREAD

**Issue by pinfieldharm** [ember-cli/ember-cli#5993]
I just created a new ember 2.6.0 app and, straight out of the box and with all default settings, every invocation of an ember command results in three deprecation warnings. You can see these in the output from ember version --verbose, below.

Steps to replicate (with ember 2.6.0 installed):
1. ember new testproj
2. cd testproj
3. ember version

---

Output from ember version --verbose:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-dependency-checker`
    at Function.Addon.lookup (/Users/paul/projects/organizer/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `Ember CLI QUnit`
    at Function.Addon.lookup (/Users/paul/projects/organizer/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
    at /Users/paul/projects/organizer/node_modules/ember-cli/lib/models/project.js:404:38
ember-cli: 2.6.1
http_parser: 2.7.0
node: 6.2.0
v8: 5.0.71.47
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by pinfieldharm** [comment]
Related issue in emberjs project: https://github.com/emberjs/ember.js/issues/13676

**Comment by stefanpenner** [comment]
These are upstream dependencies that need to be addressed, the deprecations explain which one.
