### ISSUE TITLE
ember test --silent isn't!

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#6000]
I remember working on this a couple of years ago and fixing testem to have a report-file command param so that console output didn't pollute the test output file. Now I can't find that feature - has it been removed again?

Here we go...

```
C:\projects\sc-pp\sc-pp-frontend-git>ember test ci --silent -r xunit > tests.xml
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-modal-dialog`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-hash-helper-polyfill`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-get-helper`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `liquid-fire`
    at Function.Addon.lookup (C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
    at C:\projects\sc-pp\sc-pp-frontend-git\node_modules\ember-cli\lib\models\project.js:404:38
...
```

**Comment by BryanCrotaz** [comment]
Doh. Why do I have the brainwave 10 seconds after posting an issue instead of in the last 2 hours of fighting... output to stdout is clean. Argh.
