### ISSUE TITLE
Error after create a fresh app

### ISSUE THREAD

**Issue by EQuimper** [ember-cli/ember-cli#6051]
I try to create a brand new app. I did the `ember new myapp` and cd into the folder. Inside I try the `ember s` and this is what I got

```
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/emanuelquimper/MyApp/Ember/my-new-app/ember-cli-build.js:3:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
---

Output from ember version --verbose:
```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by nathanhammond** [comment]
This looks like a broken installation (not your fault, likely some weird transient error). If this were an actual bug we'd have had people beating down our doors letting us know for over a month. Can you try removing things and starting over?

https://ember-community-slackin.herokuapp.com/

I'm closing this bug, please find us on Slack in the #-ember-cli channel for additional help!
