### ISSUE TITLE
ember addon test-addon -> EACCES: permission denied, open ...package.json

### ISSUE THREAD

**Issue by rfbarber** [ember-cli/ember-cli#6110]
I receive the following error when attempting to create a new addon:

```
EACCES: permission denied, open '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at CoreObject.writeContentsToFile (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:170:6)
    at CoreObject.module.exports.generatePackageJson (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:47:25)
    at CoreObject.module.exports.files (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:96:10)
    at CoreObject.extend.install (/usr/local/lib/node_modules/ember-cli/lib/models/blueprint.js:433:43)
    at CoreObject.module.exports.Task.extend.run (/usr/local/lib/node_modules/ember-cli/lib/tasks/install-blueprint.js:56:24)
    at CoreObject.module.exports.Command.extend.run (/usr/local/lib/node_modules/ember-cli/lib/commands/init.js:102:29)
    at /usr/local/lib/node_modules/ember-cli/lib/commands/new.js:91:12
```

package.json does not exist in the blueprints/addon/files directory:

```
rfb@slate:~/Projects$ ls -la /usr/local/lib/node_modules/ember-cli/blueprints/addon/files/
total 44
drwxr-sr-x 5 nobody rfb 4096 Jul 26 13:03 .
drwxr-sr-x 3 nobody rfb 4096 Jul 26 13:03 ..
drwxr-sr-x 2 nobody rfb 4096 Jul 14 20:37 addon
drwxr-sr-x 2 nobody rfb 4096 Jul 26 13:03 addon-config
drwxr-sr-x 2 nobody rfb 4096 Jul 14 20:37 app
-rw-r--r-- 1 nobody rfb  527 Jul 14 20:38 ember-cli-build.js
-rw-r--r-- 1 nobody rfb   96 Jul 14 20:37 index.js
-rw-r--r-- 1 nobody rfb 1073 Jul 14 20:37 LICENSE.md
-rw-r--r-- 1 nobody rfb  192 Jul 14 20:38 npmignore
-rw-r--r-- 1 nobody rfb  574 Jul 25 22:02 README.md
-rw-r--r-- 1 nobody rfb  758 Jul 25 22:02 .travis.yml
```

---

Output from ember version --verbose:

```
rfb@slate:~/Projects$ ember version --verbose
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 55.1
modules: 46
openssl: 1.0.2g
os: linux x64
rfb@slate:~/Proj
```

**Comment by stefanpenner** [comment]
This is a long running issue, yes we should fix.

On the flip side, /usr/local/lib/node_modules should most likely be writable by your current user, rather then root.

**Comment by RyanNerd** [comment]
I got bit by this recently. Here's a [guide to fixing permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) that helped me.

**Comment by locks** [comment]
Thank you for reporting it! The guide mentioned above is the recommended solution for this problem :)
