### ISSUE TITLE
Most `ember` commands are not working on Windows after `symlink-or-copy` v1.1.5 release was published on npm

### ISSUE THREAD

**Issue by ehaberev** [ember-cli/ember-cli#6156]
[`symlink-or-copy` v1.1.5](https://github.com/broccolijs/node-symlink-or-copy/releases/tag/v1.1.5) was released about 7 hours ago. After publishing this release on npm most `ember` commands (for example `ember build` or `ember install`) fails on Windows for new ember applications (after `ember init` or `ember new`) with error:
```
EEXIST: file already exists, mkdir '<some_path>\tmp'
Error: EEXIST: file already exists, mkdir '<some_path>\tmp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at testCanSymlink (<some_path>\node_modules\ember-cli-qunit\node_modules\broccoli-jshint\node_modules\broccoli-persistent-filter\node_modules\symlink-or-copy\index.js:18:6)
    at Object.<anonymous> (<some_path>\node_modules\ember-cli-qunit\node_modules\broccoli-jshint\node_modules\broccoli-persistent-filter\node_modules\symlink-or-copy\index.js:9:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

There is an [corresponding issue](https://github.com/broccolijs/node-symlink-or-copy/issues/23) in `node-symlink-or-copy` repository.

---

Output from ember version --verbose:
```
ember-cli: 2.4.3
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: win32 x64
```

**Comment by Baukereg** [comment]
Same problem here as well.

```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64
```

**Comment by herom** [comment]
Same here!

Output of `ember version --verbose`:

```
ember-cli: 2.4.3
http_parser: 2.5.2
node: 4.3.1
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
os: win32 x64
```

**Comment by globsecure** [comment]
+1 

`E:\Globsecure\superSite>ember version
EEXIST: file already exists, mkdir 'E:\Globsecure\superSite\tmp'
Error: EEXIST: file already exists, mkdir 'E:\Globsecure\superSite\tmp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at testCanSymlink (E:\Globsecure\superSite\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:18:6)
    at Object.<anonymous> (E:\Globsecure\superSite\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:9:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)`

**Comment by Vazgen7788** [comment]
``````
Same issue here.
ember-cli: 2.6.0
node: 6.3.1
os: win32 x64
```````

OS Windows 10

**Comment by Baukereg** [comment]
[Workaround](https://github.com/broccolijs/node-symlink-or-copy/issues/26)

Run ```npm install symlink-or-copy@1.1.3``` in your project folder or in _\node_modules\ember-cli_.

**Comment by stefanpenner** [comment]
I'll never to 1.1.3. So we can restore functionality to our users.

**Comment by stefanpenner** [comment]
waiting for windows CI: https://github.com/broccolijs/node-symlink-or-copy/pull/27

**Comment by Turbo87** [comment]
the problematic PR in symlink-or-copy was reverted and v1.1.6 was released which should fix things for now. we are investigating what went wrong here. closing this issue as the main problem has been solved.

**Comment by stefanpenner** [comment]
fixed: https://github.com/broccolijs/node-symlink-or-copy/pull/27 reverting another fix that introduced the issue. We will investigate and figure out whatsup.

**Comment by stefanpenner** [comment]
tracking restoring the fix that cause this bug -> https://github.com/broccolijs/node-symlink-or-copy/issues/28
