### ISSUE TITLE
Cannot find module 'cookie-signature'

### ISSUE THREAD

**Issue by mewben** [ember-cli/ember-cli#616]
- I cloned the ember-cli repository.
- cd ember-cli and sudo npm link

Afterwards, when I try any ember command, it produces this error:

```
module.js:340
    throw err;
    ^
Error: Cannot find module 'cookie-signature'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/melvin/Desktop/Boxes/ubuntu1404/projects/nodejs/github/ember-cli/node_modules/broccoli/node_modules/connect/lib/utils.js:17:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

My machine:
*\* Mac OS X Mavericks
*\* node v0.10.28
*\* npm v1.4.9

**Comment by dilipkosuri** [comment]
Try:
 `npm install cookie-signature`
If you see error regarding the permission then use the below command:
`sudo npm install cookie-signature`
