### ISSUE TITLE
Get ember-cli to work on Bash on Ubuntu for Windows

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-cli#6173]
I have tried to get my projects to run in Ubuntu Bash for Windows, but I'm running into some problems there. I saw similar things reported here: https://github.com/ember-cli/ember-cli/pull/6098#issuecomment-235137541 but I'm not sure in how far this is being tracked on its own?

My System:

- Bash on Ubuntu on Windows 10
- ember-cli: 2.8.0-beta.2
- node: 4.4.7
- os: linux x64

## Case 1: New App

I created a new app in the Ubuntu environment: `ember new testapp`. Then, I started the app with `ember s`.

This did serve the app under `localhost:4200`, but the watcher threw an error: 

```bash
File: /root/git/testapp/app
The Broccoli Plugin: [object Object] failed with:
Error: watch /root/git/testapp/app EPERM
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at NodeWatcher.watchdir (/root/git/testapp/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/root/git/testapp/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/root/git/testapp/node_modules/ember-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /root/git/testapp/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)

The broccoli plugin was instantiated at:
    at WatchedDir.Directory (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-source/index.js:14:31)
    at new WatchedDir (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-source/index.js:58:13)
    at EmberApp._initOptions (/root/git/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:200:17)
    at new EmberApp (/root/git/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:122:8)
    at module.exports (/root/git/testapp/ember-cli-build.js:6:13)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/root/git/testapp/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/root/git/testapp/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/root/git/testapp/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/root/git/testapp/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
    at CoreObject.module.exports.Task.extend.run (/root/git/testapp/node_modules/ember-cli/lib/tasks/serve.js:15:19)
```

When using `ember s --watcher=polling`, I received the following error instead:

```bash
The Broccoli Plugin: [ConfigReplace] failed with:
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at ConfigReplace.getConfig (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:122:21)
    at ConfigReplace.build (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:27:21)
    at /root/git/testapp/node_modules/ember-cli/node_modules/broccoli-config-replace/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/root/git/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConfigReplace.Plugin (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-config-replace/node_modules/broccoli-plugin/index.js:7:31)
    at new ConfigReplace (/root/git/testapp/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:13:10)
    at EmberApp.index (/root/git/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:652:10)
    at EmberApp.toArray (/root/git/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1603:10)
    at EmberApp.toTree (/root/git/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
    at module.exports (/root/git/testapp/ember-cli-build.js:23:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/root/git/testapp/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/root/git/testapp/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/root/git/testapp/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/root/git/testapp/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
```

(but it also served the app)

## Case 2: Existing App

I also tried to get an app on my Windows host system to run in the Ubuntu Bash:

```bash
cd /mnt/c/projects/my-existing-app
rimraf ./node_modules
npm install
ember s --watcher=polling
```

However, this didn't work at all for me (e.g. it didn't even serve the app under `localhost:4200`):

```bash
Serving on http://localhost:4200/
File: /mnt/c/projects/my-ember-app/tests/dummy/app
The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
Error: watch /mnt/c/projects/my-ember-app/tests/dummy/app EPERM
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at NodeWatcher.watchdir (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:56:10)
    at EmberAddon.EmberApp.index (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:641:15)
    at EmberAddon.EmberApp.toArray (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1605:10)
    at EmberAddon.EmberApp.toTree (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1628:30)
    at module.exports (/mnt/c/projects/my-ember-app/ember-cli-build.js:10:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
```

or with `ember s --watcher=polling`:

```bash
Serving on http://localhost:4200/
The Broccoli Plugin: [ConfigReplace] failed with:
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.readSync (/mnt/c/projects/my-ember-app/node_modules/ember-cli-release/node_modules/npm/node_modules/graceful-fs/polyfills.js:110:28)
    at Object.fs.readFileSync (fs.js:438:24)
    at ConfigReplace.getConfig (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:122:21)
    at ConfigReplace.build (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:27:21)
    at /mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-config-replace/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)

The broccoli plugin was instantiated at:
    at ConfigReplace.Plugin (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-config-replace/node_modules/broccoli-plugin/index.js:7:31)
    at new ConfigReplace (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/broccoli-config-replace/index.js:13:10)
    at EmberAddon.EmberApp.index (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:652:10)
    at EmberAddon.EmberApp.toArray (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1605:10)
    at EmberAddon.EmberApp.toTree (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1628:30)
    at module.exports (/mnt/c/projects/my-ember-app/ember-cli-build.js:10:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/mnt/c/projects/my-ember-app/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/mnt/c/projects/my-ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
```

I also tried this advice: `sudo chown feriese /home/feriese/.config/configstore/ember-cli.json`, but it didn't change anything.

If there is anything else I can help with, I'm happy to try stuff out on my machine!

**Comment by stefanpenner** [comment]
this is fixed on beta

**Comment by stefanpenner** [comment]
specifically: https://github.com/ember-cli/ember-cli/pull/6097

**Comment by stefanpenner** [comment]
then https://github.com/ember-cli/ember-cli/pull/6096 will make us autodetect the right thing by default.
