### ISSUE TITLE
ember-cli-htmlbars throwing Deprecation notice in 2.7.0

### ISSUE THREAD

**Issue by RyanNerd** [ember-cli/ember-cli#6175]
When running `ember s` under ember 2.7.0 
```
$ ember s

DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/home/ryan/RxTrax/rxtrax-n/node_modules/ember-cli/lib/models/addon.js:1009:27)
```

---

Output from ember version --verbose:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/home/ryan/RxTrax/rxtrax-n/node_modules/ember-cli/lib/models/addon.js:1009:27)
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.0
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2h
os: linux x64

```

**Comment by Turbo87** [comment]
can you check with `npm ls ember-cli-htmlbars` which version you are using and what dependencies are using it?

**Comment by RyanNerd** [comment]
ᐅ npm ls ember-cli-htmlbars
rxtrax-n@0.0.0 /home/ryan/RxTrax/rxtrax-n
├─┬ ember-aupac-typeahead@2.0.2
│ └── ember-cli-htmlbars@0.7.6 
└── ember-cli-htmlbars@1.0.11

**Comment by RyanNerd** [comment]
Looks like  ember-aupac-typeahead@2.0.2 is the culprit. Please mark this issue as closed. Thanks again for your help.
