### ISSUE TITLE
BroccoliMergeTrees failed when creating a nested route

### ISSUE THREAD

**Issue by ml3ha** [ember-cli/ember-cli#6179]
Hi, I'm creating my own Ember application and ran into this issue when I tried to create a new route.

Basically I had an admin route and wanted to create a nested `add` route that routed to `admin/add`. I have a bunch of other routes but this was my first nested route. When I generated the admin route and reloaded localhost, the route was working and the page still loaded. I didn't see my terminal throw this error but apparently this was an error:

```
file added routes/admin
file added templates/admin
The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
Error: EEXIST: file already exists, symlink '/Users/maxwellluo/ember-website/tmp/broccoli_merge_trees-input_base_path-rl0joAdz.tmp/0/ember-website/templates/admin/edit' -> '/Users/maxwellluo/ember-website/tmp/broccoli_merge_trees-output_path-4U9HDrUc.tmp/ember-website/templates/admin/edit'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1048:18)
    at symlink (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees._applyMkdir (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:141:12)
    at BroccoliMergeTrees.<anonymous> (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:129:37)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:115:9)
    at BroccoliMergeTrees.build (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:89:10)
    at /Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:10)
    at BroccoliMergeTrees (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:24:53)
    at module.exports (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp._processedTemplatesTree (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:794:27)
    at EmberApp.appAndDependencies (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1035:24)
    at EmberApp.javascript (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1161:34)
    at EmberApp.toArray (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/maxwellluo/ember-website/ember-cli-build.js:23:14)
```

I wasn't having issues until I generated the nested route with:

`ember g route admin/add`.

When I did this, a build error showed up in my localhost, and this was the error:

```
file changed router.js
The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
Error: ENOENT: no such file or directory, mkdir '/Users/maxwellluo/ember-website/tmp/broccoli_merge_trees-output_path-4U9HDrUc.tmp/ember-website'
```

There was somehow no output for when I added the new add route. I am wondering if this is the issue. After this, I killed the server and restarted it with `ember s`. Then this was the error

```
The Broccoli Plugin: [BroccoliMergeTrees: addonPreprocessTree(template)] failed with:
Error: ENOENT: no such file or directory, stat '/Users/maxwellluo/ember-website/tmp/broccoli_merge_trees-input_base_path-16i3mEWK.tmp/0/ember-website/templates/admin/add.hbs'
```

If anyone could provide guidance on how I can fix these build errors without breaking my entire Ember application, that would be greatly appreciated. 

---

Output from ember version --verbose:
```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64

```

**Comment by stefanpenner** [comment]
this isn't a known bug, can you reproduce repo that demonstrates this issue reproducibly?

**Comment by ml3ha** [comment]
@stefanpenner I assume this means you want the link to the repo.

https://github.com/ml3ha/ember-website

I just pushed the most recent changes, which includes the error above.

**Comment by ml3ha** [comment]
When I restart my ember server I get this:

```
Error: ENOENT: no such file or directory, stat '/Users/maxwellluo/ember-website/tmp/broccoli_merge_trees-input_base_path-wOHjI6j2.tmp/0/ember-website/templates/admin/add.hbs'
    at Error (native)
    at Object.fs.statSync (fs.js:981:18)
    at buildEntry (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:331:17)
    at BroccoliMergeTrees._mergeRelativePath (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:239:19)
    at BroccoliMergeTrees._mergeRelativePath (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:292:31)
    at BroccoliMergeTrees._mergeRelativePath (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:292:31)
    at BroccoliMergeTrees._mergeRelativePath (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:292:31)
    at BroccoliMergeTrees.build (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:70:24)
    at /Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:10)
    at BroccoliMergeTrees (/Users/maxwellluo/ember-website/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:24:53)
    at module.exports (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp._processedTemplatesTree (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:794:27)
    at EmberApp.appAndDependencies (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1035:24)
    at EmberApp.javascript (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1161:34)
    at EmberApp.toArray (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/maxwellluo/ember-website/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/maxwellluo/ember-website/ember-cli-build.js:23:14)
```

**Comment by ml3ha** [comment]
Hey, so I recloned the entire repository and npm installed and bower installed, and the issue resolved by itself.
