### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by Schnodderbalken** [ember-cli/ember-cli#6197]
I suddenly got this error:
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerge (public)] failed with:
Error: ENOENT, no such file or directory '/Users/maRcbook/dev/my-project/tmp/broccoli_merge_trees-input_base_path-UzrGI4B2.tmp/22/documentfiles'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at buildEntry (/Users/maRcbook/dev/my-project/node_modules/broccoli-merge-trees/index.js:339:17)
    at BroccoliMergeTrees._mergeRelativePath (/Users/maRcbook/dev/my-project/node_modules/broccoli-merge-trees/index.js:247:19)
    at BroccoliMergeTrees.build (/Users/maRcbook/dev/my-project/node_modules/broccoli-merge-trees/index.js:82:24)
    at /Users/maRcbook/dev/my-project/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/maRcbook/dev/my-project/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/maRcbook/dev/my-project/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/maRcbook/dev/my-project/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/maRcbook/dev/my-project/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/maRcbook/dev/my-project/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/maRcbook/dev/my-project/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/maRcbook/dev/my-project/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.publicTree (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:779:10)
    at EmberApp.toArray (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1607:10)
    at EmberApp.toTree (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
    at module.exports (/Users/maRcbook/dev/my-project/ember-cli-build.js:23:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/Users/maRcbook/dev/my-project/node_modules/ember-cli/lib/models/builder.js:54:10)
```

I already read [issue 5857 ](https://github.com/ember-cli/ember-cli/issues/5857) and [issue 5297](https://github.com/ember-cli/ember-cli/issues/5297) and did `rm -rf node_modules`, `npm cache clear` and `npm install` but the problem persists. I already have the newest version of broccoli-merge-trees (1.1.4). Does anyone have a clue how I can make my ember app start again without build errors?

---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
os: darwin x64
```

**Comment by stefanpenner** [comment]
Can you provide a reproduction?

**Comment by Schnodderbalken** [comment]
Ah interesting! I found the cause of the problem: in the `public` directory I had a symlink because I serve static files there that lie in another directory. When I delete the directory the link points at the error occurs. So either removing the link or making it not point to an empty directory fixes it.

**Comment by nathanhammond** [comment]
@stefanpenner Is this something you wish to address?
