### ISSUE TITLE
Broccoli error when trying to load assets from node_modules

### ISSUE THREAD

**Issue by oswaldoferreira** [ember-cli/ember-cli#6220]
I've tried to load a `css` file from `node_modules` folder on `ember-cli-build.js` with the following code:

`app.import('node_modules/material-design-lite/material.css');`

Double-checked the file presence but it still raises an error when I try to build.

By the way, it works just fine to load the same asset from `bower_components` folder.

Would be glad to work on this if it's a real bug.

```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.2.1
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

Stacktrace:

```
The Broccoli Plugin: [SimpleConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: ENOENT: no such file or directory, stat '/Users/osw/projects/personal/nomad/frontend/nomad/tmp/simple_concat-input_base_path-m8egHzW4.tmp/0/node_modules/material-design-lite/material.css'
    at Error (native)
    at Object.fs.statSync (fs.js:981:18)
    at ConcatWithMaps.keyForFile (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ConcatWithMaps (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:24:17)
    at module.exports (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/lib/broccoli/ember-app.js:368:10)
    at EmberApp._concatFiles (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/lib/broccoli/ember-app.js:381:15)
    at EmberApp.styles (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/lib/broccoli/ember-app.js:1316:28)
    at EmberApp.toArray (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/lib/broccoli/ember-app.js:1605:10)
    at EmberApp.toTree (/Users/osw/projects/personal/nomad/frontend/nomad/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
    at module.exports (/Users/osw/projects/personal/nomad/frontend/nomad/ember-cli-build.js:28:14)
```

**Comment by oswaldoferreira** [comment]
Ok, just found a related issue. 
https://github.com/ember-cli/ember-cli/issues/3890

Closing.
