### ISSUE TITLE
BroccoliMergeTrees EEXIST

### ISSUE THREAD

**Issue by dfreeman** [ember-cli/ember-cli#6236]
I suspect this is a bug in `broccoli-merge-trees` (or possibly `broccoli-funnel`) rather than the CLI itself, but I'm still working on narrowing down the exact source of the issue. When I add a new directory with e.g. a `component.js`, and then subsequently a `template.hbs` in that directory, I get the following error:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerge (templates)] failed with:
Error: EEXIST: file already exists, symlink '/Users/dfreeman/Desktop/merge-failure/app/templates' -> '/Users/dfreeman/Desktop/merge-failure/tmp/broccoli_merge_trees-output_path-bNpjQxAJ.tmp/merge-failure/templates'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at symlink (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees._applyMkdir (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:149:12)
    at BroccoliMergeTrees.<anonymous> (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:125:21)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:114:9)
    at BroccoliMergeTrees.build (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:101:10)
    at /Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp._templatesTree (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:714:30)
    at EmberApp._processedTemplatesTree (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:825:10)
    at EmberApp.appAndDependencies (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1060:24)
    at EmberApp.javascript (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1199:34)
    at EmberApp.toArray (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1604:10)
    at EmberApp.toTree (/Users/dfreeman/Desktop/merge-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:1626:30)
```

To reproduce, spin up a new app and `serve` it:

``` bash
ember new merge-failure
cd merge-failure
ember serve
```

Then in a separate shell, make a new directory and throw some JS in it, then add a `template.hbs`

``` bash
mkdir app/components/foo
touch app/components/foo/component.js
# Wait for the rebuild
touch app/components/foo/template.hbs
```

Environment details:

```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by dfreeman** [comment]
Originally came across this as https://github.com/salsify/ember-css-modules/issues/43, but seeing the same thing happen with `.hbs` files as above leads me to believe it's a deeper plumbing problem.

**Comment by stefanpenner** [comment]
whats the result of `npm ls fs-tree-diff`

**Comment by dfreeman** [comment]
Looks like the only one that's not `0.5.2` is the `0.4.4` copy that's bundled directly with ember-cli:

```
merge-failure@0.0.0 /Users/dfreeman/Desktop/merge-failure
├─┬ ember-cli@2.7.0
│ ├─┬ broccoli-babel-transpiler@5.6.1
│ │ └─┬ broccoli-persistent-filter@1.2.11
│ │   └── fs-tree-diff@0.5.2
│ ├─┬ broccoli-funnel@1.0.6
│ │ └── fs-tree-diff@0.5.2
│ ├─┬ broccoli-merge-trees@1.1.4
│ │ └── fs-tree-diff@0.5.2
│ ├─┬ ember-cli-preprocess-registry@2.0.0
│ │ └─┬ broccoli-clean-css@1.1.0
│ │   └─┬ broccoli-persistent-filter@1.2.11
│ │     └── fs-tree-diff@0.5.2
│ ├── fs-tree-diff@0.4.4
│ └─┬ tree-sync@1.1.4
│   └── fs-tree-diff@0.5.2
├─┬ ember-cli-babel@5.1.10
│ ├─┬ broccoli-babel-transpiler@5.6.1
│ │ ├─┬ broccoli-merge-trees@1.1.4
│ │ │ └── fs-tree-diff@0.5.2
│ │ └─┬ broccoli-persistent-filter@1.2.11
│ │   └── fs-tree-diff@0.5.2
│ └─┬ broccoli-funnel@1.0.6
│   └── fs-tree-diff@0.5.2
├─┬ ember-cli-htmlbars@1.1.0
│ └─┬ broccoli-persistent-filter@1.2.11
│   └── fs-tree-diff@0.5.2
├─┬ ember-cli-jshint@1.0.5
│ └─┬ broccoli-jshint@1.2.0
│   └─┬ broccoli-persistent-filter@1.2.11
│     └── fs-tree-diff@0.5.2
├─┬ ember-cli-qunit@2.2.1
│ ├─┬ broccoli-babel-transpiler@5.6.1
│ │ └─┬ broccoli-persistent-filter@1.2.11
│ │   └── fs-tree-diff@0.5.2
│ ├─┬ broccoli-funnel@1.0.6
│ │ └── fs-tree-diff@0.5.2
│ └─┬ broccoli-merge-trees@1.1.4
│   └── fs-tree-diff@0.5.2
├─┬ ember-data@2.7.0
│ ├─┬ broccoli-babel-transpiler@5.6.1
│ │ ├─┬ broccoli-funnel@1.0.6
│ │ │ └── fs-tree-diff@0.5.2
│ │ └─┬ broccoli-persistent-filter@1.2.11
│ │   └── fs-tree-diff@0.5.2
│ └─┬ broccoli-merge-trees@1.1.4
│   └── fs-tree-diff@0.5.2
└─┬ ember-welcome-page@1.0.3
  ├─┬ broccoli-funnel@1.0.6
  │ └── fs-tree-diff@0.5.2
  └─┬ broccoli-merge-trees@1.1.4
    └── fs-tree-diff@0.5.2
```

**Comment by dfreeman** [comment]
@stefanpenner I managed to come up with a relatively simple reproduction: https://github.com/dfreeman/broccoli-merge-failure/blob/master/index.js

Looks like this is triggered when the same directory is introduced at different times in two different inputs to the tree merge.

**Comment by stefanpenner** [comment]
@dfreeman nice reproduction, can you open an issue on [here](https://github.com/broccolijs/broccoli-merge-trees/issues/new) and we can cross link?

**Comment by stefanpenner** [comment]
fixed upstream, ensuring all broccoli-merge-trees (via npm ls) at atleast `=> 1.1.5` before reporting a related issue
