### ISSUE TITLE
fingerprint.prepend is double-prepended for assets/tests.js

### ISSUE THREAD

**Issue by pgengler** [ember-cli/ember-cli#6265]
With ember-cli 2.7+ (not with 2.6 or earlier), if fingerprinting is enabled, `fingerprint.prepend` is set to a string and `fingerprint.customHash` is set to null, the prepend string is double-prepending to "tests/assets.js" in the final index.html file for tests.

With a brand-new app generated from `ember new` with this put in the `ember-cli-build.js` file:
```
  var app = new EmberApp(defaults, {
    fingerprint: {
      enabled: true,
      prepend: 'http://localhost:4200/',
      customHash: null
    }
  });
```

The `<script>` tags in the generated tests/index.html file look like this with ember-cli 2.7, 2.8, and 2.9.0-beta.1:
```
    <script src="/testem.js" integrity=""></script>
    <script src="http://localhost:4200/assets/vendor.js"></script>
    <script src="http://localhost:4200/assets/test-support.js"></script>
    <script src="http://localhost:4200/assets/asset-weirdness.js"></script>
    <script src="http://localhost:4200/http://localhost:4200/assets/tests.js"></script>
```

Note that only "assets/tests.js" 

With ember-cli 2.6 and earlier this is the result:
```
    <script src="testem.js" integrity=""></script>
    <script src="http://localhost:4200/assets/vendor.js"></script>
    <script src="http://localhost:4200/assets/test-support.js"></script>
    <script src="http://localhost:4200/assets/asset-weirdness.js"></script>
    <script src="http://localhost:4200/assets/tests.js"></script>
    <script src="http://localhost:4200/assets/test-loader.js"></script>
```

One other possibly-related bit of weirdness is that if you include the string "assets/tests.js" in a comment in `tests/index.html` (`<!-- assets/tests.js -->`), the build process fails with this error:
```
File: tests/index.html
The Broccoli Plugin: [AssetRewrite] failed with:
TypeError: Cannot read property '2' of null
    at AssetRewrite.rewriteAssetPath (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rewrite/index.js:127:91)
    at AssetRewrite.processString (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rewrite/index.js:154:24)
    at AssetRewrite.processFile (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/phil.gengler/asset-weirdness/2.8/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/phil.gengler/asset-weirdness/2.8/node_modules/rsvp/dist/rsvp.js:553:13)
    at /Users/phil.gengler/asset-weirdness/2.8/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/Users/phil.gengler/asset-weirdness/2.8/node_modules/rsvp/dist/rsvp.js:2370:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

The broccoli plugin was instantiated at:
    at AssetRewrite.Plugin (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-plugin/index.js:7:31)
    at AssetRewrite.Filter [as constructor] (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-filter/index.js:34:10)
    at new AssetRewrite (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rewrite/index.js:27:10)
    at AssetRewrite (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rewrite/index.js:22:12)
    at new AssetRev (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rev/lib/asset-rev.js:29:10)
    at AssetRev (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at CoreObject.module.exports.postprocessTree (/Users/phil.gengler/asset-weirdness/2.8/node_modules/broccoli-asset-rev/index.js:31:40)
    at /Users/phil.gengler/asset-weirdness/2.8/node_modules/ember-cli/lib/broccoli/ember-app.js:541:27
    at Array.forEach (native)
    at EmberApp.addonPostprocessTree (/Users/phil.gengler/asset-weirdness/2.8/node_modules/ember-cli/lib/broccoli/ember-app.js:539:23)
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: darwin x64
3.3.12
```

**Comment by nathanhammond** [comment]
I believe that I can correctly peg your second issue without any research:

> One other possibly-related bit of weirdness is that if you include the string "assets/tests.js" in a comment in `tests/index.html` (`<!-- assets/tests.js -->`), the build process fails with this error ...

This is likely because [broccoli-asset-rewrite](https://github.com/rickharrison/broccoli-asset-rewrite/) uses regular expressions to handle its matching.

The first issue is likely in [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev/).

**Comment by rickharrison** [comment]
Are we sure this works in ember cli 2.6 and isn't related to broccoli-asset-rewrite#46 - That was published yesterday so I'm curious if that is what broke this.

**Comment by pgengler** [comment]
I've been having this issue since last week (when I tried upgrading an app to the latest ember-cli).

**Comment by nathanhammond** [comment]
@pgengler can you publish `asset-weirdness/2.8`?

**Comment by pgengler** [comment]
@nathanhammond Here you go: https://github.com/pgengler/asset-failure-2.8

**Comment by binhums** [comment]
@nathanhammond @pgengler I'm not sure if I've run into exactly the same issue but the stack trace looks very similar.

As far as I know my workaround here ^ stops me being blocked but I believe this is fundamentally an issue with `broccoli-asset-rev` not `broccoli-asset-writer`. I hope this helps.

**Comment by BillBrower** [comment]
@pgengler Running into this exact error after upgrading an Ember 3.4 app to Ember 3.5. Did you ever figure this out?
