### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by musaffa** [ember-cli/ember-cli#6326]
After upgrading the cli to 2.8.0, I get this socket hang up error. It usually happens on the first boot of the ember server. 
```
$ ember s
Livereload server on http://localhost:49152
Serving on http://localhost:8080/
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

Build successful - 151735ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 20441ms             
EslintValidationFilter                        | 19729ms             
Babel                                         | 19159ms             
Babel                                         | 12876ms             
EslintValidationFilter                        | 8373ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (46)                                    | 87685ms (1906 ms)   
EslintValidationFilter (3)                    | 30368ms (10122 ms) 
```

This is my current setup:

```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
3.10.5
```

**Comment by nathanhammond** [comment]
You have `/etc/hosts` or something else blocking Google Analytics. Turn off analytics inside of .ember-cli and it will stop throwing that error. Regardless, it isn't actually breaking anything. Closing as we're aware of it and are tracking it.

/cc @twokul this is a consequence of the leek `request` changeover.

**Comment by f0ru0l0rd** [comment]
Might be blocked, and might not be breaking anything, but it's disconcerting when a person loads ember, goes through a quickstart, and sees this. It's not kosher, it's frightening.

**Comment by nathanhammond** [comment]
@f0ru0l0rd We're still tracking this issue, just not here. https://github.com/twokul/leek/issues/36

**Comment by Dhevendhirancs** [comment]
yes, it is working. thanks @nathanhammond  for your valuable information
