### ISSUE TITLE
Build-Error on windows with ramdisk and a windows symlink for tmp

### ISSUE THREAD

**Issue by sandreas** [ember-cli/ember-cli#6397]
Hello,

i am using ember-cli on windows 10 and a ramdisk for tmp to improve performance and reduce ssd write bandwidth. To use a ramdisk in an ember project, a Windows-Symlink is needed (mklink -d tmp R:/ember-test/tmp), which worked perfectly in ember 2.6 but after upgrading to 2.9, i get an error. Only workaround actually is to use not ramdisk :-(

The error:
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (allTrees)] failed with:
Error: EEXIST: file already exists, mkdir 'C:\inetpub\wwwroot\ember-test\tmp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at FSMonitor._measure (C:\inetpub\wwwroot\ember-test\node_modules\heimdalljs-fs-monitor\index.js:66:21)
    at Object.mkdirSync (C:\inetpub\wwwroot\ember-test\node_modules\heimdalljs-fs-monitor\index.js:82:30)
    at findBaseDir (C:\inetpub\wwwroot\ember-test\node_modules\quick-temp\index.js:62:8)
    at makeTmpDir (C:\inetpub\wwwroot\ember-test\node_modules\quick-temp\index.js:45:41)
    at Object.makeOrReuse (C:\inetpub\wwwroot\ember-test\node_modules\quick-temp\index.js:21:22)
    at new ReadCompat (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-plugin\read_compat.js:17:13)
    at BroccoliMergeTrees.Plugin._initializeReadCompat (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-plugin\index.js:130:22)
    at BroccoliMergeTrees.Plugin.read (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-plugin\index.js:110:12)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-merge-trees\index.js:42:10)
    at BroccoliMergeTrees (C:\inetpub\wwwroot\ember-test\node_modules\broccoli-merge-trees\index.js:36:53)
    at module.exports (C:\inetpub\wwwroot\ember-test\node_modules\ember-cli\lib\broccoli\merge-trees.js:8:14)
    at EmberAddon.EmberApp.toTree (C:\inetpub\wwwroot\ember-test\node_modules\ember-cli\lib\broccoli\ember-app.js:1662:14)
    at module.exports (C:\inetpub\wwwroot\ember-test\ember-cli-build.js:17:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (C:\inetpub\wwwroot\ember-test\node_modules\ember-cli\lib\models\builder.js:70:19)
    at CoreObject.module.exports.Task.extend.init (C:\inetpub\wwwroot\ember-test\node_modules\ember-cli\lib\models\builder.js:50:10)
    at CoreObject.superWrapper [as init] (C:\inetpub\wwwroot\ember-test\node_modules\core-object\lib\assign-properties.js:32:18)
    at CoreObject.Class (C:\inetpub\wwwroot\ember-test\node_modules\core-object\core-object.js:32:33)


Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

Steps to reproduce (R:\ember-test\tmp is an empty folder on a ramdisk, but it should also work with any folder on any disk):
```
ember new ember-test
cd ember-test
mklink /d tmp R:\ember-test\tmp
ember s
```

Output from `ember version --verbose && npm --version`:
```
ember version --verbose:

ember-cli: 2.9.1
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: win32 x64


npm --version:

3.3.12
```

**Comment by jonnii** [comment]
How is your ramdisk formatted? Is it fat32 or NTFS? I've never got a ramdisk to work correctly using ember-cli.

**Comment by nathanhammond** [comment]
@sandreas Can you incrementally upgrade from 2.6 to 2.9 and let us know which version it starts to fail at? We made a number of Broccoli changes underneath the hood and it'd be good to identify what the underlying issue may be.

**Comment by sandreas** [comment]
@jonnii NTFS... i used ImDisk Toolkit with default settings and 1GB size (https://sourceforge.net/projects/imdisk-toolkit/)

@nathanhammond Sure, it'll take some time.

**Comment by nfc036** [comment]
Working on Windows 10 too. ImDisk is still working for me (currently on ember-cli 2.9.0). I use the following script to mount a Ramdisk to /tmp (not mklink'ing to a directory on an existing Ramdisk):
```
imdisk -D -m "C:\www\ember-app\tmp"
del /Q /S "C:\www\ember-app\tmp"
mkdir "C:\www\ember-app\tmp"
start C:\Windows\System32\imdisk.exe -a -s 300m -p "/fs:ntfs /q /y" -m "C:\www\ember-app\tmp"
```
Last line is the only important, the others are simply cleaning up if something is already there. I'm using this lines in a batch script that I call once before developing. And of course I'm working with Administrator rights.

**Comment by sandreas** [comment]
@nathanhammond OK, i upgraded incrementally from 2.6 to 2.9 and it worked as expected, i could not reproduce the error directly. After some days of working it happened again. Seems that it something weird with npm, where module linking (npm link) with my private repositories produces this error in an edge case.

I think this bug can be closed, because it is not a common issue. If it happens again, i'll reopen it.

**Comment by nathanhammond** [comment]
@sandreas _thank you_ for taking the time to track this down. I'm really appreciative for the additional documentation this issue provides and the research you did. It's good to know that the "common" case appears to be fine.

Still following along on this thread, so if things change do let me know!
