### ISSUE TITLE
[Ember-cli 2.10.0-beta.2] "tiny-lr" package breaks in node 0.12.x

### ISSUE THREAD

**Issue by samtsai** [ember-cli/ember-cli#6401]
Build is successful but when loading the site I encounter a `TypeError: undefined is not a function`.

I know this is not an "ember-cli" code issue but a dependency: "tiny-lr" package, so it's more of a question of should we expect 0.12.x support is already dropped with Ember 2.10.0-beta.2?

It seems the underlying issue is the Node version compatibility to support `Object.assign`, so I can workaround it by upgrading node versions locally but as a project team we're not ready to migrate just yet.

Opened ticket with "tiny-lr" to follow up with their project as well: https://github.com/mklabs/tiny-lr/issues/115

For reference: http://kangax.github.io/compat-table/es6/#node012

```
/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/src/client.js:80
        this.emit('info', Object.assign({}, data, { id: this.id }));
                                 ^
TypeError: undefined is not a function
    at Client.info (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/src/client.js:80:34)
    at Client.message (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/src/client.js:51:56)
    at EventTarget.dispatchEvent (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at instance._receiveMessage (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at null.<anonymous> (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emit (events.js:129:20)
    at null.<anonymous> (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/Users/tsaisa/Code/awp-ptc-upgrade/node_modules/ember-cli/node_modules/tiny-lr/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.10.0-beta.2
http_parser: 2.3
node: 0.12.9
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1q
os: darwin x64
2.14.9
```

**Comment by nathanhammond** [comment]
@samtsai Thank you for bringing this to our attention! Ember CLI 2.10 should support 0.12 and we will need to get back to a supported version of tiny-lr.

**Comment by nathanhammond** [comment]
Merged, waiting for release.

**Comment by nathanhammond** [comment]
Closing in favor of #6403.

**Comment by samtsai** [comment]
@nathanhammond Thanks for the quick turnaround!

**Comment by nathanhammond** [comment]
@samtsai Can you confirm that this works on ember-cli#canary?

**Comment by samtsai** [comment]
@nathanhammond just tested canary and it serves up local perfectly now! Thanks!
