### ISSUE TITLE
Have problem with ember-cli-import-polyfill

### ISSUE THREAD

**Issue by mellenaj** [ember-cli/ember-cli#6409]
Hello all! 
I cannot start my application by this problem (see the quote below), I tried to change versions of node, ember-cli and  ember-cli-import-polyfill, but nothing helps me. 

> My output is 

ember-cli:
 2.6.2
http_parser: 2.6.2
node: 5.9.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: darwin x64
3.7.3 

**Issue:**
> ➜ revenue_app_ember git:(bootstrap) ✗ ember s
Cannot read property 'app' of undefined
TypeError: Cannot read property 'app' of undefined
    at CoreObject.Addon.import (/Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-cli-moment-range/node_modules/ember-cli-import-polyfill/index.js:9:15)
    at CoreObject.module.exports.included (/Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-runtime-enumerable-includes-polyfill/index.js:19:27)
    at CoreObject.superWrapper [as included] (/Users/omaznichenko/projects/revenue_app_ember/node_modules/core-object/lib/assign-properties.js:32:18)
    at /Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-cli/lib/models/addon.js:248:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-cli/lib/models/addon.js:246:24)
    at CoreObject.extend.included (/Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-cli/lib/models/addon.js:385:10)
    at CoreObject.superWrapper [as included] (/Users/omaznichenko/projects/revenue_app_ember/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.module.exports.included (/Users/omaznichenko/projects/revenue_app_ember/node_modules/ember-data/index.js:116:26)
    at CoreObject.superWrapper [as included] (/Users/omaznichenko/projects/revenue_app_ember/node_modules/core-object/lib/assign-properties.js:32:18)

Thanks, for your attention.

**Comment by mellenaj** [comment]
changed ember-cli version to 2.8.0
