### ISSUE TITLE
ember s throwing "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by ssurana2** [ember-cli/ember-cli#6432]
Hi,

I just created a new project using `ember new testProject`. After the npm install and bower install, I tried to run ember s. I got the following error

```javascript
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at EmberApp._initVendorFiles (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/broccoli/ember-app.js:317:55)
    at new EmberApp (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/broccoli/ember-app.js:94:8)
    at module.exports (/Users/ssurana2/Desktop/Development/ember/testProject/ember-cli-build.js:6:13)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/lib/commands/serve.js:64:24
    at tryCatch (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/ssurana2/Desktop/Development/ember/testProject/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
```

The `package.json` file is
```javascript
{
  "name": "test-project",
  "version": "0.0.0",
  "description": "Small description for test-project goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.5.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  }
}
```

Output from `ember version --verbose && npm --version`:

```javascript
ember-cli: 2.5.0
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: darwin x64
2.15.9
```

**Comment by stefanpenner** [comment]
I've also noticed this. My suspicion is that a dependency bump'd itself in a non-semver way.

I believe an interim fix is bumping to the latest ember-cli from `2.5.0` to `2.9.1`

**Comment by stefanpenner** [comment]
line in question: https://github.com/ember-cli/ember-cli/blob/7c17e19a5839ce008e53fc51c26f2b71fd1fc9a7/lib/broccoli/ember-app.js#L336

**Comment by stefanpenner** [comment]
ah, i believe this is actually a lodash regression: https://github.com/ember-cli/ember-cli/blob/7c17e19a5839ce008e53fc51c26f2b71fd1fc9a7/lib/broccoli/ember-app.js#L306 i believe starts detecting `'ember-testing.js'` at https://github.com/ember-cli/ember-cli/blob/7c17e19a5839ce008e53fc51c26f2b71fd1fc9a7/lib/broccoli/ember-app.js#L313 as  as `ember-testing` `js` recently...

**Comment by stefanpenner** [comment]
i believe it is: https://github.com/lodash/lodash/issues/2810

**Comment by ssurana2** [comment]
@stefanpenner thanks for pointing to https://github.com/lodash/lodash/issues/2810. After referencing to `lodash@4.16.5`, the issue got resolved. So I guess, this is a temporary fix till the patch on lodash is pushed

**Comment by stefanpenner** [comment]
@ssurana2 awesome :)
