### ISSUE TITLE
Projects broken because of lodash recent update:: URGENT

### ISSUE THREAD

**Issue by Blackening999** [ember-cli/ember-cli#6433]
Hello,

the issue hit some projects because of recent lodash update:
https://github.com/lodash/lodash/commits/master

error-log:
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at EmberApp._initVendorFiles (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/broccoli/ember-app.js:317:55)
    at new EmberApp (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/broccoli/ember-app.js:94:8)
    at module.exports (/Users/black/Work/My_Projects/doinbound3/ember-cli-build.js:8:13)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Class.<anonymous> (/Users/black/Work/My_Projects/doinbound3/node_modules/ember-cli/lib/commands/test.js:162:27)
    at tryCatch (/Users/black/Work/My_Projects/doinbound3/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/black/Work/My_Projects/doinbound3/node_modules/rsvp/dist/rsvp.js:553:13)
    at /Users/black/Work/My_Projects/doinbound3/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/Users/black/Work/My_Projects/doinbound3/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

... ember-cli/package.json
```json
"lodash": "^4.6.1",
```
...

---

```
ember-cli: 2.5.1
http_parser: 2.6.0
node: 5.3.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
os: darwin x64
3.3.12
```

**Comment by twokul** [comment]
@Blackening999 it's an issue with `lodash@4.17.0`; `npm install --save-dev -E lodash@4.16.4 && rm -rf node_modules && npm install` should help you

**Comment by Blackening999** [comment]
@twokul yep. 4.17.1 fixed that issue
