### ISSUE TITLE
`(setq create-lockfiles nil)` shouldn't be necessary for Emacs usage

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ember-cli/ember-cli#6527]
From [this issue](https://github.com/ember-cli/ember-cli/issues/5857), it was noticed that an ENOENT error would occur when files would change. Apparently, this error still occurs when Ember picks up Emacs lock files.

I got the following error when editing and saving a file in my project with Emacs:

```
file changed router.js
ENOENT: no such file or directory, stat '/path/to/project/app/.#app.js'
Error: ENOENT: no such file or directory, stat '/path/to/project/app/.#app.js'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.realpathSync (fs.js:1679:12)
    at symlink (/path/to/project/node_modules/symlink-or-copy/index.js:68:26)
    at Function.symlinkOrCopySync [as sync] (/path/to/project/node_modules/symlink-or-copy/index.js:55:5)
    at Funnel._copy (/path/to/project/node_modules/broccoli-funnel/index.js:433:19)
    at Funnel.processFile (/path/to/project/node_modules/broccoli-funnel/index.js:416:8)
    at Funnel.applyPatch [as _applyPatch] (/path/to/project/node_modules/broccoli-funnel/index.js:333:12)
    at Funnel.<anonymous> (/path/to/project/node_modules/broccoli-funnel/index.js:287:10)
    at Array.forEach (native)
file changed app.js
ENOENT: no such file or directory, unlink '/path/to/project/tmp/funnel-output_path-BOpd48hh.tmp/.#app.js'
Error: ENOENT: no such file or directory, unlink '/path/to/project/tmp/funnel-output_path-BOpd48hh.tmp/.#app.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at Funnel.applyPatch [as _applyPatch] (/path/to/project/node_modules/broccoli-funnel/index.js:311:10)
    at Funnel.<anonymous> (/path/to/project/node_modules/broccoli-funnel/index.js:287:10)
    at Array.forEach (native)
    at Funnel.processFilters (/path/to/project/node_modules/broccoli-funnel/index.js:286:11)
    at Funnel.build (/path/to/project/node_modules/broccoli-funnel/index.js:202:10)
    at /path/to/project/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/path/to/project/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/path/to/project/node_modules/rsvp/dist/rsvp.js:553:13)
```

To reproduce, open one watched file in Emacs, and make an edit to the file, but do not save it. This will cause a lock file to be created. Then, edit another watched file in a project, and the error should occur.

The documentation recommends disabling lock files: https://ember-cli.com/user-guide/#emacs

I think this is the wrong recommendation. [The Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html) mentions this property, but also warns that file locking is actually useful:

> You can prevent the creation of lock files by setting the variable `create-lockfiles` to `nil`. **Caution:** by doing so you will lose the benefits that this feature provides.

I think that Ember CLI should instead endeavor to avoid this error when `create-lockfiles` is `t` ("true" in Emacs Lisp).

A similar issue popped up in `grunt-contrib-watch`: https://github.com/gruntjs/grunt-contrib-watch/issues/239 The solution there may also be applicable here.

Output from `ember version --verbose && npm --version`:
```
ember version --verbose && npm --version
WARNING: Node v6.9.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
version: 1.13.13
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
npm: 2.14.10
os: linux x64
3.10.8
```

Output from `emacs --version`
```
emacs --version
GNU Emacs 25.1.1
```

**Comment by stefanpenner** [comment]
we could change the system to simply ignore broken symlinks, i have been thinking about that for some time. This is what many other things do, it may result in hard to diagnose issues but so far the existing/usage of broken symlinks also causes hard to diagnose issues

**Comment by stefanpenner** [comment]
@rwjblue / @hjdivad thoughts on our system just ignoring them? in symlink or copy/merge-trees etc.

**Comment by rwjblue** [comment]
IMO, the better emacs setup is to store lock files in a central location (but not disabled). I'll share my config when back at my computer.

**Comment by rwjblue** [comment]
@stefanpenner - We could definitely ignore broken symlinks and not error like this, but I suspect that it could actually mask real errors that are better surfaced immediately.

**Comment by ef4** [comment]
I disable lockfiles entirely. I think it's a feature designed for the days of multi-user systems and it has very low value. The locking protocol is emacs-specific, so it doesn't actually protect you from concurrent changes by any other program.

Putting lockfiles elsewhere would also be fine, but that's not really a well-supported option. The problem is that lockfiles are supposed to tell you whether somebody else is editing the file in emacs, even if that user has a different configuration. So a customized location defeats the original intent. @rwjblue I am curious to see your config with centralized lockfiles. I centralize everything else (like backups and autosaves), but AFAIK there's no good option for lockfiles.

I think it would be good to make broccoli ignore broken symlinks by stripping them out when making a tree from a directory (at the first stage of a build pipeline). Deriving a tree from another tree could still error on a broken symlink, which is the bug case we'd care about.

**Comment by stefanpenner** [comment]
the actual issue that leads me to believe we should just ignore (but maybe warn) re: broken links https://github.com/broccolijs/broccoli-merge-trees/issues/52

**Comment by stefanpenner** [comment]
@ef4 thanks for the insight. I also don't role with lockfiles/swp files. The always just seem to get in the way. I already have GIT, i treat everything not in git as #yolo-ephemeral

@ef4 / @rwjblue i am curious if the two come to an agreement re: lock files and emacs

**Comment by rwjblue** [comment]
TBH, I don't find the lockfiles useful (for the same reasons as @ef4).  It is possible that I am misremembering my config (still not back at my computer).

**Comment by jacksonrayhamilton** [comment]
Whether some of us do or don't find lock files useful, Emacs does still create them by default, which means plenty of Emacs users who didn't read that part of the docs (like I didn't) will continue to trip over this and have a poor experience with the CLI. That alone might be a good enough reason to handle these things more gracefully.

**Comment by stefanpenner** [comment]
@jacksonrayhamilton maybe, it would be really nice if emacs didn't produce broken symlinks that actually cause other programs to error when they are encountered.

**Comment by hjdivad** [comment]
@stefanpenner @rwjblue seems like supporting a `.broccolirc` / `.brocignore` would handle this case as well.

**Comment by stefanpenner** [comment]
> @stefanpenner @rwjblue seems like supporting a .broccolirc / .brocignore would handle this case as well.

Sure, curious which part of the broccoli stack would filter these files out. If we doit at the start, I fear we will incur many extra  costly IO traversals. But maybe could doit in merge + the watcher, which should mitigate most issues..

**Comment by hjdivad** [comment]
> Sure, curious which part of the broccoli stack would filter these files out. If we doit at the start, I fear we will incur many extra costly IO traversals. But maybe could doit in merge + the watcher, which should mitigate most issues..

`walk-sync` already supports ignoring patterns.  Seems like we could either add support for global ignores (U with the passed in ignores) within walk-sync, or global within ember-cli that we have to propagate to all walk-syncs.

**Comment by locks** [comment]
Closing due to inactivity. Thanks everyone for the insights into the problem! If you feel this is still an issue, re-open the issue please!
