### ISSUE TITLE
modulePrefix undefined in an addon

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#6534]
Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.5.0
v8: 5.1.281.81
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
3.10.3
```

In an addon, I ran `ember g helper-test my-helper` and got
```
Couldn't determine test style - using QUnit
installing helper-test
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.decamelize (/Users/me/Code/my-addon/node_modules/ember-cli-string-utils/index.js:26:15)
    at Object.dasherize (/Users/me/Code/my-addon/node_modules/ember-cli-string-utils/index.js:51:18)
    at CoreObject.locals (/Users/me/Code/my-addon/node_modules/ember-cli-legacy-blueprints/blueprints/helper-test/index.js:38:43)
    at CoreObject.<anonymous> (/Users/me/Code/my-addon/node_modules/ember-cli/lib/models/blueprint.js:817:20)
    at initializePromise (/Users/me/Code/my-addon/node_modules/rsvp/dist/rsvp.js:588:5)
    at PromiseExt.Promise (/Users/me/Code/my-addon/node_modules/rsvp/dist/rsvp.js:1076:31)
    at new PromiseExt (/Users/me/Code/my-addon/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at CoreObject._locals (/Users/me/Code/my-addon/node_modules/ember-cli/lib/models/blueprint.js:816:12)
    at CoreObject._process (/Users/me/Code/my-addon/node_modules/ember-cli/lib/models/blueprint.js:405:17)
    at CoreObject.install (/Users/me/Code/my-addon/node_modules/ember-cli/lib/models/blueprint.js:441:17)
```

That seems to come from [here](
https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/v0.1.3/blueprints/helper-test/index.js#L38).

I generated this addon using `ember addon` from ember-cli 2.10.0.

**Comment by jamesarosen** [comment]
Scratch that. I was on a pre-ember-addon branch of the project, though I had all the ember-cli packages sitting in `node_modules/`.
