### ISSUE TITLE
`BROCCOLI_VIZ=1 ember build` is broken

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6579]
Currently, when linking against master and running `BROCCOLI_VIZ=1 ember build` the following error is triggered:

```js
Build failed.
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at Class._computeVizInfo (/Users/rjackson/src/open-source/ember-cli/lib/models/builder.js:96:31)
    at /Users/rjackson/src/open-source/ember-cli/lib/models/builder.js:315:26
    at tryCatch (/Users/rjackson/src/open-source/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/rjackson/src/open-source/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/rjackson/src/open-source/ember-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/rjackson/src/open-source/ember-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This was broken when we landed https://github.com/ember-cli/ember-cli/pull/6546.  In #6546 we added code that assumes that `resultAnnotation` is passed to our `Builder.prototype.build` method ([lib/models/builder.js#L96](https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L96)).  This is true when our build is triggered by `ember-cli-broccoli-sane-watcher` due to changes upstream in https://github.com/ember-cli/broccoli-sane-watcher/pull/8. 

The fundamental issue is that when running `ember build` we do not go through `ember-cli-broccoli-sane-watcher` at all, and we manually invoke our `Builder.prototype.build` method in the build task ([lib/tasks/build.js#L22](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/build.js#L22)) but pass in no options.

We either need to make all builds funnel through ember-cli-broccoli-sane-watcher (which seems _somewhat_ odd when we don't want a watcher) or make our build task emit the correct result annotation.

**Comment by rwjblue** [comment]
**Note:** This does not affect `BROCCOLI_VIZ=1 ember serve`, which still works properly (since the `.build` method is invoked by ember-cli-broccoli-sane-watcher).
