### ISSUE TITLE
Error: No asset files found in the path provided: dist/

### ISSUE THREAD

**Issue by MartinMalinda** [ember-cli/ember-cli#6619]
```
ember-cli: 2.11.0-beta.1
http_parser: 2.7.0
node: 5.12.0
v8: 4.6.85.32
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2h
os: darwin x64
3.8.6
```

On `ember build --environment=production`, I get:

```
Error: No asset files found in the path provided: dist/
    at AssetPrinterSize.validateAssetPath (/builds/MartinMalinda/scribe/node_modules/ember-cli/lib/models/asset-size-printer.js:80:11)
    at AssetPrinterSize.<anonymous> (/builds/MartinMalinda/scribe/node_modules/ember-cli/lib/models/asset-size-printer.js:17:10)
    at tryCatch (/builds/MartinMalinda/scribe/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/builds/MartinMalinda/scribe/node_modules/rsvp/dist/rsvp.js:553:13)
    at /builds/MartinMalinda/scribe/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/builds/MartinMalinda/scribe/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I am setting off fignerprinting in ember-cli-build.js, otherwise there's nothing special about my build.
After the build, when I check the `./dist/assets/` all the asset files are actually there.

It happens both locally and in gitlab ci.

**Comment by OpakAlex** [comment]
@MartinMalinda it happens for me too.

**Comment by OpakAlex** [comment]
I known solution @MartinMalinda You have to buy some ember `T-shirts` ))))))

**Comment by MartinMalinda** [comment]
Yeah it seems like this:
https://github.com/ember-cli/ember-cli/blob/master/lib/models/asset-size-printer.js#L79

Does not match the asset files anymore, since a `gz` extension is being added to them now. It works with `'/**/*.{css,js,css.gz,js.gz}'`

**Comment by OpakAlex** [comment]
@MartinMalinda yes, or add compress gz to app, and it will work.
```
      gzip:  {
        enabled: true,
        keepUncompressed: true
      }
```

**Comment by MartinMalinda** [comment]
I have uninstalled `ember-cli-gzip` for now. Not sure if this is ember-cli or ember-cli-gzip issue though.

**Comment by twokul** [comment]
@MartinMalinda I actually removed `validateAssetPath` method and `AssetPrinterSize` should no longer throw errors.

does it show a correct list of files with original/gzip size though?

**Comment by MartinMalinda** [comment]
@twokul I tried to run from master or from that exact commit, but I'm getting:

`Error: Missing template processor`

**Comment by locks** [comment]
Hi! Can you confirm is this problem is present in current releases?

**Comment by locks** [comment]
Closing due to inactivity. Please re-open if you encounter the problem again!
