### ISSUE TITLE
Serve and Build fail if a parent directory has a package.json file containing Babel presets

### ISSUE THREAD

**Issue by Kerrick** [ember-cli/ember-cli#6638]
Similar to meteor/meteor#5654, `ember s` and `ember b` fail when the ember app has an ancestor directory (does not have to be a direct parent) where there is a `package.json` that includes plugins/presets in the `babel` section.

---

I've created a repo you can clone to reproduce the issue at [Kerrick/ember-cli-example-failure](https://github.com/Kerrick/ember-cli-example-failure).

Here's my error output from `ember s`:

```
kerrick@kadabra:~/Temporary/ember-cli-example-failure/example-app (master)
❯ ember s
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: modules/ember-inflector/index.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
ReferenceError: [BABEL] modules/ember-inflector/index.js: Unknown option: /Users/kerrick/Temporary/ember-cli-example-failure/package.json.presets
    at Logger.error (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-babel-transpiler/index.js:105:21)
    at Babel.processString (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-babel-transpiler/index.js:204:25)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.toTree (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/ember-cli-babel/index.js:30:52)
    at /Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at Function.module.exports.preprocessJs (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at Class.preprocessJs (/Users/kerrick/Temporary/ember-cli-example-failure/example-app/node_modules/ember-cli/lib/models/addon.js:814:25)

```

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.8
```

**Comment by locks** [comment]
Thanks for filing the report. Does this still happen in current versions of ember-cli?

**Comment by Kerrick** [comment]
Newly tested.

Output from `ember version --verbose && npm --version`:

```
ember-cli: 3.16.0
http_parser: 2.8.0
node: 10.14.2
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
```

---

Here's my output from `ember s`:

```
Kerrick-MacBook-Pro:example-app kerricklong$ ember s

Build successful (12200ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: @ember/test-helpers (2)                | 2316ms (1158 ms)
Package /assets/vendor.js (1)                 | 1371ms
Babel: @ember-data/store (2)                  | 1163ms (581 ms)
BroccoliRollup (6)                            | 1152ms (192 ms)
Babel: ember-inflector (1)                    | 755ms

```

Just to confirm, I still _do_ get the error in the above-linked example repository, which runs on 2.10.0. But it looks like it's not an issue with the 3.16.0.

**Comment by rwjblue** [comment]
OK, that is awesome. I think that means we can close this out then, sorry for the super long timeframe here...
