### ISSUE TITLE
TestLoader is loading the model with the wrong name

### ISSUE THREAD

**Issue by victor95pc** [ember-cli/ember-cli#6810]
Hi I trying to create a test for my model and the TestLoader.loadModules isn't loading the right model name, can someone explain why it happened?

PS: AbstractModel is just a DS.Model

Models:

```javascript
//app/models/juridico/pasta.js
import Ember from 'ember';
import AbstractModel from 'juridico-sengerj/models/abstract-model';
import DS from 'ember-data';

export default AbstractModel.extend({
	atendimento:      DS.belongsTo('juridico/advogado/atendimento'),
	pastaAvulsa:      DS.belongsTo('juridico/pasta-avulsa'),
        encerramento:     DS.belongsTo('juridico/pasta-encerrada'),
	ocorrencias:      DS.hasMany('juridico/ocorrencia', { inverse: "pasta" }),
	objetosAcao:      DS.hasMany('juridico/objeto-acao'),
	reus:             DS.hasMany('juridico/reu'),
	tipoReclamacoes:  DS.hasMany('juridico/tipo-reclamacao'),

});

```

```javascript
//app/models/juridico/ocorrencia.js
import AbstractModel from 'juridico-sengerj/models/abstract-model';
import DS from 'ember-data';
import Ember from 'ember';

export default AbstractModel.extend({
  tipoOcorrencia:   DS.belongsTo('juridico/tipo-ocorrencia'),
  mandadoPagamento: DS.belongsTo('juridico/mandado-pagamento'),
  acordo:           DS.belongsTo('juridico/acordo'),
  alvara:           DS.belongsTo('juridico/alvara'),
  pasta:            DS.belongsTo('juridico/pasta', { inverse: "ocorrencias" }),
  documentos:       DS.hasMany('documento'),
  notas:            DS.hasMany('nota')
});

```

Test:

```javascript
//tests/unit/models/pasta-test.js
import { moduleForModel, test } from 'ember-qunit';

moduleForModel('juridico/pasta', 'Unit | Model | juridico/pasta', {
  // Specify the other units that are required for this test.
  needs: ["model:juridico/advogado/atendimento", "model:juridico/pasta-avulsa", "model:juridico/pasta-encerrada", "model:juridico/ocorrencia", "model:juridico/objeto-acao", "model:juridico/reu", "model:juridico/tipo-reclamacao"]
});

test('it exists', function(assert) {
  let model = this.subject();
  // let store = this.store();
  assert.ok(!!model);
});
```

StackTrace:

```
Died on test #1     at testWrapper (http://localhost:7357/assets/test-support.js:6663:11)
    at test (http://localhost:7357/assets/test-support.js:6677:39)
    at Module.callback (http://localhost:7357/assets/tests.js:17077:24)
    at Module.exports (http://localhost:7357/assets/vendor.js:140:32)
    at requireModule (http://localhost:7357/assets/vendor.js:32:18)
    at TestLoader.require (http://localhost:7357/assets/test-loader.js:67:9)
    at TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:58:18): No model was found for 'juridico/ocorrencium'
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.9.4
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2j
os: linux x64
3.10.10

```

**Comment by Turbo87** [comment]
can you try `moduleForModel('juridico.pasta'` instead?

**Comment by victor95pc** [comment]
Didn't worked

**Comment by stefanpenner** [comment]
`juridico/ocorrencium` looks like its trying to inflect `juridico/ocorrencia` to `juridico/ocorrencium`

the may be:

```
Ember.Inflector.inflector.uncountable(`juridico/ocorrencia`)
```

---

This does not appear to be an ember-cli issue, rather a question. In-order to keep the issue tracker under-control we recommend questions be directed to stackoverflow.
