### ISSUE TITLE
Error: ENOENT: no such file or directory, ember-cli-shims/app-shims.js

### ISSUE THREAD

**Issue by Folatt** [ember-cli/ember-cli#6854]
Adding ember-cli-shims in the bower dependencies causes this error for me.
app-shims.js has moved from {packagedir} to {packagedir}/vendor/ember-cli-shims in the 1.x version of ember-cli-shims.

Unless this requires me to write some line of code that I don't know about, I consider this to be a bug in `lib/broccoli/empber-app.js`

Works when I change this line:

```diff
@@ -298,300 +298,300 @@
    if (bowerEmberCliShims) {
--     emberShims = this.bowerDirectory + '/ember-cli-shims/app-shims.js';
++     emberShims = this.bowerDirectory + '/ember-cli-shims/vendor/ember-cli-shims/app-shims.js';
    }
```

---

Output from `ember build`:
```
[folatt@ArkOS-Dev genesis]$ ember build
cleaning up...
Build failed.
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/home/folatt/workspace/arkos/genesis/tmp/source_map_concat-input_base_path-ylXRuJMg.tmp/bower_components/ember-cli-shims/app-shims.js'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at SourceMap.addFile (/home/folatt/workspace/arkos/genesis/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /home/folatt/workspace/arkos/genesis/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/home/folatt/workspace/arkos/genesis/node_modules/broccoli-concat/concat.js:198:24)
    at /home/folatt/workspace/arkos/genesis/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/home/folatt/workspace/arkos/genesis/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise (/home/folatt/workspace/arkos/genesis/node_modules/rsvp/dist/rsvp.js:1077:31)
    at SourceMap.end (/home/folatt/workspace/arkos/genesis/node_modules/fast-sourcemap-concat/lib/source-map.js:380:10)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/home/folatt/workspace/arkos/genesis/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/home/folatt/workspace/arkos/genesis/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/home/folatt/workspace/arkos/genesis/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/broccoli/ember-app.js:392:10)
    at EmberApp._concatFiles (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/broccoli/ember-app.js:405:15)
    at EmberApp.javascript (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/broccoli/ember-app.js:1297:12)
    at EmberApp.toArray (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
    at module.exports (/home/folatt/workspace/arkos/genesis/ember-cli-build.js:89:14)
    at Class.setupBroccoliBuilder (/home/folatt/workspace/arkos/genesis/node_modules/ember-cli/lib/models/builder.js:84:19)
```

**Comment by kumkanillam** [comment]
Why do you want to include  ember-cli-shims in the bower.json?. From [ember-cli version 2.11.0](https://github.com/ember-cli/ember-new-output/compare/v2.10.1...v2.11.0), they moved `ember-cli-shims` dependancy from bower.json to package.json.  I tried [answer](http://stackoverflow.com/a/42747630/5771666) this question in SO.

**Comment by Folatt** [comment]
I did not know that. Thank you. Close this thread.
