### ISSUE TITLE
Ember.trySet is designed to be error tolerant Ember.set, but it is not working as expected

### ISSUE THREAD

**Issue by JennieJi** [ember-cli/ember-cli#6855]
Background: I have a component A, and there's an promise in A which will *SET* an attribute of A once promise resolved. So I used Ember.trySet(this, 'myAttribute', 'updateValue'), but I got following error when this component was destroyed due to transition but promise was still going on.

>Assertion Failed: calling set on destroyed object: <seller@component:A>.myAttribute = 'updateValue'
Error
    at assert (http://localhost:4200/assets/vendor.js:20671:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:31599:34)
    at set (http://localhost:4200/assets/vendor.js:36259:22)
    at Object.trySet (http://localhost:4200/assets/vendor.js:36365:12)
    at get.promise.then.e (http://localhost:4200/assets/seller.js:2715:29)
    at tryCatch (http://localhost:4200/assets/vendor.js:73121:12)
    at invokeCallback (http://localhost:4200/assets/vendor.js:73133:13)
    at publish (http://localhost:4200/assets/vendor.js:73104:7)
    at publishRejection (http://localhost:4200/assets/vendor.js:73047:3)
    at http://localhost:4200/assets/vendor.js:52589:16

Environment:
> Ember      : 2.10.2
Ember Data : 2.11.3
jQuery     : 3.1.1

**Comment by xm** [comment]
See emberjs/ember.js#12356 and emberjs/ember.js#13355

**Comment by kellyselden** [comment]
Thanks @xm. Appears to be in process upstream.
