### ISSUE TITLE
Error: EEXIST: file already exists, symlink 

### ISSUE THREAD

**Issue by tkyeung357** [ember-cli/ember-cli#6891]
hi, i am new to ember and keep occur build failed when change code via emacs.
It is because file ".DS_Store" ? Can anyone tell me how to solve it.
Thank!
````
file changed components/login-panel.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: ember-inflector]: Babel: ember-inflector] failed with:
Error: EEXIST: file already exists, symlink '/Users/timyeung/Development/Dev/webapp/tmp/broccoli_persistent_filterbabel__babel_ember_inflector-input_base_path-R3C1WKLJ.tmp/.DS_Store' -> '/Users/timyeung/Development/Dev/webapp/tmp/broccoli_persistent_filterbabel__babel_ember_inflector-output_path-1TDW03Nr.tmp/.DS_Store'
    at Object.fs.symlinkSync (fs.js:1034:18)
    at symlink (/Users/timyeung/Development/Dev/webapp/node_modules/symlink-or-copy/index.js:98:14)
    at symlinkOrCopySync (/Users/timyeung/Development/Dev/webapp/node_modules/symlink-or-copy/index.js:65:5)
    at Babel.Filter._handleFile (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-persistent-filter/index.js:178:12)
    at Babel.<anonymous> (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-persistent-filter/index.js:155:23)
    at /Users/timyeung/Development/Dev/webapp/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/timyeung/Development/Dev/webapp/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/timyeung/Development/Dev/webapp/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/timyeung/Development/Dev/webapp/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/timyeung/Development/Dev/webapp/node_modules/rsvp/dist/rsvp.js:2414:5)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/timyeung/Development/Dev/webapp/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.toTree (/Users/timyeung/Development/Dev/webapp/node_modules/ember-cli-babel/index.js:30:52)
    at /Users/timyeung/Development/Dev/webapp/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/timyeung/Development/Dev/webapp/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at Function.module.exports.preprocessJs (/Users/timyeung/Development/Dev/webapp/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at Class.preprocessJs (/Users/timyeung/Development/Dev/webapp/node_modules/ember-cli/lib/models/addon.js:1099:25)
````

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.12.0
http_parser: 2.7.0
node: 7.7.4
v8: 5.5.372.42
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2
```

**Comment by tkyeung357** [comment]
I just recognize emacs backup file causing rebuild failed #3908

**Comment by tkyeung357** [comment]
Update: https://ember-cli.com/user-guide/#emacs
