### ISSUE TITLE
SIGINT fails to clear tmp

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-cli/ember-cli#6902]
Builds are green on Travis, but fail on OSX El Capitan 

```
  2 failing

  1) Acceptance: smoke-test ember new foo, server, SIGINT clears tmp/:

      /tmp should be empty
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (tests/acceptance/smoke-test-slow.js:299:51)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at tryCatch (node_modules/rsvp/dist/rsvp.js:539:12)
      at invokeCallback (node_modules/rsvp/dist/rsvp.js:554:13)
      at publish (node_modules/rsvp/dist/rsvp.js:522:7)
      at flush (node_modules/rsvp/dist/rsvp.js:2374:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) Acceptance: smoke-test ember new foo, test, SIGINT exits with error and clears tmp/:

      /tmp should be empty
      + expected - actual

      -1
      +0
      
      at Context.<anonymous> (tests/acceptance/smoke-test-slow.js:316:51)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at tryCatch (node_modules/rsvp/dist/rsvp.js:539:12)
      at invokeCallback (node_modules/rsvp/dist/rsvp.js:554:13)
      at publish (node_modules/rsvp/dist/rsvp.js:522:7)
      at flush (node_modules/rsvp/dist/rsvp.js:2374:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)



Mocha Tests Running Time: 335215.337ms

```

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.13.0-beta.2-master-c6c7199a54
http_parser: 2.7.0
node: 7.7.3
v8: 5.5.372.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2
```

**Comment by ro0gr** [comment]
@tylerturdenpants have you tried to interrupt ember server manually? Is your /tmp empty after ctrl+c?

**Comment by tylerturdenpants** [comment]
@ro0gr this not an issue with using ember server. The issue is that when running npm tests before committing to a PR these test fail consistently. They fail on both my work OS X install and on my home OS X install.

**Comment by ro0gr** [comment]
This test has been slightly changed recently https://github.com/ember-cli/ember-cli/pull/6615/files#diff-d75db6277f3ecfc39cf8a8b795f8dc3eR335.
I've tried to reproduce failure you described on win10(have no any OS X devices) but no luck. So at this point we have SIGINT tests passing for both windows and linux nd failing for OS X.

I think it can be very helpfull if you confirm if this test passes in the release branch(before the [command  interruption staff](https://github.com/ember-cli/ember-cli/pull/6615) appeared)

**Comment by romulomachado** [comment]
I have the same problem.

**Comment by Turbo87** [comment]
@hjdivad do you have time to look into this?

**Comment by hjdivad** [comment]
@Turbo87 i'll try to take a look tonight or tomorrow

**Comment by locks** [comment]
Is this still a problem?

**Comment by tylerturdenpants** [comment]
I don’t think so. It’s safe to close.
