### ISSUE TITLE
Fail to new project

### ISSUE THREAD

**Issue by windwww** [ember-cli/ember-cli#6922]
I just build a new droplet on digitalocean and install ember-cli
but fail to new a project
does anyone have idea what's going wrong

> root@ezwork:~# ember new ember-quickstart
> installing app
>   create .bowerrc
>   create .editorconfig
>   create .ember-cli
>   create .eslintrc.js
>   create .travis.yml
>   create .watchmanconfig
>   create README.md
>   create app/app.js
>   create app/components/.gitkeep
>   create app/controllers/.gitkeep
>   create app/helpers/.gitkeep
>   create app/index.html
>   create app/models/.gitkeep
>   create app/resolver.js
>   create app/router.js
>   create app/routes/.gitkeep
>   create app/styles/app.css
>   create app/templates/application.hbs
>   create app/templates/components/.gitkeep
>   create bower.json
>   create config/environment.js
>   create ember-cli-build.js
>   create .gitignore
>   create package.json
>   create public/crossdomain.xml
>   create public/robots.txt
>   create testem.js
>   create tests/.eslintrc.js
>   create tests/helpers/destroy-app.js
>   create tests/helpers/module-for-acceptance.js
>   create tests/helpers/resolver.js
>   create tests/helpers/start-app.js
>   create tests/index.html
>   create tests/integration/.gitkeep
>   create tests/test-helper.js
>   create tests/unit/.gitkeep
>   create vendor/.gitkeep
> Error creating new application. Removing generated directory `./ember-quickstart`
> Command failed: npm install --no-optional --loglevel error
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
> Error: Command failed: npm install --no-optional --loglevel error
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
>     at Promise.all.then.arr (/usr/lib/node_modules/ember-cli/node_modules/execa/index.js:210:11)
>     at process._tickCallback (internal/process/next_tick.js:109:7)
> root@ezwork:~# ember version --verbose && npm --version
> ember-cli: 2.12.1
> http_parser: 2.7.0
> node: 6.10.1
> v8: 5.1.281.95
> uv: 1.9.1
> zlib: 1.2.8
> ares: 1.10.1-DEV
> icu: 56.1
> modules: 48
> openssl: 1.0.2k
> os: linux x64
> 4.4.4

**Comment by windwww** [comment]
Solve...
Not enough RAM
