### ISSUE TITLE
Error on Creating a Component

### ISSUE THREAD

**Issue by ietuday** [ember-cli/ember-cli#6924]
After creating a component getting this error :
I am using the rental and rental-listing example in guides.emberjs.com.

[https://guides.emberjs.com/v2.12.0/tutorial/simple-component/)

Error: Parse error on line 31:
...icle> -->{{/each}}
---------------------^
Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'
    at Object.parseError (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:25867:23)
    at Object.parse (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:25936:34)
    at Object.parse (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:25519:59)
    at Object.preprocess (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:23892:77)
    at precompile (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:12180:34)
    at Object.precompile (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-source/dist/ember-template-compiler.js:11342:12)
    at Object.template (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-htmlbars/utils.js:29:40)
    at TemplateCompiler.processString (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-htmlbars/index.js:68:36)
    at Promise.then.result.output (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/rsvp/dist/rsvp.js:589:5)

The broccoli plugin was instantiated at: 
    at TemplateCompiler.Plugin (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/broccoli-plugin/index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new TemplateCompiler (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-htmlbars/index.js:20:10)
    at TemplateCompiler (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-htmlbars/index.js:12:12)
    at Object.toTree (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-htmlbars/ember-addon-main.js:32:34)
    at /home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
    at EmberApp._processedTemplatesTree (/home/ridesoft/test-project/ember-demo/super-rentals/node_modules/ember-cli/lib/broccoli/ember-app.js:851:48)

Please help in solving this issue.

Thanks in advance

**Comment by kumkanillam** [comment]
It's just syntax issue. mostly html element are not properly closed.
```{{#each model as |rentalUnit|}}
  {{rental-listing rental=rentalUnit}}
{{/each}}```
`-` > It denotes that we should remove those line.
If you can post your hbs code, we can easily point out exactly.

**Comment by ietuday** [comment]
Thanks for commenting on my issue. 

rental.hbs

<div class="jumbo">
  <div class="right tomster"></div>
  <h2>Welcome!</h2>
  <p>
    We hope you find exactly what you're looking for in a place to stay.
  </p>
  {{#link-to 'about' class="button"}}
    About Us
  {{/link-to}}
</div>

{{#each model as |rentalUnit|}}
  {{rental-listing rental=rentalUnit}}

{{/each}}

**Comment by ietuday** [comment]
Hey, kumkanillam 

I solved the issue thanks for help.
