### ISSUE TITLE
Error: ENOENT: no such file or directory : module-template.js.t

### ISSUE THREAD

**Issue by wellington1993** [ember-cli/ember-cli#6946]
Hi,

I have this problem on private project build.

I remember another problem like this when to solve I moved a file during build, but I don't remember exactly the path of file.

Any idea abou this problem?
Thanks!

Really Sorry if duplicated.

```
➜  my_project git:(my_branch) ✗ ember s
DEPRECATION: ember-cli-test-loader should now be included as an NPM module with version 1.1.0 or greater.
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [object Object] failed with:
Error: ENOENT: no such file or directory, stat '/home/wellington/my_project/node_modules/ember-network/assets/module-template.js.t'
  at Error (native)
  at Object.fs.statSync (fs.js:844:18)
  at Filter.Template.currentTemplateFile (/home/wellington/my_project/node_modules/broccoli-templater/index.js:22:18)
  at Filter.Template.processAndCacheFile (/home/wellington/my_project/node_modules/broccoli-templater/index.js:45:27)
  at /home/wellington/my_project/node_modules/broccoli-templater/node_modules/broccoli-filter/index.js:43:23
  at /home/wellington/my_project/node_modules/promise-map-series/index.js:11:14
  at tryCatch (/home/wellington/my_project/node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (/home/wellington/my_project/node_modules/rsvp/dist/rsvp.js:554:13)
  at /home/wellington/my_project/node_modules/rsvp/dist/rsvp.js:629:16
  at flush (/home/wellington/my_project/node_modules/rsvp/dist/rsvp.js:2414:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)


The broccoli plugin was instantiated at: 
undefined


cleaning up...
```

---

Output from `ember version --verbose && npm --version`:
```
ember version --verbose && npm --version 
ember-cli: 2.12.1
http_parser: 2.7.0
node: 4.7.2
v8: 4.5.103.43
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 46
openssl: 1.0.2g
os: linux x64
4.4.4

```

**Comment by stefanpenner** [comment]
some questions

* what is in the following folder: /home/wellington/my_project/node_modules/ember-network/assets/
* what version of ember-network are you using?

**Comment by stefanpenner** [comment]
Also let me recommend switching from ember-network -> ember-fetch, They are very similar projects (API should be the same) except that ember-fetch is the original and actively maintained: https://github.com/stefanpenner/ember-fetch

**Comment by wellington1993** [comment]
@stefanpenner Sorry for the time whiteout response.

Thanks for the solution.

**Comment by wellington1993** [comment]
I forgot your reply notification bacause I've needed a notifications 
maintenance in my account from Github. @stefanpenner 

By the way thanks!
