### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat ''

### ISSUE THREAD

**Issue by bjwouda** [ember-cli/ember-cli#6950]
Hello,

First off, I should mention I'm not too well-versed in this particular area of applications (node, npm, ember, etc.). For work I'm learning it so I can continue working on this software: https://github.com/kaikoehn/tomato-trade

Unfortunately, a fresh clone combined with the usual installation steps ends up in the following error **when building**:

```
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat ''
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at symlinkWindows (C:\...\tomato-trade\node_modules\symlink-or-copy\index.js:106:25)
    at symlinkOrCopySync (C:\...\tomato-trade\node_modules\symlink-or-copy\index.js:63:5)
    at C:\...\tomato-trade\node_modules\broccoli-plugin\read_compat.js:86:11
    at tryCatch (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\...\tomato-trade\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\...\tomato-trade\node_modules\broccoli-funnel\index.js:58:10)
    at CoreObject.treeForVendor (C:\...\tomato-trade\node_modules\ember-progress-bar\index.js:20:12)
    at CoreObject._treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:358:33)
    at CoreObject.treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:326:21)
    at C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:465:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:463:30)
    at EmberApp._processedVendorTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:919:29)
    at EmberApp._processedExternalTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:949:21)
```

and the following error **when serving**:

```
Livereload server on http://localhost:49155
Serving on http://localhost:4200/
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory:
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (C:\...\tomato-trade\node_modules\broccoli-sane-watcher\index.js:90:11)
    at C:\...\tomato-trade\node_modules\ember-cli-broccoli\lib\builder.js:95:35
    at tryCatch (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:554:13)
    at C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:629:16
    at flush (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\...\tomato-trade\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\...\tomato-trade\node_modules\broccoli-funnel\index.js:58:10)
    at CoreObject.treeForVendor (C:\...\tomato-trade\node_modules\ember-progress-bar\index.js:20:12)
    at CoreObject._treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:358:33)
    at CoreObject.treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:326:21)
    at C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:465:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:463:30)
    at EmberApp._processedVendorTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:919:29)
    at EmberApp._processedExternalTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:949:21)
```

I have attempted to locate the source through both Googling and poking around, but I was unable to find much. The best I can do is tell you that it involves attempts to work with a file where the empty string is provided as the filename. I know from some console logging that the build error occurs during the symlink-or-copying phase: it attempts to symlink-or-copy the empty filename to a broccoli .tmp directory.

I'm running this on Windows 7 x64. I have personally seen this software working correctly on a server, which ran Linux, and the software was developed on OSX. This could suggest the issue is Windows only.

I'm using:

npm: 3.10.10
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: win32 x64

**Comment by stefanpenner** [comment]
Point of reference, seems to work in on OSX.

Someone have to try this on a windows machine... I'm not home right now so I dont have one handy, @kellyselden  got any cycles?

**Comment by bjwouda** [comment]
We also tried a fresh install on my coworker's Windows machine. It produces the exact same errors.

**Comment by bjwouda** [comment]
Also tried it with Node.js 7.9.0. No difference, I'm afraid.

**Comment by bjwouda** [comment]
We've also just verified that an empty Ember project does work on these machines.

**Comment by stefanpenner** [comment]
@bjwouda Ya, i gotta find time \w a windows box :)

**Comment by bjwouda** [comment]
We also got the original programmer to take a look at it but unfortunately no luck so far. He thought maybe it was something with the versions/dependencies.

**Comment by kellyselden** [comment]
I'll take a look at ember-cli 2.6.2 on a Windows machine this weekend. In the meantime, @bjwouda you could try upgrading to the latest ember-cli and see if that helps.

**Comment by bjwouda** [comment]
@kellyselden I think that's what the original programmer tried. I'll try it again.

**Comment by bjwouda** [comment]
No luck :/

```
ember-cli: 2.13.0-beta.3
node: 6.10.2
os: win32 x64
```

```
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat ''
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at symlinkWindows (C:\...\tomato-trade\node_modules\symlink-or-copy\index.js:106:25)
    at symlinkOrCopySync (C:\...\tomato-trade\node_modules\symlink-or-copy\index.js:63:5)
    at C:\...\tomato-trade\node_modules\broccoli-plugin\read_compat.js:86:11
    at tryCatch (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\...\tomato-trade\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\...\tomato-trade\node_modules\broccoli-plugin\index.js:7:31)
    at new Funnel (C:\...\tomato-trade\node_modules\broccoli-funnel\index.js:58:10)
    at Class.treeForVendor (C:\...\tomato-trade\node_modules\ember-progress-bar\index.js:20:12)
    at Class._treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:520:33)
    at Class.treeFor (C:\...\tomato-trade\node_modules\ember-cli\lib\models\addon.js:480:21)
    at project.addons.map.addon (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:538:22)
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:536:32)
    at EmberApp._processedVendorTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:960:24)
    at EmberApp._processedExternalTree (C:\...\tomato-trade\node_modules\ember-cli\lib\broccoli\ember-app.js:988:25)
```

**Comment by stefanpenner** [comment]
@bjwouda my guess is that https://github.com/null-null-null/ember-progress-bar/blob/master/index.js#L23 isn't windows compatible.

**Comment by stefanpenner** [comment]
this may fix the issue: https://github.com/null-null-null/ember-progress-bar/pull/5

**Comment by stefanpenner** [comment]
At this point, I don't believe this is an issue with ember-cli, rather with the add-on in question (which the stack trace points to).

**Comment by bjwouda** [comment]
Thank you very much, @stefanpenner and friends! This indeed addresses the issue.

I very much appreciate the effort despite it turning out not to be an ember-cli bug. I don't think I could have resolved this very quickly myself, as I am new to this particular flavour of web development.
