### ISSUE TITLE
Could not require 'ember-cli-build.js': Cannot find module 'broccoli-plugin'

### ISSUE THREAD

**Issue by tsteuwer** [ember-cli/ember-cli#6962]
Hello there!

I just added my new Google Analytics addon in Travis CI and I'm getting the following error in all the ember-try scenarios:

Link to Travis CI: https://travis-ci.org/tsteuwer/ember-tracker/builds/222669111
Code: https://github.com/tsteuwer/ember-tracker

```
=== Scenario: ember-beta =======================================================
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Building
Could not require 'ember-cli-build.js': Cannot find module 'broccoli-plugin'
Error: Could not require 'ember-cli-build.js': Cannot find module 'broccoli-plugin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/tsteuwer/ember-tracker/node_modules/ember-cli/node_modules/broccoli-stew/lib/utils/noop.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/tsteuwer/ember-tracker/node_modules/ember-cli/node_modules/broccoli-stew/lib/log.js:8:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
Result: false
```

I'm not even sure where to start debugging from here. Has anyone else received this issue or know how to resolve it? I never get this issue during development or pushing/building the github pages.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.0
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
os: linux x64
3.8.6
```

**Comment by stefanpenner** [comment]
This is fixed: https://github.com/stefanpenner/broccoli-stew/pull/152 be sure you have the correct version of broccoli-stew installed (v1.4.2 or newer)

**Comment by tsteuwer** [comment]
Thanks @stefanpenner. I'll check it out now.

**Comment by tsteuwer** [comment]
@stefanpenner upgrading to  2.12.1 did indeed fix the issue. Thank you.
