### ISSUE TITLE
2.13 w/ Babel 5: TypeError: The plugin [null,{}] didn't export a Plugin instance 

### ISSUE THREAD

**Issue by jrr** [ember-cli/ember-cli#7008]
repro steps:
- `ember new` with ember-cli 2.13.0
- downgrade [ember-cli-babel](https://github.com/babel/ember-cli-babel) to e.g. "^5.0.0"
- `ember b`

_expected output:_ successful build

_actual output:_

```
Build failed.
File: two-thirteen-babel-five/app.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: two-thirteen-babel-five]: Babel: two-thirteen-babel-five] failed with:
TypeError: The plugin [null,{}] didn't export a Plugin instance
    at PluginManager.validate (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (/Users/jrr/two-thirteen-babel-five/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/Users/jrr/two-thirteen-babel-five/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/jrr/two-thirteen-babel-five/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/jrr/two-thirteen-babel-five/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/jrr/two-thirteen-babel-five/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.toTree (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-babel/index.js:30:52)
    at /Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessJs (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at EmberApp.appAndDependencies (/Users/jrr/two-thirteen-babel-five/node_modules/ember-cli/lib/broccoli/ember-app.js:1110:27)
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.0
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
0.23.3
```

**Comment by jrr** [comment]
(for future reference, `ember-cli-babel` 5.x depends on an older version of an older version of `ember-cli-htmlbars-inline-precompiler`. credit, as usual, to rwjblue for pointing this out.)

**Comment by rwjblue** [comment]
FWIW, I have a few changes outstanding to make this much more obvious and helpful:

* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/72 - To help folks using `ember-cli-htmlbars-inline-precompile@0.4` with `ember-cli-babel@5`.
* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/73 - To help folks using `ember-cli-htmlbars-inline-precompile@0.3` with `ember-cli-babel@6`.

**Comment by allthesignals** [comment]
So what's the solution for this? I can't build my project anymore because of something similar:

```
tests/tests.lint-test.js

The plugin [null,{"loose":true,"noInterop":true}] didn't export a Plugin instance
```
