### ISSUE TITLE
No such file or directory ember/app/styles

### ISSUE THREAD

**Issue by pocockn** [ember-cli/ember-cli#7031]
I recently upgraded to Ember cli 2.13.1 from 2.10, when I tried to run my app I got the error:

```
The Broccoli Plugin: [Funnel: Funnel (styles)] failed with:
Error: ENOENT: no such file or directory, lstat 'ember/app/styles'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (ember/node_modules/symlink-or-copy/index.js:79:26)
    at symlinkOrCopySync (ember/node_modules/symlink-or-copy/index.js:65:5)
    at /ember/node_modules/broccoli-plugin/read_compat.js:86:11
    at tryCatch (ember/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (ember/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (ember/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (ember/node_modules/rsvp/dist/rsvp.js:2414:5)
    at nextTickCallbackWith0Args (node.js:436:9)
```

It seems that a styles folder is compulsory in the app folder when it shouldn't be.

```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10

```

**Comment by kellyselden** [comment]
I just stumbled on this too. Our build system expects the "app/styles" folder, and if not there, it errors.

**Comment by kellyselden** [comment]
Here's the problem line https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/90a1c8add762b84b3c5ce1b57ef6b8e30e411b00/preprocessors.js#L106

**Comment by locks** [comment]
Closing due to inactivity. If you encounter this problem on a current release let us know!
