### ISSUE TITLE
ember-cli 2.13.1 serve/build failures (SourceMapConcat: Concat: Vendor /assets/vendor.js] failed)

### ISSUE THREAD

**Issue by twest7** [ember-cli/ember-cli#7034]
Receiving this error on existing project upgraded to ember-cli 2.13.1 and on brand new project.

**update to ember-cli 2.13.1**
```
npm uninstall -g ember-cli
yarn global remove ember-cli
yarn global add ember-cli@2.13.1
```

**reproduction steps**

create new project
`ember new sandbox`

add bootstrap dependency to package.json
```
  "dependencies": {
    "bootstrap": "^3.3.7"
  },
```

install dependencies
`yarn`

add app.import statements to ember-cli-build.js
```
  app.import('node_modules/bootstrap/dist/css/bootstrap.min.css');
  app.import('node_modules/bootstrap/dist/js/bootstrap.js');
  app.import('node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff', {
    destDir: 'fonts'
  });
  app.import('node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2', {
    destDir: 'fonts'
  });
```

attempt to serve
`ember s`

receive broccoli errors about missing files

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/home/thomas/dev/sandbox/tmp/source_map_concat-input_base_path-JGy5NpTO.tmp/node_modules/bootstrap/dist/js/bootstrap.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at SourceMap.addFile (/home/thomas/dev/sandbox/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /home/thomas/dev/sandbox/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/home/thomas/dev/sandbox/node_modules/broccoli-concat/concat.js:198:24)
    at /home/thomas/dev/sandbox/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/home/thomas/dev/sandbox/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/home/thomas/dev/sandbox/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/home/thomas/dev/sandbox/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/home/thomas/dev/sandbox/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/home/thomas/dev/sandbox/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp._concatFiles (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:432:12)
    at EmberApp.javascript (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1277:14)
    at EmberApp.toArray (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:12)
    at EmberApp.toTree (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/home/thomas/dev/sandbox/ember-cli-build.js:35:14)
    at Builder.setupBroccoliBuilder (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/models/builder.js:30:10)


The Broccoli Plugin: [Funnel: Funnel
    node_modules/bootstrap/dist/fonts
    fonts
   include:2] failed with:
Error: ENOENT: no such file or directory, scandir '/home/thomas/dev/sandbox/tmp/funnel-input_base_path-LhjbH5IO.tmp/node_modules/bootstrap/dist/fonts/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at _walkSync (/home/thomas/dev/sandbox/node_modules/walk-sync/index.js:64:18)
    at Function.entries (/home/thomas/dev/sandbox/node_modules/walk-sync/index.js:40:10)
    at Funnel.processFilters (/home/thomas/dev/sandbox/node_modules/broccoli-funnel/index.js:320:26)
    at Funnel.build (/home/thomas/dev/sandbox/node_modules/broccoli-funnel/index.js:258:10)
    at /home/thomas/dev/sandbox/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/thomas/dev/sandbox/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/thomas/dev/sandbox/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/home/thomas/dev/sandbox/node_modules/rsvp/dist/rsvp.js:522:7)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/home/thomas/dev/sandbox/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/home/thomas/dev/sandbox/node_modules/broccoli-funnel/index.js:58:10)
    at funnelReducer.map.options (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1486:14)
    at Array.map (native)
    at EmberApp.otherAssets (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1480:63)
    at EmberApp.toArray (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:12)
    at EmberApp.toTree (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/home/thomas/dev/sandbox/ember-cli-build.js:35:14)
    at Builder.setupBroccoliBuilder (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/thomas/dev/sandbox/node_modules/ember-cli/lib/models/builder.js:30:10)
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10
0.23.4
```

**Comment by stefanpenner** [comment]
> add app.import statements to ember-cli-build.js

`bower_components/` and `vendor/` are the two places where you can `app.import` `node_modules` due to the size of node_modules is currently not supported. Although it could be explored that would be a nice feature and isn't considered a bug today.

**Comment by twest7** [comment]
Ahh, that's correct, it's not upgrading ember-cli that caused the issue.  It was the simultaneous migration to Yarn away from npm & bower that causes this issue.  Adding bower.json/etc. back to project and loading from bower_components fixed the error.

It seems ember-cli is moving away from bower too as it no longer mentions it in the release notes nor creates a bower.json as part of ```ember new``` or ```ember init```.

**Comment by AnnaNee** [comment]
For Googlers, this is no longer an issue as noted in: https://github.com/ember-cli/ember-cli.github.io/issues/175
