### ISSUE TITLE
After installing, while ember server this came up...

### ISSUE THREAD

**Issue by theacastus** [ember-cli/ember-cli#7039]
Hi,

today I took a look into an EmberJS and I wanted to start working on my first app, but after running `ember new <app name>` and trying to see if it works usign `ember server` the following error has been occured:
```
$ ember server

Running without permission to symlink will degrade build peformance.
See http://ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49153
File: app.js
The Broccoli Plugin: [broccoli-persistent-filter:EslintValidationFilter] failed with:
Error: No ESLint configuration found.
    at getLocalConfig (C:\Users\acast\Desktop\DDM\web\node_modules\eslint\lib\config.js:162:35)
    at Config.getConfig (C:\Users\acast\Desktop\DDM\web\node_modules\eslint\lib\config.js:260:26)
    at CLIEngine.getConfigForFile (C:\Users\acast\Desktop\DDM\web\node_modules\eslint\lib\cli-engine.js:776:29)
    at EslintValidationFilter.cacheKeyProcessString (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-lint-eslint\lib\index.js:116:24)
    at Object.processString (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:26:19)
    at Processor.processString (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-persistent-filter\lib\processor.js:20:25)
    at C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-persistent-filter\index.js:277:16
    at initializePromise (C:\Users\acast\Desktop\DDM\web\node_modules\rsvp\dist\rsvp.js:589:5)
    at new Promise$1 (C:\Users\acast\Desktop\DDM\web\node_modules\rsvp\dist\rsvp.js:1077:33)
    at invoke (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-persistent-filter\index.js:276:10)

The broccoli plugin was instantiated at:
    at EslintValidationFilter.Plugin (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-plugin\index.js:7:31)
    at EslintValidationFilter.Filter [as constructor] (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-persistent-filter\index.js:62:10)
    at new EslintValidationFilter (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-lint-eslint\lib\index.js:55:10)
    at Function.EslintValidationFilter.create (C:\Users\acast\Desktop\DDM\web\node_modules\broccoli-lint-eslint\lib\index.js:213:16)
    at Class.lintTree (C:\Users\acast\Desktop\DDM\web\node_modules\ember-cli-eslint\index.js:44:19)
    at output.project.addons.map.addon (C:\Users\acast\Desktop\DDM\web\node_modules\ember-cli\lib\broccoli\ember-app.js:639:22)
    at Array.map (native)
    at EmberApp.addonLintTree (C:\Users\acast\Desktop\DDM\web\node_modules\ember-cli\lib\broccoli\ember-app.js:637:38)
    at EmberApp.lintTestTrees (C:\Users\acast\Desktop\DDM\web\node_modules\ember-cli\lib\broccoli\ember-app.js:1183:26)
    at EmberApp.appTests (C:\Users\acast\Desktop\DDM\web\node_modules\ember-cli\lib\broccoli\ember-app.js:1154:53)

(btw. the app is still running)
```
I found a similar issue here (https://github.com/ember-cli/ember-cli/issues/5600), but none actualy solved it.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: win32 x64
4.2.0
bash: yarn: command not found

```
EDIT:
Forgot to post package.json, here it comes:
```
{
  "name": "web",
  "version": "0.0.0",
  "description": "DDM-HP Web App to impress parents :D",
  "license": "MIT",
  "author": "Vojtěch Mareš",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/theacastus/ddm_web.git"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.13.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.13.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": ">= 4"
  },
  "private": true
}
```

**Comment by theLastLivingGhost** [comment]
Hey! I'm no expert but it seems to me that you lack the config file for eslint.
`Error: No ESLint configuration found.`

Do you have a file named `.eslintrc.js` or similar in your app's root folder? It should've had been installed when `ember new <app>` was run as far as I concern.

**Comment by Turbo87** [comment]
@theacastus this is working fine for me here. as @theLastLivingGhost mentioned it seems like you are missing an `.eslintrc.js` file in your project folder that should have been created by `ember new`. could you check if that exists?

**Comment by theacastus** [comment]
Oh, it is fine now. The file `.eslintrc.js` was missing. Maybe I have accidentaly touch that file while moving the stuff on disk or remove something... nevermind.

I tried `ember new <something>` and it works just fine.

So this issue is my bad and I have no idea how it happened. But it is fine.

Closed.

ps: thanks for your answers!
