### ISSUE TITLE
Issue Running Unit Test on Fresh Install Following Documentation

### ISSUE THREAD

**Issue by hudakdidit** [ember-cli/ember-cli#7061]
Hi! 

I'm working on upgrading a larger app to 2.13v and running into some issues with unit tests. I've followed the [documentation on writing unit tests](https://guides.emberjs.com/v2.13.0/testing/unit-testing-basics/), but I receive the error below.

I've put together a sample repo which reproduces the issue: https://github.com/hudakdidit/ember-unit-test-bug

Thanks in advance for the help,
Jonathan

---
Output from `ember version --verbose && npm --version && yarn --version`:
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: win32 x64

npm --version: 3.10.8

yarn 0.21.3

```
Promise rejected before "returns the right color": Cannot read property 'match' of undefined@ 32 ms
Expected: 	
null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	
TypeError: Cannot read property 'match' of undefined
    at Class.podBasedComponentsInSubdir (http://localhost:4567/assets/vendor.js:82588:76)
    at Class.findModuleName (http://localhost:4567/assets/vendor.js:82652:34)
    at Class.resolveOther (http://localhost:4567/assets/vendor.js:82494:37)
    at Class.superWrapper [as resolveOther] (http://localhost:4567/assets/vendor.js:53426:22)
    at Class.resolve (http://localhost:4567/assets/vendor.js:17778:35)
    at _class._setupIsolatedContainer (http://localhost:4567/assets/test-support.js:9278:59)
    at _class.setupContainer (http://localhost:4567/assets/test-support.js:9110:16)
    at http://localhost:4567/assets/test-support.js:7671:28
    at initializePromise (http://localhost:4567/assets/vendor.js:60809:7)
    at new Promise (http://localhost:4567/assets/vendor.js:61297:33)
Expected red@ 47 ms
Promise rejected after "returns the right color": Cannot read property 'subject' of undefined@ 50 ms
Expected: 	
null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	
TypeError: Cannot read property 'subject' of undefined
    at _class.teardownSubject (http://localhost:4567/assets/test-support.js:9161:33)
    at http://localhost:4567/assets/test-support.js:7671:28
    at initializePromise (http://localhost:4567/assets/vendor.js:60809:7)
    at new Promise (http://localhost:4567/assets/vendor.js:61297:33)
    at nextStep (http://localhost:4567/assets/test-support.js:7670:20)
    at _class.invokeSteps (http://localhost:4567/assets/test-support.js:7677:16)
    at http://localhost:4567/assets/test-support.js:7635:25
    at tryCatch (http://localhost:4567/assets/vendor.js:60759:14)
    at invokeCallback (http://localhost:4567/assets/vendor.js:60774:15)
    at http://localhost:4567/assets/vendor.js:60849:18
```

**Comment by hudakdidit** [comment]
Hey figured it out. I need to pass a file path as the first argument to `moduleFor` like in the documentation.

I've found the following cases to work: `moduleFor('helper:my-helper', ...)`, `moduleFor(`util:nested-dir/my-util')`. The folder name argument before the colon needs to be singular, and the file needs to have a dashed name like Ember components. Perhaps this could be more clearly documented.

Thanks!
