### ISSUE TITLE
Could not require 'ember-cli-build.js': Identifier 'EmberApp' has already been declared

### ISSUE THREAD

**Issue by DustinJWalker** [ember-cli/ember-cli#7070]
This is the error I am getting whenever I try to start my server.  Project was working fine on Friday, but today... not so much.

*****here is my ember-cli-build.js

/* eslint-env node */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    'ember-bootstrap': {
      'bootstrapVersion': 3,
      'importBootstrapFont': true,
      'importBootstrapCSS': false
    }

    // ember-cli-build.js

    module.exports = function(defaults) {
      var app = new EmberApp(defaults, {
        scssLintOptions: {
          rules: [
            'border-zero': 2,
            'brace-style': 0
          ]
        }
      });

  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.

  return app.toTree();
};

*** This is the error message I am getting in the terminal

SyntaxError: Identifier 'EmberApp' has already been declared
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/DustinWalker/dustin-col-saves/node_modules/ember-cli/lib/utilities/find-build-file.js:18:17)

**Comment by stefanpenner** [comment]
This seems unrelated to CLI, and rather to maybe bumping a node version?


Your issue appears to be the following two lines:

```
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
```

Once a variable has been made constant, in that scope you cannot redefine it. Unfortunately it seems like you are.

It s possible this worked before, due to a broken version of node or something?

**Comment by stefanpenner** [comment]
If i have misunderstood please let me know how/why and I can reopen.

**Comment by DustinJWalker** [comment]
@stefanpenner I'm not really for sure whats going on with it.  It was working at the end of the week and then this morning, nothing.  Whenever I comment out either of those 2 lines this is the error message I get: 
Could not require 'ember-cli-build.js': Unexpected identifier
/Users/DustinWalker/dustin-col-saves/ember-cli-build.js:15
    module.exports = function(defaults) {
    ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/DustinWalker/dustin-col-saves/node_modules/ember-cli/lib/utilities/find-build-file.js:18:17)
