### ISSUE TITLE
Fail on production build when rewriting assets (UglifyWriter)

### ISSUE THREAD

**Issue by RuslanZavacky** [ember-cli/ember-cli#7129]
When trying latest ember-cli version with addon ember-gsap, I see an issue in production build generation:

```
broccoli-uglify-sourcemap [starting]: assets/intl/intl.complete.js 893.313KB +68ms
WARN: Output exceeds 32000 characters
  broccoli-uglify-sourcemap [finished]: assets/intl/intl.complete.js 816.567KB in 5593ms +6s
  broccoli-uglify-sourcemap [starting]: assets/intl/intl.js 150.743KB +12ms
  broccoli-uglify-sourcemap [finished]: assets/intl/intl.js 29.287KB in 398ms +398ms
  broccoli-uglify-sourcemap [starting]: assets/intl/intl.min.js 29.49KB +4ms
  broccoli-uglify-sourcemap [finished]: assets/intl/intl.min.js 29.344KB in 286ms +286ms
  broccoli-uglify-sourcemap [starting]: assets/intl/locales/en-us.js 23.889KB +3ms
  broccoli-uglify-sourcemap [finished]: assets/intl/locales/en-us.js 23.873KB in 86ms +86ms
  broccoli-uglify-sourcemap [starting]: assets/ui.js 996.477KB +22ms
  broccoli-uglify-sourcemap [finished]: assets/ui.js 712.45KB in 2372ms +2s
  broccoli-uglify-sourcemap [starting]: assets/vendor.js 6477.321KB +38ms
cleaning up...
Build failed.
  ember-cli:command [AssetRewrite#2654 -> Fingerprint#2655 -> UglifyWriter#2656] An error occurred running `Build` from the `build` command. SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:
    at JS_Parse_Error.get (eval at <anonymous> (/opt/bookingwhale/ui/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)
    at Promise.resolve.then.catch.error (/opt/bookingwhale/ui/node_modules/ember-cli/lib/models/command.js:244:102)
    at tryCatch (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) +4s
File: assets/vendor.js (92119:48)
The Broccoli Plugin: [UglifyWriter] failed with:
SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:
    at JS_Parse_Error.get (eval at <anonymous> (/opt/bookingwhale/ui/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)
    at writeError (/opt/bookingwhale/ui/node_modules/console-ui/lib/write-error.js:23:23)
    at UI.writeError (/opt/bookingwhale/ui/node_modules/console-ui/lib/index.js:159:3)
    at CLI.logError (/opt/bookingwhale/ui/node_modules/ember-cli/lib/cli/cli.js:273:13)
    at tryCatch (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/opt/bookingwhale/ui/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

To reproduce that, even with a new project

```
ember new ember-gsap-test --yarn
yarn add ember-gsap@RuslanZavacky/ember-gsap#bump-deps --dev
```

I had to add a gsap with updated babel, to avoid any potential differences.

After some investigation it seems that this part of `index.js` in ember-gsap is causing trouble:

```js
importDependencies(app) {
  const plugins = this.addonConfig.plugins || [];
  const vendor = this.treePaths.vendor;

  app.import(vendor + '/gsap/TweenMax.js');

  if (plugins.includes('draggable')) {
    app.import(vendor + '/gsap/Draggable.js');
  }

  if (plugins.includes('scrollTo')) {
    app.import(vendor + '/gsap/ScrollToPlugin.js');
  }

  app.import('vendor/gsap-shim.js', {
    exports: {
      'gsap': ['TweenMax', 'TweenLite', 'TimelineMax', 'TimelineLite', 'easing'],
      'TweenMax': ['default'],
      'TweenLite': ['default'],
      'TimelineMax': ['default'],
      'TimelineLite': ['default']
    }
  });
},
```

`app.import('vendor/gsap-shim.js' ...)` is causing it to fail.

Are there some changes needed to adapt to the latest ember version? As this error didn't happen with the previous version.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.2
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
5.0.3
0.19.1
```

**Comment by stefanpenner** [comment]
My guess is syntax uglify can't parse. I wonder if we should switch to uglify-es or something...

**Comment by rwjblue** [comment]
Yes, we should switch to uglify-es (there is a PR open for this in broccoli-uglify-sourcemap that needs cleaning up).

**Comment by stefanpenner** [comment]
I think the open question was how to handle the config option changes...

**Comment by rwjblue** [comment]
Ya, I think it's just a major version bump for our related  packages...

**Comment by locks** [comment]
This has since been addressed :)
