### ISSUE TITLE
Cannot find module 'babel-plugin-transform-es2015-block-scoping'

### ISSUE THREAD

**Issue by devdemi** [ember-cli/ember-cli#7135]
Hi!

When I execute `ember server` I get net error message:

```
Cannot find module 'babel-plugin-transform-es2015-block-scoping'
Error: Cannot find module 'babel-plugin-transform-es2015-block-scoping'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/fe/node_modules/ember-data/lib/stripped-build-plugins.js:7:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Before I haven't received errors like this. Everything was ok.
I have no ideas how to resolve this promblem. Please advice what I need to do.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: linux x64
2.15.9

```

**Comment by devdemi** [comment]
`ember-data` has dependecy "babel-plugin-transform-es2015-block-scoping": "^6.24.1"
and I found this plugin in follow path:
`node_modules/ember-data/node_modules/ember-cli-babel/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-block-scoping/package.json`

**Comment by stefanpenner** [comment]
can you share steps to reproduce?

**Comment by bartam** [comment]
I had the same issue with our CI builds.  Turns out the CI npm version was 2.X.X.  Upgrading to 5.0.3 solved this for me.

**Comment by Matt-Jensen** [comment]
I had same issue and result as @bartam. Fixed travis CI by updating `.travis.yml` to:

```
node_js:
  - "5"
```

**Comment by synaptiko** [comment]
I have the same issue. Whenever I do `ember new <something>` and `cd <something> && ember serve` I get this error…

My versions:
```
ember-cli: 2.9.1
node: 8.1.2
npm: 5.0.3
```

I simply solve it by `npm install --save-dev babel-plugin-transform-es2015-block-scoping` and then it works…

**Comment by typeoneerror** [comment]
My repro steps:

```
$ nvm use stable 
Now using node v8.1.1 (npm v5.0.3)
$ npm install -g ember-cli@2.8.0
$ ember new my-app
$ cd my-app && ember serve
```


```
Cannot find module 'babel-plugin-transform-es2015-block-scoping'
Error: Cannot find module 'babel-plugin-transform-es2015-block-scoping'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/typeoneerror/Dev/ember/my-app/node_modules/ember-data/lib/stripped-build-plugins.js:7:29)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by Turbo87** [comment]
This appears to be an issue with Ember Data, not Ember CLI (see https://github.com/emberjs/data/issues/5024).

**Comment by MichalBryxi** [comment]
Had the same problem in:
```
ember-cli: 2.12.2
node: 4.x (LTS)
```
[Fix](https://github.com/ember-cli/ember-cli/issues/7135#issuecomment-310905715) from @synaptiko works for us.
