### ISSUE TITLE
Invalid Version for Ember-Cli-Babel upon project upgrade

### ISSUE THREAD

**Issue by robSturcke** [ember-cli/ember-cli#7138]
When updating project from 2.12.2 to 2.13.2 I've run into a error with SemVer node module upon running `ember init` or `ember s`.

 ```
Invalid Version: https://registry.npmjs.org/ember-cli-babel/-/ember-cli-babel-6.1.0.tgz

    TypeError: Invalid Version: https://registry.npmjs.org/ember-cli-babel/-/ember-cli-babel-6.1.0.tgz

at new SemVer (/Users/code/website/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/code/website/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/Users/code/website/node_modules/semver/semver.js:1085:16)
    at Class.Addon.(anonymous function) (/Users/code/website/node_modules/ember-cli/lib/models/addon.js:1547:25)
    at Class.init (/Users/code/website/node_modules/ember-cli/lib/models/addon.js:234:57)
    at Class.superWrapper [as init] (/Users/code/website/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.CoreObject (/Users/code/website/node_modules/core-object/core-object.js:9:15)
    at Class (/Users/code/website/node_modules/core-object/core-object.js:21:5)
    at Class (/Users/code/website/node_modules/core-object/core-object.js:21:5)
    at graph.topsort.vertex (/Users/code/website/node_modules/ember-cli/lib/models/addons-factory.js:55:21)

```

I tried a removal and fresh install of Semver, as well as a reinstall of Ember-Cli-Babel but nothing works unfortunately.  I can start new projects and run `ember init` or `ember s` just fine.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.2
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
5.0.3
0.24.6
```

**Comment by jakedetels** [comment]
@robSturcke, did you identify a solution for this issue?
