### ISSUE TITLE
ember server - throws error - not able to run the app

### ISSUE THREAD

**Issue by 3gwebtrain** [ember-cli/ember-cli#7158]
I am getting an error with `ember server` how to fix this?

here is the error details:

```
PS F:\EmberJS\libraray-app> ember server
The Broccoli Plugin: [ConfigReplace] failed with:
Error: Build Canceled: Broccoli Builder ran into an error with Funnel plugin. �
    at new BroccoliBuildError (F:\EmberJS\libraray-app\node_modules\broccoli-builder\lib\broccoli-build-error.js:40:9)
    at F:\EmberJS\libraray-app\node_modules\broccoli-builder\lib\builder.js:168:19
    at tryCatch (F:\EmberJS\libraray-app\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (F:\EmberJS\libraray-app\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (F:\EmberJS\libraray-app\node_modules\rsvp\dist\rsvp.js:522:7)
    at publishRejection (F:\EmberJS\libraray-app\node_modules\rsvp\dist\rsvp.js:457:3)
    at flush (F:\EmberJS\libraray-app\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at ConfigReplace.Plugin (F:\EmberJS\libraray-app\node_modules\broccoli-plugin\index.js:7:31)
    at new ConfigReplace (F:\EmberJS\libraray-app\node_modules\broccoli-config-replace\index.js:13:10)
    at EmberApp.index (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\broccoli\ember-app.js:686:12)
    at EmberApp.toArray (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\broccoli\ember-app.js:1661:12)
    at EmberApp.toTree (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\broccoli\ember-app.js:1684:38)
    at module.exports (F:\EmberJS\libraray-app\ember-cli-build.js:22:14)
    at Builder.setupBroccoliBuilder (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\models\builder.js:56:19)
    at new Builder (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\models\builder.js:30:10)
    at ServeTask.run (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\tasks\serve.js:24:55)
    at Promise.resolve.then (F:\EmberJS\libraray-app\node_modules\ember-cli\lib\models\command.js:242:46)


Livereload server on http://localhost:49153
```

**Comment by tsteuwer** [comment]
Hey! Thank god I'm not the only one. I thought I wasn't following the upgrade instructions correctly or something. I am going through trying to update all my apps/addons to the new version of ember and none of them run with this exact same issue in the CLI when i run `ember s`.

Here is the full stack when you visit localhost:4200:

```
Broccoli Plugin: Funnel

The Broccoli Plugin: [ConfigReplace] failed with:

                Error: ENOENT: no such file or directory, lstat '/home/troy/development/my-addon/tmp/funnel-input_base_path-WNhZaVbY.tmp/index.html'
    at Error (native)
    at Object.fs.lstatSync (fs.js:976:18)
    at symlink (/home/troy/development/my-addon/node_modules/symlink-or-copy/index.js:79:26)
    at Function.symlinkOrCopySync [as sync] (/home/troy/development/my-addon/node_modules/symlink-or-copy/index.js:65:5)
    at Funnel._copy (/home/troy/development/my-addon/node_modules/broccoli-funnel/index.js:492:19)
    at Funnel.processFile (/home/troy/development/my-addon/node_modules/broccoli-funnel/index.js:475:8)
    at Funnel.applyPatch [as _applyPatch] (/home/troy/development/my-addon/node_modules/broccoli-funnel/index.js:389:12)
    at Funnel.<anonymous> (/home/troy/development/my-addon/node_modules/broccoli-funnel/index.js:343:10)
    at Array.forEach (native)
    at Funnel.processFilters (/home/troy/development/my-addon/node_modules/broccoli-funnel/index.js:342:11)
              
                Error: Build Canceled: Broccoli Builder ran into an error with Funnel plugin. 💥
    at new BroccoliBuildError (/home/troy/development/my-addon/node_modules/broccoli-builder/lib/broccoli-build-error.js:40:9)
    at /home/troy/development/my-addon/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/home/troy/development/my-addon/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/troy/development/my-addon/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/home/troy/development/my-addon/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/home/troy/development/my-addon/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/home/troy/development/my-addon/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at ConfigReplace.Plugin (/home/troy/development/my-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new ConfigReplace (/home/troy/development/my-addon/node_modules/broccoli-config-replace/index.js:13:10)
    at EmberApp.index (/home/troy/development/my-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:698:12)
    at EmberApp.toArray (/home/troy/development/my-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:1673:12)
    at EmberApp.toTree (/home/troy/development/my-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:38)
    at module.exports (/home/troy/development/my-addon/ember-cli-build.js:22:14)
    at Builder.setupBroccoliBuilder (/home/troy/development/my-addon/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/troy/development/my-addon/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/home/troy/development/my-addon/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/home/troy/development/my-addon/node_modules/ember-cli/lib/models/command.js:242:46)

Livereload server on http://localhost:49153
```

**Comment by stefanpenner** [comment]
@tsteuwer its not clear your issue is related to this one. That being said, we should still investigate. Mind sharing a reproduction? My theory is your `app/index.html` is missing?

**Comment by stefanpenner** [comment]
@3gwebtrain not that this fixes your issue, but i noticed your stacktrace was not quite correct -> https://github.com/ember-cli/broccoli-builder/pull/14 should correct it (removing the extra frames at the top).

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-builder/pull/16 also further improves the stack...

**Comment by tsteuwer** [comment]
I changed some version numbers around and was able to get around the issue. I can't remember what exactly I changed but I did get that issue above by following the upgrade path from 2.10.0 to 13. Unless OP can replicate you can probably close this.

**Comment by tsteuwer** [comment]
Sorry am on mobile and doesn't let me edit but index.html was there.

**Comment by tylerturdenpants** [comment]
Having a similar issue.

**Comment by tylerturdenpants** [comment]
@stefanpenner I'm willing to pick up where the original submitter left off it's just that my addons are internal and cannot be shared publicly per IT policy.  Is there another way to go about resolving the issue?

**Comment by stefanpenner** [comment]
@tylerturdenpants maybe the following?

> I can't remember what exactly I changed but I did get that issue above by following the upgrade path from 2.10.0 to 13. Unless 

Without having a reproduction, I am not totally sure how to help/debug on this one...

**Comment by gossi** [comment]
I had this problem yesterday and it cost me half a day to fix it. I had a missing `index.html` file but it was present in my `/app` folder. I had it missing in the `/tests` folder. I created an empty one there and it was working again.

For all people searching for this problem on google and come here, this might be the solution for you ;)

Maybe `ember-cli` can run an "integrity" check for all required files first and report problems before continuing?

**Comment by TechGladiator** [comment]
Repost from https://github.com/ember-cli/ember-cli/issues/5600:

> I'm getting this error when I try to run `ember serve` in `cmd` or `powershell`. Not getting it in Linux, and I can get it to work in Windows by running `cmd` or `powershell` with admin rights. Seems to just be a permissions issue on Windows.
>
>`ember-cli@2.16`

**Comment by nesevis** [comment]
@gossi That fixed my issue as well! Cheers.

**Comment by ldong** [comment]
It's 2019 now, and just in case you ran into such issue on Mac, like this:
![image](https://user-images.githubusercontent.com/5491695/59144261-1a39d280-898a-11e9-99ba-20a6fa79a059.png)

```
ember -v                                                                                                                                                                    
ember-cli: 3.11.0-beta.3
node: 12.2.0
os: darwin x64
```

You might have a slightly chance running a `Module Unification` app that created by others, in that case, try turn on these flags and run:

```
MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true ./node_modules/ember-cli/bin/ember s --port=4201
```
