### ISSUE TITLE
`ember s` is failing with `no such file or directory` w.r.t. `ember-cli-ic-ajax`

### ISSUE THREAD

**Issue by sarbbottam** [ember-cli/ember-cli#7159]
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor)] failed with:
Error: ENOENT: no such file or directory, lstat 'node_modules/ember-cli-ic-ajax/node_modules'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at symlink (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/symlink-or-copy/index.js:79:26)
    at symlinkOrCopySync (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/symlink-or-copy/index.js:65:5)
    at /Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/broccoli-plugin/read_compat.js:86:11
    at tryCatch (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/sabandyo/GitCorp/learning-web-common_trunk/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
```

**Comment by stefanpenner** [comment]
I don't believe this is an issue with ember-cli. If that file doesn't exist, we can't really do much.

Could you try `rm -rf node_modules` `npm install`

Its also worth noting, ember-cli-ic-ajax isn't actively maintained, ember-ajax or ember-fetch may be better (more maintained, and supported addons).

**Comment by sarbbottam** [comment]
>Could you try `rm -rf node_modules` `npm install`

I tried it, prior reporting the issue.

Initially I was using `node 8` but `ember-cli` warned me, then I moved to `node 7` and finally `node 6`. For every `node version` I did `rm -rf node_modules && npm i`.

**Comment by sarbbottam** [comment]
Okay, I hacked it 
`cd node_modules/ember-cli-ic-ajax && npm i && cd ../.. && ember s` and I guess satisfied with the workaround. 

But I can't figure out why I had to `cd node_modules/ember-cli-ic-ajax && npm i` and `npm i` at the `project root` did not install the dependencies' dependency.

**Comment by sarbbottam** [comment]
I don't think it is an issue with `ember-cli` thus closing the issue.
