### ISSUE TITLE
The plugin [null,{"loose":true,"noIterop":true}] didn't export a Plugin instance

### ISSUE THREAD

**Issue by mk-conn** [ember-cli/ember-cli#7230]
Error:

```
The Broccoli Plugin: [BroccoliMergeTrees: Addon#compileAddon(ember-cli-notifications) ] failed with:
TypeError: The plugin [null,{"loose":true,"noIterop":true}] didn't export a Plugin instance
    at PluginManager.validate (/Users/mk/PhpstormProjects/ember-project/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/mk/PhpstormProjects/ember-project/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/mk/PhpstormProjects/ember-project/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/mk/PhpstormProjects/ember-project/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/mk/PhpstormProjects/ember-project/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/Users/mk/PhpstormProjects/ember-project/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/mk/PhpstormProjects/ember-project/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-merge-trees/index.js:42:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/mk/PhpstormProjects/ember-project/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at Class.compileAddon (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/models/addon.js:1084:12)
    at Class.treeForAddon (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/models/addon.js:738:26)
    at Class._treeFor (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/models/addon.js:551:33)
    at Class.treeFor (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/models/addon.js:511:21)
    at project.addons.map.addon (/Users/mk/PhpstormProjects/ember-project/node_modules/ember-cli/lib/broccoli/ember-app.js:557:22)
    at Array.map (native)
```
When I remove `ember-cli-notifications` it still fails but with `ember-welcome-page` so the ember-cli-notifications add-on seems not to be the cause... 

My package.json:
````
"broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-chrome-devtools": "^0.1.1",
    "ember-cli": "~2.14.0",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.3",
    "ember-cli-inject-live-reload": "^1.7.0",
    "ember-cli-mirage": "^0.3.4",
    "ember-cli-moment-shim": "^3.3.3",
    "ember-cli-notifications": "^4.2.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-sass": "^6.1.2",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.14.4",
    "ember-data-change-tracker": "^0.5.6",
    "ember-export-application-global": "^2.0.0",
    "ember-infinity": "^0.2.8",
    "ember-load-initializers": "^1.0.0",
    "ember-markdown-it": "^0.0.5",
    "ember-moment": "^7.3.1",
    "ember-resolver": "^4.3.0",
    "ember-route-action-helper": "^2.0.2",
    "ember-source": "~2.14.0",
    "ember-welcome-page": "^3.1.1",
    "loader.js": "^4.5.1",
    "semantic-ui-ember": "^2.0.1"
```

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.0
http_parser: 2.7.0
node: 8.1.4
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
5.3.0
0.27.5

```

**Comment by Turbo87** [comment]
@mk-conn what's the content of your `ember-cli-build.js` file?

**Comment by mk-conn** [comment]
I just added 
```
'ember-cli-babel': {
      includePolyfill: true
    },
```
and  changed to "ember-cli-babel": "^6.3.0" and have no problems any more... (dunno about the 6.3.0 version, if this makes a difference, can't really test right now, as I'm reaching a deadline soon :-/ )
