### ISSUE TITLE
Build breaks in 2.15-beta.1

### ISSUE THREAD

**Issue by vlascik** [ember-cli/ember-cli#7241]
I'm getting errors like this with several addons (ember-bootstrap, ember-wormhole, ...). 
```
broccoli-funnel:Funnel build, { in: '83ms', linkedRoots: false, inputPath: 'P:\\Project\\tmp\\funnel-input_base_path-SaAvmQfV.tmp', destPath: 'P:\\Project\\tmp\\funnel-output_path-9YFj8qPd.tmp' } +2ms
  broccoli-funnel:Funnel: Addon#_addonTemplateFiles (ember-bootstrap) build, { in: '4ms', linkedRoots: true, inputPath: 'P:\\Project\\tmp\\funnel-input_base_path-hNalfa2c.tmp/', destPath: 'P:\\Project\\tmp\\funnel-output_path-EwsG95h7.tmp/ember-bootstrap/templates' } +5ms
  broccoli-persistent-filter:TemplateCompiler [Babel#3352 -> TemplateCompiler#3353 -> derivePatches#3365] derivePatches duration: 7.19 ms {"patches":59,"entries":59,"walk":{"entries":59,"duration":"7.09 ms"}} +9ms
  async-disk-cache get: C:\Users\x\AppData\Local\Temp\x\if-you-need-to-delete-this-open-an-issue-async-disk-cache\275c0eaf736fb9d83bff69b5b9663b42ef38732a\d99d14fb9150a842a30f270d48aa972796f5ba98 +10ms
  broccoli-sane-watcher [Addon#compileAddon(ember-bootstrap) #3335 -> Babel#3352 -> TemplateCompiler#3353] triggerError { TypeError: Cannot read property 'visitors' of undefined at preprocess (P:\Project\node_modules\ember-source\dist\@glimmer\syntax.js:1574:1) at exports.precompile (P:\Project\node_modules\ember-source\dist\@glimmer\compiler.js:1437:1) at Object.template (P:\Project\node_modules\ember-cli-htmlbars\utils.js:29:40) at TemplateCompiler.processString (P:\Project\node_modules\ember-cli-htmlbars\index.js:76:40) at Promise.then.result.output (P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23) at initializePromise (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:240:5) at new Promise (P:\Project\node_modules\rsvp\dist\lib\rsvp\promise.js:143:33) at P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:40:18 at tryCatch (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:198:12) at invokeCallback (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:211:13) The broccoli plugin was instantiated at: at Babel.Plugin (P:\Project\node_modules\broccoli-plugin\index.js:7:31) at Babel.Filter [as constructor] (P:\Project\node_modules\broccoli-persistent-filter\index.js:64:10) at new Babel (P:\Project\node_modules\broccoli-babel-transpiler\index.js:36:10) at processModulesOnly (P:\Project\node_modules\ember-cli\lib\broccoli\babel-process-modules-only.js:28:10) at Class.compileAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:1087:30) at Class.treeForAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:745:26) at Class.superWrapper (P:\Project\node_modules\core-object\lib\assign-properties.js:34:20) at Class._treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:556:33) at Class.treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:516:21) at project.addons.reduce (P:\Project\node_modules\ember-cli\lib\broccoli\ember-app.js:559:25) message: 'The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: Modules for Templates]: Babel: Modules for Templates] failed with:', stack: 'TypeError: Cannot read property \'visitors\' of undefined\n    at preprocess (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\syntax.js:1574:1)\n    at exports.precompile (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\compiler.js:1437:1)\n    at Object.template (P:\\Project\\node_modules\\ember-cli-htmlbars\\utils.js:29:40)\n    at TemplateCompiler.processString (P:\\Project\\node_modules\\ember-cli-htmlbars\\index.js:76:40)\n    at Promise.then.result.output (P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:41:23)\n    at initializePromise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:240:5)\n    at new Promise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\promise.js:143:33)\n    at P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:40:18\n    at tryCatch (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:198:12)\n    at invokeCallback (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:211:13)\n\nThe broccoli plugin was instantiated at: \n    at Babel.Plugin (P:\\Project\\node_modules\\broccoli-plugin\\index.js:7:31)\n    at Babel.Filter [as constructor] (P:\\Project\\node_modules\\broccoli-persistent-filter\\index.js:64:10)\n    at new Babel (P:\\Project\\node_modules\\broccoli-babel-transpiler\\index.js:36:10)\n    at processModulesOnly (P:\\Project\\node_modules\\ember-cli\\lib\\broccoli\\babel-process-modules-only.js:28:10)\n    at Class.compileAddon (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:1087:30)\n    at Class.treeForAddon (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:745:26)\n    at Class.superWrapper (P:\\Project\\node_modules\\core-object\\lib\\assign-properties.js:34:20)\n    at Class._treeFor (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:556:33)\n    at Class.treeFor (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:516:21)\n    at project.addons.reduce (P:\\Project\\node_modules\\ember-cli\\lib\\broccoli\\ember-app.js:559:25)\n\n', broccoliPayload: { versions: { 'broccoli-builder': '0.18.8', node: 'v6.11.0' }, broccoliNode: { nodeName: 'TemplateCompiler', nodeAnnotation: 'TemplateCompiler', instantiationStack: '' }, error: { message: 'Cannot read property \'visitors\' of undefined', stack: 'TypeError: Cannot read property \'visitors\' of undefined\n    at preprocess (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\syntax.js:1574:1)\n    at exports.precompile (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\compiler.js:1437:1)\n    at Object.template (P:\\Project\\node_modules\\ember-cli-htmlbars\\utils.js:29:40)\n    at TemplateCompiler.processString (P:\\Project\\node_modules\\ember-cli-htmlbars\\index.js:76:40)\n    at Promise.then.result.output (P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:41:23)\n    at initializePromise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:240:5)\n    at new Promise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\promise.js:143:33)\n    at P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:40:18\n    at tryCatch (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:198:12)\n    at invokeCallback (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:211:13)', errorType: 'Template Compiler Error', codeFrame: 'Cannot read property \'visitors\' of undefined', location: [Object] } }, wasCanceled: true } +50ms
  ember-cli:watcher [Addon#compileAddon(ember-bootstrap) #3335 -> Babel#3352 -> TemplateCompiler#3353] didError { TypeError: Cannot read property 'visitors' of undefined at preprocess (P:\Project\node_modules\ember-source\dist\@glimmer\syntax.js:1574:1) at exports.precompile (P:\Project\node_modules\ember-source\dist\@glimmer\compiler.js:1437:1) at Object.template (P:\Project\node_modules\ember-cli-htmlbars\utils.js:29:40) at TemplateCompiler.processString (P:\Project\node_modules\ember-cli-htmlbars\index.js:76:40) at Promise.then.result.output (P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23) at initializePromise (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:240:5) at new Promise (P:\Project\node_modules\rsvp\dist\lib\rsvp\promise.js:143:33) at P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:40:18 at tryCatch (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:198:12) at invokeCallback (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:211:13) The broccoli plugin was instantiated at: at Babel.Plugin (P:\Project\node_modules\broccoli-plugin\index.js:7:31) at Babel.Filter [as constructor] (P:\Project\node_modules\broccoli-persistent-filter\index.js:64:10) at new Babel (P:\Project\node_modules\broccoli-babel-transpiler\index.js:36:10) at processModulesOnly (P:\Project\node_modules\ember-cli\lib\broccoli\babel-process-modules-only.js:28:10) at Class.compileAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:1087:30) at Class.treeForAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:745:26) at Class.superWrapper (P:\Project\node_modules\core-object\lib\assign-properties.js:34:20) at Class._treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:556:33) at Class.treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:516:21) at project.addons.reduce (P:\Project\node_modules\ember-cli\lib\broccoli\ember-app.js:559:25) message: 'The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: Modules for Templates]: Babel: Modules for Templates] failed with:', stack: 'TypeError: Cannot read property \'visitors\' of undefined\n    at preprocess (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\syntax.js:1574:1)\n    at exports.precompile (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\compiler.js:1437:1)\n    at Object.template (P:\\Project\\node_modules\\ember-cli-htmlbars\\utils.js:29:40)\n    at TemplateCompiler.processString (P:\\Project\\node_modules\\ember-cli-htmlbars\\index.js:76:40)\n    at Promise.then.result.output (P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:41:23)\n    at initializePromise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:240:5)\n    at new Promise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\promise.js:143:33)\n    at P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:40:18\n    at tryCatch (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:198:12)\n    at invokeCallback (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:211:13)\n\nThe broccoli plugin was instantiated at: \n    at Babel.Plugin (P:\\Project\\node_modules\\broccoli-plugin\\index.js:7:31)\n    at Babel.Filter [as constructor] (P:\\Project\\node_modules\\broccoli-persistent-filter\\index.js:64:10)\n    at new Babel (P:\\Project\\node_modules\\broccoli-babel-transpiler\\index.js:36:10)\n    at processModulesOnly (P:\\Project\\node_modules\\ember-cli\\lib\\broccoli\\babel-process-modules-only.js:28:10)\n    at Class.compileAddon (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:1087:30)\n    at Class.treeForAddon (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:745:26)\n    at Class.superWrapper (P:\\Project\\node_modules\\core-object\\lib\\assign-properties.js:34:20)\n    at Class._treeFor (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:556:33)\n    at Class.treeFor (P:\\Project\\node_modules\\ember-cli\\lib\\models\\addon.js:516:21)\n    at project.addons.reduce (P:\\Project\\node_modules\\ember-cli\\lib\\broccoli\\ember-app.js:559:25)\n\n', broccoliPayload: { versions: { 'broccoli-builder': '0.18.8', node: 'v6.11.0' }, broccoliNode: { nodeName: 'TemplateCompiler', nodeAnnotation: 'TemplateCompiler', instantiationStack: '' }, error: { message: 'Cannot read property \'visitors\' of undefined', stack: 'TypeError: Cannot read property \'visitors\' of undefined\n    at preprocess (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\syntax.js:1574:1)\n    at exports.precompile (P:\\Project\\node_modules\\ember-source\\dist\\@glimmer\\compiler.js:1437:1)\n    at Object.template (P:\\Project\\node_modules\\ember-cli-htmlbars\\utils.js:29:40)\n    at TemplateCompiler.processString (P:\\Project\\node_modules\\ember-cli-htmlbars\\index.js:76:40)\n    at Promise.then.result.output (P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:41:23)\n    at initializePromise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:240:5)\n    at new Promise (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\promise.js:143:33)\n    at P:\\Project\\node_modules\\broccoli-persistent-filter\\lib\\strategies\\persistent.js:40:18\n    at tryCatch (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:198:12)\n    at invokeCallback (P:\\Project\\node_modules\\rsvp\\dist\\lib\\rsvp\\-internal.js:211:13)', errorType: 'Template Compiler Error', codeFrame: 'Cannot read property \'visitors\' of undefined', location: [Object] } }, wasCanceled: true } +6ms
  leek enqueue eventType:exception silent:true payload:{ description: 'Error', fatal: undefined } +2ms
  ember-cli:live-reload: [Addon#compileAddon(ember-bootstrap) #3335 -> Babel#3352 -> TemplateCompiler#3353] files %a [ 'LiveReload due to compile error' ] +0ms
  tinylr:server Changed event (Files: LiveReload due to compile error) +2ms
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: Modules for Templates]: Babel: Modules for Templates] failed with:
TypeError: Cannot read property 'visitors' of undefined
    at preprocess (P:\Project\node_modules\ember-source\dist\@glimmer\syntax.js:1574:1)
    at exports.precompile (P:\Project\node_modules\ember-source\dist\@glimmer\compiler.js:1437:1)
    at Object.template (P:\Project\node_modules\ember-cli-htmlbars\utils.js:29:40)
    at TemplateCompiler.processString (P:\Project\node_modules\ember-cli-htmlbars\index.js:76:40)
    at Promise.then.result.output (P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23)
    at initializePromise (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:240:5)
    at new Promise (P:\Project\node_modules\rsvp\dist\lib\rsvp\promise.js:143:33)
    at P:\Project\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:40:18
    at tryCatch (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:198:12)
    at invokeCallback (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:211:13)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (P:\Project\node_modules\broccoli-plugin\index.js:7:31)
    at Babel.Filter [as constructor] (P:\Project\node_modules\broccoli-persistent-filter\index.js:64:10)
    at new Babel (P:\Project\node_modules\broccoli-babel-transpiler\index.js:36:10)
    at processModulesOnly (P:\Project\node_modules\ember-cli\lib\broccoli\babel-process-modules-only.js:28:10)
    at Class.compileAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:1087:30)
    at Class.treeForAddon (P:\Project\node_modules\ember-cli\lib\models\addon.js:745:26)
    at Class.superWrapper (P:\Project\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:556:33)
    at Class.treeFor (P:\Project\node_modules\ember-cli\lib\models\addon.js:516:21)
    at project.addons.reduce (P:\Project\node_modules\ember-cli\lib\broccoli\ember-app.js:559:25)
```
---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.0-beta.1
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: win32 x64
npm: 4.6.1
yarn: 0.27.5

ember-cli-babel: 6.6.0
ember-cli-htmlbars: 2.0.2
```
It seems to be happening on hbs templates, if I remove them, the build continues.

**Comment by stefanpenner** [comment]
Mind providing s repo with a reproduction

**Comment by vlascik** [comment]
While doing the reproduction I was able to narrow the problem down to `ember-hammertime`, so I'll close this and create an issue on their repo.

**Comment by rwjblue** [comment]
FWIW, something about the AST transform that is being used there is the issue. Not sure if the faullt lies with ember-cli-htmlbars or emberjs/ember.js though.
