### ISSUE TITLE
CI Failing for beta/master due

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#7276]
After merging `release` branch into `beta` (and `beta` into `master`) this morning (which hadn't been done for a while apparently), I introduced some failing tests.

```
not ok 101 Acceptance: ember new verify fixtures addon + npm + !welcome
  AssertionError: expected ".travis.yml" to equal "/home/travis/build/ember-cli/ember-cli/tests/fixtures/addon/npm/.travis.yml"
      at tests/acceptance/new-test.js:423:15
      at Array.forEach (native)
      at Context.<anonymous> (tests/acceptance/new-test.js:421:9)
      at next (native)
      at onFulfilled (node_modules/co/index.js:65:19)
      at tryCatch (node_modules/rsvp/dist/rsvp.js:525:12)
      at invokeCallback (node_modules/rsvp/dist/rsvp.js:538:13)
      at publish (node_modules/rsvp/dist/rsvp.js:508:7)
      at flush (node_modules/rsvp/dist/rsvp.js:2415:5)

not ok 102 Acceptance: ember new verify fixtures addon + yarn + welcome
  AssertionError: expected ".travis.yml" to equal "/home/travis/build/ember-cli/ember-cli/tests/fixtures/addon/yarn/.travis.yml"
      at tests/acceptance/new-test.js:444:15
      at Array.forEach (native)
      at Context.<anonymous> (tests/acceptance/new-test.js:442:9)
      at next (native)
      at onFulfilled (node_modules/co/index.js:65:19)
      at tryCatch (node_modules/rsvp/dist/rsvp.js:525:12)
      at invokeCallback (node_modules/rsvp/dist/rsvp.js:538:13)
      at publish (node_modules/rsvp/dist/rsvp.js:508:7)
      at flush (node_modules/rsvp/dist/rsvp.js:2415:5)
```

**Comment by kellyselden** [comment]
I can fix these since they are my tests

**Comment by rwjblue** [comment]
Thank you @kellyselden, sorry I didn't fix them before merging forward. 😢

**Comment by Turbo87** [comment]
@kellyselden is this fixed?

**Comment by kellyselden** [comment]
Yep
