### ISSUE TITLE
build error is encountered like :EPERM: operation not permitted, open '..\tmp\build.lock'

### ISSUE THREAD

**Issue by nimilraveendran** [ember-cli/ember-cli#7337]
A build error is encountered like :EPERM: operation not permitted, open '..\tmp\build.lock' while a reload needs to be done to the web page after editing a javascript file. Ember Js is used at the front end with Ember-cli version is 2.4.3 and node.js is 7.9.0. Windows 10 64bit is the OS. After this error the ember serve stops and the terminal hangs up. But this is working fine with Mac.Please help me out.

Error details are as follws:

EPERM: operation not permitted, open '..\tmp\build.lock'
________________________________________
Error: EPERM: operation not permitted, open '..\tmp\build.lock'
    at Object.fs.openSync (fs.js:558:18)
    at Class.preBuild (..\node_modules\ember-cli-rails-addon\index.js:38:10)
    at ..\node_modules\ember-cli\lib\models\builder.js:144:34
    at Array.map (native)
    at Class.processAddonBuildSteps (..\node_modules\ember-cli\lib\models\builder.js:142:43)
    at Class.build (..\node_modules\ember-cli\lib\models\builder.js:163:17)
    at Watcher_build [as build] (..\node_modules\broccoli-sane-watcher\index.js:75:6)
    at Watcher.<anonymous> (..\node_modules\broccoli-sane-watcher\index.js:43:17)
    at tryCatch (..\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (..\node_modules\rsvp\dist\rsvp.js:538:13)

**Comment by locks** [comment]
Thanks for reporting! Closing due to inactivity, if this still happens with current releases please let us know.
