### ISSUE TITLE
cannot build a module unification app  with 2.16.beta-2, 2.18.0-beta.1

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-cli#7343]
```
ember-cli: 2.16.0-beta.2
http_parser: 2.7.0
node: 8.6.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.3.0
0.23.4
```
Run the following commands and see below error:
1. `ember new test-app2 -b ember-module-unification-blueprint`
2. `ember build`
```
cleaning up...
Build failed.
The Broccoli Plugin: [ConfigReplace] failed with:
Error: ENOENT: no such file or directory, lstat '/private/tmp/test-app2/app'
    at Object.fs.lstatSync (fs.js:948:11)
    at symlink (/private/tmp/test-app2/node_modules/symlink-or-copy/index.js:79:26)
    at symlinkOrCopySync (/private/tmp/test-app2/node_modules/symlink-or-copy/index.js:65:5)
    at /private/tmp/test-app2/node_modules/broccoli-plugin/read_compat.js:86:11
    at tryCatch (/private/tmp/test-app2/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/private/tmp/test-app2/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/private/tmp/test-app2/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/private/tmp/test-app2/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The broccoli plugin was instantiated at: 
    at ConfigReplace.Plugin (/private/tmp/test-app2/node_modules/broccoli-plugin/index.js:7:31)
    at new ConfigReplace (/private/tmp/test-app2/node_modules/broccoli-config-replace/index.js:13:10)
    at EmberApp.index (/private/tmp/test-app2/node_modules/ember-cli/lib/broccoli/ember-app.js:752:12)
    at EmberApp.toArray (/private/tmp/test-app2/node_modules/ember-cli/lib/broccoli/ember-app.js:1806:12)
    at EmberApp.toTree (/private/tmp/test-app2/node_modules/ember-cli/lib/broccoli/ember-app.js:1831:32)
    at module.exports (/private/tmp/test-app2/ember-cli-build.js:24:14)
    at Builder.setupBroccoliBuilder (/private/tmp/test-app2/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/private/tmp/test-app2/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/private/tmp/test-app2/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/private/tmp/test-app2/node_modules/ember-cli/lib/models/command.js:243:46)
```
I expected the build to complete; I verified 2.16.beta-1 successfully builds the app.

**Comment by rwjblue** [comment]
Thanks for reporting!

**Comment by charlesfonlupt** [comment]
I have the same issue. 

```
ember-cli: 2.18.0-beta.1
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.3.2
```

After running a clean install I have this message : 

```
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
Error: Attempting to watch missing directory: /Users/charlesfonlupt/pupl/app
    at Watcher_addWatchDir [as addWatchDir] (/Users/charlesfonlupt/pupl/node_modules/ember-cli-broccoli-sane-watcher/index.js:142:11)
    at /Users/charlesfonlupt/pupl/node_modules/broccoli-builder/lib/builder.js:135:35
    at tryCatch (/Users/charlesfonlupt/pupl/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/charlesfonlupt/pupl/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/charlesfonlupt/pupl/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/charlesfonlupt/pupl/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/Users/charlesfonlupt/pupl/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/charlesfonlupt/pupl/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:57:10)
    at EmberApp._rawAppIndex (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/broccoli/ember-app.js:776:12)
    at EmberApp.index (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/broccoli/ember-app.js:759:20)
    at EmberApp.toArray (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/broccoli/ember-app.js:1820:12)
    at EmberApp.toTree (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/broccoli/ember-app.js:1845:32)
    at module.exports (/Users/charlesfonlupt/pupl/ember-cli-build.js:24:14)
    at Builder.setupBroccoliBuilder (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/Users/charlesfonlupt/pupl/node_modules/ember-cli/lib/tasks/serve.js:24:55)
```

Any update ?

**Comment by efx** [comment]
@charlesfonlupt I can't speak to the detailed internals of module unification, but I know the team is doing a lot of work to make it happen. Check out [ember community slack](https://embercommunity.slack.com/) #st-module-unification channel for details on getting involved.

**Comment by charlesfonlupt** [comment]
@efx Thanks a lot for the quick answer. 

I am sure the team is working hard on every issue. Just wanted to give some complement of information. I will try to connect me to the ember slack, following your advice.

**Comment by efx** [comment]
seeing the same with: 
```
ember-cli: 2.18.0-beta.1
node: 9.2.0
os: darwin x64
```.
Exempting that particular failure with a try/catch, I still get another error related to ember build not being able to find `index.html`. Do these defaults have anything to do with it? https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L55-L58

**Comment by efx** [comment]
I was able to build our app using master as of 80b4a7a5525355f405266d9660cf41915efbaa49. For the impatient, you can clone ember-cli and npm link it to your project.

**Comment by mixonic** [comment]
Closed in favor of https://github.com/emberjs/ember.js/issues/16373
