### ISSUE TITLE
Deleting any app/* or tests/* files (templates, models, routes, etc.) breaks ember serve

### ISSUE THREAD

**Issue by allthesignals** [ember-cli/ember-cli#7347]
Removing / moving a file breaks `ember serve` and shows build error:
```
Broccoli Plugin: EslintValidationFilter

The Broccoli Plugin: [SimpleConcatConcat] failed with:

                Error: ENOENT: no such file or directory, lstat '/Users/mgardner/labs-zola/tmp/broccoli_persistent_filtereslint_validation_filter-input_base_path-CfyDFsxH.tmp/unit/serializers/bookmark-test.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at EslintValidationFilter.Filter.isDirectory (/Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:270:23)
    at EslintValidationFilter.Filter.getDestFilePath (/Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:275:12)
    at EslintValidationFilter.getDestFilePath (/Users/mgardner/labs-zola/node_modules/broccoli-lint-eslint/lib/index.js:123:55)
    at /Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:154:52
    at /Users/mgardner/labs-zola/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:606:14
              
                Error: ENOENT: no such file or directory, lstat '/Users/mgardner/labs-zola/tmp/broccoli_persistent_filtereslint_validation_filter-input_base_path-CfyDFsxH.tmp/unit/serializers/bookmark-test.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at EslintValidationFilter.Filter.isDirectory (/Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:270:23)
    at EslintValidationFilter.Filter.getDestFilePath (/Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:275:12)
    at EslintValidationFilter.getDestFilePath (/Users/mgardner/labs-zola/node_modules/broccoli-lint-eslint/lib/index.js:123:55)
    at /Users/mgardner/labs-zola/node_modules/broccoli-persistent-filter/index.js:154:52
    at /Users/mgardner/labs-zola/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/mgardner/labs-zola/node_modules/rsvp/dist/rsvp.js:606:14

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/Users/mgardner/labs-zola/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/Users/mgardner/labs-zola/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/Users/mgardner/labs-zola/node_modules/broccoli-concat/index.js:26:10)
    at Function.EslintValidationFilter.create (/Users/mgardner/labs-zola/node_modules/broccoli-lint-eslint/lib/index.js:215:10)
    at Class.lintTree (/Users/mgardner/labs-zola/node_modules/ember-cli-eslint/index.js:44:19)
    at output.project.addons.map.addon (/Users/mgardner/labs-zola/node_modules/ember-cli/lib/broccoli/ember-app.js:649:22)
    at Array.map (native)
    at EmberApp.addonLintTree (/Users/mgardner/labs-zola/node_modules/ember-cli/lib/broccoli/ember-app.js:647:38)
    at EmberApp.lintTestTrees (/Users/mgardner/labs-zola/node_modules/ember-cli/lib/broccoli/ember-app.js:1192:28)
    at EmberApp.appTests (/Users/mgardner/labs-zola/node_modules/ember-cli/lib/broccoli/ember-app.js:1162:28)
```

Is there a way to avoid this? When switching between branches, restarting the server any time a file was removed or moved can slow down development. 

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.11.1
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
5.3.0
1.1.0
```

**Comment by scottkidder** [comment]
I am seeing the same thing

My Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.0-beta.2
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
5.3.0
1.1.0
```

**Comment by scottkidder** [comment]
Currently my workaround on encountering this is to run:
`touch app/foo`

Then the app will rebuild and I just delete `app/foo` before committing.

This is a pain but better than killing the server and needing to do a fresh build.

**Comment by hakilebara** [comment]
I have the same problem. I think the problem is that ember-cli tries to run eslint on already deleted files. 

The bug can be reproduced by doing a `ember g route foo && ember d route foo` while `ember serve` is running.

**Comment by morhook** [comment]
This problems happens a lot when updating from a `git` (usually some coworkers of mine delete files, kind-of-annoying, like @pfmmfp )

**Comment by rwjblue** [comment]
The latest release of broccoli-lint-eslint (4.2.1) includes the fix for this.

**Comment by morhook** [comment]
Upgraded with `yarn upgrade ember-cli-eslint` and this is fits like a glove!!!!!

**Comment by allthesignals** [comment]
YAS!!! Life-changing.
