### ISSUE TITLE
ember serve crashes on clean install of 2.16.1 - Error: Cannot find module 'uglify-js/'

### ISSUE THREAD

**Issue by hakilebara** [ember-cli/ember-cli#7371]
`ember new newapp`
`cd newapp`
`ember s`

```
Livereload server on http://localhost:7021
Cannot stop: not the current node.
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeFor (ember-data - addon)] failed with:
Error: Cannot find module 'uglify-js/' from '/Users/kaos/Projects/newapp/node_modules/handlebars/'
    at Function.module.exports [as sync] (/Users/kaos/Projects/newapp/node_modules/resolve/lib/sync.js:40:15)
    at resolvePkg (/Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/resolve-pkg.js:20:18)
    at pkg (/Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/pkg.js:17:20)
    at again (/Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/deps-for.js:18:22)
    at /Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (<anonymous>)
    at again (/Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (<anonymous>)
    at again (/Users/kaos/Projects/newapp/node_modules/hash-for-dep/lib/deps-for.js:26:55)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/kaos/Projects/newapp/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/kaos/Projects/newapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/kaos/Projects/newapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at Class.treeFor (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/models/addon.js:527:30)
    at project.addons.reduce (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/broccoli/ember-app.js:620:25)
    at Array.reduce (<anonymous>)
    at EmberApp.addonTreesFor (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/broccoli/ember-app.js:618:32)
    at EmberApp._addonTree (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1082:29)
    at EmberApp._processedExternalTree (/Users/kaos/Projects/newapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1135:25)
```

I can fix it by resolving the dependency manually `npm install uglify-js`

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.1
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.4.2
1.1.0
```

**Comment by Rup1** [comment]
Same issue here, manually installing it worked.

**Comment by Turbo87** [comment]
it looks like `handlebars` is importing `uglify-js` unconditionally in https://github.com/wycats/handlebars.js/blob/660a1175364aaef8903d7446f06adcb1f8d27acd/lib/precompiler.js#L7 but only lists it as an optional dependency in https://github.com/wycats/handlebars.js/blob/58ec656fbc7fe7fdde1f731d0dcd52b688922c25/package.json#L29 🤦‍♂️

**Comment by rwjblue** [comment]
Wow, this is great actually.  Apparently the `dependencies` list is mutated by the `npm` client upon install.  You can see [here](https://unpkg.com/handlebars@4.0.10/package.json) that `handlebars@4.0.10`'s `package.json` _does not_ include `uglify-js` in its `dependencies`, but if you do:

```js
mkdir random-thing
cd random-thing
npm install handlebars
cat node_modules/handlebars/package.json
```

You will see that `npm` client has added `uglify-js` to its list of `dependencies`.

**Comment by rwjblue** [comment]
See related issues / PR's that fell out of debugging this:

* https://github.com/stefanpenner/hash-for-dep/issues/20
* https://github.com/stefanpenner/hash-for-dep/pull/38
* https://github.com/emberjs/data/issues/5222
* https://github.com/emberjs/data/pull/5223

For now, folks affected by this can `npm i uglify-js`.  I'd like to get reviews on the `hash-for-dep` change, and get it released as a patch version bump so folks will be able to do a `yarn upgrade` to correct the issue.

In the meantime, folks can `npm i uglify-js` to get it working.

**Comment by Turbo87** [comment]
> In the meantime, folks can npm i uglify-js to get it working.

or use `yarn` ... :trollface:

**Comment by hakilebara** [comment]
Should we communicate on this? New users following the 'Getting Started' guide will face an error message from the get go.

**Comment by Turbo87** [comment]
@hakilebara we're already in the process of fixing this (see https://github.com/stefanpenner/hash-for-dep/pull/38), should be resolved soon.

**Comment by rwjblue** [comment]
I just released ember-data@2.16.3, which works around this issue (by moving `broccoli-test-helper > broccoli > handlebars > uglify-js` to a dev dependency).

The upstream PR in hash-for-dep is still the correct way forward, but the immediate issue of anyone following the general `ember new foo && cd foo && ember s` steps receiving an error has been mitigated.

Closing...

**Comment by rwjblue** [comment]
@hakilebara - Thank you very much for the detailed issue report on this!

**Comment by nknapp** [comment]
I tried a very simplistic setup with (npm@5.4.2)

```bash
mkdir tmp-project
cd tmp-project
npm init -y
npm install handlebars@4.0.10
```

and it **did** install `uglify-js` as a dependency of handlebars. Have you found out, why it was not installed? Is this a Linux-Windows issue?

**Comment by rwjblue** [comment]
`npm install —no-optional` was being used internally I believe
