### ISSUE TITLE
Build broken: "didn't export a Plugin instance" - ember-cli 2.15

### ISSUE THREAD

**Issue by allthesignals** [ember-cli/ember-cli#7389]
This seems to have happened after doing nothing particularly related to tests, linting, or otherwise (I was editing a file in app/). This is so bewildering I don't know where to start. Maybe I upgraded ember-cli incorrectly (I went from 2.9.1 to 2.15)? 

```
Dang! Looks like a Build Error.

cityxcity/tests/app.lint-test.js

The plugin [null,{"loose":true,"noInterop":true}] didn't export a Plugin instance
Expand stack frames
Broccoli Plugin: Babel

The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:

                TypeError: The plugin [null,{"loose":true,"noInterop":true}] didn't export a Plugin instance
    at PluginManager.validate (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/index.js:110:22)
              
                TypeError: The plugin [null,{"loose":true,"noInterop":true}] didn't export a Plugin instance
    at PluginManager.validate (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/mgardner/cityxcity/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/Users/mgardner/cityxcity/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/mgardner/cityxcity/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/mgardner/cityxcity/node_modules/broccoli-merge-trees/index.js:42:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/mgardner/cityxcity/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp._mergeTrees (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1832:12)
    at EmberApp.appTests (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1185:25)
    at EmberApp.test (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1166:28)
    at EmberApp.toArray (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:63)
    at EmberApp.toTree (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1711:38)
    at module.exports (/Users/mgardner/cityxcity/ember-cli-build.js:38:14)


              
Environment

broccoli-builder@0.18.8, node@v6.11.1
```

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.1
http_parser: 2.7.0
node: 6.11.1
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
5.3.0
1.1.0
```

**Comment by Turbo87** [comment]
@allthesignals did you only update Ember CLI or also other dependencies? This looks like an issue related to the update from Babel 5 to Babel 6.

**Comment by locks** [comment]
Closing due to inactivity. Feel free to reopen if you still have an issue!
