### ISSUE TITLE
 Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by pictaile** [ember-cli/ember-cli#7396]
I install daterangepicker only.
I have  `ember-cli: 2.10.0`

I make `ember server` and get error:

File: ember-cli-daterangepicker/components/date-range-picker.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)

The broccoli plugin was instantiated at:
    at Babel.Plugin (F:\Projects\tomaq\node_modules\broccoli-plugin\index.js:7:31)
    at Babel.Filter [as constructor] (F:\Projects\tomaq\node_modules\broccoli-persistent-filter\index.js:62:10)
    at new Babel (F:\Projects\tomaq\node_modules\broccoli-babel-transpiler\index.js:35:10)
    at EmberApp._addonTree (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:913:29)
    at EmberApp._processedVendorTree (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:947:20)
    at EmberApp._processedExternalTree (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:978:21)
    at EmberApp.appAndDependencies (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:1087:30)
    at EmberApp.javascript (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:1217:34)
    at EmberApp.toArray (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:1646:10)
    at EmberApp.toTree (F:\Projects\tomaq\node_modules\ember-cli\lib\broccoli\ember-app.js:1668:30)
    at module.exports (F:\Projects\tomaq\ember-cli-build.js:43:14)
    at CoreObject.setupBroccoliBuilder (F:\Projects\tomaq\node_modules\ember-cli\lib\models\builder.js:72:19)
    at CoreObject.init (F:\Projects\tomaq\node_modules\ember-cli\lib\models\builder.js:52:10)
    at CoreObject.superWrapper [as init] (F:\Projects\tomaq\node_modules\core-object\lib\assign-properties.js:32:18)
    at CoreObject.Class (F:\Projects\tomaq\node_modules\core-object\core-object.js:32:33)
    at CoreObject.run (F:\Projects\tomaq\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at F:\Projects\tomaq\node_modules\ember-cli\lib\commands\serve.js:76:24
    at tryCatch (F:\Projects\tomaq\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (F:\Projects\tomaq\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (F:\Projects\tomaq\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (F:\Projects\tomaq\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

How wix it

**Comment by workmanw** [comment]
I can help! I had this exact issue and it was related to running two ember-cli processes in parallel. It turns out that ember-cli uses global build cache and if two ember-cli processes are running at once this global cache can be clobbered. The work around is to use this env variable to effectively disable the global shared cache: `BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT`.

See: https://github.com/stefanpenner/broccoli-persistent-filter/issues/124

**Comment by pictaile** [comment]
Hi, thankyou for answer. Where set this variable?  at ./config/environment.js &

**Comment by workmanw** [comment]
@pictaile You can set the variable when invoking ember-cli:

`BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT=./dist-build-cache ember-cli build -prod`

Also, would you mind confirming if you are running two ember-cli processes in parallel?

**Comment by pictaile** [comment]
Thank you it working!
I have windows OS and s In powerShell  set next:

 `$env:BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT = "./dist-build-cache" `

`ember server`
