### ISSUE TITLE
`ember new` yields a build error when trying to build the app - "Cannot find module 'color-convert'

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#7402]
When trying to do:
```
$ ember new mockup --yarn
...
$ cd mockup
$ ember build
```

I get:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'color-convert'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/mockup/node_modules/ansi-styles/index.js:2:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Running `yarn add color-convert` fixes the issue for me...
Perhaps I'm missing something that's wrong with my environment, but I have no idea what that might be.

Thanks in advance!

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.11.4
v8: 5.1.281.108
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
5.5.1
1.0.1
```

**Comment by kellyselden** [comment]
I tried to reproduce, but everything worked fine for me. Try updating yarn. Closing as I don't think there is much we can do.
