### ISSUE TITLE
Addon blueprints can get the wrong versions of their dependencies

### ISSUE THREAD

**Issue by bendemboski** [ember-cli/ember-cli#7431]
This is a report stemming from [this](https://github.com/felixrieseberg/ember-electron/issues/320) bug over in `ember-electron`. It can be repro'ed very easily.

## Repro

```
$ ember new bad-deps --yarn
$ cd bad-deps
$ ember install ember-electron@2.7.1
```

(the `@2.7.1` is critical as I'm about to commit a workaround to `ember-electron`).

and the output will be:

```
~$ ember new bad-deps --yarn
installing app
  create .editorconfig
  create .ember-cli
  create .eslintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.eslintrc.js
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Yarn: Installed dependencies
Successfully initialized git.
~$ cd bad-deps/
~/bad-deps$ ember install ember-electron@2.7.1
Yarn: Installed ember-electron@2.7.1
installing ember-electron
  create ember-electron/.compilerc
  create ember-electron/main.js
  create ember-electron/test-main.js
  create testem-electron.js
Project needs forge config
_fsExtra2.default.pathExists is not a function
TypeError: _fsExtra2.default.pathExists is not a function
    at _callee8$ (/Users/ben/bad-deps/node_modules/electron-forge/dist/api/import.js:115:38)
    at tryCatch (/Users/ben/bad-deps/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/ben/bad-deps/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/ben/bad-deps/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at Generator.tryCatcher (/Users/ben/bad-deps/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/ben/bad-deps/node_modules/bluebird/js/release/generators.js:97:49)
    at /Users/ben/bad-deps/node_modules/bluebird/js/release/generators.js:201:15
    at /Users/ben/bad-deps/node_modules/electron-forge/dist/api/import.js:653:17
    at EmberElectronBlueprint._installElectronTooling (/Users/ben/bad-deps/node_modules/ember-electron/blueprints/ember-electron/index.js:61:12)
    at _checkForgeConfig.then (/Users/ben/bad-deps/node_modules/ember-electron/blueprints/ember-electron/index.js:26:24)
    at tryCatcher (/Users/ben/bad-deps/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:329:19)
    at invokeCallback (/Users/ben/bad-deps/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:507:31)
    at publish (/Users/ben/bad-deps/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:493:7)
    at flush (/Users/ben/bad-deps/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:2432:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
~/bad-deps$ 
```

## Root cause (summary)
This is happening because the installation of the node packages during the `ember install` causes a different version of `fs-extra` to be hoisted to the root of `node_modules`, but a different, older, version is still in the require cache, so when a module tries to `require('fs-extra')` as part of running the blueprint, it gets a too-old version of `fs-extra` and throws an exception.

## Root cause (detail)
`yam` depends on `fs-extra@^0.30.0`, and sometime during the `ember install` _before_ it invokes `yarn add ember-electron`, `yam` requires `fs-extra`, caching `node_modules/fs-extra/lib/index.js` with the `0.30.0` contents. When `yarn` installs `ember-electron`, it also installs its dependency, `electron-forge` which depends on `fs-extra@^4.0.0`. `yarn` puts `electron-forge` at the root of `node_modules`, pushes the `0.30.0` version of `fs-extra` into `node_modules/yam/node_modules` and hoists the `4.0.0` version of `fs-extra` to the root of `node_modules`. Then `ember-electron`'s blueprint runs, and it calls into `electron-forge`'s API, so it's still running in the same process space. `electron-forge` requires `fs-extra`, which resolves to `node_modules/fs-extra/lib/index.js`, which is still cached from earlier, but the cache value is the `0.30.0` version, so `electron-forge` throws an exception.

## Proposed fix
The safest fix I can think of is to blow away the whole require cache from `tasks/npm-install.js` and `tasks/npm-uninstall.js` after the install/uninstall completes. Anytime we run an install/uninstall operation we risk moving require-cached files around and causing the filesystem to diverge from the in-memory cache, and it seems risky to make any assumptions about how the package manager is hoisting, so it's safest to consider the entire cache invalid.

We could potentially do it in `tasks/addon-install.js` since that's the only known case of this being a problem, but then we risk introducing a bug very much like this, but under slightly different circumstances, in the future.

## Drawbacks of proposed fix
The only drawback I can think of is the performance hit from no longer having a bunch of modules cached. However, in our current use cases this should be pretty minimal since the bulk of the code that is going to be loaded is already loaded, and the compiled sub-modules are already in memory referenced by module-scoped variables. Plus every single case where we would get a performance gain by hitting the cache is a potential place where the cache could contain the wrong version of the module. Also, `npm`/`yarn` operations don't happen in normal development workflows (`ember serve`, `ember build`, `ember test`, etc.), so the performance loss seems like it will have minimal impact and be well worth guaranteeing to addon authors that they'll always get the expected versions of their dependencies.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember version --verbose && npm --version && yarn --version
Running node v7.9.0 (npm v4.2.0)
ember-cli: 2.16.2
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
5.5.1
1.3.2
```

**Comment by bendemboski** [comment]
I'm happy to open a PR with my proposed fix, but I'd like to hear from a core team member that this is not a terrible idea first. Also, I could use some guidance on how to test this (a unit test that verifies that the cache is emptied wouldn't be hard, but do we want an integration/acceptance test?)

**Comment by rwjblue** [comment]
A possible alternative to this proposed fix above is to exec a new process to run the blueprint. Likely will take longer, but will also result in an even more correct result...

**Comment by bendemboski** [comment]
Yeah, that would make sense, although seems like it might be a much more invasive/risky change? Maybe not, and/or maybe worth it -- I don't feel qualified to judge.

But even with that fix, the underlying code issue would still exist, which is that we have this nice API (tasks) for running npm operations that can effectively corrupt our require cache. Fixing this blueprint bug seems like highest priority, but personally I'd prefer to also see the underlying issue addressed so it won't bite anybody in the future.

**Comment by locks** [comment]
According to @bendemboski this issue ocurred to them just a couple weeks ago.

**Comment by locks** [comment]
@bendemboski howdy! did you end up working on it? is it still a problem?

**Comment by bendemboski** [comment]
@locks I didn't -- this one fell off my radar after we worked around it by instructing `ember-electron` users to run the blueprint manually. I don't know if it's still an issue or not, but since nobody seems to have referenced/commented on/etc this PR I'd say it's save to close, and we can re-open it if it starts causing problems again?
