### ISSUE TITLE
Error: EBUSY: resource busy or locked, symlink

### ISSUE THREAD

**Issue by parivajk** [ember-cli/ember-cli#7544]
---
Hi 
I have a existing ember.js project which I want to edit/mod. When running 'ember serve' I get the error below. I read the other issues similar to this but none of the suggestion helped me so far. Can anyone please help how to solve this?

Output from `ember version --verbose && npm --version`(I don't have yarn):
ember-cli: 2.5.1
http_parser: 2.5.2
node: 4.4.2
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: win32 x64
```
The Broccoli Plugin: [BroccoliMergeTrees: Addon#treeForAddon(ember-resolver)] fa
iled with:
Error: EBUSY: resource busy or locked, symlink 'C:\myprojectfolder\tmp\broccoli_merge_trees-output_path-4bEVMEkF.tmp' -> 'C:\myprojectfolder\tmp\broccoli_merge_trees-input_base
_path-ADR7FwCy.tmp'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at symlinkWindows (myprojectfolder\node_m
odules\symlink-or-copy\index.js:123:18)
    at symlinkOrCopySync (myprojectfolder\nod
e_modules\symlink-or-copy\index.js:63:5)
    at myprojectfolder\node_modules\broccoli-
plugin\read_compat.js:86:11
    at tryCatch (myprojectfolder\node_modules
\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (myprojectfolder\node_m
odules\rsvp\dist\rsvp.js:538:13)
    at publish (myprojectfolder\node_modules\
rsvp\dist\rsvp.js:508:7)
    at flush (myprojectfolder\node_modules\rs
vp\dist\rsvp.js:2415:5)
    at nextTickCallbackWith0Args (node.js:420:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (C:\myprojectfolder\node_modules\broccoli-plugin\index.js:7:31)
    at new BroccoliMergeTrees (C:\myprojectfolder\node_modules\broccoli-merge-trees\index.js:42:10)
    at BroccoliMergeTrees (myprojectfolder\no
de_modules\broccoli-merge-trees\index.js:36:53)
    at mergeTrees (myprojectfolder\node_modul
es\ember-cli\lib\models\addon.js:35:14)
    at Class.Addon.treeForAddon (C:\myprojectfolder\node_modules\ember-cli\lib\models\addon.js:406:10)
    at Class._treeFor (myprojectfolder\node_m
odules\ember-cli\lib\models\addon.js:322:31)
    at Class.treeFor (myprojectfolder\node_mo
dules\ember-cli\lib\models\addon.js:290:19)
    at myprojectfolder\node_modules\ember-cli
\lib\broccoli\ember-app.js:463:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\myprojectfolder\node_modules\ember-cli\lib\broccoli\ember-app.js:461:30)

```

Cheers
Viktor

**Comment by locks** [comment]
Closing due to inactivity. Thanks for reporting, and if you still encounter this problem please let us know.
