### ISSUE TITLE
3.0.0.beta.1 fails to start with `ember s`

### ISSUE THREAD

**Issue by 0xadada** [ember-cli/ember-cli#7552]
Just tried upgrading to Ember 3.0.0.beta.1 using `ember update` command from ember-cli-update addon. After resolving conflicts, i ran `ember s` and ran into the error below.

upgrade is on a branch here https://github.com/mirai-audio/mir/tree/16/library-ember-3beta

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.0.0-beta.1
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.3.2
```

trace of bug
```
$ ember s
Path must be a string. Received undefined


Stack Trace and Error Report: /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T/error.dump.118f766ba9e6854a07cd61a8428bd49e.log
```
then
```
$ cat /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T/error.dump.118f766ba9e6854a07cd61a8428bd49e.log
=================================================================================

ENV Summary:

  TIME: Fri Jan 12 2018 16:30:30 GMT-0500 (EST)
  TITLE: ember
  ARGV:
  - /Users/ron/.nvm/versions/node/v8.9.3/bin/node
  - /usr/local/bin/ember
  - s
  EXEC_PATH: /Users/ron/.nvm/versions/node/v8.9.3/bin/node
  TMPDIR: /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T
  SHELL: /usr/local/bin/bash
  PATH:
  - /Users/ron/.pyenv/shims
  - /Users/ron/.rvm/gems/ruby-head/bin
  - /Users/ron/.rvm/gems/ruby-head@global/bin
  - /Users/ron/.rvm/rubies/ruby-head/bin
  - /Users/ron/.nvm/versions/node/lts/*/bin
  - /Users/ron/.nvm/versions/node/v8.9.3/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/ron/bin
  - /Applications/Xcode.app/Contents/Developer/usr/bin
  - /Users/ron/.rvm/bin
  - /Users/ron/.config/yarn/global/node_modules/.bin
  PLATFORM: darwin x64
  FREEMEM: 568143872
  TOTALMEM: 17179869184
  UPTIME: 2342929
  LOADAVG: 2.11328125,2.029296875,2.01513671875
  CPUS:
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.3
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.48
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Path must be a string. Received undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Path must be a string. Received undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at _migrateAddonInitializers (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:92:32)
    at migrateInitializers (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:121:3)
    at Class.included (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/index.js:66:5)
    at project.addons.project.addons.filter.addon (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:538:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:535:47)
    at new EmberApp (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:164:10)
    at module.exports (/Users/ron/mirai-audio/mir/ember-cli-build.js:9:13)

=================================================================================
```

Error has been replicated on CircleCI as well:
https://circleci.com/gh/mirai-audio/mir/254

**Comment by rwjblue** [comment]
Thanks for reporting!  This seems like the same issue as reported in https://github.com/ember-fastboot/ember-cli-fastboot/issues/563, can you confirm that the error is not present when you remove `ember-cli-fastboot` from your `package.json`?

**Comment by 0xadada** [comment]
@rwjblue yessir, i'll report back.

**Comment by 0xadada** [comment]
@rwjblue confirmed.

**Comment by 0xadada** [comment]
should be fixed by https://github.com/0xadada/ember-cli-fastboot/commit/3a7daca150d841af7c724728145b90151c6cc207

**Comment by 0xadada** [comment]
fixed in PR https://github.com/ember-fastboot/ember-cli-fastboot/pull/567
