### ISSUE TITLE
Default travis lint command fails with new app

### ISSUE THREAD

**Issue by john-griffin** [ember-cli/ember-cli#7580]
Running the following commands with cli 2.18.1 installed:

```
ember new new-app --yarn
cd new-app
yarn lint:js
```

Errors like this:

```
yarn run v1.3.2
$ eslint ./*.js app config lib server tests
module.js:540
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/john/Documents/ember/new-app/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.18.1
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
os: darwin x64
2.15.12
1.3.2
```

**Comment by john-griffin** [comment]
For some reason removing `node_modules` and then doing `yarn install` fixes this. ¯\_(ツ)_/¯
