### ISSUE TITLE
Error with ember build production

### ISSUE THREAD

**Issue by mapeveri** [ember-cli/ember-cli#7613]
Hi everyone, I have one problem with te command: 

> ember build --environment=production

This display this message on the terminal:

```
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
TypeError: Cannot read property 'length' of undefined
```

My version of ember-cli is: 

```
ember-cli: 2.18.0
node: 9.5.0
os: linux x64
```

My targets.js:

```
/* eslint-env node */
module.exports = {
  browsers: [
    'ie 9',
    'IE 11',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```
My version of ember-cli-uglify is 2.0.0.

Any idea?.

Thanks!

**Comment by Turbo87** [comment]
do you have a stacktrace for that error?

**Comment by mapeveri** [comment]
Sorry, What is stacktrace . The error only happens to me when I build for production.

**Comment by Turbo87** [comment]
```
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
TypeError: Cannot read property 'length' of undefined
```

is that all you see on the terminal? there is usually a description printed after it that describes where that error was thrown.

**Comment by mapeveri** [comment]
Sorry, this is my stacktrace:

> ERROR Summary:
> 
>   - broccoliBuilderErrorStack: TypeError: Cannot read property 'length' of undefined
>     at UglifyWriter.processFile (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:119:67)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:67:16
>     at Array.forEach (<anonymous>)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:57:25
>     at Array.forEach (<anonymous>)
>     at UglifyWriter.build (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:56:19)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-plugin/read_compat.js:93:34
>     at tryCatch (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:525:12)
>     at invokeCallback (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:538:13)
>     at publish (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:508:7)
>   - codeFrame: Cannot read property 'length' of undefined
>   - errorMessage: The Broccoli Plugin: [Fingerprint] failed with:
>   - errorType: Build Error
>   - location:
>     - column: [undefined]
>     - file: [undefined]
>     - line: [undefined]
>     - treeDir: [undefined]
>   - message: The Broccoli Plugin: [Fingerprint] failed with:
>   - name: Error
>   - nodeAnnotation: UglifyWriter
>   - nodeName: UglifyWriter
>   - originalErrorMessage: Cannot read property 'length' of undefined
>   - stack: TypeError: Cannot read property 'length' of undefined
>     at UglifyWriter.processFile (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:119:67)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:67:16
>     at Array.forEach (<anonymous>)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:57:25
>     at Array.forEach (<anonymous>)
>     at UglifyWriter.build (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-uglify-sourcemap/index.js:56:19)
>     at /media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-plugin/read_compat.js:93:34
>     at tryCatch (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:525:12)
>     at invokeCallback (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:538:13)
>     at publish (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/rsvp/dist/rsvp.js:508:7)
> 
> The broccoli plugin was instantiated at: 
>     at Fingerprint.Plugin (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-plugin/index.js:7:31)
>     at Fingerprint.Filter [as constructor] (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-filter/index.js:34:10)
>     at new Fingerprint (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
>     at Fingerprint (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
>     at new AssetRev (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
>     at AssetRev (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
>     at Class.postprocessTree (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/broccoli-asset-rev/index.js:31:40)
>     at projectOrAddon.addons.reduce (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
>     at Array.reduce (<anonymous>)
>     at addonProcessTree (/media/martinpeveri/windows/Desarrollo/mytaskpanel/mytaskpanel-frontend/mytaskpanel/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
>

**Comment by rwjblue** [comment]
I believe there is an uglify error happening in your build, but it seems like our debug logging is throwing an error here https://github.com/ember-cli/broccoli-uglify-sourcemap/blob/v2.0.1/index.js#L119

Because it assumes `result.code` will exist (before checking `result.error`)...

**Comment by mapeveri** [comment]
@rwjblue Then is it an error of ember-cli?. Thanks!

**Comment by snewcomer** [comment]
Getting this error on ember-cli 3.2 && ember-cli-uglify ^2.1 when building for production.

```
broccoliBuilderErrorStack: TypeError: argname.definition is not a function

node_modules/terser/tools/node.js:21:1), <anonymous>:10835:31)
```

**Comment by locks** [comment]
Closing due to inactivity. Uglify has been updated since this issue was open to support more recent JS syntax, so it is likely addressed.
