### ISSUE TITLE
CSS Imports stop working with Ember-CLI 3.1

### ISSUE THREAD

**Issue by hinti** [ember-cli/ember-cli#7800]
CSS Imports stopped working with Ember-CLI 3.1 (Works with Ember-CLI 3.0)

**Steps to reproduce (Windows 10)**

```
ember new cssimport
cd cssimport
echo @import url("general.css"); >> app\styles\app.css
echo body { background: green; } > app\styles\general.css
yarn build -prod
```

**Outcome of Production build**

```
cleaning up...
Build failed.
Build Error (CleanCSSFilter) in assets/cssimport.css

Broken @import declaration of "general.css"

Stack Trace and Error Report: C:\.../error.dump.2f53f5cb9cc11605612cee8836a9fd88.log

```

**Stack Trace**

```
 ERROR Summary:
  - broccoliBuilderErrorStack: Error: Broken @import declaration of "general.css"
    at arrayToError (C:\...\cssimport\node_modules\array-to-error\index.js:45:15)
    at minifyCallback (C:\...\cssimport\node_modules\clean-css-promise\index.js:33:20)
    at whenSourceMapReady (C:\...\cssimport\node_modules\clean-css\lib\clean.js:139:16)
    at Object.whenDone (C:\...\cssimport\node_modules\clean-css\lib\clean.js:155:14)
    at processNext (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:105:13)
    at importFrom (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:79:10)
    at processNext (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:104:16)
    at inlineLocalResource (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:355:12)
    at inline (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:218:10)
    at importFrom (C:\...\cssimport\node_modules\clean-css\lib\imports\inliner.js:74:12)
  - codeFrame: Broken @import declaration of "general.css"
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `CleanCSSFilter` plugin. ðŸ’¥
Broken @import declaration of "general.css"

```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.2
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: win32 x64
5.6.0
1.6.0
```

**Comment by sranka** [comment]
Having the same issue after upgrade from Ember 2.18 to 3.1,  the broken css imports are in my case created by ember-component-css addon.

**Comment by sranka** [comment]
My investigation:

CleanCSS instance is constructed with a wrong relativePath option during the build process:
The options created for Clean CSS are:
  minifyCSS: { processImport: true, relativeTo: 'assets' },
  relativeTo: '/ember_project/tmp/broccoli_persistent_filterclean_cssfilter-input_base_path-fndAK9Gk.tmp' 

the relativeTo option should be '/ember_project/tmp/broccoli_persistent_filterclean_cssfilter-input_base_path-fndAK9Gk.tmp**/assets**' 

Indeed the change is between Ember 3.0 and Ember 3.1 , the options that are provided to CleanCSS were IMHO changed in a wrong way in https://github.com/ember-cli/ember-cli/commit/b0727ec5ea953c57f83178bb48bbd654693cab0c#diff-392bb207fea8bcbeb4a084bb445f7cc7

Reverting a part of your changes that setups correct options for preprocessMinifyCss fixes this issue in lib/broccoli/ember-app.js @1600 in 'beta' branch:

      if (cssMinificationEnabled === true) {
        let cssOptions = this.options.minifyCSS.options || {};	
        cssOptions.registry = this.registry;
        preprocessedStyles = preprocessMinifyCss(preprocessedStyles, cssOptions);
        vendorStyles = preprocessMinifyCss(vendorStyles, cssOptions);
      }

@twokul Can you please comment on the observation above? I found this defect in the beta branch, and a similar one (but in lib/broccoli/default.js ) in the master branch.

**Comment by sranka** [comment]
Created a pull request with a suggested fix, it would be nice to have a backport of the fix in Ember 3.2 or in Ember 3.1.x . I can help with it when required.

**Comment by twokul** [comment]
@sranka thanks for the patch! PR reviewed, I can help you with backporting.

**Comment by sranka** [comment]
@Benjy1979 See https://ember-cli.com/asset-compilation#minifying

    minifyCSS: {
      enabled: false
    }

A non-production build of CSS files is then applied to a production build.

**Comment by Benjy1979** [comment]
Thankyou.

**Comment by jjwatts** [comment]
I'm getting the same issue currently with Ember CLI v3.3. Tracking it down, it looks like it maybe to do with the minify options not getting passed to CleanCSS, resulting in the relative path not being appended (and therefore @import not being able to find relative files).

In the method 'preprocessMinifyCss' in ember-cli-preprocessor-registry/preprocessors.js it looks like perhaps

```
  if (plugins.length === 0) {
    var compiler = require('broccoli-clean-css');
    return compiler(tree, options);
  }
```

Should be:

```
  if (plugins.length === 0) {
    var compiler = require('broccoli-clean-css');
    return compiler(tree, options.minifyCSS);
  }
```

That seemed to resolve my issue with @import statements in CSS not working for my production builds.
