### ISSUE TITLE
Module Unification Blueprint can't find styles directory

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#7832]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.2.0-beta.2
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: linux x64
5.6.0
1.6.0
```

## Steps to reproduce:

```bash
$ npm install -g github:ember-cli/ember-cli#master
# at the time of opening this issue, master is f14a2770131dc2427f086b6f2771031dc517797c
$ MODULE_UNIFICATION=true ember new app-test
$ cd app-test
$ MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true yarn start
yarn run v1.6.0
$ ember serve
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Build Error (Funnel)

ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'


Stack Trace and Error Report: /tmp/error.dump.0478bbc24a2b420162674a3911219902.log

```

cat of that dump file
```
=================================================================================

ENV Summary:

  TIME: Tue May 15 2018 09:04:36 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /home/me/.nvm/versions/node/v8.11.1/bin/node
  - /tmp/app-test/node_modules/.bin/ember
  - serve
  EXEC_PATH: /home/me/.nvm/versions/node/v8.11.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/app-test/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /tmp/app-test/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.yarn/bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/.pythons/Python-3.6.3/bin
  - /home/me/.cargo/bin
  - /usr/local/heroku/bin
  - /tmp/node_modules/.bin
  - /home/me/apps/phantomjs/bin
  - /home/me/scripts/system-utils
  - /home/me/scripts/git
  - /home/me/scripts/rails
  - /home/me/scripts
  - /home/me/.nvm/versions/node/v8.11.1/bin
  - /home/me/.cargo/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/me/.fzf/bin
  - /home/me/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 181231616
  TOTALMEM: 8242163712
  UPTIME: 88573
  LOADAVG: 0.64013671875,0.9462890625,1.21533203125
  CPUS:
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2686
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2675
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2630
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2599
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.11.1
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
    at Object.fs.readdirSync (fs.js:904:18)
    at _walkSync (/tmp/app-test/node_modules/walk-sync/index.js:74:18)
    at Function.entries (/tmp/app-test/node_modules/walk-sync/index.js:50:10)
    at Funnel.processFilters (/tmp/app-test/node_modules/broccoli-funnel/index.js:322:26)
    at Funnel.build (/tmp/app-test/node_modules/broccoli-funnel/index.js:258:10)
    at /tmp/app-test/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:2415:5)
  - codeFrame: ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
  - name: Error
  - nodeAnnotation: Funnel
  - nodeName: Funnel
  - originalErrorMessage: ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
  - stack: Error: ENOENT: no such file or directory, scandir '/tmp/app-test/tmp/funnel-input_base_path-hUGhvc8L.tmp/app-test/styles/'
    at Object.fs.readdirSync (fs.js:904:18)
    at _walkSync (/tmp/app-test/node_modules/walk-sync/index.js:74:18)
    at Function.entries (/tmp/app-test/node_modules/walk-sync/index.js:50:10)
    at Funnel.processFilters (/tmp/app-test/node_modules/broccoli-funnel/index.js:322:26)
    at Funnel.build (/tmp/app-test/node_modules/broccoli-funnel/index.js:258:10)
    at /tmp/app-test/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/tmp/app-test/node_modules/rsvp/dist/rsvp.js:2415:5)

=================================================================================
```

### Expected:

to see successful build without sass errors.

**Comment by twokul** [comment]
I think I know what that is
