### ISSUE TITLE
ember build command (for glimmer applications) fail if I had .orig files

### ISSUE THREAD

**Issue by gokatz** [ember-cli/ember-cli#7871]
While running  `ember build` command in `glimmer` application, I got a build error,

```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
undefined

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/gokul/Project/extensions/my-app/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/gokul/Project/extensions/my-app/node_modules/@glimmer/application-pipeline/node_modules/broccoli-merge-trees/index.js:16:10)
    at GlimmerApp.buildConfigTree (/Users/gokul/Project/extensions/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:355:26)
    at GlimmerApp.javascript (/Users/gokul/Project/extensions/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:232:31)
    at GlimmerApp.toTree (/Users/gokul/Project/extensions/my-app/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:297:27)
    at module.exports (/Users/gokul/Project/extensions/my-app/ember-cli-build.js:15:14)
    at Builder.setupBroccoliBuilder (/Users/gokul/Project/extensions/my-app/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/gokul/Project/extensions/my-app/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/Users/gokul/Project/extensions/my-app/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/Users/gokul/Project/extensions/my-app/node_modules/ember-cli/lib/models/command.js:243:46)
```

Since the error message was not sufficent, I debug the command and found out the reason for the failure to be 

```
"Both `ui/components/MyApp/component` and `ui/components/MyApp/component.ts` represent component:/my-app/components/MyApp, please rename one to remove the collision."
```

This error is caused beacuse I had a `.orig` file for the above component while rebasing against master. When I delete the `.orig` file, `ember build` ran successfully!

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
1.5.1
```

**Now,**

- Should we ignore `.orig` file by default?
- Displaying the original error message would be more helpful. I dig a little bit and found that we have'nt passed/reference `isSilentError` (in [broccoli-build-error](https://github.com/ember-cli/broccoli-builder/blob/0-18-x/lib/broccoli-build-error.js#L15)). So, the message got ignored. When I reference the `isSilentError` in broccoli-build-error. I got the following error message without trace.

```
Build Canceled: Broccoli Builder ran into an error with ResolutionMapBuilder plugin. 💥
Both `ui/components/MyApp/component` and `ui/components/MyApp/component.ts` represent component:my-app/components/MyApp, please rename one to remove the collision.
```
 Is this intentional?

**Comment by Turbo87** [comment]
@gokatz please move this issue to the https://github.com/glimmerjs/glimmer.js/ issue tracker. this is an issue with the Glimmer build pipeline, but not with Ember CLI itself.
