### ISSUE TITLE
`Acceptance: addon-mu-smoke-test` test failure

### ISSUE THREAD

**Issue by cyk** [ember-cli/ember-cli#7872]
[PR #7869 uncovered](https://github.com/ember-cli/ember-cli/pull/7869#discussion_r194243066) that`tests/acceptance/addon-mu-smoke-test-slow.js` actually fails for MU. 

The [test is now skipped](https://github.com/ember-cli/ember-cli/blob/5b60f35460da5c915347c077fcd72c97e610c7aa/tests/acceptance/addon-mu-smoke-test-slow.js#L24).

Prior to that PR, `MODULE_UNIFICATION` env was never set, so the new command in `createTestTargets` would generate a classic app.

<details>
<summary>Test output</summary>

```sh
> EMBER_CLI_MODULE_UNIFICATION=true yarn test tests/acceptance/addon-mu-smoke-test-slow.js

Acceptance: addon-mu-smoke-test
      Running: node_modules/ember-cli/bin/ember build in: /Users/cyk/Code/cyk/ember-cli/tmp/some_cool_addon_clone-xNdcqGo9.tmp

#...snip...

not ok 1 Chrome 67.0 - Acceptance: renders imported component
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: You cannot use the same root element (DIV) multiple times in an Ember.Application
                at new EmberError (http://localhost:7357/assets/vendor.js:25528:25)
                at assert (http://localhost:7357/assets/vendor.js:25778:15)
                at Class.setup (http://localhost:7357/assets/vendor.js:57876:86)
                at Class.setupEventDispatcher (http://localhost:7357/assets/vendor.js:23373:18)
                at Class._bootSync (http://localhost:7357/assets/vendor.js:23328:14)
                at http://localhost:7357/assets/vendor.js:24294:30
                at initializePromise (http://localhost:7357/assets/vendor.js:63704:7)
                at new Promise (http://localhost:7357/assets/vendor.js:64184:35)
                at Class.boot (http://localhost:7357/assets/vendor.js:24293:27)
                at http://localhost:7357/assets/test-support.js:8178:36
        message: >
            Promise rejected before "renders imported component": Assertion Failed: You cannot use the same root element (DIV) multiple times in an Ember.Application
        Log: |
    ...
```
</details>

**Comment by ppcano** [comment]
#8312 tries to close this issue.
