### ISSUE TITLE
Errors and warning with Node 10 using ember-cli 3.30

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#7995]
after ` npm install` using Node 10.9.0:
```
npm install        

> fsevents@1.1.3 install /Users/villander/Projects/web_app/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::839839::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse

            MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::171171::11::  notenote: : 

            'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom

            macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from ../fsevents.ccIn file included from :../fsevents.cc6::
6:
../../nan/nan.h:../../nan/nan.h854::85418::18 : warning: warning: 'MakeCallback' 'MakeCallback'is  isdeprecated:  deprecated:Use 
Use      
MakeCallback(...,       MakeCallback(...,async_context)  async_context)[-Wdeprecated-declarations] [-Wdeprecated-declarations]

    return node::MakeCallback(
    return node::MakeCallback(
                 ^
                 ^
/Users/villander/.node-gyp/10.9.0/include/node/node.h:/Users/villander/.node-gyp/10.9.0/include/node/node.h164::1641::1 : note: note: 
      
'MakeCallback'       'MakeCallback'has  hasbeen  beenexplicitly  explicitlymarked  markeddeprecated  deprecatedhere here

NODE_DEPRECATED("Use MakeCallback(..., async_context)",
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
^
/Users/villander/.node-gyp/10.9.0/include/node/node.h:/Users/villander/.node-gyp/10.9.0/include/node/node.h88::8820::20 : note: note: expanded expandedfrom 
from      
macro       macro'NODE_DEPRECATED' 'NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator
    __attribute__((deprecated(message))) declarator
                   ^
                   ^
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::869869::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse

            MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::157157::11::  notenote: : 

            'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom

            macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
../../nan/nan.h../../nan/nan.h::14781478::3131::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse

            MakeCallback(...,MakeCallback(...,  async_context)async_context)  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return scope.Escape(node::MakeCallback(    return scope.Escape(node::MakeCallback(

                              ^                              ^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::171171::11::  notenote: : 

            'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/villander/.node-gyp/10.9.0/include/node/node.h/Users/villander/.node-gyp/10.9.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom

            macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

4 warnings generated.
4 warnings generated.
sed: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
  SOLINK_MODULE(target) Release/fse.node
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/villander/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/villander/.nvm/versions/node/v10.9.0/bin/node" "/Users/villander/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/villander/Projects/web_app/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/villander/.nvm/versions/node/v10.9.0/bin/node /Users/villander/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/villander/Projects/web_app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/villander/.nvm/versions/node/v10.9.0/bin/node" "/Users/villander/Projects/web_app/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/villander/Projects/web_app/node_modules/fsevents
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/villander/.nvm/versions/node/v10.9.0/bin/node /Users/villander/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/villander/Projects/web_app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> fsevents@1.2.4 install /Users/villander/Projects/web_app/node_modules/sane/node_modules/fsevents
> node install

[fsevents] Success: "/Users/villander/Projects/web_app/node_modules/sane/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.2.4 install /Users/villander/Projects/web_app/node_modules/watchpack/node_modules/fsevents
> node install

[fsevents] Success: "/Users/villander/Projects/web_app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.0 install /Users/villander/Projects/web_app/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/villander/.npm/node-sass/4.9.0/darwin-x64-64_binding.node

> spawn-sync@1.0.15 postinstall /Users/villander/Projects/web_app/node_modules/spawn-sync
> node postinstall


> node-sass@4.9.0 postinstall /Users/villander/Projects/web_app/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/villander/Projects/web_app/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1694 packages from 743 contributors and audited 119996 packages in 19.215s
found 25 vulnerabilities (4 low, 19 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by stefanpenner** [comment]
Based on the above log it looks like you are including webpack somewhere as a dependency. And that is introducing this native dependency. Maybe via ember-auto-import?

If so, this may not be an ember-cli issue. As it wouldn’t be part of what ember-cli ships by default, rather a userland module or addon.

**Comment by amusedberry** [comment]
Hi! I know this was closed, but I have a similar issue since the first day I started using ember (since version 2.3 if I'm not wrong). I just get warnings about fsevents whenever I use `ember new`, `ember serve` or `ember build`. I code on windows, so I can't install fsevents. It does not affect me, but it is hard to pitch ember to coworkers with all those warnings roaming around.

This is my current build:
```
ember-cli: 3.4.3
node: 10.8.0
os: win32 x64
```

Here are the warnings for a new ember app:
```
PS C:\> ember new app
WARNING:
WARNING: The 'package.json' file for the addon at C:\Users\User\AppData\Roaming\npm\node_modules\ember-cli\node_modules\ember-cli-broccoli-sane-watcher\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at C:\Users\User\AppData\Roaming\npm\node_modules\ember-cli\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
installing app
create ...
WARNING: Ember CLI is using the global npm, but your npm version has not yet been verified to work with the current Ember CLI release.
npm: Installed dependencies
Successfully initialized git.

PS C:\> cd app
PS C:\app> ember s
WARNING:
WARNING: The 'package.json' file for the addon at C:\app\node_modules\ember-cli-broccoli-sane-watcher\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at C:\app\node_modules\qunit\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at C:\app\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
```

Here are the warnings for a new ember app with ember-cli-sass and liquid-fire.
```
WARNING:
WARNING: The 'package.json' file for the addon at {root}\node_modules\chokidar
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at {root}\node_modules\ember-cli-broccoli-sane-watcher\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at {root}\node_modules\qunit\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at {root}\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
```

**Comment by Turbo87** [comment]
@amusedberry that is an unrelated issue. as you can see at https://github.com/amasad/sane/blob/49f251a95e6db118ad71223b1eca93c876d9aacc/package.json#L55 `fsevents` is specified as an optional dependency so I have no idea why npm decided to warn you about it missing. did you try to use `yarn` instead of `npm`?
