### ISSUE TITLE
Package Info tests are failing on windows

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7998]
https://github.com/ember-cli/ember-cli/blob/master/tests/unit/models/package-info-cache-test.js#L185

```sh
 1) models/package-info-cache.js
      packageInfo
        valid project
          validates projectPackageInfo:
    AssertionError: expected undefined to exist
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:214:38)

 2) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 0 errors:
    TypeError: Cannot read property 'hasErrors' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:220:35)

 3) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 1 dependencyPackage:
    TypeError: Cannot read property 'dependencyPackages' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:225:53)

 4) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 82devDependencyPackages:
    TypeError: Cannot read property 'devDependencyPackages' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:233:56)

 5) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 1 in-repo addon named "ember-super-button":
    TypeError: Cannot read property 'inRepoAddons' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:240:47)

 6) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 7 internal addon packages:
    TypeError: Cannot read property 'internalAddons' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:249:49)

 7) models/package-info-cache.js
      packageInfo
        valid project
          shows projectPackageInfo has 7 node-module entries:
    TypeError: Cannot read property 'nodeModules' of undefined
     at Context.<anonymous> (tests\unit\models\package-info-cache-test.js:256:46)
```

**Comment by twokul** [comment]
likely realted to https://github.com/ember-cli/ember-cli/issues/7981

**Comment by twokul** [comment]
cc @dcombslinkedin

**Comment by dcombslinkedin** [comment]
@twokul , I have a fix coming in shortly for the package-info-cache-test.js errors. The problem was trivial - adding / instead of ${path.sep} in 3 places when specifying a file to search for.

**Comment by dcombslinkedin** [comment]
@twokul  - https://github.com/ember-cli/ember-cli/pull/8002/files

**Comment by stefanpenner** [comment]
Let’s normalize in getEntry and callers can continue to call as if they where in posix

**Comment by scalvert** [comment]
This issue is affecting my PR (#8000) also.

**Comment by twokul** [comment]
@scalvert I'm spending tomorrow to work on cli@3.4 release tomorrow, and will make sure it's fixed

**Comment by dcombslinkedin** [comment]
This issue was already closed with my original fix the other day. If you want to change that fix, that's fine, but it should not be failing at this point. @scalvert, I would assume at this point that you are unblocked if you'[re using the beta branch.

**Comment by stefanpenner** [comment]
@twokul / @dcombslinkedin can this be closed?

**Comment by scalvert** [comment]
I'm unblocked, thanks.
