### ISSUE TITLE
Error on production build [Cannot read property '_walk' of null]

### ISSUE THREAD

**Issue by bajcmartinez** [ember-cli/ember-cli#8075]
Hi all,

When building my project in production mode I'm getting `Cannot read property '_walk' of null`. This happens to a few of our projects and started happening a few days back.

Anyone else with this issue? Any ideas how to solve it?

Thanks

```
ENV Summary:

  TIME: Fri Sep 28 2018 10:27:46 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/z002fawe/.nvm/versions/node/v10.9.0/bin/node
  - /Users/z002fawe/.nvm/versions/node/v10.9.0/bin/ember
  - build
  - --environment=production
  EXEC_PATH: /Users/z002fawe/.nvm/versions/node/v10.9.0/bin/node
  TMPDIR: /var/folders/5g/tl5x1p1d15bbrv8fg4r1xmcw0000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Applications/Wireshark.app/Contents/MacOS
  - /Applications/Postgres.app/Contents/Versions/10/bin/
  - /anaconda3/bin
  - /Users/z002fawe/.nvm/versions/node/v10.9.0/bin
  PLATFORM: darwin x64
  FREEMEM: 1813299200
  TOTALMEM: 17179869184
  UPTIME: 90110
  LOADAVG: 3.5947265625,2.98388671875,2.85546875
  CPUS:
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.9.0
  - openssl: 1.1.0i
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.8.275.24-node.14
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property '_walk' of null
    at AST_Dot.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1145:29)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_Dot._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1144:24)
    at AST_VarDef.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1091:40)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_VarDef._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1089:24)
    at AST_Var.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:999:32)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_Var._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:996:24)
    at walk_body (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:510:17)
  - codeFrame: Cannot read property '_walk' of null
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `UglifyWriter` plugin. 💥
Cannot read property '_walk' of null
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `UglifyWriter` plugin. 💥
Cannot read property '_walk' of null
  - name: Error
  - nodeAnnotation: UglifyWriter
  - nodeName: UglifyWriter
  - originalErrorMessage: Cannot read property '_walk' of null
  - stack: TypeError: Cannot read property '_walk' of null
    at AST_Dot.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1145:29)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_Dot._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1144:24)
    at AST_VarDef.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1091:40)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_VarDef._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1089:24)
    at AST_Var.eval (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:999:32)
    at TreeWalker._visit (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:1546:21)
    at AST_Var._walk (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:996:24)
    at walk_body (eval at <anonymous> (/Users/z002fawe/Projects/product-advisor/test/pa-aurora-frontend/node_modules/terser/tools/node.js:21:1), <anonymous>:510:17)

=================================================================================
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.1
http_parser: 2.8.0
node: 10.9.0
v8: 6.8.275.24-node.14
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.6.0
```

**Comment by guneetsinghbhatia** [comment]
I have same error .
Output from ember version --verbose && npm --version && yarn --version:
ember-cli: 2.18.2
http_parser: 2.8.0
node: 10.7.0
v8: 6.7.288.49-node.15
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.2.0
1.9.2

**Comment by KyleCartmell** [comment]
I'm working on the same problem in a completely different stack. Seems to be a transitive dependency issue via uglify related to acorn?

**Comment by gs-akhan** [comment]
@KyleCartmell Thank you, this saved my day.. I really don't know why all my prod builds in Jenkins were failing all of sudden. :(
I added this for now and it worked. 

Please let me know if there is full proof solution if you find.

**Comment by bajcmartinez** [comment]
@KyleCartmell thanks, that could be a workaround for now, good catch! Hopefully, this is solved soon

**Comment by guneetsinghbhatia** [comment]
@KyleCartmell thanks, Will use this workaround for now.

**Comment by alechirsch** [comment]
I put this into my ember-cli-build configuration and the build still fails `ember build --environment production`
```
		'ember-cli-uglify': {
			uglify: {
				compress: {
					collapse_vars: false,
					reduce_vars: false
				}
			}
		},
```

Any ideas?

**Comment by alechirsch** [comment]
Just kidding, it worked for me. I accidentally put it in the wrong place.

**Comment by Penthious** [comment]
We had the same issue and our workaround is what @alechirsch said, put that code snippet inside of `ember-cli-build` and you should be good to go.

**Comment by jrjohnson** [comment]
If this is happening in your build could you follow the directions over at https://github.com/terser-js/terser/issues/120#issuecomment-425979826 to report the details?

**Comment by serchavalos** [comment]
> @KyleCartmell Thank you, this saved my day.. I really don't know why all my prod builds in Jenkins were failing all of sudden. :(
> I added this for now and it worked.

Same here. I'm really confused about how this happened in first place. Could somebody explain why this config is needed now?

**Comment by jrjohnson** [comment]
@serchavalos lots of details are available over in terser-js/terser#120

**Comment by serchavalos** [comment]
@jrjohnson ahh yes 🤦‍♂️ now I see it. Thanks!

**Comment by rwwagner90** [comment]
Just started getting this error as well. Do we need to update configs in ember-cli or is terser planning to fix things there?

**Comment by rwjblue** [comment]
AFAICT the terser folks opened an issue on tether to see if they would be open to working around on their side:

https://github.com/HubSpot/tether/issues/291

In theory, we _could_ change our default terser config, but in general would prefer not to...

**Comment by rwwagner90** [comment]
@rwjblue I'm getting this error without tether though, so I think there needs to either be a broader terser fix or we need to change our config.

**Comment by locks** [comment]
Closing due to inactivity. If you are still affected by the problem described, please let us know!
