### ISSUE TITLE
Upgrading from 3.1.4 to 3.4.3 results in broccoli error

### ISSUE THREAD

**Issue by Bouke** [ember-cli/ember-cli#8094]
I upgraded my project using `ember-cli-update` to 3.4.3 and then some additional dependencies using `yarn upgrade-interactive --latest`.

This is now the output of `yarn ember build`:

```
WARNING: [ember-cli-template-lint] Test framework detection was unsuccessful. Please provide a "testGenerator" option explicitly to enable the test generators.
broccoli-persistent-filter:EslintValidationFilter: Expected Broccoli node, got null for inputNodes[0]
```

This doesn't mean anything to me or what  the cause might be. I would love to hear where this issue is coming from.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
$ yarn ember version --verbose                                                                  ✔  6264  21:00:03
yarn run v1.10.1
$ node_modules/.bin/ember version --verbose
ember-cli: 3.4.3
http_parser: 2.8.0
node: 10.11.0
v8: 6.8.275.32-node.28
uv: 1.23.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.33.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
✨  Done in 1.55s.
```

My dependencies in `package.json`:
```
    "@ember-decorators/babel-transforms": "2.1.2",
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.7.0",
    "@types/ember": "^3.0.24",
    "@types/ember-data": "^3.1.1",
    "@types/rsvp": "^4.0.1",
    "babel-eslint": "^8.2.3",
    "ember-ajax": "^3.1.0",
    "ember-cli": "~3.4.3",
    "ember-cli-babel": "^7.1.2",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-less": "^2.0.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-typescript": "^1.3.2",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.4.0",
    "ember-decorators": "^2.2.0",
    "ember-islands": "^1.4.0",
    "ember-load-initializers": "^1.1.0",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.4.0",
    "eslint-plugin-ember": "^5.2.0",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.7.1",
    "semantic-ui-ember": "https://github.com/Bouke/Semantic-UI-Ember.git#457bfde7ad165c890ce6e13032bb3d73173b9960",
    "typescript": "^3.1.1"
```

My `ember-cli-build.js`:
```js
module.exports = function(defaults) {
    var vendorFiles = {};
    vendorFiles['jquery.js'] = null; // will be available from wrapper application
    let app = new EmberApp(defaults, {
        eslint: {
            group: false,
        },
        vendorFiles: vendorFiles,
        storeConfigInMeta: false,
        fingerprint: {
            enabled: false
        },
        babel: {
            plugins: []
        },
        SemanticUI: { ... }
    });
    return app.toTree();
};
```

The stack trace from the error:
```
  - stack: TypeError: broccoli-persistent-filter:EslintValidationFilter: Expected Broccoli node, got null for inputNodes[0]
    at EslintValidationFilter.Plugin (myproject/node_modules/broccoli-plugin/index.js:23:13)
    at EslintValidationFilter.Filter [as constructor] (myproject/node_modules/broccoli-persistent-filter/index.js:78:10)
    at new EslintValidationFilter (myproject/node_modules/broccoli-lint-eslint/lib/index.js:67:10)
    at Function.EslintValidationFilter.create (myproject/node_modules/broccoli-lint-eslint/lib/index.js:214:12)
    at Class.lintTree (myproject/node_modules/ember-cli-eslint/index.js:44:19)
    at addons.reduce (myproject/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:6:23)
    at Array.reduce (<anonymous>)
    at lintAddonsByType (myproject/node_modules/ember-cli/lib/utilities/lint-addons-by-type.js:4:17)
    at EmberApp.addonLintTree (myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:892:18)
    at EmberApp.getLintTests (myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1405:28)
```

**Comment by Bouke** [comment]
I've found the upstream problem: https://github.com/ember-cli/ember-cli-eslint/issues/249.
