### ISSUE TITLE
CI is broken _somehow_ related to npm package resolution

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#8098]
<details>
<summary>The most recent builds of `master` and `beta` branch are failing due to a somewhat bizarre npm resolution failure. The `release` branch seems to be passing without issue.</summary>

```
Cannot find module 'babel-plugin-debug-macros'
Error: Cannot find module 'babel-plugin-debug-macros'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Class._getDebugPlugin (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:100:29)
    at Class.registerTransformWithParent (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:54:30)
    at Class.included (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:36:10)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
Cannot find module 'babel-plugin-debug-macros'
Error: Cannot find module 'babel-plugin-debug-macros'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Class._getDebugPlugin (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:100:29)
    at Class.registerTransformWithParent (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:54:30)
    at Class.included (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:36:10)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
Cannot find module 'babel-plugin-debug-macros'
Error: Cannot find module 'babel-plugin-debug-macros'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Class._getDebugPlugin (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:100:29)
    at Class.registerTransformWithParent (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:54:30)
    at Class.included (/home/travis/build/ember-cli/ember-cli/tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:36:10)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.reduce (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:463)
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:134:263)
    at Class.included (/home/travis/build/ember-cli/ember-cli/lib/models/addon.js:235:70)
    at Class.superWrapper [as included] (/home/travis/build/ember-cli/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
not ok 1300 Acceptance: smoke-test ember test still runs when a JavaScript testem config exists
  Error: Cannot find module 'babel-plugin-debug-macros'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.resolve (internal/modules/cjs/helpers.js:30:19)
      at Class._getDebugPlugin (tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:100:29)
      at Class.registerTransformWithParent (tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:54:30)
      at Class.included (tmp/node-iTKrxhyQ.tmp/node_modules/ember-compatibility-helpers/index.js:36:10)
      at Class.superWrapper [as included] (node_modules/core-object/lib/assign-properties.js:34:20)
      at addons.reduce (lib/models/addon.js:134:463)
      at Array.reduce (<anonymous>)
      at Class.eachAddonInvoke (lib/models/addon.js:134:263)
      at Class.included (lib/models/addon.js:235:70)
      at Class.superWrapper [as included] (node_modules/core-object/lib/assign-properties.js:34:20)
      at addons.reduce (lib/models/addon.js:134:463)
      at Array.reduce (<anonymous>)
      at Class.eachAddonInvoke (lib/models/addon.js:134:263)
      at Class.included (lib/models/addon.js:235:70)
      at Class.superWrapper [as included] (node_modules/core-object/lib/assign-properties.js:34:20)
```
</details>

---

* Builds:
  * master: https://travis-ci.org/ember-cli/ember-cli/builds/438880030
  * beta: https://travis-ci.org/ember-cli/ember-cli/builds/438581797
  * release: https://travis-ci.org/ember-cli/ember-cli/builds/438581788

---

Current bisect status (`git bisect log`):

```
git bisect start
# good: [8fdd60aff31fbf3e5bb01c5418d27c6971765c36] Merge pull request #8071 from ember-cli/greenkeeper/sane-4.0.0
git bisect good 8fdd60aff31fbf3e5bb01c5418d27c6971765c36
# bad: [63171e91b898b5ad282f453360ca9eff4720af8d] Release v3.5.0-beta.1.
git bisect bad 63171e91b898b5ad282f453360ca9eff4720af8d
# good: [681b6fc94e0e0cd3bd546aa7fe625dbe378dd5ae] Merge remote-tracking branch 'origin/release' into beta
git bisect good 681b6fc94e0e0cd3bd546aa7fe625dbe378dd5ae
# good: [cac9a1a383816124bafed9f7609a076e3560cd4d] Merge pull request #7910 from astronomersiva/experiment_flags_in_ember_cli
git bisect good cac9a1a383816124bafed9f7609a076e3560cd4d
# good: [2ffcf6b99f5132f1e59055bfd93e26985c999ef2] Update codecoverage.sh file
git bisect good 2ffcf6b99f5132f1e59055bfd93e26985c999ef2
# bad: [33f9097d094f4d4c1d81a03273f0661d29d64284] Merge pull request #7973 from dcyriller/coverage-job-adjustment
git bisect bad 33f9097d094f4d4c1d81a03273f0661d29d64284
# bad: [2d92c310c1b889983422ed76aca05a276981a70b] Merge pull request #7971 from rwjblue/stop-mucking-with-npm-versions
git bisect bad 2d92c310c1b889983422ed76aca05a276981a70b
# bad: [8f94c321409eef2a9687fc99e6d36c68bff71f90] Merge pull request #7972 from rwjblue/remove-ember-install-acceptance-test
git bisect bad 8f94c321409eef2a9687fc99e6d36c68bff71f90
# bad: [e9cded4e87f021d7aad97e8c6d5f82cd3a901998] Remove `ember install` slow test.
git bisect bad e9cded4e87f021d7aad97e8c6d5f82cd3a901998
# good: [3f2957ebde536e762063c28e696df47823b9332f] Merge pull request #7959 from dcyriller/fix-doc
git bisect good 3f2957ebde536e762063c28e696df47823b9332f
# first bad commit: [e9cded4e87f021d7aad97e8c6d5f82cd3a901998] Remove `ember install` slow test.
```

**Comment by rwjblue** [comment]
Current bisect status:

```
git bisect start
# good: [8fdd60aff31fbf3e5bb01c5418d27c6971765c36] Merge pull request #8071 from ember-cli/greenkeeper/sane-4.0.0
git bisect good 8fdd60aff31fbf3e5bb01c5418d27c6971765c36
# bad: [63171e91b898b5ad282f453360ca9eff4720af8d] Release v3.5.0-beta.1.
git bisect bad 63171e91b898b5ad282f453360ca9eff4720af8d
# good: [681b6fc94e0e0cd3bd546aa7fe625dbe378dd5ae] Merge remote-tracking branch 'origin/release' into beta
git bisect good 681b6fc94e0e0cd3bd546aa7fe625dbe378dd5ae
```

**Comment by rwjblue** [comment]
At this point I suspect the issue is https://github.com/ember-cli/ember-cli/pull/7971, but still bisecting to confirm. 

My hypothesis is that when ran with npm@5 / npm@6 we end up with a topology in local tests (where we attempt to `npm link` things around to avoid repeated `npm install` / `yarn install` steps) that is not valid.  More info to follow (hopefully)...

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/ember-cli/pull/8106
