### ISSUE TITLE
3.5.0 - Warning without trace

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#8163]
After updated ember project to ember-cli 3.5.0 i have these warnings,

```
ember-cli: 3.5.0
node: 8.11.4
os: darwin x64

```

```
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Filter: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to broccoli-persistent-filter:Mapper
-~- created here: -~-
    at Mapper.Plugin (/Users/villander/Projects/web_app/node_modules/broccoli-plugin/index.js:7:31)
    at Mapper.Filter [as constructor] (/Users/villander/Projects/web_app/node_modules/broccoli-persistent-filter/index.js:64:10)
    at new Mapper (/Users/villander/Projects/web_app/node_modules/broccoli-stew/lib/map.js:38:10)
    at Mapper (/Users/villander/Projects/web_app/node_modules/broccoli-stew/lib/map.js:36:12)
    at Class.treeForVendor (/Users/villander/Projects/web_app/node_modules/ember-fetch/index.js:85:19)
    at Class._treeFor (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/addon.js:616:33)
    at Class.treeFor (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/addon.js:576:21)
    at addons.reduce (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/addon.js:449:26)
    at Array.reduce (<anonymous>:null:null)
    at Class.eachAddonInvoke (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/addon.js:446:24)
    at Class.treeFor (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/addon.js:575:22)
    at project.addons.reduce (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:699:26)
    at Array.reduce (<anonymous>:null:null)
    at EmberApp._addonTreesFor (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:697:32)
    at EmberApp.addonTreesFor (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:721:17)
    at EmberApp.getExternalTree (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:1255:30)
    at EmberApp.toArray (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:1619:12)
    at EmberApp.toTree (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/broccoli/ember-app.js:1747:22)
    at module.exports (/Users/villander/Projects/web_app/ember-cli-build.js:57:14)
    at Builder.readBuildFile (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

-~- (end) -~----------------
```

I also have this warning

```
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Filter

Build successful (8727ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
broccoli-persistent-filter:EslintValid... (3) | 1835ms (611 ms)     
SassCompiler (1)                              | 1456ms              
ember-auto-import-analyzer (3)                | 799ms (266 ms)      
Rollup (1)                                    | 652ms               
Package /assets/vendor.js (1)                 | 594ms               
Bundler (1)                                   | 487ms               


```

**Comment by rwjblue** [comment]
The instantiation stack in the error tells you which addon is causing things to fall back. You should `yarn list ember-fetch` or `npm ls ember-fetch` and update it to a more recent version.

**Comment by aalimovs** [comment]
Had the same issue, `ember-fetch` was causing issue because `ember-simple-auth` 1.6.0 was using it. Bumping it to `1.7.0` fixed the issues.

We've also had to remove `ember-freestyle` 0.9.0 (latest version at this time). Waiting for https://github.com/chrislopresto/ember-freestyle/issues/186 to merge

**Comment by rwjblue** [comment]
Thanks for concfirming @aalimovs.

Closing this as I'm fairly sure that the warning is as useful as we can make it 😢

**Comment by villander** [comment]
I updated `ember-simple-auth` to 1.7.0 and the warning disappeared. Thanks @rwjblue @aalimovs
