### ISSUE TITLE
Error running `ember new my-app -b @glimmer/blueprint`,

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli#8204]
crosslink: https://github.com/glimmerjs/glimmer.js/issues/158

tested on:
ember-cli@3.6.0-beta.1
ember-cli@3.4.3
ember-cli@3.3.0
ember-cli@3.1.3

platform: windows

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-388-12oj9rm.em0ah\node_modules\@glimmer\blueprint\package.json'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-388-12oj9rm.em0ah\node_modules\@glimmer\blueprint\package.json'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'C:\Users\ALEKSA~1\AppData\Local\Temp\ember-cli1181022-388-12oj9rm.em0ah\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at InstallBlueprintTask._validateNpmModule (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:133:15)
    at _createTempFolder.then.then.modulePath (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:92:14)
    at tryCatcher (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at publish (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:481:7)
    at flush (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)
```

**Comment by kellyselden** [comment]
Appears to be working now on 3.17.0.
