### ISSUE TITLE
error in tests running on linux

### ISSUE THREAD

**Issue by atomkirk** [ember-cli/ember-cli#8468]
The tests run fine on all our Macs, but as we're trying to set up CI, we get a strange error on linux:

```
not ok 931 Chrome 72.0 - helper:search-highlight: custom wrapper
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read property 'exports' of undefined
                at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:109:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:109:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:109:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
        message: >
            Promise rejected before "custom wrapper": Cannot read property 'exports' of undefined
        Log: |
            { type: 'info',
              text: '\'Unit assertion failed and test has been paused for inspection.\'\n' }
            { type: 'error',
              text: '{ module: \'helper:search-highlight\',\n  name: \'custom wrapper\',\n  result: false,\n  message: \'Promise rejected before "custom wrapper": Cannot read property \\\'exports\\\' of undefined\',\n  actual: null,\n  testId: \'c02bdf85\',\n  negative: false,\n  runtime: 70,\n  todo: false,\n  source: \'TypeError: Cannot read property \\\'exports\\\' of undefined\\n    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)\\n    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)\\n    at Module.exports (http://localhost:7357/assets/vendor.js:109:10)\\n    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)\\n    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)\\n    at Module.exports (http://localhost:7357/assets/vendor.js:109:10)\\n    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)\\n    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)\\n    at Module.exports (http://localhost:7357/assets/vendor.js:109:10)\\n    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)\' }\n' }
    ...
```

1) Node versions are identical,
2) ember versions are identical 
3) `yarn list` output is identical.
4) I even zipped up and copied `node_modules` from the linux machine to my mac and compared it to the `node_modules` on my mac (where the tests pass) and they are IDENTICAL.
5) Both have identical targets.js (seeing as its in version control) and I set CI=false in both cases.
6) All relevant environment variables the same

yet, `CI=false ember build -e test` is slightly different on the mac from linux. Here is a picture of part of the diff. The left is my mac, right is linux:

![image](https://user-images.githubusercontent.com/2091439/53601027-5a5a0f80-3b68-11e9-9447-7481437950d2.png)

So it looks like on linux, on the exact same codebase, same environment variables, same node version, same ember version, ember build is transpiling to older javascript (`var` etc) and on linux, its not. I cannot figure out what is different. This seems like a bug! If its not, can you explain whats going on and maybe it'd be helpful for me to open a PR on the ember-cli docs explaining this?

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.4
http_parser: 2.8.0
node: 8.15.1
v8: 6.2.414.75
uv: 1.23.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.33.0
napi: 3
openssl: 1.0.2r
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: linux x64
6.4.1
1.13.0
```

**Comment by atomkirk** [comment]
The problem was not installing the yarn dependencies in our in-repo addon 😑
