### ISSUE TITLE
Error: getRealDirectoryPath is not a function

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#8483]
When generating a new application using canary (specifically c97dee84155f050) the application is generated but running any commands within it emits an error:

```
❯ ember v
/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/project.js:708
        throw reason;
        ^

TypeError: getRealDirectoryPath is not a function
    at PackageInfoCache._readPackage (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/package-info-cache/index.js:450:20)
    at PackageInfoCache.loadProject (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/package-info-cache/index.js:169:24)
    at new Project (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/project.js:87:47)
    at Function.closestSync (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/project.js:686:12)
    at Function.projectOrnullProject (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/models/project.js:703:22)
    at module.exports (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/lib/cli/index.js:133:25)
    at Object.<anonymous> (/Users/rjackson/sandbox/octane-app-20190306/node_modules/ember-cli/bin/ember:34:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
```

This seems related to the recent resolve-package-path work /cc @stefanpenner @davecombs

**Comment by rwjblue** [comment]
Tracked this down to https://github.com/stefanpenner/resolve-package-path/issues/11. Working on a fix over there...

**Comment by rwjblue** [comment]
resolve-package-path 1.2.3 published 🎉

folks should get the updated/fixed version automatically...
