### ISSUE TITLE
Incorrect deprecation warning about using Ember.$ being spat out in browser console.

### ISSUE THREAD

**Issue by Benjy1979** [ember-cli/ember-cli#8727]
Despite having:

`import $ from 'jquery';`

The browser in the development server 4200 is complaining about the use of Ember.$ but yet in the code there is no use of it. It is the ember-cli that is putting it in.

`deprecate.js:120 DEPRECATION: Using Ember.$() has been deprecated, use `import jQuery from 'jquery';` instead [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.
        at logDeprecationStackTrace (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47377:23)
        at HANDLERS.<computed> (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47471:11)
        at raiseOnDeprecation (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47404:11)
        at HANDLERS.<computed> (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47471:11)
        at invoke (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47483:11)
        at deprecate (http://localhost:4200/roomviewer-tkc/assets/vendor.js:47442:30)
        at Object.get [as $] (http://localhost:4200/roomviewer-tkc/assets/vendor.js:67479:52)
        at Class.init (http://localhost:4200/roomviewer-tkc/assets/ember-roomviewer-tkc.js:7003:48)
        at initialize (http://localhost:4200/roomviewer-tkc/assets/vendor.js:40469:9)`

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.10.1
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: win32 x64
6.9.0
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by locks** [comment]
With the removal of jQuery from the default blueprints, this issue does no longer seem relevant. Thanks for the initial report!
