### ISSUE TITLE
CI Failures: Function.prototype.apply was called on undefined

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#8796]
As of 2019-08-06 our CI has been failing this test:

https://github.com/ember-cli/ember-cli/blob/97561451f5fc411e5068dd428ce6cc23a80fbc45/tests/acceptance/smoke-test-slow.js#L241

With this error:

```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:224377)
    at xu (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:226413)
    at wu (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:227391)
    at Eu (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:295976)
    at n (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/esm/esm.js:1:279589)
    at getFeatures (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/@ember-data/-build-infra/src/features.js:5:33)
    at Object.<anonymous> (/home/travis/build/ember-cli/ember-cli/tmp/node-FGpJBujF.tmp/node_modules/@ember-data/-build-infra/src/features.js:31:18)
```

The issue appears to be an incompatibility with [esm](https://github.com/standard-things/esm) and [heimdall-fs-monitor](https://github.com/heimdalljs/heimdall-fs-monitor), I've reported the issue in https://github.com/heimdalljs/heimdall-fs-monitor/issues/22 (and will work on fixing over there) but cross posting here for visibility.

**Comment by locks** [comment]
Linked PR has been merged.
