### ISSUE TITLE
Ember CLI 3.13.x - template compilation error

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/ember-cli#8867]
I'm not sure what changed between Ember CLI 3.12 and 3.13 but we have started to get a compilation error on a set of templates which previously were fine.

We have some templates which do not sit within the regular `app/templates` directory, instead they sit within our own custom `app/templates-raw` directory. We do this for legacy reasons as these templates actually get compiled by a separate broccoli pipeline using a fork of [`broccoli-template-builder`](https://www.npmjs.com/package/broccoli-template-builder) in ember-cli-build.js.

```
app/
|
|_ template/
   |
   |_ components/ 
|
|_ templates-raw/ (*.handlebars files compiled by a custom broccoli pipeline)
   |
   |_ email-templates/
      |
      |_ email-templates-announcement.handlebars
```

In 3.12 and under it appears these files were ignored by the main Ember build process, but trying out 3.13 it looks they are now being compiled by the main build process (maybe they always were but we didn't notice?). This now causes them to throw a compilation error and the build fails.

failing template example (cut right down for brevity)
```hbs
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<body>
<!-- HTML comment -->
</body>
</html>
```

If I either remove the HTML comment or remove the doctype the build runs to completion.

<details>
<summary>

> broccoliBuilderErrorStack: Error: Closing tag `body` (on line 5) without an open tag.

Click for full stack trace
</summary>

```
=================================================================================

ENV Summary:

  TIME: Mon Sep 30 2019 17:51:50 GMT+0100 (Irish Standard Time)
  TITLE: ember
  ARGV:
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  - /Users/pat/hacking/handlebars-error/node_modules/.bin/ember
  - build
  EXEC_PATH: /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  TMPDIR: /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/yarn--1569862306735-0.931441433165739
  - /Users/pat/hacking/handlebars-error/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/hacking/handlebars-error/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/.nvm/versions/node/v10.15.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin
  - /Users/pat/.yarn/bin
  - /Users/pat/.config/yarn/global/node_modules/.bin
  - /Users/pat/.rbenv/shims
  - /Library/Frameworks/Python.framework/Versions/3.7/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin
  - /Users/pat/.yarn/bin
  - /Users/pat/.config/yarn/global/node_modules/.bin
  - /Users/pat/.rbenv/shims
  - /Library/Frameworks/Python.framework/Versions/3.7/bin
  PLATFORM: darwin x64
  FREEMEM: 25772032
  TOTALMEM: 17179869184
  UPTIME: 1837776
  LOADAVG: 2.70947265625,2.51416015625,3.4306640625
  CPUS:
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Closing tag `body` (on line 5) without an open tag.
    at new SyntaxError (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4302:25)
    at validateEndTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5799:13)
    at TokenizerEventHandlers.finishEndTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5666:7)
    at TokenizerEventHandlers.finishTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5643:14)
    at EventedTokenizer.endTagName (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:13695:27)
    at EventedTokenizer.tokenizePart (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:13988:19)
    at TokenizerEventHandlers.ContentStatement (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4667:22)
    at TokenizerEventHandlers.acceptNode (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4408:29)
    at TokenizerEventHandlers.Program (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4523:14)
    at TokenizerEventHandlers.acceptNode (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4408:29)
  - code: [undefined]
  - codeFrame: Closing tag `body` (on line 5) without an open tag.
  - errorMessage: handlebars-error/templates-raw/email-templates/email-templates-announcement.handlebars: Closing tag `body` (on line 5) without an open tag.
        in /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/broccoli-36754RQjsWimHS1Ue/out-190-funnel_process_templates_app_files
        at broccoli-persistent-filter:TemplateCompiler
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: handlebars-error/templates-raw/email-templates/email-templates-announcement.handlebars
    - line: [undefined]
    - treeDir: /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/broccoli-36754RQjsWimHS1Ue/out-190-funnel_process_templates_app_files
  - message: handlebars-error/templates-raw/email-templates/email-templates-announcement.handlebars: Closing tag `body` (on line 5) without an open tag.
        in /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/broccoli-36754RQjsWimHS1Ue/out-190-funnel_process_templates_app_files
        at broccoli-persistent-filter:TemplateCompiler
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:TemplateCompiler
  - originalErrorMessage: Closing tag `body` (on line 5) without an open tag.
  - stack: Error: Closing tag `body` (on line 5) without an open tag.
    at new SyntaxError (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4302:25)
    at validateEndTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5799:13)
    at TokenizerEventHandlers.finishEndTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5666:7)
    at TokenizerEventHandlers.finishTag (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:5643:14)
    at EventedTokenizer.endTagName (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:13695:27)
    at EventedTokenizer.tokenizePart (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:13988:19)
    at TokenizerEventHandlers.ContentStatement (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4667:22)
    at TokenizerEventHandlers.acceptNode (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4408:29)
    at TokenizerEventHandlers.Program (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4523:14)
    at TokenizerEventHandlers.acceptNode (/Users/pat/hacking/handlebars-error/node_modules/ember-source/dist/ember-template-compiler.js:4408:29)

=================================================================================
```
</details>

---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.13.1
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
✨  Done in 1.67s.
6.4.1
1.13.0
```

Reproduction repo: https://github.com/patocallaghan/handlebars-error
Reproduction step: `yarn && yarn build`

It's worth noting that simply downgrading the ember-cli dependency to 3.12 causes the build to pass without issue.

**Comment by rwjblue** [comment]
In ember-cli@3.13 the full app and addon trees are passed to the template compiler. Prior to that, only `app/templates` would be passed (unless you were using pods, then also `app/pod-prefix-here/**/template.hbs` would pass through). In order to support colocated components, the template compiler must receive both the JS files and the template files from the full app/addon tree.

**Comment by rwjblue** [comment]
FWIW, I chatted with @boris-petrov about a similar issue (in that case it was due to ember-cli-webfont) and suggested they filter out their server side compiled handlebars templates in their `ember-cli-build.js` file. Something like:

```js
new EmberApp(defaults, { 
  trees: { 
    app: new Funnel('app', { 
      exclude: ['webfonts-svg/']
    })
  }
})
```

**Comment by patocallaghan** [comment]
@rwjblue Thanks for the suggestions, that's unblocked us. It's been a long overdue task on our end to move away from having these templates. Thanks 🙇 I'm happy to close the issue.
