### ISSUE TITLE
Error: Could not find module `htmlbars-inline-precompile` imported from...

### ISSUE THREAD

**Issue by jacobq** [ember-cli/ember-cli#8868]
There appears to be a bug in the `latest` (3.13.1) version that is not present in 3.12 or 3.14.0-beta.2, but I couldn't find the GH issue for it so figured I ought to create one in case others are impacted by this / looking for answers. Perhaps someone would be so kind as to comment a link to the canonical issue and/or commit(s) that fixed it and then close this issue.

The problem can be demonstrated by running the code below:

```
npm uninstall -g ember-cli
npm install -g ember-cli@3.13.1
ember new --skip-git --skip-bower --no-welcome junk-app
cd junk-app
ember g component my-comp
ember test
#cd ..
#rm -rf junk-app
```

Note that the default tests for the component fail with errors like the following:
```
$ ember test
Environment: test
cleaning up...
Built project successfully. Stored in "/tmp/tests-dist-2019830-8074-15vxtay.p3m9".
not ok 1 Chrome 77.0 - [1 ms] - TestLoader Failures: junk-app/tests/integration/components/my-comp-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            Error: Could not find module `htmlbars-inline-precompile` imported from `junk-app/tests/integration/components/my-comp-test`
                at missingModule (http://localhost:7357/assets/vendor.js:252:11)
                at findModule (http://localhost:7357/assets/vendor.js:263:7)
                at Module.findDeps (http://localhost:7357/assets/vendor.js:173:24)
                at findModule (http://localhost:7357/assets/vendor.js:267:11)
                at requireModule (http://localhost:7357/assets/vendor.js:29:15)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:13837:9)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:13830:14)
                at loadTests (http://localhost:7357/assets/test-support.js:14534:22)
                at start (http://localhost:7357/assets/test-support.js:14211:33)
                at Module.callback (http://localhost:7357/assets/tests.js:92:25)
        message: >
            Died on test #1     at TestLoader.moduleLoadFailure (http://localhost:7357/assets/test-support.js:14509:22)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:13839:14)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:13830:14)
                at loadTests (http://localhost:7357/assets/test-support.js:14534:22)
                at start (http://localhost:7357/assets/test-support.js:14211:33)
                at Module.callback (http://localhost:7357/assets/tests.js:92:25)
                at Module.exports (http://localhost:7357/assets/vendor.js:111:32): Could not find module `htmlbars-inline-precompile` imported from `junk-app/tests/integration/components/my-comp-test`
        negative: >
            false
        browser log: |
    ...
ok 2 Chrome 77.0 - [0 ms] - ESLint | app: app.js
ok 3 Chrome 77.0 - [1 ms] - ESLint | app: components/my-comp.js
ok 4 Chrome 77.0 - [0 ms] - ESLint | app: resolver.js
ok 5 Chrome 77.0 - [1 ms] - ESLint | app: router.js
ok 6 Chrome 77.0 - [0 ms] - TemplateLint: junk-app/templates/application.hbs
ok 7 Chrome 77.0 - [0 ms] - TemplateLint: junk-app/templates/components/my-comp.hbs
ok 8 Chrome 77.0 - [0 ms] - ESLint | tests: integration/components/my-comp-test.js
ok 9 Chrome 77.0 - [0 ms] - ESLint | tests: test-helper.js
ok 10 Chrome 77.0 - [1 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
not ok 11 Chrome 77.0 - [undefined ms] - Global error: Uncaught TypeError: Cannot read property 'length' of undefined at http://localhost:7357/assets/test-support.js, line 5767
 After execution of test: ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
    ---
        browser log: |
            testContext: [object Object]
            ERROR: Uncaught TypeError: Cannot read property 'length' of undefined at http://localhost:7357/assets/test-support.js, line 5767
            
    ...

1..11
# tests 11
# pass  9
# skip  0
# fail  2
Testem finished with non-zero exit code. Tests failed.
```

I attempted to bisect this (by linking `ember` in global npm to `bin/ember` in the repo and running app/component generation & testing) and got the following (suggesting #8851):
```
git bisect start
# bad: [40171d6c15ccb73606506d8394de5d592a12b950] Release v3.13.1
git bisect bad 40171d6c15ccb73606506d8394de5d592a12b950
# good: [6e570dea9bd1c57980f59355560b5d2bfae74a93] Release v3.12.0
git bisect good 6e570dea9bd1c57980f59355560b5d2bfae74a93
# good: [4083f1e0108aee5df3009a8972194b9b81fea966] Bump semver from 6.1.3 to 6.2.0
git bisect good 4083f1e0108aee5df3009a8972194b9b81fea966
# good: [b2e5ed2f04e405644e688cf183f61a6b1ec0de5d] Bump resolve from 1.11.1 to 1.12.0
git bisect good b2e5ed2f04e405644e688cf183f61a6b1ec0de5d
# good: [316fcf0f3ac3489b827538733d52d0d4e9ef6ce6] Update app and addon blueprints to latest version of packages. (#8816)
git bisect good 316fcf0f3ac3489b827538733d52d0d4e9ef6ce6
# bad: [a21e1bba18de77e714f207030223a38303eea6c4] Update ember-resolver to 5.3.0. (#8853)
git bisect bad a21e1bba18de77e714f207030223a38303eea6c4
# good: [987928a61e3b95ae33be3ccfe543163a8a463866] Update broccoli dependencies/devDependencies to latest. (#8850)
git bisect good 987928a61e3b95ae33be3ccfe543163a8a463866
# bad: [a5723c79ba81db56517c6fcbfb058d47f69d7656] Update Ember ecosystem packages to latest version. (#8851)
git bisect bad a5723c79ba81db56517c6fcbfb058d47f69d7656
```

Possibly similar but probably unrelated issues:
* #4089
* #8867

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.13.1
node: 12.11.0
v8: 7.7.299.11-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: linux x64
6.11.3
1.19.0
```

Hope that's helpful

**Comment by jacobq** [comment]
As I was trying to figure this out, I think it's actually related to a bug in `ember-cli-htmlbars` since forcing that version back to 4.0.1 seems to fix it.
https://github.com/ember-cli/ember-cli-htmlbars/issues/312

**Comment by rwjblue** [comment]
This is likely the same as https://github.com/ember-cli/ember-cli-htmlbars/issues/312
