### ISSUE TITLE
Ember Upgrade Error  - The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by VolodyaCm** [ember-cli/ember-cli#8979]
Hello,

After upgrading Ember project from 2.18 to 3.15

ERROR Summary:
  - broccoliBuilderErrorStack: [undefined]
  - code: ERR_INVALID_ARG_TYPE
  - codeFrame: [undefined]
  - errorMessage: The "path" argument must be of type string. Received type undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: The "path" argument must be of type string. Received type undefined
  - name: TypeError [ERR_INVALID_ARG_TYPE]
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at Class.pellPath (S:\pr\pjc\ember-app\node_modules\ember-pell\index.js:21:17)
    at Class.treeForVendor (S:\pr\pjc\ember-app\node_modules\ember-pell\index.js:27:32)
    at Class._treeFor (S:\pr\pjc\ember-app\node_modules\ember-cli\lib\models\addon.js:700:33)
    at Class.treeFor (S:\pr\pjc\ember-app\node_modules\ember-cli\lib\models\addon.js:660:21)
    at project.addons.reduce (S:\pr\pjc\ember-app\node_modules\ember-cli\lib\broccoli\ember-app.js:721:26)
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (S:\pr\pjc\ember-app\node_modules\ember-cli\lib\broccoli\ember-app.js:719:32)
    at EmberApp.addonTreesFor (S:\pr\pjc\ember-app\node_modules\ember-cli\lib\broccoli\ember-app.js:743:17)

**Comment by rwjblue** [comment]
Did you take a look at the code indicated by the stack trace? What is going on in `ember-pell`'s `index.js` at line 21?

**Comment by VolodyaCm** [comment]
Looks like that it is a bug with ember-pell. I just upgraded ember-pell to last version and it works.
But after that I got the following error:   
Please see here [#78](https://github.com/broccolijs/broccoli-merge-trees/issues/78)

Error:

  1.  [BroccoliMergeTrees: Application Dist]
  2.  [Funnel]
Merge error: file assets/web-workers/web-worker.js exists in /tmp/broccoli-7125bfG4vxxY1kdf/out-543-broccoli_merge_trees_application_dist and /tmp/broccoli-7125bfG4vxxY1kdf/out-545-funnel
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at MergeTrees._getMergedDirectory2 (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/merge-trees/index.js:151:19)
    at MergeTrees._getMergedDirectory2 (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/merge-trees/index.js:174:33)
    at MergeTrees._getMergedDirectory2 (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/merge-trees/index.js:174:33)
    at MergeTrees._getMergedDirectory (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/merge-trees/index.js:40:17)
    at MergeTrees.merge (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/merge-trees/index.js:27:20)
    at BroccoliMergeTrees.build (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:36:21)
    at resolve (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/broccoli/dist/wrappers/transform-node.js:68:45)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/broccoli/dist/wrappers/transform-node.js:53:16)
    at Promise.resolve.then.then.then (/mnt/s/pr/pjc/bcg/ember-app/node_modules/ember-cli/node_modules/broccoli/dist/builder.js:99:36)
(node:7125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:7125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
