### ISSUE TITLE
empty "server" folder in project root broke build

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli#9029]
I'm doing "step-by-step" app and rolling back commits from created server middleware I fased such issue (folder exists, because git don't remove it, but there is no files)
Produced error look unclear for cummon user and I think it make sence to improve it or silentrly handle empty "server" folder.

ember-cli 3.15.2
env: windows

octane app:
```
server <- folder
```

```
$ ember s
Cannot find module './server' from 'C:\Users\lifeart\Documents\repos\longestjs\pizza'
Stack Trace and Error Report: C:\Users\lifeart\AppData\Local\Temp/error.dump.5cf25c0b55910baad8d2f05e79b6c3b9.log
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: MODULE_NOT_FOUND
  - codeFrame: [undefined]
  - errorMessage: Cannot find module './server' from 'C:\Users\lifeart\Documents\repos\longestjs\pizza'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module './server' from 'C:\Users\lifeart\Documents\repos\longestjs\pizza'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module './server' from 'C:\Users\lifeart\Documents\repos\longestjs\pizza'
    at Function.resolveSync [as sync] (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\resolve\lib\sync.js:81:15)
    at Project.resolveSync (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\ember-cli\lib\models\project.js:354:20)
    at Project.require (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\ember-cli\lib\models\project.js:370:21)
    at ExpressServerTask.processAppMiddlewares (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\ember-cli\lib\tasks\server\express-server.js:120:33)
    at Promise.resolve.then.then (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\ember-cli\lib\tasks\server\express-server.js:255:24)
    at tryCatcher (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\rsvp\dist\rsvp.js:498:33)
    at publish (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\rsvp\dist\rsvp.js:484:9)
    at flush (C:\Users\lifeart\Documents\repos\longestjs\pizza\node_modules\rsvp\dist\rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

looks issue from this line - https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/express-server.js#L120

and failed at

![image](https://user-images.githubusercontent.com/1360552/74283407-dbd38f00-4d32-11ea-8797-16ba96a7a0a8.png)

**Comment by rwjblue** [comment]
Sure, seems fine to guard for `MODULE_NOT_FOUND` there (but not generally swallow all errors).

**Comment by locks** [comment]
Closing issue manually since it wasn't linked to the PR!
