### ISSUE TITLE
Building an addon without a `tests/dummy/app/templates` folder results in a build error

### ISSUE THREAD

**Issue by mansona** [ember-cli/ember-cli#9082]
I know this may sound like a strange use case I have a specific use case where it is relevant 😂 I'll not go into that use case because it complicates things but let me know if you think it's relevant and I'm happy to share.

**Steps to reproduce**

- `npm init ember-addon test-addon`
  - creates a brand new addon guaranteed to be with the latest ember-cli
- `cd test-addon`
- `rm -rf tests/dummy/app/templates`
- `npm start` 
- 💥 

the error in the console is

```
Directory not found: /Users/mansona/temp/test-addon/tests/dummy/app/templates
```

and I'll paste the full error report at the end of the issue.

The thing that makes me so confused about this issue is that doing something similar in an Ember app doesn't crash 🤔 that makes me think that a) we have specific code to deal with this in the case of Ember apps and b) that the dummy Ember app is not doing the same stuff as the "real" Ember app.

Steps to **not** reproduce in an Ember app: 

- `npm init ember-app test-app-templates`
- `cd test-app-templates`
- `rm -rf app/templates`
- `npm start` 
- builds fine 🎉 🤔 🙃 

---

(note I'm not using Yarn for any of these commands)
Output from `ember version --verbose && npm --version && yarn --version`:
```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
ember-cli: 3.16.0
node: 12.11.1
v8: 7.7.299.11-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.14.2
1.21.1
```

--- 

Full error report: 

```
cat /var/folders/r5/bw5frvnn5k794hk62w3vp7km0000gn/T/error.dump.ad8d390961cbce484daca7e0e9269546.log
=================================================================================

ENV Summary:

  TIME: Mon Mar 09 2020 21:13:29 GMT+0000 (Greenwich Mean Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/mansona/temp/test-addon/node_modules/.bin/ember
  - serve
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/r5/bw5frvnn5k794hk62w3vp7km0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/mansona/temp/test-addon/node_modules/.bin
  - /Users/mansona/.rvm/gems/ruby-2.6.3/bin
  - /Users/mansona/.rvm/gems/ruby-2.6.3@global/bin
  - /Users/mansona/.rvm/rubies/ruby-2.6.3/bin
  - /Users/mansona/google-cloud-sdk/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/mansona/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 1021603840
  TOTALMEM: 17179869184
  UPTIME: 1904874
  LOADAVG: 3.36181640625,3.9892578125,3.60400390625
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.39.2
  - node: 12.11.1
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.32.0
  - v8: 7.7.299.11-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Directory not found: /Users/mansona/temp/test-addon/tests/dummy/app/templates
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Directory not found: /Users/mansona/temp/test-addon/tests/dummy/app/templates
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Directory not found: /Users/mansona/temp/test-addon/tests/dummy/app/templates
    at Builder.checkInputPathsExist (/Users/mansona/temp/test-addon/node_modules/broccoli/dist/builder.js:260:23)
    at new Builder (/Users/mansona/temp/test-addon/node_modules/broccoli/dist/builder.js:55:14)
    at Builder.setupBroccoliBuilder (/Users/mansona/temp/test-addon/node_modules/ember-cli/lib/models/builder.js:84:22)
    at new Builder (/Users/mansona/temp/test-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/mansona/temp/test-addon/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /Users/mansona/temp/test-addon/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/Users/mansona/temp/test-addon/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/mansona/temp/test-addon/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/mansona/temp/test-addon/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/mansona/temp/test-addon/node_modules/rsvp/dist/rsvp.js:2441:7)

=================================================================================
```

**Comment by rwjblue** [comment]
The fix here is to guard specifying a `templates` tree in `new EmberAddon` here: 

https://github.com/ember-cli/ember-cli/blob/28be1a59c4a722d3fdda4ff492e38a944ca6b479/lib/broccoli/ember-addon.js#L35-L44

All of these should check `fs.existsSync` before specifying the tree...

**Comment by locks** [comment]
@mansona poke
