### ISSUE TITLE
Unable to use CLI - TypeError: hash(...).then(...).finally is not a function

### ISSUE THREAD

**Issue by jhotujec** [ember-cli/ember-cli#9137]
When trying to use latest version of ember cli I am getting an error that renders cli unusable.

**npm**
```
npm --version
3.5.2
```

**ember-cli** (can't use ember version; error log below)
```
npm show ember-cli version
3.17.0
```

**ember version**
```
$ ember version --verbose
/usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:248
      .finally(() => {
              ^

TypeError: hash(...).then(...).finally is not a function
    at CLI.run (/usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:248:15)
    at module.exports (/usr/local/lib/node_modules/ember-cli/lib/cli/index.js:146:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/bin/ember:34:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

**ember new**
```
$ ember new test
/usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:248
      .finally(() => {
              ^

TypeError: hash(...).then(...).finally is not a function
    at CLI.run (/usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:248:15)
    at module.exports (/usr/local/lib/node_modules/ember-cli/lib/cli/index.js:146:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/bin/ember:34:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

```

**Comment by jhotujec** [comment]
Everything works after updating node to the latest version.
