### ISSUE TITLE
Build fails in projects with package `ember-moment`

### ISSUE THREAD

**Issue by andygoalkeeper** [ember-cli/ember-cli#9206]
During the last day an error occured in Ember-CLI 3.16 or 3.17 when building projects with npm-package `ember-moment` in dependencies:

```
ember new project
cd project
ember install ember-moment
ember build --environment=production
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: Unexpected token: eof (undefined)
    at ee (/apps/project/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/apps/project/node_modules/terser/dist/bundle.min.js:1:28031)
    at l (/apps/project/node_modules/terser/dist/bundle.min.js:1:28122)
    at f (/apps/project/node_modules/terser/dist/bundle.min.js:1:28175)
    at N (/apps/project/node_modules/terser/dist/bundle.min.js:1:38279)
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:30375
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:28763
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:32107
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:32217
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:28763
  - code: [undefined]
  - codeFrame: Unexpected token: eof (undefined)
  - errorMessage: Unexpected token: eof (undefined)
        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/apps/project/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/apps/project/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/apps/project/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/apps/project/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/apps/project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/apps/project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/apps/project/node_modules/ember-cli/lib/broccoli/ember-app.js:846:12)
    at EmberApp.host.addonPostprocessTree (/apps/project/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/apps/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1669:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: 94477
    - treeDir: [undefined]
  - message: Unexpected token: eof (undefined)
        at UglifyWriter
-~- created here: -~-
    at UglifyWriter.Plugin (/apps/project/node_modules/broccoli-plugin/index.js:7:31)
    at new UglifyWriter (/apps/project/node_modules/broccoli-uglify-sourcemap/index.js:38:10)
    at UglifyWriter (/apps/project/node_modules/broccoli-uglify-sourcemap/index.js:33:12)
    at Class.postprocessTree (/apps/project/node_modules/ember-cli-uglify/index.js:54:50)
    at projectOrAddon.addons.reduce (/apps/project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/apps/project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/apps/project/node_modules/ember-cli/lib/broccoli/ember-app.js:846:12)
    at EmberApp.host.addonPostprocessTree (/apps/project/node_modules/ember-auto-import/js/auto-import.js:108:20)
    at EmberApp.toTree (/apps/project/node_modules/ember-cli/lib/broccoli/ember-app.js:1669:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: UglifyWriter
  - originalErrorMessage: Unexpected token: eof (undefined)
  - stack: SyntaxError: Unexpected token: eof (undefined)
    at ee (/apps/project/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/apps/project/node_modules/terser/dist/bundle.min.js:1:28031)
    at l (/apps/project/node_modules/terser/dist/bundle.min.js:1:28122)
    at f (/apps/project/node_modules/terser/dist/bundle.min.js:1:28175)
    at N (/apps/project/node_modules/terser/dist/bundle.min.js:1:38279)
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:30375
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:28763
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:32107
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:32217
    at /apps/project/node_modules/terser/dist/bundle.min.js:1:28763
```

package.json:
```
{
  "name": "project",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for project goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build --environment=production",
    "lint": "npm-run-all --aggregate-output --continue-on-error --parallel lint:*",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "npm-run-all lint:* test:*",
    "test:ember": "ember test"
  },
  "devDependencies": {
    "@ember/optional-features": "^1.3.0",
    "@glimmer/component": "^1.0.0",
    "@glimmer/tracking": "^1.0.0",
    "babel-eslint": "^10.1.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.5.3",
    "ember-cli": "~3.17.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.18.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-htmlbars": "^4.2.3",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-uglify": "^3.0.0",
    "ember-data": "~3.17.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^7.0.1",
    "ember-load-initializers": "^2.1.1",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^8.0.0",
    "ember-qunit": "^4.6.0",
    "ember-resolver": "^7.0.0",
    "ember-source": "~3.17.0",
    "ember-template-lint": "^2.4.0",
    "ember-welcome-page": "^4.0.0",
    "eslint": "^6.8.0",
    "eslint-plugin-ember": "^7.10.1",
    "eslint-plugin-node": "^11.0.0",
    "loader.js": "^4.7.0",
    "npm-run-all": "^4.1.5",
    "qunit-dom": "^1.1.0"
  },
  "engines": {
    "node": "10.* || >= 12"
  },
  "ember": {
    "edition": "octane"
  }
}
```

Probably it's related to new release of npm-package `broccoli-plugin` (4.0.3, published a day ago).

**Comment by andygoalkeeper** [comment]
I'm sorry. It's related to release of moment.js 2.25.
`"moment": "2.24.0"` in `package.json` fixes this error.

**Comment by edprats** [comment]
thank you @andygoalkeeper, this worked! but how were you able to figure out it was moment.js from the build error?
