### ISSUE TITLE
Failure while rebuilding a project during a build

### ISSUE THREAD

**Issue by gedaiu** [ember-cli/ember-cli#9230]
It looks like ember cli fails rebuilding a project while a build is running.

If I save a file while ember cli is building, I get this cli error:
```
Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 1191ms              
Bundler (1)                                   | 759ms               
ember-auto-import-analyzer (8)                | 259ms (32 ms)       
Babel: ogm (5)                                | 235ms (47 ms)       

(node:10057) UnhandledPromiseRejectionWarning: Error: Cannot start a build if one is already running
    at Builder.build (/home/gedaiu/workspace/gis-collective/frontend/ogm-frontend/node_modules/broccoli/lib/builder.ts:128:13)
    at Builder.build (/home/gedaiu/workspace/gis-collective/frontend/ogm-frontend/node_modules/ember-cli/lib/models/builder.js:197:30)
(node:10057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
file changed integration/components/manage/visibility-test.js
```
and the server renders this weird page:
![image](https://user-images.githubusercontent.com/4217037/81922451-6e0e5c00-95dc-11ea-8b4f-0c8fbc20e95e.png)

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.18.0
node: 12.16.3
v8: 7.8.279.23-node.35
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
os: linux x64
6.13.1
1.22.4
```

**Comment by rwjblue** [comment]
Can you double check your `broccoli` version (`npm ls broccoli` or `yarn why broccoli`)?

**Comment by gedaiu** [comment]
Sure!

```
❯ yarn why broccoli
yarn why v1.22.4
[1/4] Why do we have the module "broccoli"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "broccoli@3.4.0"
info Reasons this module exists
   - "ember-cli" depends on it
   - Hoisted from "ember-cli#broccoli"
info Disk size without dependencies: "564KB"
info Disk size with unique dependencies: "7.91MB"
info Disk size with transitive dependencies: "41.21MB"
info Number of shared dependencies: 144
Done in 1.61s.
```

**Comment by locks** [comment]
I tried reproducing this with current versions of Ember CLI and couldn't, so I'm closing the issue. Hopefully you no longer encounter this issue, but if you do please let us know!
