### ISSUE TITLE
ember serve: Cannot find module @babel/compat-data/corejs3-shipped-proposals 

### ISSUE THREAD

**Issue by mk-conn** [ember-cli/ember-cli#9235]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.18.0
node: 14.2.0
v8: 8.1.307.31-node.33
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0
os: darwin x64
6.14.4
1.22.4
```

Here is the full stacktrace:

```
=================================================================================

ENV Summary:

  TIME: Mon May 18 2020 22:35:50 GMT+0200 (Central European Summer Time)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/14.2.0/bin/node
  - /usr/local/bin/ember
  - serve
  EXEC_PATH: /usr/local/Cellar/node/14.2.0/bin/node
  TMPDIR: /var/folders/6k/d428w_j94mz87s41051m2z340000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/opt/icu4c/sbin
  - /usr/local/opt/icu4c/bin
  - /Users/mkrueger/.composer/vendor/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  PLATFORM: darwin x64
  FREEMEM: 34156544
  TOTALMEM: 17179869184
  UPTIME: 30862
  LOADAVG: 8.05517578125,7.28466796875,6.74755859375
  CPUS:
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 36.1
  - icu: 66.1
  - llhttp: 2.0.4
  - modules: 83
  - napi: 6
  - nghttp2: 1.40.0
  - node: 14.2.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.37.0
  - v8: 8.1.307.31-node.33
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
  - code: [undefined]
  - codeFrame: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
  - errorMessage: ember-macro-helpers/test-support/compute.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
        in /var/folders/6k/d428w_j94mz87s41051m2z340000gn/T/broccoli-92333wV6cb4cPNPiY/out-046-funnel_addon_tree_for_test_support_ember_macro_helpers
        at broccoli-persistent-filter:Babel > [Babel: ember-macro-helpers] (Babel: ember-macro-helpers)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-macro-helpers/test-support/compute.js
    - line: [undefined]
    - treeDir: /var/folders/6k/d428w_j94mz87s41051m2z340000gn/T/broccoli-92333wV6cb4cPNPiY/out-046-funnel_addon_tree_for_test_support_ember_macro_helpers
  - message: ember-macro-helpers/test-support/compute.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
        in /var/folders/6k/d428w_j94mz87s41051m2z340000gn/T/broccoli-92333wV6cb4cPNPiY/out-046-funnel_addon_tree_for_test_support_ember_macro_helpers
        at broccoli-persistent-filter:Babel > [Babel: ember-macro-helpers] (Babel: ember-macro-helpers)
  - name: Error
  - nodeAnnotation: Babel: ember-macro-helpers
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-macro-helpers]
  - originalErrorMessage: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
  - stack: Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/mkrueger/Projects/events/resources/frontend/node_modules/broccoli-babel-transpiler/lib/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mkrueger/Projects/events/resources/frontend/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)

=================================================================================

```

**Comment by rwjblue** [comment]
Can you share a reproduction? I'm not seeing a similar issue when running against a fresh app.

**Comment by mk-conn** [comment]
Hm, not really... I'll try to remove any 3rdparty package now step by step and see what happens... Btw, I upgraded from 3.14 straight to 3.18.

**Comment by rwjblue** [comment]
Sure, that should be fine in general.

**Comment by mk-conn** [comment]
I just took the package.json from the ember-new-output repo (v3.18.0) and yarn installed new and ember serve still does not run... I'm a bit out of ideas what to do next in order to find the cause... ?

**Comment by mk-conn** [comment]
So here is what worked for me: instead of yarn I used npm to install all packages... so something does not work with the yarn install.

**Comment by ghedamat** [comment]
@mk-conn @rwjblue we started seeing this today when circleci bumped their node image do 12.17 

it "seems" that older versions of node don't have the issue, specifically I'm locking us now to 12.13 and everything is back to green

have not investigated further 

/cc @typeoneerror that linked me to this

https://twitter.com/Design__Pattern/status/1262596127045509120

**Comment by rwjblue** [comment]
Y'all using `npm` or `yarn` @ghedamat? (Trying to see if it is perhaps related to a new / updated bundled npm version with those nodes).

**Comment by ghedamat** [comment]
@rwjblue yarn on all the repos where I had the issue 

Our apps have a ton of dependencies both internal and external but maybe I can try to setup a reproduction this weekend 

We are on very recent (3.16) ember cli though.

**Comment by rwjblue** [comment]
Hmph, then I can't really explain why it would have different behaviors in two different minor releases of Node 12.x.

**Comment by ghedamat** [comment]
No problem!

I'll see if I can setup a repro. I sure is a weird one..

**Comment by MrChocolatine** [comment]
Exact same error on our side, NodeJS `12.17.0` is the culprit, running tests etc in `12.16.x` still works.

**Comment by rwjblue** [comment]
Seems like the biggest change in 12.17.0 is the removal of the `--experimental-modules` flag (it is on by default now).

I’m not quite sure why that would cause this error, but it does seem like a large change to make for an LTS release and definitely a prime suspect here. 


https://nodejs.org/en/blog/release/v12.17.0

**Comment by rwjblue** [comment]
FWIW, I did the following using Node 12.17.0:

```
npx ember-cli new foo --yarn
cd foo
node ./node_modules/.bin/ember build
```

And it built without errors. Has anyone had a chance to put together a reproduction (or share a branch / etc on a public app or addon that reproduces)?

**Comment by rwjblue** [comment]
Seems like this is what was reported in https://github.com/nodejs/node/issues/32852, which had a fix included in `@babel/preset-env@7.9.0`.

**Comment by ghedamat** [comment]
@rwjblue sorry, have had no time yet to put together a repro.

I had seen some comments about `@babel/preset-env` having a fix even last week.

I'll have to look into if and how we can force our apps to use `7.9.0`

as always thanks for your help and guidance!

**Comment by rwjblue** [comment]
I think you can basically do something like:

* Add `"@babel/preset-env": "^7.10.2" to `resolutions` in `package.json`
* Run `yarn install`
* Remove the resolution override
* Run `yarn install`

This **should** result in all of the `ember-cli-babel@7` versions that you have throughout your `node_modules` graph updated to the latest (without having to keep `resolutions` checked in).

**Comment by rwjblue** [comment]
I'm going to close for now, I think this this is solved by updating `@babel/preset-env` to latest.

**Comment by MrChocolatine** [comment]
For the records, I took inspiration from [@rwjblue's post](https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-637697483) (thank you for the hint) and also read [this article](https://medium.com/@ayushya/upgrading-javascript-packages-deep-dependencies-using-yarn-8b5983d5fb6b).

- I had to delete 2 entries in my `yarn.lock` :
```diff
- "@babel/preset-env@^7.0.0", "@babel/preset-env@^7.8.4":
-   version "7.8.7"
-   resolved ...
- 
- "@babel/preset-env@^7.9.0":
-   version "7.10.2"
-   resolved ...
```

- Delete local directories `rm -rf tmp dist`
- Reinstall dependencies `yarn install`
- Switch to NodeJS last LTS `12.x`

And everything is working again, locally and on the CI.
