### ISSUE TITLE
npm install -g ember-cli fails on Mac OS Catalina Version 10.15.4

### ISSUE THREAD

**Issue by HeroicHitesh** [ember-cli/ember-cli#9244]
Output from `ember version --verbose && npm --version && yarn --version`:
```
zsh: command not found: ember
```
This is my first encounter with `npm install -g ember-cli` and on running the command I am getting this o/p
```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @babel/polyfill@7.8.7: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...textextensions","vers'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-05-27T06_44_20_555Z-debug.log
```
You can find contents of `/Users/apple/.npm/_logs/2020-05-27T06_44_20_555Z-debug.log` in this [gist](https://gist.github.com/HeroicHitesh/27fe183e0b2da22dcad39d5b9b7e237c)

I am using `Mac OS Catalina Version 10.15.4`

Any help is appreciated.

**Comment by rwjblue** [comment]
Hmm, it seems that something in the `npm` installation was not properly downloaded (looks like the JSON got truncated).

If you run the command again, does it error the same way?

**Comment by HeroicHitesh** [comment]
Yes the same error comes up each time I try to install `ember-cli`

**Comment by rwjblue** [comment]
Can you clear your `npm` cache (via `npm cache clean`), and retry?

**Comment by HeroicHitesh** [comment]
I tried `npm cache clean` but it gives 
```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-05-28T05_21_49_063Z-debug.log
```
Logs 
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/apple/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/Users/apple/.nvm/versions/node/v12.16.1/bin/npm',
1 verbose cli   'cache',
1 verbose cli   'clean'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose config Skipping project config: /Users/apple/.npmrc. (matches userconfig)
5 verbose npm-session f16e8176a6b091f6
6 verbose stack Error: As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
6 verbose stack
6 verbose stack If you're sure you want to delete the entire cache, rerun this command with --force.
6 verbose stack     at clean (/Users/apple/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/cache.js:72:22)
6 verbose stack     at EventEmitter.cache (/Users/apple/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/cache.js:47:16)
6 verbose stack     at Object.commandCache.<computed> (/Users/apple/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/npm.js:156:13)
6 verbose stack     at EventEmitter.<anonymous> (/Users/apple/.nvm/versions/node/v12.16.1/lib/node_modules/npm/bin/npm-cli.js:131:30)
6 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
7 verbose cwd /Users/apple
8 verbose Darwin 19.4.0
9 verbose argv "/Users/apple/.nvm/versions/node/v12.16.1/bin/node" "/Users/apple/.nvm/versions/node/v12.16.1/bin/npm" "cache" "clean"
10 verbose node v12.16.1
11 verbose npm  v6.13.4
12 error As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
12 error
12 error If you're sure you want to delete the entire cache, rerun this command with --force.
13 verbose exit [ 1, true ]
```

So, I used `npm cache clean -f`

And now retrying the same command i.e., `npm install -g ember-cli` I was able to install ember-cli successfully.
@rwjblue Thanks for the help.
Can you please explain what was going wrong earlier?

**Comment by rwjblue** [comment]
When you install a package (with any package manager, e.g. `npm`, `yarn`, `pnpm`, etc) it downloads a compressed file (usually a `.tar.gz` file). It caches that downloaded tarball so that it can avoid fetching the same file repeatedly from the network. In this case, I suspect that the downloaded file itself was corrupted (perhaps from a network interruption, a bug in the NPM registry, etc) but it was still placed into your cache. When the tarball was unpacked and used it was malformed and caused the error you reported. Since it was stored in your global cache, even repeated re-installs would hit the same problem. Clearing the cache purges the malformed tarball so that a subsequent install can not error.

**Comment by jupiter888** [comment]
that really helped me understand about duplications handling!!! interesting, thank you
