### ISSUE TITLE
When using yarn 2, there is no template pre-processor

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9322]
```
Missing template processor

Stack Trace and Error Report: /tmp/error.dump.bf88498764147872ef5ad3eedda320cb.log
```

Output from `yarn ember version --verbose; npm --version; yarn --version`:
```
ember-cli: 3.21.0
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
pnp: 3
os: linux x64
6.14.6
2.2.2
```

1. Clone: https://github.com/NullVoxPopuli/ember-yarn-2 
2. `git checkout 25ab3470eab96ab95007a47224a90f001cbdff28` (HEAD at the time of writing)
3. `yarn`
4. `yarn start`
5. Error: 

<details><summary>Log file</summary>

```
=================================================================================

ENV Summary:

  TIME: Sun Sep 06 2020 07:34:02 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /home/me/.volta/tools/image/node/12.18.3/bin/node
  - /home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/bin/ember
  - serve
  EXEC_PATH: /home/me/.volta/tools/image/node/12.18.3/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/xfs-424fa0c0
  - /home/me/.volta/tools/image/yarn/1.22.5/bin
  - /home/me/.volta/tools/image/node/12.18.3/bin
  - /home/me/.pythons/Python-3.6.3/bin
  - /home/me/.cargo/bin
  - /home/me/Applications
  - /home/me/apps/phantomjs/bin
  - /home/me/scripts/system-utils
  - /home/me/scripts/git
  - /home/me/scripts/rails
  - /home/me/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/me/.dotnet/tools
  - /home/me/.dotnet/tools
  - /home/me/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 13833887744
  TOTALMEM: 17388265472
  UPTIME: 220
  LOADAVG: 0.07666015625,0.11962890625,0.05322265625
  CPUS:
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 37.0
  - http_parser: 2.9.3
  - icu: 67.1
  - llhttp: 2.0.4
  - modules: 72
  - napi: 6
  - nghttp2: 1.41.0
  - node: 12.18.3
  - openssl: 1.1.1g
  - pnp: 3
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.38.0
  - v8: 7.8.279.23-node.39
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Missing template processor
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Missing template processor
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Missing template processor
    at module.exports.preprocessTemplates (/home/me/.yarn/berry/cache/ember-cli-preprocess-registry-npm-3.3.0-a6fe60c13a-6.zip/node_modules/ember-cli-preprocess-registry/preprocessors.js:166:11)
    at DefaultPackager.processTemplates (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:444:9)
    at DefaultPackager.processAppAndDependencies (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:225:14)
    at DefaultPackager.packageJavascript (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:1176:32)
    at EmberApp._legacyPackage (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/broccoli/ember-app.js:1617:48)
    at EmberApp.toTree (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/broccoli/ember-app.js:1663:27)
    at module.exports (/home/me/Development/NullVoxPopuli/ember-yarn-2/ember-cli-build.js:23:14)
    at Builder.readBuildFile (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/me/.yarn/berry/cache/ember-cli-npm-3.21.0-a01eaa3a9d-6.zip/node_modules/ember-cli/lib/models/builder.js:29:10)

=================================================================================

```

</details>

**Comment by amirhosseinak20** [comment]
Hi, I have same above issue. is there any fix?
`
=================================================================================

ENV Summary:

  TIME: Tue Nov 03 2020 13:47:56 GMT+0330 (Iran Standard Time)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/bin/ember
  - serve
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /bin/zsh
  PATH:
  - /tmp/xfs-e3d19d0f
  - /home/amirhosseinak20/.rvm/gems/ruby-2.6.6/bin
  - /home/amirhosseinak20/.rvm/gems/ruby-2.6.6@global/bin
  - /home/amirhosseinak20/.rvm/rubies/ruby-2.6.6/bin
  - /home/amirhosseinak20/bin
  - /sbin
  - /bin
  - /usr/sbin
  - /usr/bin
  - /usr/local/bin
  - /snap/bin
  - /home/amirhosseinak20/.rvm/bin
  - /home/amirhosseinak20/.rvm/bin
  - /home/amirhosseinak20/.local/bin
  PLATFORM: linux x64
  FREEMEM: 2780291072
  TOTALMEM: 16748785664
  UPTIME: 7146
  LOADAVG: 0.91,0.85,0.74
  CPUS:
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3243
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3127
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3235
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3308
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3235
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3240
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3187
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 3103
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.14.0
  - openssl: 1.1.1g
  - pnp: 3
  - tz: 2020a
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Missing template processor
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Missing template processor
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Missing template processor
    at module.exports.preprocessTemplates (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-preprocess-registry-npm-3.3.0-a6fe60c13a-f49ebfdaba.zip/node_modules/ember-cli-preprocess-registry/preprocessors.js:166:11)
    at DefaultPackager.processTemplates (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:444:9)
    at DefaultPackager.processAppAndDependencies (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:225:14)
    at DefaultPackager.packageJavascript (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/broccoli/default-packager.js:1176:32)
    at EmberApp._legacyPackage (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/broccoli/ember-app.js:1613:48)
    at EmberApp.toTree (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/broccoli/ember-app.js:1659:27)
    at module.exports (/home/amirhosseinak20/Projects/quiverq/watson/ember-cli-build.js:23:14)
    at Builder.readBuildFile (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/amirhosseinak20/Projects/quiverq/watson/.yarn/cache/ember-cli-npm-3.22.0-12434bb7b9-19dee18213.zip/node_modules/ember-cli/lib/models/builder.js:29:10)

=================================================================================

`

**Comment by ohcibi** [comment]
I have this issue only within a docker container. On my mac I can do `yarn workspace my-app ember serve|test|build` without any issues but when running the build during docker build I get the template processor error.

**Comment by tsengia** [comment]
Encountered this issue as well, to reproduce:

```bash
ember new test-application --yarn
cd test-application
yarn start
```

The `ember new --yarn ...` command does give me a Warning saying:
```
WARNING: Yarn v2 is not fully supported. Proceeding with yarn: 3.6.1
```
I am assuming this warning is warning me about this error file that gets generated (some info omitted):
```
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 41.0
  - icu: 71.1
  - llhttp: 6.0.10
  - modules: 108
  - napi: 8
  - nghttp2: 1.47.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 18.12.0
  - openssl: 3.0.5+quic
  - pnp: 3
  - tz: 2022b
  - unicode: 14.0
  - uv: 1.43.0
  - v8: 10.2.154.15-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Missing template processor
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Missing template processor
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Missing template processor
    at module.exports.preprocessTemplates (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-preprocess-registry-npm-3.3.0-a6fe60c13a-7b0a19b084.zip\node_modules\ember-cli-preprocess-registry\preprocessors.js:166:11)
    at DefaultPackager.processTemplates (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\broccoli\default-packager.js:445:9)
    at DefaultPackager.processAppAndDependencies (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\broccoli\default-packager.js:226:14)
    at DefaultPackager.packageJavascript (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\broccoli\default-packager.js:1190:32)
    at EmberApp._legacyPackage (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\broccoli\ember-app.js:1706:48)
    at EmberApp.toTree (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\broccoli\ember-app.js:1752:27)
    at module.exports (D:\Tyler\Documents\Programming\Projects\test-application\ember-cli-build.js:10:14)
    at Builder.readBuildFile (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\models\builder.js:48:20)
    at async Builder.setupBroccoliBuilder (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\models\builder.js:68:17)
    at async Builder.ensureBroccoliBuilder (D:\Tyler\Documents\Programming\Projects\test-application\.yarn\cache\ember-cli-npm-4.12.1-6f2c97ba1e-3e60666372.zip\node_modules\ember-cli\lib\models\builder.js:56:7)

```

**Comment by NullVoxPopuli** [comment]
Closing, as I don't use yarn
