### ISSUE TITLE
Latest version 3.21.2 generating 'Invalid Broccoli2 node detected' error

### ISSUE THREAD

**Issue by briemarie** [ember-cli/ember-cli#9339]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.21.2
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: darwin x64
6.14.6
1.22.5
```

I just upgraded to 3.21.2 from 3.7.1 after I copied a starter app. When run `ember serve` I get the following error. Please note that I ran `npm outdated` and updated all of my packages so I'm on the latest and greatest across my app dependencies. I've looked into the error extensively and it appears from the stacktrace to be coming from the ember-cli package itself not any of the other dependencies. Any help would be appreciated. I don't want to downgrade again to such an old version of ember-cli.
Cheers!

```
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Object: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (TreeMerger (vendor))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/Users/*/src/*/*/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/*/src/*/*/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/*/src/*/*/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/Users/*/src/*/*/node_modules/ember-cli/lib/broccoli/merge-trees.js:90:33)
    at EmberApp.getExternalTree (/Users/*/src/*/*/node_modules/ember-cli/lib/broccoli/ember-app.js:1186:9)
    at EmberApp.toArray (/Users/*/src/*/*/node_modules/ember-cli/lib/broccoli/ember-app.js:1544:12)
    at EmberApp.toTree (/Users/*/src/*/*/node_modules/ember-cli/lib/broccoli/ember-app.js:1648:36)
    at module.exports (/Users/*/src/*/*/ember-cli-build.js:26:14)
    at Builder.readBuildFile (/Users/*/src/*/*/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/*/src/**/node_modules/ember-cli/lib/models/builder.js:63:22)
-~- (end) -~----------------

WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
```

**Comment by rwjblue** [comment]
Hmm. ember-cli doesn't emit this error for new applications. 🤔 

I know you mentioned that you ran `npm outdated`, but have you re-rolled your lock file to see if perhaps a transitive dependency (I _think_ `npm outdated` is only going to help you with things you directly depend on, not _their_ dependencies) is causing you grief here?

**Comment by joshuaswift** [comment]
@briemarie Did you have any joy solving this issue? We're getting the exact same error when upgrading to 3.16. All dependencies up to date and tried re-rolling the lock file.

**Comment by briemarie** [comment]
@joshuaswift This was such a long time ago now... trying to remember how I solved it, but I believe I solved it by downgrading my node version down to 10 (although I don't remember which version I had tried, possibly 11).

**Comment by locks** [comment]
Thanks for taking the time to answer! This issue seems no longer relevant to current versions so I'll be closing it. If anyone runs into this please open a new issue with a reproduction!
