### ISSUE TITLE
Array buffer allocation failed during `ember test`

### ISSUE THREAD

**Issue by justinzelinsky** [ember-cli/ember-cli#9594]
I recently updated `ember-qunit` to latest which also required me to install `qunit` and `@ember/test-helpers` manually. I noticed that when I would run my ~7000 unit tests that I would run into an error like this:

```bash
not ok 1889 Chrome 92.0 - [1221 ms] - Unit | Component | <myComponent>
    ---
        actual: >
            null
        stack: >
            RangeError: Array buffer allocation failed
                at new ArrayBuffer (<anonymous>)
                at new Int32Array (<anonymous>)
                at new HeapImpl (http://localhost:9001/assets/vendor.js:70039:19)
                at artifacts (http://localhost:9001/assets/vendor.js:70301:13)
                at new Renderer (http://localhost:9001/assets/vendor.js:35061:52)
                at new InteractiveRenderer (http://localhost:9001/assets/vendor.js:35316:3)
                at Function.create (http://localhost:9001/assets/vendor.js:35325:14)
                at FactoryManager.create (http://localhost:9001/assets/vendor.js:25093:25)
                at Proxy.create (http://localhost:9001/assets/vendor.js:24811:20)
                at instantiateFactory (http://localhost:9001/assets/vendor.js:24912:71)
```

To be honest, not sure where to go from here. Any advice would be appreciated.

```
ember-cli: 3.24.0
node: 14.17.3
nom: 6.14.13
```

**Comment by locks** [comment]
Tracked over at https://github.com/emberjs/ember-qunit/issues/873!
