### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9682]
Output from `ember version --verbose && npm --version && yarn --version`:
```
an error
(but outside of my app directory): 
ember-cli: 3.28.3
node: 14.18.1
v8: 8.4.371.23-node.84
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.4
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: linux x64
8.1.2
1.22.17
```

With the addon@v2 format on the horizon, I figured I'd give a shot at making my addon true ESM, and not even using CJS / legacy node, by default.

I've run in to a snag, where, due to ember-cli still being in CJS, it cannot import ESM. For example, I have an `addon-main.js`, defined as:
```js
import { dirname } from 'path';
import { fileURLToPath } from 'url';

import { addonV1Shim } from  '@embroider/addon-shim';

const __dirname = dirname(fileURLToPath(import.meta.url));
export default addonV1Shim(__dirname);
```
and in my addon's package.json:
```
  "type": "module",
  "files": [
    "addon-main.js",
    "dist"
  ],
    "ember-addon": {
    "version": 2,
    "type": "addon",
    "main": "addon-main.js",
...
```
and I get the this error when trying to run _any_ `ember` command in the CLI:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /✂️/ember-resources/ember-resources/addon-main.js
require() of ES modules is not supported.
require() of /✂️/ember-resources/ember-resources/addon-main.js from /✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename addon-main.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /✂️/ember-resources/ember-resources/package.json.
```

<details><summary>full error log</summary>

```

=================================================================================

ENV Summary:

  TIME: Sat Oct 30 2021 22:41:27 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/14.18.1/bin/node
  - /✂️/ember-resources/testing/ember-app/node_modules/.bin/ember
  - install
  - ember-cli-typescript
  EXEC_PATH: 🏠/.volta/tools/image/node/14.18.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - 🏠/.volta/tools/image/npm/7.22.0/bin
  - 🏠/.volta/tools/image/yarn/1.22.11/bin
  - 🏠/.volta/tools/image/node/14.18.1/bin
  - 🏠/.volta/bin
  - 🏠/.pythons/Python-3.6.3/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.volta/bin
  - 🏠/.pythons/Python-3.6.3/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /snap/bin
  - 🏠/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 15492227072
  TOTALMEM: 33442410496
  UPTIME: 122305.49
  LOADAVG: 0.33,0.52,0.76
  CPUS:
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 1351
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 1978
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.4
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.18.1
  - openssl: 1.1.1l
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 8.4.371.23-node.84
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: ERR_REQUIRE_ESM
  - codeFrame: [undefined]
  - errorMessage: Must use import to load ES Module: /✂️/ember-resources/ember-resources/addon-main.js
require() of ES modules is not supported.
require() of /✂️/ember-resources/ember-resources/addon-main.js from /✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename addon-main.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /✂️/ember-resources/ember-resources/package.json.

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Must use import to load ES Module: /✂️/ember-resources/ember-resources/addon-main.js
require() of ES modules is not supported.
require() of /✂️/ember-resources/ember-resources/addon-main.js from /✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename addon-main.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /✂️/ember-resources/ember-resources/package.json.

  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /✂️/ember-resources/ember-resources/addon-main.js
require() of ES modules is not supported.
require() of /✂️/ember-resources/ember-resources/addon-main.js from /✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename addon-main.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /✂️/ember-resources/ember-resources/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at PackageInfo._getAddonEntryPoint (/✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:561:12)
    at PackageInfo.getAddonInstance (/✂️/ember-resources/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:512:38)
    at /✂️/ember-resources/node_modules/ember-cli/lib/models/instantiate-addons.js:74:27
    at Vertices.each (/✂️/ember-resources/node_modules/dag-map/dag-map.umd.js:197:13)

=================================================================================
```

</details>

**Comment by Polve** [comment]
Are there any updates on the ESM front?

**Comment by NullVoxPopuli** [comment]
Progress on native Vite support is happening, which would enable this

**Comment by Polve** [comment]
So for the time being we can't use (external) ESM dependencies in ember?

What is the recommended way to develop a node module that must also be used in a ember app?

**Comment by NullVoxPopuli** [comment]
You can still use ESM dependencies. 

All v2 addons are esm.
This already works.

 This issue is about not transpiling away esm, which is different.

If your npm package supports browsers, you can use it as of 4 or 5 years ago via emben-auto-import

**Comment by Polve** [comment]
Thanks for the clarification: the whole thing is quite a mess for someone without a deep understanding of all nuances.

So, in my node module I need to use something like rollup to create a package to import in the ember app?

**Comment by NullVoxPopuli** [comment]
Nay, in embroider as well, imports just work 🎉
