### ISSUE TITLE
Disable bower deprecations when running ember-cli test suite

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#9795]
At the moment when running the tests we are presented with bower deprecations a considerable amount of times.

`bowerDependencies`:

```
DEPRECATION: `bowerDependencies` has been deprecated.
If you still need access to the project's Bower dependencies, you will have to manually resolve the project's `bower.json` file instead. [ID: ember-cli.project.bower-dependencies]
at getStackTrace (/Users/ricardo/src/_cli/ember-cli/lib/debug/deprecate.js:99:15)
at deprecate (/Users/ricardo/src/_cli/ember-cli/lib/debug/deprecate.js:77:8)
at Project.bowerDependencies (/Users/ricardo/src/_cli/ember-cli/lib/models/project.js:412:5)
at Context.<anonymous> (/Users/ricardo/src/_cli/ember-cli/tests/unit/models/project-test.js:330:22)
at callFn (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runnable.js:366:21)
at Test.Runnable.run (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runnable.js:354:5)
at Runner.runTest (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:678:10)
at /Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:801:12
at next (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:593:14)
at /Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:603:7
```

`bowerDirectory`:

```
DEPRECATION: `bowerDirectory` has been deprecated.
If you still need access to the project's Bower directory, you will have to manually resolve the project's `.bowerrc` file, and read the `directory` property instead. [ID: ember-cli.project.bower-directory]
at getStackTrace (/Users/ricardo/src/_cli/ember-cli/lib/debug/deprecate.js:99:15)
at deprecate (/Users/ricardo/src/_cli/ember-cli/lib/debug/deprecate.js:77:8)
at Project.get bowerDirectory [as bowerDirectory] (/Users/ricardo/src/_cli/ember-cli/lib/models/project.js:133:5)
at Context.<anonymous> (/Users/ricardo/src/_cli/ember-cli/tests/unit/models/project-test.js:649:22)
at callFn (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runnable.js:366:21)
at Test.Runnable.run (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runnable.js:354:5)
at Runner.runTest (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:678:10)
at /Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:801:12
at next (/Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:593:14)
at /Users/ricardo/src/_cli/ember-cli/node_modules/mocha/lib/runner.js:603:7
```

This deprecation should be disabled where appropriate so the test output is as clean as possible.

**Comment by locks** [comment]
It is also appearing in `ember -v`, `ember new`, and `yarn start` (which calls `ember sesrver`).

**Comment by bertdeblock** [comment]
Closing as all Bower deprecations have been cleaned up.
