### ISSUE TITLE
ember build fails with " Invalid Version: 2022.06.27.00"

### ISSUE THREAD

**Issue by dinager** [ember-cli/ember-cli#9967]
`ember build -w` fails with the following error:
```
TypeError: Invalid Version: 2022.06.27.00
    at new SemVer (/Users/dina/my-app/node_modules/semver/semver.js:323:11)
    at Range.test (/Users/dina/my-app/node_modules/semver/semver.js:1203:15)
    at Function.satisfies (/Users/dina/my-app/node_modules/semver/semver.js:1257:16)
    at /Users/dina/my-app/node_modules/ember-cli/lib/models/watcher.js:108:18
    at tryCatch (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
``` 
More details: until yesterday my app ran ok with `ember build`,  yesterday I reinstalled my node (I am using volta) and since then I get the above exception.
Here is my volta installation:
```
volta setup
volta install node@16
volta install ember-cli 
volta install node@6 
volta install npm@3 
volta install bower
```
here is my package.json:
```
{
  "name": "my-app",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "build-prod": "ember build --production",
    "test": "ember test --silent -r xunit > tests/results/results.xml"
  },
  "repository": "",
  "engines": {
    "node": "6.9.4",
    "npm": "3.10.8"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@abcum/ember-helpers": "4.2.1",
    "@stripe/stripe-js": "^1.5.0",
    "acorn": "^6.1.0",
    "babel-cli": "^6.26.0",
    "babel-core": "6.26.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-latest": "^6.24.0",
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-array-helper": "^1.0.1",
    "ember-assign-polyfill": "2.6.0",
    "ember-cli": "2.4.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-file-picker": "0.0.12",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-json-module": "0.0.3",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.6.0",
    "ember-cli-showdown": "3.2.2",
    "ember-cli-uglify": "^1.2.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-fetch": "5.1.1",
    "ember-intl": "2.27.0",
    "ember-load-initializers": "^0.5.0",
    "ember-paper": "0.2.15",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^2.0.3",
    "ember-truth-helpers": "1.2.0",
    "ember-wormhole": "0.3.5",
    "file-saver": "^1.3.2",
    "intl-format-cache": "2.1.0",
    "loader.js": "^4.0.0"
  },
  "volta": {
    "node": "6.17.1"
  },
  "dependencies": {}
}
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-ajax -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-array-helper -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-cli-app-version -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> Ember CLI QUnit -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-cli-showdown -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-export-application-global -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> intl-relativeformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> intl-relativeformat -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-intl -> intl-relativeformat -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-paper -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-paper -> ember-css-transitions -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-paper -> ember-wormhole -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-radio-button -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-resolver -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-truth-helpers -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: easy-send -> ember-wormhole -> ember-cli-babel
WARNING: WARNING: Node v6.17.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
version: 2.4.0
Invalid Version: 2022.06.27.00
TypeError: Invalid Version: 2022.06.27.00
    at new SemVer (/Users/dina/my-app/node_modules/semver/semver.js:323:11)
    at Range.test (/Users/dina/my-app/node_modules/semver/semver.js:1203:15)
    at Function.satisfies (/Users/dina/my-app/node_modules/semver/semver.js:1257:16)
    at /Users/dina/my-app/node_modules/ember-cli/lib/models/watcher.js:108:18
    at tryCatch (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/dina/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by dinager** [comment]
Found the cause:  `watchman`.
Ran `brew uninstall watchman`, now ember runs ok

**Comment by dinager** [comment]
looks like there is an opened issue on watchman
https://github.com/facebook/watchman/issues/915
